QuickJSPP: qjs::Value Class Reference
qjs::Value Class Reference
JSValue with RAAI semantics.
#include "quickjspp.hpp"
Public Member Functions
template<typename T >
Value (JSContext *ctx, T &&val)
Use context.newValue(val) instead.
Value (const Value &rhs)
Value (Value &&rhs)
Value & operator= (Value rhs)
bool operator== (JSValueConst other) const
bool operator!= (JSValueConst other) const
bool operator== (const Value &rhs) const
Returns true if 2 values are the same (equality for arithmetic types or point to the same object)
bool operator!= (const Value &rhs) const
~Value ()
bool isError () const
template<typename T >
auto as () const
Conversion helper function: value.as<T>()
template<typename T >
operator T () const
Explicit conversion: static_cast<T>(value) or (T)value.
JSValue release ()
operator JSValue () &&
Implicit conversion to JSValue (rvalue only).
template<typename Key >
detail::property_proxy< Key > operator[] (Key key)
Access JS properties.
template<typename Function >
Value & add (const char *name, Function &&f)
template<auto F>
std::enable_if_t<!std::is_member_object_pointer_v< decltype(F)>, Value & > add (const char *name)
template<auto FGet, auto FSet>
Value & add_getter_setter (const char *name)
template<auto FGet>
Value & add_getter (const char *name)
template<auto M>
std::enable_if_t< std::is_member_object_pointer_v< decltype(M)>, Value & > add (const char *name)
std::string toJSON (const Value &replacer=Value{nullptr, JS_UNDEFINED}, const Value &space=Value{nullptr, JS_UNDEFINED})
Public Attributes
JSValue v
JSContext * ctx = nullptr
Detailed Description
JSValue with RAAI semantics.
A wrapper over (JSValue v, JSContext * ctx). Calls JS_FreeValue(ctx, v) on destruction. Can be copied and moved. A JSValue can be released by either JSValue x = std::move(value); or JSValue x = value.release(), then the Value becomes invalid and FreeValue won't be called Can be converted to C++ type, for example: auto string = value.as<std::string>(); qjs::exception would be thrown on error Properties can be accessed (read/write): value["property1"] = 1; value[2] = "2";
Definition at line 997 of file quickjspp.hpp.
Constructor & Destructor Documentation
Value() [1/3]
template<typename T > qjs::Value::Value (JSContext * ctx, T && val) inline
Use context.newValue(val) instead.
Definition at line 1006 of file quickjspp.hpp.
References ctx, JS_IsException(), and v.
Referenced by qjs::Context::Module::add(), qjs::Context::eval(), qjs::Context::fromJSON(), qjs::Context::getException(), qjs::Context::global(), qjs::Context::newObject(), toJSON(), qjs::js_traits< Value >::unwrap(), qjs::js_traits< std::vector< T > >::unwrap(), qjs::js_traits< std::pair< U, V > >::unwrap(), qjs::js_traits< std::vector< T > >::wrap(), and qjs::js_traits< std::pair< U, V > >::wrap().
                                     : ctx(ctx)
     {
         v = js_traits<std::decay_t<T>>::wrap(ctx, std::forward<T>(val));
         if(JS_IsException(v))
             throw exception{};
     }
Value() [2/3]
qjs::Value::Value (const Value & rhs) inline
Definition at line 1013 of file quickjspp.hpp.
References ctx, JS_DupValue(), and v.
     {
         ctx = rhs.ctx;
         v = JS_DupValue(ctx, rhs.v);
     }
Value() [3/3]
qjs::Value::Value (Value && rhs) inline
Definition at line 1019 of file quickjspp.hpp.
References ctx, and v.
     {
         std::swap(ctx, rhs.ctx);
         v = rhs.v;
     }
~Value()
qjs::Value::~Value () inline
Definition at line 1049 of file quickjspp.hpp.
References ctx, JS_FreeValue(), and v.
     {
         if(ctx) JS_FreeValue(ctx, v);
     }
Member Function Documentation
operator=()
Value& qjs::Value::operator= (Value rhs) inline
Definition at line 1025 of file quickjspp.hpp.
References ctx, and v.
     {
         std::swap(ctx, rhs.ctx);
         std::swap(v, rhs.v);
         return *this;
     }
operator==() [1/2]
bool qjs::Value::operator== (JSValueConst other) const inline
Definition at line 1032 of file quickjspp.hpp.
References v.
Referenced by operator!=(), and operator==().
     {
         return JS_VALUE_GET_TAG(v) == JS_VALUE_GET_TAG(other) && JS_VALUE_GET_PTR(v) == JS_VALUE_GET_PTR(other);
     }
operator!=() [1/2]
bool qjs::Value::operator!= (JSValueConst other) const inline
Definition at line 1037 of file quickjspp.hpp.
References operator==().
 { return !((*this) == other); }
operator==() [2/2]
bool qjs::Value::operator== (const Value & rhs) const inline
Returns true if 2 values are the same (equality for arithmetic types or point to the same object)
Definition at line 1041 of file quickjspp.hpp.
References ctx, operator==(), and v.
Referenced by operator!=().
     {
         return ctx == rhs.ctx && (*this == rhs.v);
     }
operator!=() [2/2]
bool qjs::Value::operator!= (const Value & rhs) const inline
Definition at line 1046 of file quickjspp.hpp.
References operator==().
 { return !((*this) == rhs); }
isError()
bool qjs::Value::isError () const inline
Definition at line 1054 of file quickjspp.hpp.
References ctx, JS_IsError(), and v.
Referenced by main().
 { return JS_IsError(ctx, v); }
as()
template<typename T > auto qjs::Value::as () const inline
Conversion helper function: value.as<T>()
Template Parameters
T type to convert to
Returns
type returned by js_traits<std::decay_t<T>>::unwrap that should be implicitly convertible to T
Definition at line 1061 of file quickjspp.hpp.
References ctx, and v.
 { return js_traits<std::decay_t<T>>::unwrap(ctx, v); }
operator T()
template<typename T > qjs::Value::operator T () const inline explicit
Explicit conversion: static_cast<T>(value) or (T)value.
Definition at line 1065 of file quickjspp.hpp.
 { return as<T>(); }
release()
JSValue qjs::Value::release () inline
Definition at line 1067 of file quickjspp.hpp.
References ctx, and v.
Referenced by operator JSValue(), qjs::js_traits< Value >::wrap(), qjs::js_traits< std::vector< T > >::wrap(), and qjs::js_traits< std::pair< U, V > >::wrap().
     {
         ctx = nullptr;
         return v;
     }
operator JSValue()
qjs::Value::operator JSValue () && inline
Implicit conversion to JSValue (rvalue only).
Example: JSValue v = std::move(value);
Definition at line 1074 of file quickjspp.hpp.
References release().
 { return release(); }
operator[]()
template<typename Key > detail::property_proxy<Key> qjs::Value::operator[] (Key key) inline
Access JS properties.
Returns proxy type which is implicitly convertible to qjs::Value
Definition at line 1079 of file quickjspp.hpp.
References ctx, and v.
Referenced by add(), main(), qjs::js_traits< std::vector< T > >::unwrap(), qjs::js_traits< std::pair< U, V > >::unwrap(), qjs::js_traits< std::vector< T > >::wrap(), and qjs::js_traits< std::pair< U, V > >::wrap().
     {
         return {ctx, v, std::move(key)};
     }
add() [1/3]
template<typename Function > Value& qjs::Value::add (const char * name, Function && f) inline
Definition at line 1087 of file quickjspp.hpp.
References ctx, and operator[]().
     {
         (*this)[name] = js_traits<decltype(std::function{std::forward<Function>(f)})>::wrap(ctx,
                                                                                             std::forward<Function>(f));
         return *this;
     }
add() [2/3]
template<auto F> std::enable_if_t<!std::is_member_object_pointer_v<decltype(F)>, Value&> qjs::Value::add (const char * name) inline
Definition at line 1098 of file quickjspp.hpp.
References operator[]().
     {
         (*this)[name] = fwrapper<F>{name};
         return *this;
     }
add_getter_setter()
template<auto FGet, auto FSet> Value& qjs::Value::add_getter_setter (const char * name) inline
Definition at line 1106 of file quickjspp.hpp.
References ctx, JS_FreeAtom(), JS_NewAtom(), and v.
     {
         auto prop = JS_NewAtom(ctx, name);
         using fgetter = fwrapper<FGet, true>;
         using fsetter = fwrapper<FSet, true>;
         int ret = JS_DefinePropertyGetSet(ctx, v, prop,
                                           js_traits<fgetter>::wrap(ctx, fgetter{name}),
                                           js_traits<fsetter>::wrap(ctx, fsetter{name}),
                                           JS_PROP_CONFIGURABLE | JS_PROP_WRITABLE | JS_PROP_ENUMERABLE
         );
         JS_FreeAtom(ctx, prop);
         if(ret < 0)
             throw exception{};
         return *this;
     }
add_getter()
template<auto FGet> Value& qjs::Value::add_getter (const char * name) inline
Definition at line 1124 of file quickjspp.hpp.
References ctx, JS_FreeAtom(), JS_NewAtom(), and v.
     {
         auto prop = JS_NewAtom(ctx, name);
         using fgetter = fwrapper<FGet, true>;
         int ret = JS_DefinePropertyGetSet(ctx, v, prop,
                                           js_traits<fgetter>::wrap(ctx, fgetter{name}),
                                           JS_UNDEFINED,
                                           JS_PROP_CONFIGURABLE | JS_PROP_ENUMERABLE
         );
         JS_FreeAtom(ctx, prop);
         if(ret < 0)
             throw exception{};
         return *this;
     }
add() [3/3]
template<auto M> std::enable_if_t<std::is_member_object_pointer_v<decltype(M)>, Value&> qjs::Value::add (const char * name) inline
Definition at line 1142 of file quickjspp.hpp.
     {
         if constexpr (detail::get_set<M>::is_const::value)
         {
             return add_getter<detail::get_set<M>::get>(name);
         }
         else
         {
             return add_getter_setter<detail::get_set<M>::get, detail::get_set<M>::set>(name);
         }
     }
toJSON()
std::string qjs::Value::toJSON (const Value & replacer = Value{nullptr, JS_UNDEFINED}, const Value & space = Value{nullptr, JS_UNDEFINED}) inline
Definition at line 1155 of file quickjspp.hpp.
References Value().
                                         {nullptr, JS_UNDEFINED}, const Value& space = Value{nullptr, JS_UNDEFINED})
     {
         assert(ctx);
         assert(!replacer.ctx || ctx == replacer.ctx);
         assert(!space.ctx || ctx == space.ctx);
         JSValue json = JS_JSONStringify(ctx, v, replacer.v, space.v);
         return (std::string) Value{ctx, json};
     }
Member Data Documentation
v
JSValue qjs::Value::v
Definition at line 1000 of file quickjspp.hpp.
Referenced by add_getter(), add_getter_setter(), as(), qjs::Context::Module::class_registrar< T >::constructor(), isError(), qjs::Context::Module::Module(), operator=(), operator==(), operator[](), release(), qjs::js_traits< std::function< R(Args...)> >::unwrap(), Value(), and ~Value().
ctx
JSContext* qjs::Value::ctx = nullptr
Definition at line 1001 of file quickjspp.hpp.
Referenced by add(), qjs::Context::Module::add(), add_getter(), add_getter_setter(), as(), isError(), operator=(), operator==(), operator[](), release(), qjs::js_traits< std::function< R(Args...)> >::unwrap(), Value(), qjs::js_traits< Value >::wrap(), and ~Value().
The documentation for this class was generated from the following file:
quickjspp.hpp