QuickJSPP: quickjs/cutils.h File Reference
cutils.h File Reference
#include <stdlib.h>
#include <inttypes.h>
Classes
struct DynBuf
Macros
#define likely(x) __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#define force_inline inline __attribute__((always_inline))
#define no_inline __attribute__((noinline))
#define __maybe_unused __attribute__((unused))
#define xglue(x, y) x ## y
#define glue(x, y) xglue(x, y)
#define stringify(s) tostring(s)
#define tostring(s) #s
#define offsetof(type, field) ((size_t) &((type *)0)->field)
#define countof(x) (sizeof(x) / sizeof((x)[0]))
#define UTF8_CHAR_LEN_MAX 6
Typedefs
typedef int BOOL
typedef void * DynBufReallocFunc(void *opaque, void *ptr, size_t size)
typedef struct DynBuf DynBuf
Enumerations
enum { FALSE = 0, TRUE = 1 }
Functions
void pstrcpy (char *buf, int buf_size, const char *str)
char * pstrcat (char *buf, int buf_size, const char *s)
int strstart (const char *str, const char *val, const char **ptr)
int has_suffix (const char *str, const char *suffix)
static int max_int (int a, int b)
static int min_int (int a, int b)
static uint32_t max_uint32 (uint32_t a, uint32_t b)
static uint32_t min_uint32 (uint32_t a, uint32_t b)
static int64_t max_int64 (int64_t a, int64_t b)
static int64_t min_int64 (int64_t a, int64_t b)
static int clz32 (unsigned int a)
static int clz64 (uint64_t a)
static int ctz32 (unsigned int a)
static int ctz64 (uint64_t a)
struct __attribute__ ((packed)) packed_u64
static uint64_t get_u64 (const uint8_t *tab)
static int64_t get_i64 (const uint8_t *tab)
static void put_u64 (uint8_t *tab, uint64_t val)
static uint32_t get_u32 (const uint8_t *tab)
static int32_t get_i32 (const uint8_t *tab)
static void put_u32 (uint8_t *tab, uint32_t val)
static uint32_t get_u16 (const uint8_t *tab)
static int32_t get_i16 (const uint8_t *tab)
static void put_u16 (uint8_t *tab, uint16_t val)
static uint32_t get_u8 (const uint8_t *tab)
static int32_t get_i8 (const uint8_t *tab)
static void put_u8 (uint8_t *tab, uint8_t val)
static uint16_t bswap16 (uint16_t x)
static uint32_t bswap32 (uint32_t v)
static uint64_t bswap64 (uint64_t v)
void dbuf_init (DynBuf *s)
void dbuf_init2 (DynBuf *s, void *opaque, DynBufReallocFunc *realloc_func)
int dbuf_realloc (DynBuf *s, size_t new_size)
int dbuf_write (DynBuf *s, size_t offset, const uint8_t *data, size_t len)
int dbuf_put (DynBuf *s, const uint8_t *data, size_t len)
int dbuf_put_self (DynBuf *s, size_t offset, size_t len)
int dbuf_putc (DynBuf *s, uint8_t c)
int dbuf_putstr (DynBuf *s, const char *str)
static int dbuf_put_u16 (DynBuf *s, uint16_t val)
static int dbuf_put_u32 (DynBuf *s, uint32_t val)
static int dbuf_put_u64 (DynBuf *s, uint64_t val)
int __attribute__ ((format(printf, 2, 3))) dbuf_printf(DynBuf *s
int const char void dbuf_free (DynBuf *s)
static BOOL dbuf_error (DynBuf *s)
static void dbuf_set_error (DynBuf *s)
int unicode_to_utf8 (uint8_t *buf, unsigned int c)
int unicode_from_utf8 (const uint8_t *p, int max_len, const uint8_t **pp)
static int from_hex (int c)
void rqsort (void *base, size_t nmemb, size_t size, int(*cmp)(const void *, const void *, void *), void *arg)
Variables
int const char * fmt
Macro Definition Documentation
likely
#define likely (x) __builtin_expect(!!(x), 1)
Definition at line 34 of file cutils.h.
unlikely
#define unlikely (x) __builtin_expect(!!(x), 0)
Definition at line 35 of file cutils.h.
force_inline
#define force_inline inline __attribute__((always_inline))
Definition at line 36 of file cutils.h.
no_inline
#define no_inline __attribute__((noinline))
Definition at line 37 of file cutils.h.
__maybe_unused
#define __maybe_unused __attribute__((unused))
Definition at line 38 of file cutils.h.
xglue
#define xglue (x, y) x ## y
Definition at line 40 of file cutils.h.
glue
#define glue (x, y) xglue(x, y)
Definition at line 41 of file cutils.h.
stringify
#define stringify (s) tostring(s)
Definition at line 42 of file cutils.h.
tostring
#define tostring (s) #s
Definition at line 43 of file cutils.h.
offsetof
#define offsetof (type, field) ((size_t) &((type *)0)->field)
Definition at line 46 of file cutils.h.
countof
#define countof (x) (sizeof(x) / sizeof((x)[0]))
Definition at line 49 of file cutils.h.
UTF8_CHAR_LEN_MAX
#define UTF8_CHAR_LEN_MAX 6
Definition at line 276 of file cutils.h.
Typedef Documentation
BOOL
typedef int BOOL
Definition at line 52 of file cutils.h.
DynBufReallocFunc
typedef void* DynBufReallocFunc(void *opaque, void *ptr, size_t size)
Definition at line 234 of file cutils.h.
DynBuf
typedef struct DynBuf DynBuf
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FALSE
TRUE
Definition at line 55 of file cutils.h.
      {
     FALSE = 0,
     TRUE = 1,
 };
Function Documentation
pstrcpy()
void pstrcpy (char * buf, int buf_size, const char * str)
Definition at line 32 of file cutils.c.
Referenced by js_module_set_import_meta(), lre_compile(), and pstrcat().
 {
     int c;
     char *q = buf;
     if (buf_size <= 0)
         return;
     for(;;) {
         c = *str++;
         if (c == 0 || q >= buf + buf_size - 1)
             break;
         *q++ = c;
     }
     *q = '\0';
 }
pstrcat()
char* pstrcat (char * buf, int buf_size, const char * s)
Definition at line 50 of file cutils.c.
References pstrcpy().
Referenced by js_module_set_import_meta().
 {
     int len;
     len = strlen(buf);
     if (len < buf_size)
         pstrcpy(buf + len, buf_size - len, s);
     return buf;
 }
strstart()
int strstart (const char * str, const char * val, const char ** ptr)
Definition at line 59 of file cutils.c.
Referenced by js_atof().
 {
     const char *p, *q;
     p = str;
     q = val;
     while (*q != '\0') {
         if (*p != *q)
             return 0;
         p++;
         q++;
     }
     if (ptr)
         *ptr = p;
     return 1;
 }
has_suffix()
int has_suffix (const char * str, const char * suffix)
Definition at line 75 of file cutils.c.
Referenced by js_module_loader().
 {
     size_t len = strlen(str);
     size_t slen = strlen(suffix);
     return (len >= slen && !memcmp(str + len - slen, suffix, slen));
 }
max_int()
static int max_int (int a, int b) inline static
Definition at line 66 of file cutils.h.
Referenced by __JS_NewAtom(), add_fast_array_element(), async_func_init(), compact_properties(), cr_realloc(), js_function_bind(), js_math_min_max(), JS_NewClass1(), js_realloc_array(), js_reflect_apply(), js_string_slice(), JS_ToUint8ClampFree(), js_typed_array___speciesCreate(), js_typed_array_slice(), js_typed_array_subarray(), push_scope(), resize_properties(), and string_buffer_realloc().
 {
     if (a > b)
         return a;
     else
         return b;
 }
min_int()
static int min_int (int a, int b) inline static
Definition at line 74 of file cutils.h.
Referenced by JS_CallInternal(), JS_JSONStringify(), js_math_min_max(), js_string_compare(), js_string_pad(), JS_ToUint8ClampFree(), js_typed_array_copyWithin(), and string_buffer_realloc().
 {
     if (a < b)
         return a;
     else
         return b;
 }
max_uint32()
static uint32_t max_uint32 (uint32_t a, uint32_t b) inline static
Definition at line 82 of file cutils.h.
Referenced by js_object_list_add(), and js_string_codePointRange().
 {
     if (a > b)
         return a;
     else
         return b;
 }
min_uint32()
static uint32_t min_uint32 (uint32_t a, uint32_t b) inline static
Definition at line 90 of file cutils.h.
Referenced by JS_DumpMemoryUsage(), and js_string_codePointRange().
 {
     if (a < b)
         return a;
     else
         return b;
 }
max_int64()
static int64_t max_int64 (int64_t a, int64_t b) inline static
Definition at line 98 of file cutils.h.
Referenced by js_array_buffer_slice(), and js_array_slice().
 {
     if (a > b)
         return a;
     else
         return b;
 }
min_int64()
static int64_t min_int64 (int64_t a, int64_t b) inline static
Definition at line 106 of file cutils.h.
Referenced by js_array_copyWithin().
 {
     if (a < b)
         return a;
     else
         return b;
 }
clz32()
static int clz32 (unsigned int a) inline static
Definition at line 115 of file cutils.h.
Referenced by js_math_clz32().
 {
     return __builtin_clz(a);
 }
clz64()
static int clz64 (uint64_t a) inline static
Definition at line 121 of file cutils.h.
Referenced by bf_set_float64(), clz(), and fast_udiv_init().
 {
     return __builtin_clzll(a);
 }
ctz32()
static int ctz32 (unsigned int a) inline static
Definition at line 127 of file cutils.h.
 {
     return __builtin_ctz(a);
 }
ctz64()
static int ctz64 (uint64_t a) inline static
Definition at line 133 of file cutils.h.
Referenced by ctz().
 {
     return __builtin_ctzll(a);
 }
__attribute__() [1/2]
struct __attribute__ ((packed))
Definition at line 138 of file cutils.h.
{
     uint64_t v;
 };
get_u64()
static uint64_t get_u64 (const uint8_t * tab) inline static
Definition at line 150 of file cutils.h.
Referenced by bc_get_u64(), and js_dataview_getValue().
 {
     return ((const struct packed_u64 *)tab)->v;
 }
get_i64()
static int64_t get_i64 (const uint8_t * tab) inline static
Definition at line 155 of file cutils.h.
 {
     return (int64_t)((const struct packed_u64 *)tab)->v;
 }
put_u64()
static void put_u64 (uint8_t * tab, uint64_t val) inline static
Definition at line 160 of file cutils.h.
Referenced by js_dataview_setValue().
 {
     ((struct packed_u64 *)tab)->v = val;
 }
get_u32()
static uint32_t get_u32 (const uint8_t * tab) inline static
Definition at line 165 of file cutils.h.
Referenced by bc_byte_swap(), bc_get_u32(), code_has_label(), code_match(), compute_stack_size(), find_jump_target(), free_bytecode_atoms(), get_label_pos(), get_lvalue(), JS_CallInternal(), js_dataview_getValue(), js_parse_delete(), js_parse_postfix_expr(), JS_ReadFunctionBytecode(), JS_WriteFunctionBytecode(), lre_exec_backtrack(), lre_get_groupnames(), resolve_labels(), resolve_variables(), set_object_name(), set_object_name_computed(), and skip_dead_code().
 {
     return ((const struct packed_u32 *)tab)->v;
 }
get_i32()
static int32_t get_i32 (const uint8_t * tab) inline static
Definition at line 170 of file cutils.h.
Referenced by resolve_labels().
 {
     return (int32_t)((const struct packed_u32 *)tab)->v;
 }
put_u32()
static void put_u32 (uint8_t * tab, uint32_t val) inline static
Definition at line 175 of file cutils.h.
Referenced by bc_byte_swap(), js_dataview_setValue(), js_parse_class(), js_parse_statement_or_decl(), JS_ReadFunctionBytecode(), JS_WriteFunctionBytecode(), lre_compile(), optimize_scope_make_global_ref(), re_parse_disjunction(), re_parse_term(), resolve_labels(), and set_object_name().
 {
     ((struct packed_u32 *)tab)->v = val;
 }
get_u16()
static uint32_t get_u16 (const uint8_t * tab) inline static
Definition at line 180 of file cutils.h.
Referenced by bc_byte_swap(), bc_get_u16(), code_match(), compute_stack_size(), get_lvalue(), JS_CallInternal(), js_dataview_getValue(), js_parse_postfix_expr(), lre_exec_backtrack(), re_check_advance(), re_is_simple_quantifier(), resolve_labels(), and resolve_variables().
 {
     return ((const struct packed_u16 *)tab)->v;
 }
get_i16()
static int32_t get_i16 (const uint8_t * tab) inline static
Definition at line 185 of file cutils.h.
Referenced by JS_CallInternal().
 {
     return (int16_t)((const struct packed_u16 *)tab)->v;
 }
put_u16()
static void put_u16 (uint8_t * tab, uint16_t val) inline static
Definition at line 190 of file cutils.h.
Referenced by bc_byte_swap(), js_dataview_setValue(), optimize_scope_make_ref(), and resolve_labels().
 {
     ((struct packed_u16 *)tab)->v = val;
 }
get_u8()
static uint32_t get_u8 (const uint8_t * tab) inline static
Definition at line 195 of file cutils.h.
Referenced by code_match().
 {
     return *tab;
 }
get_i8()
static int32_t get_i8 (const uint8_t * tab) inline static
Definition at line 200 of file cutils.h.
Referenced by JS_CallInternal().
 {
     return (int8_t)*tab;
 }
put_u8()
static void put_u8 (uint8_t * tab, uint8_t val) inline static
Definition at line 205 of file cutils.h.
Referenced by resolve_labels().
 {
     *tab = val;
 }
bswap16()
static uint16_t bswap16 (uint16_t x) inline static
Definition at line 210 of file cutils.h.
Referenced by bc_byte_swap(), bc_put_u16(), js_dataview_getValue(), and js_dataview_setValue().
 {
     return (x >> 8) | (x << 8);
 }
bswap32()
static uint32_t bswap32 (uint32_t v) inline static
Definition at line 215 of file cutils.h.
Referenced by bc_byte_swap(), bc_put_u32(), js_dataview_getValue(), and js_dataview_setValue().
 {
     return ((v & 0xff000000) >> 24) | ((v & 0x00ff0000) >>  8) |
         ((v & 0x0000ff00) <<  8) | ((v & 0x000000ff) << 24);
 }
bswap64()
static uint64_t bswap64 (uint64_t v) inline static
Definition at line 221 of file cutils.h.
Referenced by bc_put_u64(), js_dataview_getValue(), and js_dataview_setValue().
 {
     return ((v & ((uint64_t)0xff << (7 * 8))) >> (7 * 8)) |
         ((v & ((uint64_t)0xff << (6 * 8))) >> (5 * 8)) |
         ((v & ((uint64_t)0xff << (5 * 8))) >> (3 * 8)) |
         ((v & ((uint64_t)0xff << (4 * 8))) >> (1 * 8)) |
         ((v & ((uint64_t)0xff << (3 * 8))) << (1 * 8)) |
         ((v & ((uint64_t)0xff << (2 * 8))) << (3 * 8)) |
         ((v & ((uint64_t)0xff << (1 * 8))) << (5 * 8)) |
         ((v & ((uint64_t)0xff << (0 * 8))) << (7 * 8));
 }
dbuf_init()
void dbuf_init (DynBuf * s)
Definition at line 98 of file cutils.c.
References dbuf_init2().
 {
     dbuf_init2(s, NULL, NULL);
 }
dbuf_init2()
void dbuf_init2 (DynBuf * s, void * opaque, DynBufReallocFunc * realloc_func)
Definition at line 89 of file cutils.c.
References dbuf_default_realloc(), DynBuf::opaque, and DynBuf::realloc_func.
Referenced by bf_ftoa_internal(), dbuf_init(), js_dbuf_init(), js_std_dbuf_init(), lre_compile(), and unicode_normalize().
 {
     memset(s, 0, sizeof(*s));
     if (!realloc_func)
         realloc_func = dbuf_default_realloc;
     s->opaque = opaque;
     s->realloc_func = realloc_func;
 }
dbuf_realloc()
int dbuf_realloc (DynBuf * s, size_t new_size)
Definition at line 104 of file cutils.c.
References DynBuf::allocated_size, DynBuf::buf, DynBuf::error, and TRUE.
Referenced by __attribute__(), dbuf_insert(), dbuf_put(), dbuf_put_self(), dbuf_write(), js_parse_for_in_of(), js_parse_statement_or_decl(), JS_WriteObjectAtoms(), re_parse_alternative(), and unicode_normalize().
 {
     size_t size;
     uint8_t *new_buf;
     if (new_size > s->allocated_size) {
         if (s->error)
             return -1;
         size = s->allocated_size * 3 / 2;
         if (size > new_size)
             new_size = size;
         new_buf = s->realloc_func(s->opaque, s->buf, new_size);
         if (!new_buf) {
             s->error = TRUE;
             return -1;
         }
         s->buf = new_buf;
         s->allocated_size = new_size;
     }
     return 0;
 }
dbuf_write()
int dbuf_write (DynBuf * s, size_t offset, const uint8_t * data, size_t len)
Definition at line 125 of file cutils.c.
References DynBuf::buf, dbuf_realloc(), and DynBuf::size.
 {
     size_t end;
     end = offset + len;
     if (dbuf_realloc(s, end))
         return -1;
     memcpy(s->buf + offset, data, len);
     if (end > s->size)
         s->size = end;
     return 0;
 }
dbuf_put()
int dbuf_put (DynBuf * s, const uint8_t * data, size_t len)
Definition at line 137 of file cutils.c.
References DynBuf::allocated_size, DynBuf::buf, dbuf_realloc(), and DynBuf::size.
Referenced by __attribute__(), bc_put_u64(), dbuf_put_u16(), dbuf_put_u32(), dbuf_put_u64(), dbuf_putc(), dbuf_putstr(), js_parse_for_in_of(), js_parse_statement_or_decl(), js_printf_internal(), js_std_urlGet(), JS_WriteArrayBuffer(), JS_WriteFunctionBytecode(), JS_WriteString(), lre_compile(), output_digits(), re_parse_term(), resolve_labels(), and resolve_variables().
 {
     if (unlikely((s->size + len) > s->allocated_size)) {
         if (dbuf_realloc(s, s->size + len))
             return -1;
     }
     memcpy(s->buf + s->size, data, len);
     s->size += len;
     return 0;
 }
dbuf_put_self()
int dbuf_put_self (DynBuf * s, size_t offset, size_t len)
Definition at line 148 of file cutils.c.
References DynBuf::allocated_size, DynBuf::buf, dbuf_realloc(), and DynBuf::size.
Referenced by re_parse_term().
 {
     if (unlikely((s->size + len) > s->allocated_size)) {
         if (dbuf_realloc(s, s->size + len))
             return -1;
     }
     memcpy(s->buf + s->size, s->buf + offset, len);
     s->size += len;
     return 0;
 }
dbuf_putc()
int dbuf_putc (DynBuf * s, uint8_t c)
Definition at line 159 of file cutils.c.
References dbuf_put().
Referenced by bc_put_u8(), bf_ftoa_internal(), build_backtrace(), compute_pc2line_info(), dbuf_put_leb128(), emit_op(), emit_u8(), get_loc_or_ref(), http_get_header_line(), instantiate_hoisted_definitions(), js_printf_internal(), js_std_file_getline(), js_std_file_readAsString(), js_std_urlGet(), lre_compile(), optimize_scope_make_global_ref(), optimize_scope_make_ref(), output_digits(), push_short_int(), put_short_code(), re_emit_goto(), re_emit_op(), re_emit_op_u16(), re_emit_op_u32(), re_emit_op_u8(), re_parse_term(), resolve_labels(), resolve_scope_private_field(), resolve_scope_var(), resolve_variables(), and var_object_test().
 {
     return dbuf_put(s, &c, 1);
 }
dbuf_putstr()
int dbuf_putstr (DynBuf * s, const char * str)
Definition at line 164 of file cutils.c.
References dbuf_put().
Referenced by bf_ftoa_internal(), and js_std_urlGet().
 {
     return dbuf_put(s, (const uint8_t *)str, strlen(str));
 }
dbuf_put_u16()
static int dbuf_put_u16 (DynBuf * s, uint16_t val) inline static
Definition at line 253 of file cutils.h.
References dbuf_put().
Referenced by bc_put_u16(), emit_u16(), get_loc_or_ref(), instantiate_hoisted_definitions(), optimize_scope_make_ref(), push_short_int(), put_short_code(), re_emit_op_u16(), re_emit_range(), resolve_labels(), resolve_scope_private_field(), resolve_scope_var(), and resolve_variables().
 {
     return dbuf_put(s, (uint8_t *)&val, 2);
 }
dbuf_put_u32()
static int dbuf_put_u32 (DynBuf * s, uint32_t val) inline static
Definition at line 257 of file cutils.h.
References dbuf_put().
Referenced by bc_put_u32(), emit_op(), emit_u32(), instantiate_hoisted_definitions(), lre_compile(), optimize_scope_make_global_ref(), push_short_int(), re_emit_goto(), re_emit_op_u32(), re_emit_range(), resolve_labels(), resolve_scope_private_field(), resolve_scope_var(), resolve_variables(), to_nfd_rec(), and var_object_test().
 {
     return dbuf_put(s, (uint8_t *)&val, 4);
 }
dbuf_put_u64()
static int dbuf_put_u64 (DynBuf * s, uint64_t val) inline static
Definition at line 261 of file cutils.h.
References dbuf_put().
 {
     return dbuf_put(s, (uint8_t *)&val, 8);
 }
__attribute__() [2/2]
int __attribute__ ((format(printf, 2, 3)))
Referenced by bf_ftoa_internal(), build_backtrace(), and js_std_urlGet().
dbuf_free()
int const char void dbuf_free (DynBuf * s)
Definition at line 194 of file cutils.c.
References DynBuf::buf, DynBuf::opaque, and DynBuf::realloc_func.
Referenced by build_backtrace(), js_create_function(), js_free_function_def(), js_printf_internal(), js_std_file_getline(), js_std_file_readAsString(), js_std_urlGet(), JS_WriteObject2(), JS_WriteObjectAtoms(), lre_compile(), resolve_labels(), and resolve_variables().
 {
     /* we test s->buf as a fail safe to avoid crashing if dbuf_free()
        is called twice */
     if (s->buf) {
         s->realloc_func(s->opaque, s->buf, 0);
     }
     memset(s, 0, sizeof(*s));
 }
dbuf_error()
static BOOL dbuf_error (DynBuf * s) inline static
Definition at line 268 of file cutils.h.
References DynBuf::error.
Referenced by bf_ftoa_internal(), build_backtrace(), js_std_urlGet(), lre_compile(), re_parse_term(), resolve_labels(), resolve_variables(), and unicode_normalize().
{
     return s->error;
 }
dbuf_set_error()
static void dbuf_set_error (DynBuf * s) inline static
Definition at line 271 of file cutils.h.
References DynBuf::error, and TRUE.
Referenced by output_digits().
 {
     s->error = TRUE;
 }
unicode_to_utf8()
int unicode_to_utf8 (uint8_t * buf, unsigned int c)
Definition at line 206 of file cutils.c.
Referenced by JS_AtomGetStrRT(), js_printf_internal(), JS_ToCStringLen2(), parse_ident(), and re_parse_group_name().
 {
     uint8_t *q = buf;
     if (c < 0x80) {
         *q++ = c;
     } else {
         if (c < 0x800) {
             *q++ = (c >> 6) | 0xc0;
         } else {
             if (c < 0x10000) {
                 *q++ = (c >> 12) | 0xe0;
             } else {
                 if (c < 0x00200000) {
                     *q++ = (c >> 18) | 0xf0;
                 } else {
                     if (c < 0x04000000) {
                         *q++ = (c >> 24) | 0xf8;
                     } else if (c < 0x80000000) {
                         *q++ = (c >> 30) | 0xfc;
                         *q++ = ((c >> 24) & 0x3f) | 0x80;
                     } else {
                         return 0;
                     }
                     *q++ = ((c >> 18) & 0x3f) | 0x80;
                 }
                 *q++ = ((c >> 12) & 0x3f) | 0x80;
             }
             *q++ = ((c >> 6) & 0x3f) | 0x80;
         }
         *q++ = (c & 0x3f) | 0x80;
     }
     return q - buf;
 }
unicode_from_utf8()
int unicode_from_utf8 (const uint8_t * p, int max_len, const uint8_t ** pp)
Definition at line 251 of file cutils.c.
References utf8_first_code_mask, and utf8_min_code.
Referenced by get_class_atom(), JS_NewStringLen(), js_parse_regexp(), js_parse_string(), js_parse_template_part(), js_printf_internal(), json_next_token(), next_token(), parse_ident(), re_parse_group_name(), skip_shebang(), and skip_spaces().
 {
     int l, c, b, i;
     c = *p++;
     if (c < 0x80) {
         *pp = p;
         return c;
     }
     switch(c) {
     case 0xc0: case 0xc1: case 0xc2: case 0xc3:
     case 0xc4: case 0xc5: case 0xc6: case 0xc7:
     case 0xc8: case 0xc9: case 0xca: case 0xcb:
     case 0xcc: case 0xcd: case 0xce: case 0xcf:
     case 0xd0: case 0xd1: case 0xd2: case 0xd3:
     case 0xd4: case 0xd5: case 0xd6: case 0xd7:
     case 0xd8: case 0xd9: case 0xda: case 0xdb:
     case 0xdc: case 0xdd: case 0xde: case 0xdf:
         l = 1;
         break;
     case 0xe0: case 0xe1: case 0xe2: case 0xe3:
     case 0xe4: case 0xe5: case 0xe6: case 0xe7:
     case 0xe8: case 0xe9: case 0xea: case 0xeb:
     case 0xec: case 0xed: case 0xee: case 0xef:
         l = 2;
         break;
     case 0xf0: case 0xf1: case 0xf2: case 0xf3:
     case 0xf4: case 0xf5: case 0xf6: case 0xf7:
         l = 3;
         break;
     case 0xf8: case 0xf9: case 0xfa: case 0xfb:
         l = 4;
         break;
     case 0xfc: case 0xfd:
         l = 5;
         break;
     default:
         return -1;
     }
     /* check that we have enough characters */
     if (l > (max_len - 1))
         return -1;
     c &= utf8_first_code_mask[l - 1];
     for(i = 0; i < l; i++) {
         b = *p++;
         if (b < 0x80 || b >= 0xc0)
             return -1;
         c = (c << 6) | (b & 0x3f);
     }
     if (c < utf8_min_code[l - 1])
         return -1;
     *pp = p;
     return c;
 }
from_hex()
static int from_hex (int c) inline static
Definition at line 281 of file cutils.h.
Referenced by lre_parse_escape(), and string_get_hex().
 {
     if (c >= '0' && c <= '9')
         return c - '0';
     else if (c >= 'A' && c <= 'F')
         return c - 'A' + 10;
     else if (c >= 'a' && c <= 'f')
         return c - 'a' + 10;
     else
         return -1;
 }
rqsort()
void rqsort (void * base, size_t nmemb, size_t size, int(*)(const void *, const void *, void *) cmp, void * arg)
Referenced by js_array_sort(), js_build_module_ns(), JS_GetOwnPropertyNamesInternal(), and js_typed_array_sort().
Variable Documentation
fmt
int const char* fmt
Definition at line 266 of file cutils.h.