QuickJSPP: quickjs/libbf.h File Reference
libbf.h File Reference
#include <stddef.h>
#include <stdint.h>
Classes
struct bf_t
struct bfdec_t
struct BFConstCache
struct bf_context_t
Macros
#define LIMB_LOG2_BITS 6
#define LIMB_BITS (1 << LIMB_LOG2_BITS)
#define BF_RAW_EXP_MIN INT64_MIN
#define BF_RAW_EXP_MAX INT64_MAX
#define LIMB_DIGITS 19
#define BF_DEC_BASE UINT64_C(10000000000000000000)
#define BF_EXP_BITS_MIN 3
#define BF_EXP_BITS_MAX (LIMB_BITS - 3)
#define BF_EXT_EXP_BITS_MAX (BF_EXP_BITS_MAX + 1)
#define BF_PREC_MIN 2
#define BF_PREC_MAX (((limb_t)1 << (LIMB_BITS - 2)) - 2)
#define BF_PREC_INF (BF_PREC_MAX + 1) /* infinite precision */
#define BF_CHKSUM_MOD (UINT64_C(975620677) * UINT64_C(9795002197))
#define BF_EXP_ZERO BF_RAW_EXP_MIN
#define BF_EXP_INF (BF_RAW_EXP_MAX - 1)
#define BF_EXP_NAN BF_RAW_EXP_MAX
#define BF_FLAG_SUBNORMAL (1 << 3)
#define BF_FLAG_RADPNT_PREC (1 << 4)
#define BF_RND_MASK 0x7
#define BF_EXP_BITS_SHIFT 5
#define BF_EXP_BITS_MASK 0x3f
#define BF_FLAG_EXT_EXP (BF_EXP_BITS_MASK << BF_EXP_BITS_SHIFT)
#define BF_ST_INVALID_OP (1 << 0)
#define BF_ST_DIVIDE_ZERO (1 << 1)
#define BF_ST_OVERFLOW (1 << 2)
#define BF_ST_UNDERFLOW (1 << 3)
#define BF_ST_INEXACT (1 << 4)
#define BF_ST_MEM_ERROR (1 << 5)
#define BF_RADIX_MAX 36 /* maximum radix for bf_atof() and bf_ftoa() */
#define BF_DIVREM_EUCLIDIAN BF_RNDF
#define BF_ATOF_NO_HEX (1 << 16)
#define BF_ATOF_BIN_OCT (1 << 17)
#define BF_ATOF_NO_NAN_INF (1 << 18)
#define BF_ATOF_EXPONENT (1 << 19)
#define BF_FTOA_FORMAT_MASK (3 << 16)
#define BF_FTOA_FORMAT_FIXED (0 << 16)
#define BF_FTOA_FORMAT_FRAC (1 << 16)
#define BF_FTOA_FORMAT_FREE (2 << 16)
#define BF_FTOA_FORMAT_FREE_MIN (3 << 16)
#define BF_FTOA_FORCE_EXP (1 << 20)
#define BF_FTOA_ADD_PREFIX (1 << 21)
#define BF_FTOA_JS_QUIRKS (1 << 22)
#define BF_GET_INT_MOD (1 << 0)
#define BF_POW_JS_QUIRKS (1 << 16) /* (+/-1)^(+/-Inf) = NaN, 1^NaN = NaN */
Typedefs
typedef __int128 int128_t
typedef unsigned __int128 uint128_t
typedef int64_t slimb_t
typedef uint64_t limb_t
typedef uint128_t dlimb_t
typedef uint32_t bf_flags_t
typedef void * bf_realloc_func_t(void *opaque, void *ptr, size_t size)
typedef struct bf_context_t bf_context_t
Enumerations
enum bf_rnd_t {
BF_RNDN, BF_RNDZ, BF_RNDD, BF_RNDU,
BF_RNDNA, BF_RNDA, BF_RNDF
}
Functions
static int bf_get_exp_bits (bf_flags_t flags)
static bf_flags_t bf_set_exp_bits (int n)
static slimb_t bf_max (slimb_t a, slimb_t b)
static slimb_t bf_min (slimb_t a, slimb_t b)
void bf_context_init (bf_context_t *s, bf_realloc_func_t *realloc_func, void *realloc_opaque)
void bf_context_end (bf_context_t *s)
void bf_clear_cache (bf_context_t *s)
static void * bf_realloc (bf_context_t *s, void *ptr, size_t size)
static void * bf_malloc (bf_context_t *s, size_t size)
static void bf_free (bf_context_t *s, void *ptr)
void bf_init (bf_context_t *s, bf_t *r)
static void bf_delete (bf_t *r)
static void bf_neg (bf_t *r)
static int bf_is_finite (const bf_t *a)
static int bf_is_nan (const bf_t *a)
static int bf_is_zero (const bf_t *a)
static void bf_memcpy (bf_t *r, const bf_t *a)
int bf_set_ui (bf_t *r, uint64_t a)
int bf_set_si (bf_t *r, int64_t a)
void bf_set_nan (bf_t *r)
void bf_set_zero (bf_t *r, int is_neg)
void bf_set_inf (bf_t *r, int is_neg)
int bf_set (bf_t *r, const bf_t *a)
void bf_move (bf_t *r, bf_t *a)
int bf_get_float64 (const bf_t *a, double *pres, bf_rnd_t rnd_mode)
int bf_set_float64 (bf_t *a, double d)
int bf_cmpu (const bf_t *a, const bf_t *b)
int bf_cmp_full (const bf_t *a, const bf_t *b)
int bf_cmp (const bf_t *a, const bf_t *b)
static int bf_cmp_eq (const bf_t *a, const bf_t *b)
static int bf_cmp_le (const bf_t *a, const bf_t *b)
static int bf_cmp_lt (const bf_t *a, const bf_t *b)
int bf_add (bf_t *r, const bf_t *a, const bf_t *b, limb_t prec, bf_flags_t flags)
int bf_sub (bf_t *r, const bf_t *a, const bf_t *b, limb_t prec, bf_flags_t flags)
int bf_add_si (bf_t *r, const bf_t *a, int64_t b1, limb_t prec, bf_flags_t flags)
int bf_mul (bf_t *r, const bf_t *a, const bf_t *b, limb_t prec, bf_flags_t flags)
int bf_mul_ui (bf_t *r, const bf_t *a, uint64_t b1, limb_t prec, bf_flags_t flags)
int bf_mul_si (bf_t *r, const bf_t *a, int64_t b1, limb_t prec, bf_flags_t flags)
int bf_mul_2exp (bf_t *r, slimb_t e, limb_t prec, bf_flags_t flags)
int bf_div (bf_t *r, const bf_t *a, const bf_t *b, limb_t prec, bf_flags_t flags)
int bf_divrem (bf_t *q, bf_t *r, const bf_t *a, const bf_t *b, limb_t prec, bf_flags_t flags, int rnd_mode)
int bf_rem (bf_t *r, const bf_t *a, const bf_t *b, limb_t prec, bf_flags_t flags, int rnd_mode)
int bf_remquo (slimb_t *pq, bf_t *r, const bf_t *a, const bf_t *b, limb_t prec, bf_flags_t flags, int rnd_mode)
int bf_rint (bf_t *r, int rnd_mode)
int bf_round (bf_t *r, limb_t prec, bf_flags_t flags)
int bf_sqrtrem (bf_t *r, bf_t *rem1, const bf_t *a)
int bf_sqrt (bf_t *r, const bf_t *a, limb_t prec, bf_flags_t flags)
slimb_t bf_get_exp_min (const bf_t *a)
int bf_logic_or (bf_t *r, const bf_t *a, const bf_t *b)
int bf_logic_xor (bf_t *r, const bf_t *a, const bf_t *b)
int bf_logic_and (bf_t *r, const bf_t *a, const bf_t *b)
int bf_atof (bf_t *a, const char *str, const char **pnext, int radix, limb_t prec, bf_flags_t flags)
int bf_atof2 (bf_t *r, slimb_t *pexponent, const char *str, const char **pnext, int radix, limb_t prec, bf_flags_t flags)
int bf_mul_pow_radix (bf_t *r, const bf_t *T, limb_t radix, slimb_t expn, limb_t prec, bf_flags_t flags)
char * bf_ftoa (size_t *plen, const bf_t *a, int radix, limb_t prec, bf_flags_t flags)
int bf_get_int32 (int *pres, const bf_t *a, int flags)
int bf_get_int64 (int64_t *pres, const bf_t *a, int flags)
int bf_get_uint64 (uint64_t *pres, const bf_t *a)
void mp_print_str (const char *str, const limb_t *tab, limb_t n)
void bf_print_str (const char *str, const bf_t *a)
int bf_resize (bf_t *r, limb_t len)
int bf_get_fft_size (int *pdpl, int *pnb_mods, limb_t len)
int bf_normalize_and_round (bf_t *r, limb_t prec1, bf_flags_t flags)
int bf_can_round (const bf_t *a, slimb_t prec, bf_rnd_t rnd_mode, slimb_t k)
slimb_t bf_mul_log2_radix (slimb_t a1, unsigned int radix, int is_inv, int is_ceil1)
int mp_mul (bf_context_t *s, limb_t *result, const limb_t *op1, limb_t op1_size, const limb_t *op2, limb_t op2_size)
limb_t mp_add (limb_t *res, const limb_t *op1, const limb_t *op2, limb_t n, limb_t carry)
limb_t mp_add_ui (limb_t *tab, limb_t b, size_t n)
int mp_sqrtrem (bf_context_t *s, limb_t *tabs, limb_t *taba, limb_t n)
int mp_recip (bf_context_t *s, limb_t *tabr, const limb_t *taba, limb_t n)
limb_t bf_isqrt (limb_t a)
int bf_const_log2 (bf_t *T, limb_t prec, bf_flags_t flags)
int bf_const_pi (bf_t *T, limb_t prec, bf_flags_t flags)
int bf_exp (bf_t *r, const bf_t *a, limb_t prec, bf_flags_t flags)
int bf_log (bf_t *r, const bf_t *a, limb_t prec, bf_flags_t flags)
int bf_pow (bf_t *r, const bf_t *x, const bf_t *y, limb_t prec, bf_flags_t flags)
int bf_cos (bf_t *r, const bf_t *a, limb_t prec, bf_flags_t flags)
int bf_sin (bf_t *r, const bf_t *a, limb_t prec, bf_flags_t flags)
int bf_tan (bf_t *r, const bf_t *a, limb_t prec, bf_flags_t flags)
int bf_atan (bf_t *r, const bf_t *a, limb_t prec, bf_flags_t flags)
int bf_atan2 (bf_t *r, const bf_t *y, const bf_t *x, limb_t prec, bf_flags_t flags)
int bf_asin (bf_t *r, const bf_t *a, limb_t prec, bf_flags_t flags)
int bf_acos (bf_t *r, const bf_t *a, limb_t prec, bf_flags_t flags)
static void bfdec_init (bf_context_t *s, bfdec_t *r)
static void bfdec_delete (bfdec_t *r)
static void bfdec_neg (bfdec_t *r)
static int bfdec_is_finite (const bfdec_t *a)
static int bfdec_is_nan (const bfdec_t *a)
static int bfdec_is_zero (const bfdec_t *a)
static void bfdec_memcpy (bfdec_t *r, const bfdec_t *a)
int bfdec_set_ui (bfdec_t *r, uint64_t a)
int bfdec_set_si (bfdec_t *r, int64_t a)
static void bfdec_set_nan (bfdec_t *r)
static void bfdec_set_zero (bfdec_t *r, int is_neg)
static void bfdec_set_inf (bfdec_t *r, int is_neg)
static int bfdec_set (bfdec_t *r, const bfdec_t *a)
static void bfdec_move (bfdec_t *r, bfdec_t *a)
static int bfdec_cmpu (const bfdec_t *a, const bfdec_t *b)
static int bfdec_cmp_full (const bfdec_t *a, const bfdec_t *b)
static int bfdec_cmp (const bfdec_t *a, const bfdec_t *b)
static int bfdec_cmp_eq (const bfdec_t *a, const bfdec_t *b)
static int bfdec_cmp_le (const bfdec_t *a, const bfdec_t *b)
static int bfdec_cmp_lt (const bfdec_t *a, const bfdec_t *b)
int bfdec_add (bfdec_t *r, const bfdec_t *a, const bfdec_t *b, limb_t prec, bf_flags_t flags)
int bfdec_sub (bfdec_t *r, const bfdec_t *a, const bfdec_t *b, limb_t prec, bf_flags_t flags)
int bfdec_add_si (bfdec_t *r, const bfdec_t *a, int64_t b1, limb_t prec, bf_flags_t flags)
int bfdec_mul (bfdec_t *r, const bfdec_t *a, const bfdec_t *b, limb_t prec, bf_flags_t flags)
int bfdec_mul_si (bfdec_t *r, const bfdec_t *a, int64_t b1, limb_t prec, bf_flags_t flags)
int bfdec_div (bfdec_t *r, const bfdec_t *a, const bfdec_t *b, limb_t prec, bf_flags_t flags)
int bfdec_divrem (bfdec_t *q, bfdec_t *r, const bfdec_t *a, const bfdec_t *b, limb_t prec, bf_flags_t flags, int rnd_mode)
int bfdec_rem (bfdec_t *r, const bfdec_t *a, const bfdec_t *b, limb_t prec, bf_flags_t flags, int rnd_mode)
int bfdec_rint (bfdec_t *r, int rnd_mode)
int bfdec_sqrt (bfdec_t *r, const bfdec_t *a, limb_t prec, bf_flags_t flags)
int bfdec_round (bfdec_t *r, limb_t prec, bf_flags_t flags)
int bfdec_get_int32 (int *pres, const bfdec_t *a)
int bfdec_pow_ui (bfdec_t *r, const bfdec_t *a, limb_t b)
char * bfdec_ftoa (size_t *plen, const bfdec_t *a, limb_t prec, bf_flags_t flags)
int bfdec_atof (bfdec_t *r, const char *str, const char **pnext, limb_t prec, bf_flags_t flags)
void bfdec_print_str (const char *str, const bfdec_t *a)
static int bfdec_resize (bfdec_t *r, limb_t len)
int bfdec_normalize_and_round (bfdec_t *r, limb_t prec1, bf_flags_t flags)
Variables
const limb_t mp_pow_dec [LIMB_DIGITS+1]
Macro Definition Documentation
LIMB_LOG2_BITS
#define LIMB_LOG2_BITS 6
Definition at line 31 of file libbf.h.
LIMB_BITS
#define LIMB_BITS (1 << LIMB_LOG2_BITS)
Definition at line 36 of file libbf.h.
BF_RAW_EXP_MIN
#define BF_RAW_EXP_MIN INT64_MIN
Definition at line 44 of file libbf.h.
BF_RAW_EXP_MAX
#define BF_RAW_EXP_MAX INT64_MAX
Definition at line 45 of file libbf.h.
LIMB_DIGITS
#define LIMB_DIGITS 19
Definition at line 47 of file libbf.h.
BF_DEC_BASE
#define BF_DEC_BASE UINT64_C(10000000000000000000)
Definition at line 48 of file libbf.h.
BF_EXP_BITS_MIN
#define BF_EXP_BITS_MIN 3
Definition at line 65 of file libbf.h.
BF_EXP_BITS_MAX
#define BF_EXP_BITS_MAX (LIMB_BITS - 3)
Definition at line 67 of file libbf.h.
BF_EXT_EXP_BITS_MAX
#define BF_EXT_EXP_BITS_MAX (BF_EXP_BITS_MAX + 1)
Definition at line 69 of file libbf.h.
BF_PREC_MIN
#define BF_PREC_MIN 2
Definition at line 71 of file libbf.h.
BF_PREC_MAX
#define BF_PREC_MAX (((limb_t)1 << (LIMB_BITS - 2)) - 2)
Definition at line 73 of file libbf.h.
BF_PREC_INF
#define BF_PREC_INF (BF_PREC_MAX + 1) /* infinite precision */
Definition at line 75 of file libbf.h.
BF_CHKSUM_MOD
#define BF_CHKSUM_MOD (UINT64_C(975620677) * UINT64_C(9795002197))
Definition at line 78 of file libbf.h.
BF_EXP_ZERO
#define BF_EXP_ZERO BF_RAW_EXP_MIN
Definition at line 83 of file libbf.h.
BF_EXP_INF
#define BF_EXP_INF (BF_RAW_EXP_MAX - 1)
Definition at line 84 of file libbf.h.
BF_EXP_NAN
#define BF_EXP_NAN BF_RAW_EXP_MAX
Definition at line 85 of file libbf.h.
BF_FLAG_SUBNORMAL
#define BF_FLAG_SUBNORMAL (1 << 3)
Definition at line 121 of file libbf.h.
BF_FLAG_RADPNT_PREC
#define BF_FLAG_RADPNT_PREC (1 << 4)
Definition at line 125 of file libbf.h.
BF_RND_MASK
#define BF_RND_MASK 0x7
Definition at line 127 of file libbf.h.
BF_EXP_BITS_SHIFT
#define BF_EXP_BITS_SHIFT 5
Definition at line 128 of file libbf.h.
BF_EXP_BITS_MASK
#define BF_EXP_BITS_MASK 0x3f
Definition at line 129 of file libbf.h.
BF_FLAG_EXT_EXP
#define BF_FLAG_EXT_EXP (BF_EXP_BITS_MASK << BF_EXP_BITS_SHIFT)
Definition at line 132 of file libbf.h.
BF_ST_INVALID_OP
#define BF_ST_INVALID_OP (1 << 0)
Definition at line 168 of file libbf.h.
BF_ST_DIVIDE_ZERO
#define BF_ST_DIVIDE_ZERO (1 << 1)
Definition at line 169 of file libbf.h.
BF_ST_OVERFLOW
#define BF_ST_OVERFLOW (1 << 2)
Definition at line 170 of file libbf.h.
BF_ST_UNDERFLOW
#define BF_ST_UNDERFLOW (1 << 3)
Definition at line 171 of file libbf.h.
BF_ST_INEXACT
#define BF_ST_INEXACT (1 << 4)
Definition at line 172 of file libbf.h.
BF_ST_MEM_ERROR
#define BF_ST_MEM_ERROR (1 << 5)
Definition at line 174 of file libbf.h.
BF_RADIX_MAX
#define BF_RADIX_MAX 36 /* maximum radix for bf_atof() and bf_ftoa() */
Definition at line 176 of file libbf.h.
BF_DIVREM_EUCLIDIAN
#define BF_DIVREM_EUCLIDIAN BF_RNDF
Definition at line 291 of file libbf.h.
BF_ATOF_NO_HEX
#define BF_ATOF_NO_HEX (1 << 16)
Definition at line 310 of file libbf.h.
BF_ATOF_BIN_OCT
#define BF_ATOF_BIN_OCT (1 << 17)
Definition at line 312 of file libbf.h.
BF_ATOF_NO_NAN_INF
#define BF_ATOF_NO_NAN_INF (1 << 18)
Definition at line 314 of file libbf.h.
BF_ATOF_EXPONENT
#define BF_ATOF_EXPONENT (1 << 19)
Definition at line 316 of file libbf.h.
BF_FTOA_FORMAT_MASK
#define BF_FTOA_FORMAT_MASK (3 << 16)
Definition at line 335 of file libbf.h.
BF_FTOA_FORMAT_FIXED
#define BF_FTOA_FORMAT_FIXED (0 << 16)
Definition at line 340 of file libbf.h.
BF_FTOA_FORMAT_FRAC
#define BF_FTOA_FORMAT_FRAC (1 << 16)
Definition at line 343 of file libbf.h.
BF_FTOA_FORMAT_FREE
#define BF_FTOA_FORMAT_FREE (2 << 16)
Definition at line 357 of file libbf.h.
BF_FTOA_FORMAT_FREE_MIN
#define BF_FTOA_FORMAT_FREE_MIN (3 << 16)
Definition at line 361 of file libbf.h.
BF_FTOA_FORCE_EXP
#define BF_FTOA_FORCE_EXP (1 << 20)
Definition at line 364 of file libbf.h.
BF_FTOA_ADD_PREFIX
#define BF_FTOA_ADD_PREFIX (1 << 21)
Definition at line 367 of file libbf.h.
BF_FTOA_JS_QUIRKS
#define BF_FTOA_JS_QUIRKS (1 << 22)
Definition at line 370 of file libbf.h.
BF_GET_INT_MOD
#define BF_GET_INT_MOD (1 << 0)
Definition at line 376 of file libbf.h.
BF_POW_JS_QUIRKS
#define BF_POW_JS_QUIRKS (1 << 16) /* (+/-1)^(+/-Inf) = NaN, 1^NaN = NaN */
Definition at line 405 of file libbf.h.
Typedef Documentation
int128_t
typedef __int128 int128_t
Definition at line 39 of file libbf.h.
uint128_t
typedef unsigned __int128 uint128_t
Definition at line 40 of file libbf.h.
slimb_t
typedef int64_t slimb_t
Definition at line 41 of file libbf.h.
limb_t
typedef uint64_t limb_t
Definition at line 42 of file libbf.h.
dlimb_t
typedef uint128_t dlimb_t
Definition at line 43 of file libbf.h.
bf_flags_t
typedef uint32_t bf_flags_t
Definition at line 135 of file libbf.h.
bf_realloc_func_t
typedef void* bf_realloc_func_t(void *opaque, void *ptr, size_t size)
Definition at line 137 of file libbf.h.
bf_context_t
typedef struct bf_context_t bf_context_t
Enumeration Type Documentation
bf_rnd_t
enum bf_rnd_t
Enumerator
BF_RNDN
BF_RNDZ
BF_RNDD
BF_RNDU
BF_RNDNA
BF_RNDA
BF_RNDF
Definition at line 108 of file libbf.h.
              {
     BF_RNDN, /* round to nearest, ties to even */
     BF_RNDZ, /* round to zero */
     BF_RNDD, /* round to -inf (the code relies on (BF_RNDD xor BF_RNDU) = 1) */
     BF_RNDU, /* round to +inf */
     BF_RNDNA, /* round to nearest, ties away from zero */
     BF_RNDA, /* round away from zero */
     BF_RNDF, /* faithful rounding (nondeterministic, either RNDD or RNDU,
                 inexact flag is always set)  */
 } bf_rnd_t;
Function Documentation
bf_get_exp_bits()
static int bf_get_exp_bits (bf_flags_t flags) inline static
Definition at line 152 of file libbf.h.
Referenced by __bf_round(), __bfdec_round(), bf_set_overflow(), and check_exp_underflow_overflow().
 {
     int e;
     e = (flags >> BF_EXP_BITS_SHIFT) & BF_EXP_BITS_MASK;
     if (e == BF_EXP_BITS_MASK)
         return BF_EXP_BITS_MAX + 1;
     else
         return BF_EXP_BITS_MAX - e;
 }
bf_set_exp_bits()
static bf_flags_t bf_set_exp_bits (int n) inline static
Definition at line 162 of file libbf.h.
Referenced by bf_get_float64().
 {
     return ((BF_EXP_BITS_MAX - n) & BF_EXP_BITS_MASK) << BF_EXP_BITS_SHIFT;
 }
bf_max()
static slimb_t bf_max (slimb_t a, slimb_t b) inline static
Definition at line 178 of file libbf.h.
Referenced by __bf_div(), __bfdec_div(), bf_add_internal(), bf_add_limb(), bf_asin(), bf_atan(), bf_cmpu(), bf_ftoa_internal(), bf_get_rnd_add(), bf_logic_op(), bf_mul_2exp(), bf_sin(), bf_sincos(), bf_tan(), bf_tdivremu(), bfdec_add_internal(), bfdec_get_rnd_add(), and bfdec_sqrt().
 {
     if (a > b)
         return a;
     else
         return b;
 }
bf_min()
static slimb_t bf_min (slimb_t a, slimb_t b) inline static
Definition at line 186 of file libbf.h.
Referenced by bf_add_internal(), bf_get_fft_size(), bf_logic_op(), bf_mul(), bf_mul_2exp(), bf_sqrt(), bfdec_sqrt(), count_cancelled_bits(), limb_to_ntt(), mp_divnorm(), mp_mul(), ntt_conv(), ntt_to_limb(), and output_digits().
 {
     if (a < b)
         return a;
     else
         return b;
 }
bf_context_init()
void bf_context_init (bf_context_t * s, bf_realloc_func_t * realloc_func, void * realloc_opaque)
Definition at line 171 of file libbf.c.
References bf_context_t::realloc_func, and bf_context_t::realloc_opaque.
 {
     memset(s, 0, sizeof(*s));
     s->realloc_func = realloc_func;
     s->realloc_opaque = realloc_opaque;
 }
bf_context_end()
void bf_context_end (bf_context_t * s)
Definition at line 179 of file libbf.c.
References bf_clear_cache().
 {
     bf_clear_cache(s);
 }
bf_clear_cache()
void bf_clear_cache (bf_context_t * s)
Definition at line 4206 of file libbf.c.
References bf_const_free(), fft_clear_cache(), bf_context_t::log2_cache, and bf_context_t::pi_cache.
Referenced by bf_context_end().
 {
 #ifdef USE_FFT_MUL
     fft_clear_cache(s);
 #endif
     bf_const_free(&s->log2_cache);
     bf_const_free(&s->pi_cache);
 }
bf_realloc()
static void* bf_realloc (bf_context_t * s, void * ptr, size_t size) inline static
Definition at line 200 of file libbf.h.
References bf_context_t::realloc_func, and bf_context_t::realloc_opaque.
Referenced by bf_delete(), bf_free(), and bf_malloc().
 {
     return s->realloc_func(s->realloc_opaque, ptr, size);
 }
bf_malloc()
static void* bf_malloc (bf_context_t * s, size_t size) inline static
Definition at line 206 of file libbf.h.
References bf_realloc().
Referenced by ntt_malloc().
 {
     return bf_realloc(s, NULL, size);
 }
bf_free()
static void bf_free (bf_context_t * s, void * ptr) inline static
Definition at line 211 of file libbf.h.
References bf_realloc().
Referenced by __bf_div(), __bfdec_div(), bf_ftoa_internal(), bf_integer_from_radix(), bf_integer_to_radix(), bf_move(), bf_sqrt(), bfdec_add_internal(), bfdec_sqrt(), fft_clear_cache(), mp_div_dec(), mp_divnorm_large(), mp_recip(), mp_sqrtrem(), mp_sqrtrem_dec(), and ntt_free().
 {
     /* must test ptr otherwise equivalent to malloc(0) */
     if (ptr)
         bf_realloc(s, ptr, 0);
 }
bf_init()
void bf_init (bf_context_t * s, bf_t * r)
Definition at line 184 of file libbf.c.
References bf_t::ctx, bf_t::expn, bf_t::len, bf_t::sign, and bf_t::tab.
Referenced by bf_acos(), bf_add_epsilon(), bf_add_si(), bf_asin(), bf_asin_internal(), bf_atan(), bf_atan2_internal(), bf_atan_internal(), bf_atof_internal(), bf_const_get(), bf_const_log2_internal(), bf_const_log2_rec(), bf_const_pi_internal(), bf_convert_to_radix(), bf_exp_internal(), bf_ftoa_internal(), bf_get_float64(), bf_integer_from_radix(), bf_integer_from_radix_rec(), bf_integer_to_radix(), bf_integer_to_radix_rec(), bf_log(), bf_log_internal(), bf_logic_op(), bf_mul(), bf_mul_pow_radix(), bf_mul_si(), bf_mul_ui(), bf_op2(), bf_pow(), bf_pow_generic(), bf_pow_int(), bf_pow_ui_ui(), bf_rem(), bf_remquo(), bf_sincos(), bf_sqrt_sin(), bf_sqrtrem(), bf_tan_internal(), bfdec_init(), check_exact_power2n(), check_exp_underflow_overflow(), chud_bs(), and output_digits().
 {
     r->ctx = s;
     r->sign = 0;
     r->expn = BF_EXP_ZERO;
     r->len = 0;
     r->tab = NULL;
 }
bf_delete()
static void bf_delete (bf_t * r) inline static
Definition at line 220 of file libbf.h.
References bf_realloc(), bf_t::ctx, and bf_t::tab.
Referenced by bf_acos(), bf_add_epsilon(), bf_add_si(), bf_asin(), bf_asin_internal(), bf_atan(), bf_atan2_internal(), bf_atan_internal(), bf_atof_internal(), bf_const_free(), bf_const_log2_internal(), bf_const_log2_rec(), bf_const_pi_internal(), bf_convert_to_radix(), bf_exp_internal(), bf_ftoa_internal(), bf_get_float64(), bf_integer_from_radix(), bf_integer_from_radix_rec(), bf_integer_to_radix(), bf_integer_to_radix_rec(), bf_log(), bf_log_internal(), bf_logic_op(), bf_mul_pow_radix(), bf_mul_si(), bf_mul_ui(), bf_pow(), bf_pow_generic(), bf_pow_int(), bf_pow_ui_ui(), bf_rem(), bf_remquo(), bf_sincos(), bf_sqrt_sin(), bf_sqrtrem(), bf_tan_internal(), bfdec_delete(), check_exp_underflow_overflow(), chud_bs(), and output_digits().
 {
     bf_context_t *s = r->ctx;
     /* we accept to delete a zeroed bf_t structure */
     if (s && r->tab) {
         bf_realloc(s, r->tab, 0);
     }
 }
bf_neg()
static void bf_neg (bf_t * r) inline static
Definition at line 229 of file libbf.h.
References bf_t::sign.
Referenced by bf_asin_internal(), bf_atan_internal(), bf_pow(), bf_sincos(), bf_sqrt_sin(), and bf_sqrtrem().
 {
     r->sign ^= 1;
 }
bf_is_finite()
static int bf_is_finite (const bf_t * a) inline static
Definition at line 234 of file libbf.h.
References bf_t::expn.
Referenced by bf_get_float64(), and bf_mul_pow_radix().
 {
     return (a->expn < BF_EXP_INF);
 }
bf_is_nan()
static int bf_is_nan (const bf_t * a) inline static
Definition at line 239 of file libbf.h.
References bf_t::expn.
Referenced by bf_divrem(), bf_pow_generic(), and bf_sqrtrem().
 {
     return (a->expn == BF_EXP_NAN);
 }
bf_is_zero()
static int bf_is_zero (const bf_t * a) inline static
Definition at line 244 of file libbf.h.
References bf_t::expn.
 {
     return (a->expn == BF_EXP_ZERO);
 }
bf_memcpy()
static void bf_memcpy (bf_t * r, const bf_t * a) inline static
Definition at line 249 of file libbf.h.
Referenced by bfdec_memcpy().
 {
     *r = *a;
 }
bf_set_ui()
int bf_set_ui (bf_t * r, uint64_t a)
Definition at line 209 of file libbf.c.
References bf_resize(), bf_set_nan(), clz(), bf_t::expn, bf_t::sign, and bf_t::tab.
Referenced by bf_acos(), bf_add_epsilon(), bf_asin(), bf_atan(), bf_atan2_internal(), bf_atan_internal(), bf_const_log2_rec(), bf_const_pi_internal(), bf_cos(), bf_exp(), bf_exp_internal(), bf_integer_from_radix_rec(), bf_integer_to_radix_rec(), bf_log(), bf_log_internal(), bf_mul_ui(), bf_pow(), bf_pow_int(), bf_pow_ui(), bf_pow_ui_ui(), bf_set_si(), bf_sincos(), bf_sqrtrem(), bf_tdivremu(), check_exp_underflow_overflow(), and chud_bs().
 {
     r->sign = 0;
     if (a == 0) {
         r->expn = BF_EXP_ZERO;
         bf_resize(r, 0); /* cannot fail */
     }
 #if LIMB_BITS == 32
     else if (a <= 0xffffffff)
 #else
     else
 #endif
     {
         int shift;
         if (bf_resize(r, 1))
             goto fail;
         shift = clz(a);
         r->tab[0] = a << shift;
         r->expn = LIMB_BITS - shift;
     }
 #if LIMB_BITS == 32
     else {
         uint32_t a1, a0;
         int shift;
         if (bf_resize(r, 2))
             goto fail;
         a0 = a;
         a1 = a >> 32;
         shift = clz(a1);
         r->tab[0] = a0 << shift;
         r->tab[1] = (a1 << shift) | (a0 >> (LIMB_BITS - shift));
         r->expn = 2 * LIMB_BITS - shift;
     }
 #endif
     return 0;
  fail:
     bf_set_nan(r);
     return BF_ST_MEM_ERROR;
 }
bf_set_si()
int bf_set_si (bf_t * r, int64_t a)
Definition at line 250 of file libbf.c.
References bf_set_ui(), and bf_t::sign.
Referenced by bf_add_si(), bf_atan_internal(), and bf_mul_si().
 {
     int ret;
     if (a < 0) {
         ret = bf_set_ui(r, -a);
         r->sign = 1;
     } else {
         ret = bf_set_ui(r, a);
     }
     return ret;
 }
bf_set_nan()
void bf_set_nan (bf_t * r)
Definition at line 263 of file libbf.c.
References bf_resize(), bf_t::expn, and bf_t::sign.
Referenced by __bf_div(), bf_acos(), bf_add_internal(), bf_asin(), bf_atan(), bf_atan2_internal(), bf_atof_internal(), bf_cos(), bf_divrem(), bf_exp(), bf_log(), bf_logic_op(), bf_mul(), bf_pow(), bf_pow_generic(), bf_set(), bf_set_float64(), bf_set_overflow(), bf_set_ui(), bf_sin(), bf_sqrt(), bf_sqrtrem(), bf_tan(), and bfdec_set_nan().
 {
     bf_resize(r, 0); /* cannot fail */
     r->expn = BF_EXP_NAN;
     r->sign = 0;
 }
bf_set_zero()
void bf_set_zero (bf_t * r, int is_neg)
Definition at line 270 of file libbf.c.
References bf_resize(), bf_t::expn, and bf_t::sign.
Referenced by __bf_div(), __bf_round(), bf_acos(), bf_add_internal(), bf_asin(), bf_atan(), bf_atof_internal(), bf_divrem(), bf_exp(), bf_log(), bf_mul(), bf_pow(), bf_set_float64(), bf_sin(), bf_tan(), bfdec_set_zero(), and check_exp_underflow_overflow().
 {
     bf_resize(r, 0); /* cannot fail */
     r->expn = BF_EXP_ZERO;
     r->sign = is_neg;
 }
bf_set_inf()
void bf_set_inf (bf_t * r, int is_neg)
Definition at line 277 of file libbf.c.
References bf_resize(), bf_t::expn, and bf_t::sign.
Referenced by __bf_div(), bf_add_internal(), bf_atof_internal(), bf_exp(), bf_log(), bf_mul(), bf_pow(), bf_set_float64(), bf_set_overflow(), and bfdec_set_inf().
 {
     bf_resize(r, 0); /* cannot fail */
     r->expn = BF_EXP_INF;
     r->sign = is_neg;
 }
bf_set()
int bf_set (bf_t * r, const bf_t * a)
Definition at line 285 of file libbf.c.
References bf_resize(), bf_set_nan(), bf_t::expn, bf_t::len, bf_t::sign, and bf_t::tab.
Referenced by bf_add_internal(), bf_asin(), bf_atan(), bf_atan_internal(), bf_atof_internal(), bf_const_get(), bf_const_log2_rec(), bf_convert_to_radix(), bf_divrem(), bf_ftoa_internal(), bf_get_float64(), bf_log_internal(), bf_mul_pow_radix(), bf_pow(), bf_pow_ui(), bf_sin(), bf_sincos(), bf_sqrt(), bf_sqrt_sin(), bf_sqrtrem(), bf_tan(), bf_tdivremu(), bfdec_set(), and check_exact_power2n().
 {
     if (r == a)
         return 0;
     if (bf_resize(r, a->len)) {
         bf_set_nan(r);
         return BF_ST_MEM_ERROR;
     }
     r->sign = a->sign;
     r->expn = a->expn;
     memcpy(r->tab, a->tab, a->len * sizeof(limb_t));
     return 0;
 }
bf_move()
void bf_move (bf_t * r, bf_t * a)
Definition at line 300 of file libbf.c.
References bf_free(), bf_t::ctx, and bf_t::tab.
Referenced by bf_mul(), bf_op2(), and bfdec_move().
 {
     bf_context_t *s = r->ctx;
     if (r == a)
         return;
     bf_free(s, r->tab);
     *r = *a;
 }
bf_get_float64()
int bf_get_float64 (const bf_t * a, double * pres, bf_rnd_t rnd_mode)
Definition at line 2433 of file libbf.c.
References bf_delete(), bf_init(), bf_is_finite(), bf_round(), bf_set(), bf_set_exp_bits(), bf_t::ctx, Float64Union::d, bf_t::expn, bf_t::sign, bf_t::tab, and Float64Union::u.
 {
     Float64Union u;
     int e, ret;
     uint64_t m;
     ret = 0;
     if (a->expn == BF_EXP_NAN) {
         u.u = 0x7ff8000000000000; /* quiet nan */
     } else {
         bf_t b_s, *b = &b_s;
         bf_init(a->ctx, b);
         bf_set(b, a);
         if (bf_is_finite(b)) {
             ret = bf_round(b, 53, rnd_mode | BF_FLAG_SUBNORMAL | bf_set_exp_bits(11));
         }
         if (b->expn == BF_EXP_INF) {
             e = (1 << 11) - 1;
             m = 0;
         } else if (b->expn == BF_EXP_ZERO) {
             e = 0;
             m = 0;
         } else {
             e = b->expn + 1023 - 1;
 #if LIMB_BITS == 32
             if (b->len == 2) {
                 m = ((uint64_t)b->tab[1] << 32) | b->tab[0];
             } else {
                 m = ((uint64_t)b->tab[0] << 32);
             }
 #else
             m = b->tab[0];
 #endif
             if (e <= 0) {
                 /* subnormal */
                 m = m >> (12 - e);
                 e = 0;
             } else {
                 m = (m << 1) >> 12;
             }
         }
         u.u = m | ((uint64_t)e << 52) | ((uint64_t)b->sign << 63);
         bf_delete(b);
     }
     *pres = u.d;
     return ret;
 }
bf_set_float64()
int bf_set_float64 (bf_t * a, double d)
Definition at line 2482 of file libbf.c.
References bf_resize(), bf_set_inf(), bf_set_nan(), bf_set_zero(), clz64(), Float64Union::d, bf_t::expn, bf_t::sign, bf_t::tab, and Float64Union::u.
 {
     Float64Union u;
     uint64_t m;
     int shift, e, sgn;
     u.d = d;
     sgn = u.u >> 63;
     e = (u.u >> 52) & ((1 << 11) - 1);
     m = u.u & (((uint64_t)1 << 52) - 1);
     if (e == ((1 << 11) - 1)) {
         if (m != 0) {
             bf_set_nan(a);
         } else {
             bf_set_inf(a, sgn);
         }
     } else if (e == 0) {
         if (m == 0) {
             bf_set_zero(a, sgn);
         } else {
             /* subnormal number */
             m <<= 12;
             shift = clz64(m);
             m <<= shift;
             e = -shift;
             goto norm;
         }
     } else {
         m = (m << 11) | ((uint64_t)1 << 63);
     norm:
         a->expn = e - 1023 + 1;
 #if LIMB_BITS == 32
         if (bf_resize(a, 2))
             goto fail;
         a->tab[0] = m;
         a->tab[1] = m >> 32;
 #else
         if (bf_resize(a, 1))
             goto fail;
         a->tab[0] = m;
 #endif
         a->sign = sgn;
     }
     return 0;
 fail:
     bf_set_nan(a);
     return BF_ST_MEM_ERROR;
 }
bf_cmpu()
int bf_cmpu (const bf_t * a, const bf_t * b)
Definition at line 738 of file libbf.c.
References bf_max(), bf_t::expn, get_limbz(), and bf_t::len.
Referenced by bf_acos(), bf_add_internal(), bf_asin(), bf_atan(), bf_cmp(), bf_cmp_full(), bf_convert_to_radix(), bf_divrem(), bf_ftoa_internal(), bf_integer_to_radix_rec(), bf_pow(), bf_tdivremu(), and bfdec_cmpu().
 {
     slimb_t i;
     limb_t len, v1, v2;
     if (a->expn != b->expn) {
         if (a->expn < b->expn)
             return -1;
         else
             return 1;
     }
     len = bf_max(a->len, b->len);
     for(i = len - 1; i >= 0; i--) {
         v1 = get_limbz(a, a->len - len + i);
         v2 = get_limbz(b, b->len - len + i);
         if (v1 != v2) {
             if (v1 < v2)
                 return -1;
             else
                 return 1;
         }
     }
     return 0;
 }
bf_cmp_full()
int bf_cmp_full (const bf_t * a, const bf_t * b)
Definition at line 764 of file libbf.c.
References bf_cmpu(), bf_t::expn, and bf_t::sign.
Referenced by bfdec_cmp_full().
 {
     int res;
     if (a->expn == BF_EXP_NAN || b->expn == BF_EXP_NAN) {
         if (a->expn == b->expn)
             res = 0;
         else if (a->expn == BF_EXP_NAN)
             res = 1;
         else
             res = -1;
     } else if (a->sign != b->sign) {
         res = 1 - 2 * a->sign;
     } else {
         res = bf_cmpu(a, b);
         if (a->sign)
             res = -res;
     }
     return res;
 }
bf_cmp()
int bf_cmp (const bf_t * a, const bf_t * b)
Definition at line 788 of file libbf.c.
References bf_cmpu(), bf_t::expn, and bf_t::sign.
Referenced by bf_cmp_eq(), bf_cmp_le(), bf_cmp_lt(), and bfdec_cmp().
 {
     int res;
     if (a->expn == BF_EXP_NAN || b->expn == BF_EXP_NAN) {
         res = 2;
     } else if (a->sign != b->sign) {
         if (a->expn == BF_EXP_ZERO && b->expn == BF_EXP_ZERO)
             res = 0;
         else
             res = 1 - 2 * a->sign;
     } else {
         res = bf_cmpu(a, b);
         if (a->sign)
             res = -res;
     }
     return res;
 }
bf_cmp_eq()
static int bf_cmp_eq (const bf_t * a, const bf_t * b) inline static
Definition at line 267 of file libbf.h.
References bf_cmp().
Referenced by bf_log(), and bf_pow().
 {
     return bf_cmp(a, b) == 0;
 }
bf_cmp_le()
static int bf_cmp_le (const bf_t * a, const bf_t * b) inline static
Definition at line 272 of file libbf.h.
References bf_cmp().
 {
     return bf_cmp(a, b) <= 0;
 }
bf_cmp_lt()
static int bf_cmp_lt (const bf_t * a, const bf_t * b) inline static
Definition at line 277 of file libbf.h.
References bf_cmp().
Referenced by bf_log_internal(), and check_exp_underflow_overflow().
 {
     return bf_cmp(a, b) < 0;
 }
bf_add()
int bf_add (bf_t * r, const bf_t * a, const bf_t * b, limb_t prec, bf_flags_t flags)
Definition at line 2206 of file libbf.c.
References __bf_add(), and bf_op2().
Referenced by bf_add_epsilon(), bf_add_si(), bf_atan2_internal(), bf_atan_internal(), bf_const_log2_rec(), bf_const_pi_internal(), bf_integer_from_radix_rec(), bf_integer_to_radix_rec(), bf_log_internal(), bf_sincos(), bf_sqrt_sin(), bf_sqrtrem(), and chud_bs().
 {
     return bf_op2(r, a, b, prec, flags, __bf_add);
 }
bf_sub()
int bf_sub (bf_t * r, const bf_t * a, const bf_t * b, limb_t prec, bf_flags_t flags)
Definition at line 2212 of file libbf.c.
References __bf_sub(), and bf_op2().
Referenced by bf_divrem(), bf_exp_internal(), bf_integer_to_radix_rec(), and bf_tdivremu().
 {
     return bf_op2(r, a, b, prec, flags, __bf_sub);
 }
bf_add_si()
int bf_add_si (bf_t * r, const bf_t * a, int64_t b1, limb_t prec, bf_flags_t flags)
Definition at line 2248 of file libbf.c.
References bf_add(), bf_delete(), bf_init(), bf_set_si(), and bf_t::ctx.
Referenced by bf_asin_internal(), bf_atan_internal(), bf_divrem(), bf_exp_internal(), bf_integer_to_radix_rec(), bf_log_internal(), bf_logic_op(), and bf_sincos().
 {
     bf_t b;
     int ret;
     bf_init(r->ctx, &b);
     ret = bf_set_si(&b, b1);
     ret |= bf_add(r, a, &b, prec, flags);
     bf_delete(&b);
     return ret;
 }
bf_mul()
int bf_mul (bf_t * r, const bf_t * a, const bf_t * b, limb_t prec, bf_flags_t flags)
Definition at line 1524 of file libbf.c.
References bf_init(), bf_min(), bf_move(), bf_normalize_and_round(), bf_resize(), BF_RNDF, bf_set_inf(), bf_set_nan(), bf_set_zero(), bf_t::ctx, bf_t::expn, fft_mul(), bf_t::len, mp_mul_basecase(), bf_t::sign, and bf_t::tab.
Referenced by bf_asin_internal(), bf_atan_internal(), bf_const_log2_rec(), bf_const_pi_internal(), bf_convert_to_radix(), bf_exp_internal(), bf_integer_from_radix_rec(), bf_integer_to_radix_rec(), bf_log_internal(), bf_mul_pow_radix(), bf_mul_si(), bf_mul_ui(), bf_pow(), bf_pow_ui(), bf_sincos(), bf_sqrt_sin(), bf_sqrtrem(), bf_tdivremu(), and chud_bs().
 {
     int ret, r_sign;
     if (a->len < b->len) {
         const bf_t *tmp = a;
         a = b;
         b = tmp;
     }
     r_sign = a->sign ^ b->sign;
     /* here b->len <= a->len */
     if (b->len == 0) {
         if (a->expn == BF_EXP_NAN || b->expn == BF_EXP_NAN) {
             bf_set_nan(r);
             ret = 0;
         } else if (a->expn == BF_EXP_INF || b->expn == BF_EXP_INF) {
             if ((a->expn == BF_EXP_INF && b->expn == BF_EXP_ZERO) ||
                 (a->expn == BF_EXP_ZERO && b->expn == BF_EXP_INF)) {
                 bf_set_nan(r);
                 ret = BF_ST_INVALID_OP;
             } else {
                 bf_set_inf(r, r_sign);
                 ret = 0;
             }
         } else {
             bf_set_zero(r, r_sign);
             ret = 0;
         }
     } else {
         bf_t tmp, *r1 = NULL;
         limb_t a_len, b_len, precl;
         limb_t *a_tab, *b_tab;
         a_len = a->len;
         b_len = b->len;
         if ((flags & BF_RND_MASK) == BF_RNDF) {
             /* faithful rounding does not require using the full inputs */
             precl = (prec + 2 + LIMB_BITS - 1) / LIMB_BITS;
             a_len = bf_min(a_len, precl);
             b_len = bf_min(b_len, precl);
         }
         a_tab = a->tab + a->len - a_len;
         b_tab = b->tab + b->len - b_len;
 #ifdef USE_FFT_MUL
         if (b_len >= FFT_MUL_THRESHOLD) {
             int mul_flags = 0;
             if (r == a)
                 mul_flags |= FFT_MUL_R_OVERLAP_A;
             if (r == b)
                 mul_flags |= FFT_MUL_R_OVERLAP_B;
             if (fft_mul(r->ctx, r, a_tab, a_len, b_tab, b_len, mul_flags))
                 goto fail;
         } else
 #endif
         {
             if (r == a || r == b) {
                 bf_init(r->ctx, &tmp);
                 r1 = r;
                 r = &tmp;
             }
             if (bf_resize(r, a_len + b_len)) {
             fail:
                 bf_set_nan(r);
                 ret = BF_ST_MEM_ERROR;
                 goto done;
             }
             mp_mul_basecase(r->tab, a_tab, a_len, b_tab, b_len);
         }
         r->sign = r_sign;
         r->expn = a->expn + b->expn;
         ret = bf_normalize_and_round(r, prec, flags);
     done:
         if (r == &tmp)
             bf_move(r1, &tmp);
     }
     return ret;
 }
bf_mul_ui()
int bf_mul_ui (bf_t * r, const bf_t * a, uint64_t b1, limb_t prec, bf_flags_t flags)
Definition at line 2224 of file libbf.c.
References bf_delete(), bf_init(), bf_mul(), bf_set_ui(), and bf_t::ctx.
Referenced by bf_const_pi_internal(), bf_sincos(), check_exp_underflow_overflow(), and chud_bs().
 {
     bf_t b;
     int ret;
     bf_init(r->ctx, &b);
     ret = bf_set_ui(&b, b1);
     ret |= bf_mul(r, a, &b, prec, flags);
     bf_delete(&b);
     return ret;
 }
bf_mul_si()
int bf_mul_si (bf_t * r, const bf_t * a, int64_t b1, limb_t prec, bf_flags_t flags)
Definition at line 2236 of file libbf.c.
References bf_delete(), bf_init(), bf_mul(), bf_set_si(), and bf_t::ctx.
Referenced by bf_exp_internal(), bf_log_internal(), bf_pow(), and check_exp_underflow_overflow().
 {
     bf_t b;
     int ret;
     bf_init(r->ctx, &b);
     ret = bf_set_si(&b, b1);
     ret |= bf_mul(r, a, &b, prec, flags);
     bf_delete(&b);
     return ret;
 }
bf_mul_2exp()
int bf_mul_2exp (bf_t * r, slimb_t e, limb_t prec, bf_flags_t flags)
Definition at line 1606 of file libbf.c.
References __bf_round(), bf_max(), bf_min(), bf_t::expn, and bf_t::len.
Referenced by bf_acos(), bf_atan(), bf_atan_internal(), bf_exp_internal(), bf_log_internal(), bf_pow(), bf_sincos(), and bf_sqrt_sin().
 {
     slimb_t e_max;
     if (r->len == 0)
         return 0;
     e_max = ((limb_t)1 << BF_EXT_EXP_BITS_MAX) - 1;
     e = bf_max(e, -e_max);
     e = bf_min(e, e_max);
     r->expn += e;
     return __bf_round(r, prec, flags, r->len, 0);
 }
bf_div()
int bf_div (bf_t * r, const bf_t * a, const bf_t * b, limb_t prec, bf_flags_t flags)
Definition at line 2218 of file libbf.c.
References __bf_div(), and bf_op2().
Referenced by bf_asin_internal(), bf_atan_internal(), bf_const_log2_internal(), bf_const_pi_internal(), bf_convert_to_radix(), bf_exp_internal(), bf_integer_to_radix_rec(), bf_log_internal(), bf_mul_pow_radix(), bf_pow_int(), bf_sincos(), bf_tan_internal(), and bf_tdivremu().
 {
     return bf_op2(r, a, b, prec, flags, __bf_div);
 }
bf_divrem()
int bf_divrem (bf_t * q, bf_t * r, const bf_t * a, const bf_t * b, limb_t prec, bf_flags_t flags, int rnd_mode)
Definition at line 1732 of file libbf.c.
References bf_add_si(), bf_cmpu(), bf_is_nan(), BF_RNDA, BF_RNDD, BF_RNDN, BF_RNDNA, BF_RNDU, BF_RNDZ, bf_round(), bf_set(), bf_set_nan(), bf_set_zero(), bf_sub(), bf_tdivremu(), bf_t::expn, FALSE, get_bit(), bf_t::len, bf_t::sign, bf_t::tab, and TRUE.
Referenced by bf_rem(), and bf_remquo().
 {
     bf_t a1_s, *a1 = &a1_s;
     bf_t b1_s, *b1 = &b1_s;
     int q_sign, ret;
     BOOL is_ceil, is_rndn;
     assert(q != a && q != b);
     assert(r != a && r != b);
     assert(q != r);
     if (a->len == 0 || b->len == 0) {
         bf_set_zero(q, 0);
         if (a->expn == BF_EXP_NAN || b->expn == BF_EXP_NAN) {
             bf_set_nan(r);
             return 0;
         } else if (a->expn == BF_EXP_INF || b->expn == BF_EXP_ZERO) {
             bf_set_nan(r);
             return BF_ST_INVALID_OP;
         } else {
             bf_set(r, a);
             return bf_round(r, prec, flags);
         }
     }
     q_sign = a->sign ^ b->sign;
     is_rndn = (rnd_mode == BF_RNDN || rnd_mode == BF_RNDNA);
     switch(rnd_mode) {
     default:
     case BF_RNDZ:
     case BF_RNDN:
     case BF_RNDNA:
         is_ceil = FALSE;
         break;
     case BF_RNDD:
         is_ceil = q_sign;
         break;
     case BF_RNDU:
         is_ceil = q_sign ^ 1;
         break;
     case BF_RNDA:
         is_ceil = TRUE;
         break;
     case BF_DIVREM_EUCLIDIAN:
         is_ceil = a->sign;
         break;
     }
     a1->expn = a->expn;
     a1->tab = a->tab;
     a1->len = a->len;
     a1->sign = 0;
     b1->expn = b->expn;
     b1->tab = b->tab;
     b1->len = b->len;
     b1->sign = 0;
     /* XXX: could improve to avoid having a large 'q' */
     bf_tdivremu(q, r, a1, b1);
     if (bf_is_nan(q) || bf_is_nan(r))
         goto fail;
     if (r->len != 0) {
         if (is_rndn) {
             int res;
             b1->expn--;
             res = bf_cmpu(r, b1);
             b1->expn++;
             if (res > 0 ||
                 (res == 0 &&
                  (rnd_mode == BF_RNDNA ||
                   get_bit(q->tab, q->len, q->len * LIMB_BITS - q->expn)))) {
                 goto do_sub_r;
             }
         } else if (is_ceil) {
         do_sub_r:
             ret = bf_add_si(q, q, 1, BF_PREC_INF, BF_RNDZ);
             ret |= bf_sub(r, r, b1, BF_PREC_INF, BF_RNDZ);
             if (ret & BF_ST_MEM_ERROR)
                 goto fail;
         }
     }
     r->sign ^= a->sign;
     q->sign = q_sign;
     return bf_round(r, prec, flags);
  fail:
     bf_set_nan(q);
     bf_set_nan(r);
     return BF_ST_MEM_ERROR;
 }
bf_rem()
int bf_rem (bf_t * r, const bf_t * a, const bf_t * b, limb_t prec, bf_flags_t flags, int rnd_mode)
Definition at line 1826 of file libbf.c.
References bf_delete(), bf_divrem(), bf_init(), and bf_t::ctx.
 {
     bf_t q_s, *q = &q_s;
     int ret;
     bf_init(r->ctx, q);
     ret = bf_divrem(q, r, a, b, prec, flags, rnd_mode);
     bf_delete(q);
     return ret;
 }
bf_remquo()
int bf_remquo (slimb_t * pq, bf_t * r, const bf_t * a, const bf_t * b, limb_t prec, bf_flags_t flags, int rnd_mode)
Definition at line 1847 of file libbf.c.
References bf_delete(), bf_divrem(), bf_get_limb(), bf_init(), and bf_t::ctx.
Referenced by bf_sincos().
 {
     bf_t q_s, *q = &q_s;
     int ret;
     bf_init(r->ctx, q);
     ret = bf_divrem(q, r, a, b, prec, flags, rnd_mode);
     bf_get_limb(pq, q, BF_GET_INT_MOD);
     bf_delete(q);
     return ret;
 }
bf_rint()
int bf_rint (bf_t * r, int rnd_mode)
Definition at line 2299 of file libbf.c.
References bf_round().
Referenced by bf_convert_to_radix(), bf_integer_to_radix_rec(), bf_sqrtrem(), and bf_tdivremu().
 {
     return bf_round(r, 0, rnd_mode | BF_FLAG_RADPNT_PREC);
 }
bf_round()
int bf_round (bf_t * r, limb_t prec, bf_flags_t flags)
Definition at line 667 of file libbf.c.
References __bf_round(), and bf_t::len.
Referenced by bf_const_get(), bf_divrem(), bf_ftoa_internal(), bf_get_float64(), bf_mul_pow_radix(), bf_rint(), and bf_sqrt().
 {
     if (r->len == 0)
         return 0;
     return __bf_round(r, prec, flags, r->len, 0);
 }
bf_sqrtrem()
int bf_sqrtrem (bf_t * r, bf_t * rem1, const bf_t * a)
Definition at line 2073 of file libbf.c.
References bf_add(), bf_delete(), bf_init(), bf_is_nan(), bf_mul(), bf_neg(), bf_rint(), BF_RNDZ, bf_set(), bf_set_nan(), bf_set_ui(), bf_sqrt(), bf_t::ctx, bf_t::expn, bf_t::len, and bf_t::sign.
Referenced by check_exact_power2n().
 {
     int ret;
     if (a->len == 0) {
         if (a->expn == BF_EXP_NAN) {
             bf_set_nan(r);
         } else if (a->expn == BF_EXP_INF && a->sign) {
             goto invalid_op;
         } else {
             bf_set(r, a);
         }
         if (rem1)
             bf_set_ui(rem1, 0);
         ret = 0;
     } else if (a->sign) {
  invalid_op:
         bf_set_nan(r);
         if (rem1)
             bf_set_ui(rem1, 0);
         ret = BF_ST_INVALID_OP;
     } else {
         bf_t rem_s, *rem;
         bf_sqrt(r, a, (a->expn + 1) / 2, BF_RNDZ);
         bf_rint(r, BF_RNDZ);
         /* see if the result is exact by computing the remainder */
         if (rem1) {
             rem = rem1;
         } else {
             rem = &rem_s;
             bf_init(r->ctx, rem);
         }
         /* XXX: could avoid recomputing the remainder */
         bf_mul(rem, r, r, BF_PREC_INF, BF_RNDZ);
         bf_neg(rem);
         bf_add(rem, rem, a, BF_PREC_INF, BF_RNDZ);
         if (bf_is_nan(rem)) {
             ret = BF_ST_MEM_ERROR;
             goto done;
         }
         if (rem->len != 0) {
             ret = BF_ST_INEXACT;
         } else {
             ret = 0;
         }
     done:
         if (!rem1)
             bf_delete(rem);
     }
     return ret;
 }
bf_sqrt()
int bf_sqrt (bf_t * r, const bf_t * a, limb_t prec, bf_flags_t flags)
Definition at line 2126 of file libbf.c.
References bf_free(), bf_min(), bf_resize(), bf_round(), bf_set(), bf_set_nan(), bf_t::ctx, bf_t::expn, bf_t::len, mp_scan_nz(), mp_shr(), mp_sqrtrem(), bf_t::sign, and bf_t::tab.
Referenced by bf_asin_internal(), bf_atan_internal(), bf_const_pi_internal(), bf_log_internal(), bf_sqrt_sin(), and bf_sqrtrem().
 {
     bf_context_t *s = a->ctx;
     int ret;
     assert(r != a);
     if (a->len == 0) {
         if (a->expn == BF_EXP_NAN) {
             bf_set_nan(r);
         } else if (a->expn == BF_EXP_INF && a->sign) {
             goto invalid_op;
         } else {
             bf_set(r, a);
         }
         ret = 0;
     } else if (a->sign) {
  invalid_op:
         bf_set_nan(r);
         ret = BF_ST_INVALID_OP;
     } else {
         limb_t *a1;
         slimb_t n, n1;
         limb_t res;
         /* convert the mantissa to an integer with at least 2 *
            prec + 4 bits */
         n = (2 * (prec + 2) + 2 * LIMB_BITS - 1) / (2 * LIMB_BITS);
         if (bf_resize(r, n))
             goto fail;
         a1 = bf_malloc(s, sizeof(limb_t) * 2 * n);
         if (!a1)
             goto fail;
         n1 = bf_min(2 * n, a->len);
         memset(a1, 0, (2 * n - n1) * sizeof(limb_t));
         memcpy(a1 + 2 * n - n1, a->tab + a->len - n1, n1 * sizeof(limb_t));
         if (a->expn & 1) {
             res = mp_shr(a1, a1, 2 * n, 1, 0);
         } else {
             res = 0;
         }
         if (mp_sqrtrem(s, r->tab, a1, n)) {
             bf_free(s, a1);
             goto fail;
         }
         if (!res) {
             res = mp_scan_nz(a1, n + 1);
         }
         bf_free(s, a1);
         if (!res) {
             res = mp_scan_nz(a->tab, a->len - n1);
         }
         if (res != 0)
             r->tab[0] |= 1;
         r->sign = 0;
         r->expn = (a->expn + 1) >> 1;
         ret = bf_round(r, prec, flags);
     }
     return ret;
  fail:
     bf_set_nan(r);
     return BF_ST_MEM_ERROR;
 }
bf_get_exp_min()
slimb_t bf_get_exp_min (const bf_t * a)
Definition at line 1620 of file libbf.c.
References ctz(), bf_t::expn, bf_t::len, and bf_t::tab.
Referenced by bf_pow(), and check_exact_power2n().
 {
     slimb_t i;
     limb_t v;
     int k;
     for(i = 0; i < a->len; i++) {
         v = a->tab[i];
         if (v != 0) {
             k = ctz(v);
             return a->expn - (a->len - i) * LIMB_BITS + k;
         }
     }
     return 0;
 }
bf_logic_or()
int bf_logic_or (bf_t * r, const bf_t * a, const bf_t * b)
Definition at line 2409 of file libbf.c.
References bf_logic_op().
 {
     return bf_logic_op(r, a, b, BF_LOGIC_OR);
 }
bf_logic_xor()
int bf_logic_xor (bf_t * r, const bf_t * a, const bf_t * b)
Definition at line 2415 of file libbf.c.
References bf_logic_op().
 {
     return bf_logic_op(r, a, b, BF_LOGIC_XOR);
 }
bf_logic_and()
int bf_logic_and (bf_t * r, const bf_t * a, const bf_t * b)
Definition at line 2421 of file libbf.c.
References bf_logic_op().
 {
     return bf_logic_op(r, a, b, BF_LOGIC_AND);
 }
bf_atof()
int bf_atof (bf_t * a, const char * str, const char ** pnext, int radix, limb_t prec, bf_flags_t flags)
Definition at line 3145 of file libbf.c.
References bf_atof_internal(), and FALSE.
 {
     slimb_t dummy_exp;
     return bf_atof_internal(r, &dummy_exp, str, pnext, radix, prec, flags, FALSE);
 }
bf_atof2()
int bf_atof2 (bf_t * r, slimb_t * pexponent, const char * str, const char ** pnext, int radix, limb_t prec, bf_flags_t flags)
Definition at line 3137 of file libbf.c.
References bf_atof_internal(), and FALSE.
 {
     return bf_atof_internal(r, pexponent, str, pnext, radix, prec, flags,
                             FALSE);
 }
bf_mul_pow_radix()
int bf_mul_pow_radix (bf_t * r, const bf_t * T, limb_t radix, slimb_t expn, limb_t prec, bf_flags_t flags)
Definition at line 2756 of file libbf.c.
References bf_delete(), bf_div(), bf_init(), bf_is_finite(), bf_mul(), bf_pow_ui_ui(), BF_RNDN, bf_round(), bf_set(), ceil_log2(), bf_t::ctx, and bf_t::len.
Referenced by bf_atof_internal(), and bf_ftoa_internal().
 {
     int ret, expn_sign, overflow;
     slimb_t e, extra_bits, prec1, ziv_extra_bits;
     bf_t B_s, *B = &B_s;
     if (T->len == 0) {
         return bf_set(r, T);
     } else if (expn == 0) {
         ret = bf_set(r, T);
         ret |= bf_round(r, prec, flags);
         return ret;
     }
     e = expn;
     expn_sign = 0;
     if (e < 0) {
         e = -e;
         expn_sign = 1;
     }
     bf_init(r->ctx, B);
     if (prec == BF_PREC_INF) {
         /* infinite precision: only used if the result is known to be exact */
         ret = bf_pow_ui_ui(B, radix, e, BF_PREC_INF, BF_RNDN);
         if (expn_sign) {
             ret |= bf_div(r, T, B, T->len * LIMB_BITS, BF_RNDN);
         } else {
             ret |= bf_mul(r, T, B, BF_PREC_INF, BF_RNDN);
         }
     } else {
         ziv_extra_bits = 16;
         for(;;) {
             prec1 = prec + ziv_extra_bits;
             /* XXX: correct overflow/underflow handling */
             /* XXX: rigorous error analysis needed */
             extra_bits = ceil_log2(e) * 2 + 1;
             ret = bf_pow_ui_ui(B, radix, e, prec1 + extra_bits, BF_RNDN | BF_FLAG_EXT_EXP);
             overflow = !bf_is_finite(B);
             /* XXX: if bf_pow_ui_ui returns an exact result, can stop
                after the next operation */
             if (expn_sign)
                 ret |= bf_div(r, T, B, prec1 + extra_bits, BF_RNDN | BF_FLAG_EXT_EXP);
             else
                 ret |= bf_mul(r, T, B, prec1 + extra_bits, BF_RNDN | BF_FLAG_EXT_EXP);
             if (ret & BF_ST_MEM_ERROR)
                 break;
             if ((ret & BF_ST_INEXACT) &&
                 !bf_can_round(r, prec, flags & BF_RND_MASK, prec1) &&
                 !overflow) {
                 /* and more precision and retry */
                 ziv_extra_bits = ziv_extra_bits  + (ziv_extra_bits / 2);
             } else {
                 /* XXX: need to use __bf_round() to pass the inexact
                    flag for the subnormal case */
                 ret = bf_round(r, prec, flags) | (ret & BF_ST_INEXACT);
                 break;
             }
         }
     }
     bf_delete(B);
     return ret;
 }
bf_ftoa()
char* bf_ftoa (size_t * plen, const bf_t * a, int radix, limb_t prec, bf_flags_t flags)
Definition at line 3994 of file libbf.c.
References bf_ftoa_internal(), and FALSE.
 {
     return bf_ftoa_internal(plen, a, radix, prec, flags, FALSE);
 }
bf_get_int32()
int bf_get_int32 (int * pres, const bf_t * a, int flags)
Definition at line 2533 of file libbf.c.
References bf_t::expn, get_bits(), bf_t::len, bf_t::sign, and bf_t::tab.
 {
     uint32_t v;
     int ret;
     if (a->expn >= BF_EXP_INF) {
         ret = BF_ST_INVALID_OP;
         if (flags & BF_GET_INT_MOD) {
             v = 0;
         } else if (a->expn == BF_EXP_INF) {
             v = (uint32_t)INT32_MAX + a->sign;
         } else {
             v = INT32_MAX;
         }
     } else if (a->expn <= 0) {
         v = 0;
         ret = 0;
     } else if (a->expn <= 31) {
         v = a->tab[a->len - 1] >> (LIMB_BITS - a->expn);
         if (a->sign)
             v = -v;
         ret = 0;
     } else if (!(flags & BF_GET_INT_MOD)) {
         ret = BF_ST_INVALID_OP;
         if (a->sign) {
             v = (uint32_t)INT32_MAX + 1;
             if (a->expn == 32 &&
                 (a->tab[a->len - 1] >> (LIMB_BITS - 32)) == v) {
                 ret = 0;
             }
         } else {
             v = INT32_MAX;
         }
     } else {
         v = get_bits(a->tab, a->len, a->len * LIMB_BITS - a->expn);
         if (a->sign)
             v = -v;
         ret = 0;
     }
     *pres = v;
     return ret;
 }
bf_get_int64()
int bf_get_int64 (int64_t * pres, const bf_t * a, int flags)
Definition at line 2577 of file libbf.c.
References bf_t::expn, get_bits(), bf_t::len, bf_t::sign, and bf_t::tab.
Referenced by bf_get_limb().
 {
     uint64_t v;
     int ret;
     if (a->expn >= BF_EXP_INF) {
         ret = BF_ST_INVALID_OP;
         if (flags & BF_GET_INT_MOD) {
             v = 0;
         } else if (a->expn == BF_EXP_INF) {
             v = (uint64_t)INT64_MAX + a->sign;
         } else {
             v = INT64_MAX;
         }
     } else if (a->expn <= 0) {
         v = 0;
         ret = 0;
     } else if (a->expn <= 63) {
 #if LIMB_BITS == 32
         if (a->expn <= 32)
             v = a->tab[a->len - 1] >> (LIMB_BITS - a->expn);
         else
             v = (((uint64_t)a->tab[a->len - 1] << 32) |
                  get_limbz(a, a->len - 2)) >> (64 - a->expn);
 #else
         v = a->tab[a->len - 1] >> (LIMB_BITS - a->expn);
 #endif
         if (a->sign)
             v = -v;
         ret = 0;
     } else if (!(flags & BF_GET_INT_MOD)) {
         ret = BF_ST_INVALID_OP;
         if (a->sign) {
             uint64_t v1;
             v = (uint64_t)INT64_MAX + 1;
             if (a->expn == 64) {
                 v1 = a->tab[a->len - 1];
 #if LIMB_BITS == 32
                 v1 = (v1 << 32) | get_limbz(a, a->len - 2);
 #endif
                 if (v1 == v)
                     ret = 0;
             }
         } else {
             v = INT64_MAX;
         }
     } else {
         slimb_t bit_pos = a->len * LIMB_BITS - a->expn;
         v = get_bits(a->tab, a->len, bit_pos);
 #if LIMB_BITS == 32
         v |= (uint64_t)get_bits(a->tab, a->len, bit_pos + 32) << 32;
 #endif
         if (a->sign)
             v = -v;
         ret = 0;
     }
     *pres = v;
     return ret;
 }
bf_get_uint64()
int bf_get_uint64 (uint64_t * pres, const bf_t * a)
Definition at line 2638 of file libbf.c.
References bf_t::expn, bf_t::len, bf_t::sign, and bf_t::tab.
 {
     uint64_t v;
     int ret;
     if (a->expn == BF_EXP_NAN) {
         goto overflow;
     } else if (a->expn <= 0) {
         v = 0;
         ret = 0;
     } else if (a->sign) {
         v = 0;
         ret = BF_ST_INVALID_OP;
     } else if (a->expn <= 64) {
 #if LIMB_BITS == 32
         if (a->expn <= 32)
             v = a->tab[a->len - 1] >> (LIMB_BITS - a->expn);
         else
             v = (((uint64_t)a->tab[a->len - 1] << 32) |
                  get_limbz(a, a->len - 2)) >> (64 - a->expn);
 #else
         v = a->tab[a->len - 1] >> (LIMB_BITS - a->expn);
 #endif
         ret = 0;
     } else {
     overflow:
         v = UINT64_MAX;
         ret = BF_ST_INVALID_OP;
     }
     *pres = v;
     return ret;
 }
mp_print_str()
void mp_print_str (const char * str, const limb_t * tab, limb_t n)
Definition at line 685 of file libbf.c.
 {
     slimb_t i;
     printf("%s= 0x", str);
     for(i = n - 1; i >= 0; i--) {
         if (i != (n - 1))
             printf("_");
         printf(FMT_LIMB, tab[i]);
     }
     printf("\n");
 }
bf_print_str()
void bf_print_str (const char * str, const bf_t * a)
Definition at line 712 of file libbf.c.
References bf_t::expn, bf_t::len, bf_t::sign, and bf_t::tab.
 {
     slimb_t i;
     printf("%s=", str);
     if (a->expn == BF_EXP_NAN) {
         printf("NaN");
     } else {
         if (a->sign)
             putchar('-');
         if (a->expn == BF_EXP_ZERO) {
             putchar('0');
         } else if (a->expn == BF_EXP_INF) {
             printf("Inf");
         } else {
             printf("0x0.");
             for(i = a->len - 1; i >= 0; i--)
                 printf(FMT_LIMB, a->tab[i]);
             printf("p%" PRId_LIMB, a->expn);
         }
     }
     printf("\n");
 }
bf_resize()
int bf_resize (bf_t * r, limb_t len)
Definition at line 194 of file libbf.c.
References bf_t::len, and bf_t::tab.
Referenced by __bf_div(), __bf_round(), bf_add_internal(), bf_atof_internal(), bf_logic_op(), bf_mul(), bf_normalize_and_round(), bf_set(), bf_set_float64(), bf_set_inf(), bf_set_nan(), bf_set_overflow(), bf_set_ui(), bf_set_zero(), bf_sqrt(), bfdec_resize(), fft_mul(), and output_digits().
 {
     limb_t *tab;
     if (len != r->len) {
         tab = bf_realloc(r->ctx, r->tab, len * sizeof(limb_t));
         if (!tab && len != 0)
             return -1;
         r->tab = tab;
         r->len = len;
     }
     return 0;
 }
bf_get_fft_size()
int bf_get_fft_size (int * pdpl, int * pnb_mods, limb_t len)
Definition at line 8308 of file libbf.c.
References bf_min(), ceil_log2(), and ntt_int_bits.
Referenced by fft_mul().
 {
     int dpl, fft_len_log2, n_bits, nb_mods, dpl_found, fft_len_log2_found;
     int int_bits, nb_mods_found;
     limb_t cost, min_cost;
     min_cost = -1;
     dpl_found = 0;
     nb_mods_found = 4;
     fft_len_log2_found = 0;
     for(nb_mods = 3; nb_mods <= NB_MODS; nb_mods++) {
         int_bits = ntt_int_bits[NB_MODS - nb_mods];
         dpl = bf_min((int_bits - 4) / 2,
                      2 * LIMB_BITS + 2 * NTT_MOD_LOG2_MIN - NTT_MOD_LOG2_MAX);
         for(;;) {
             fft_len_log2 = ceil_log2((len * LIMB_BITS + dpl - 1) / dpl);
             if (fft_len_log2 > NTT_PROOT_2EXP)
                 goto next;
             n_bits = fft_len_log2 + 2 * dpl;
             if (n_bits <= int_bits) {
                 cost = ((limb_t)(fft_len_log2 + 1) << fft_len_log2) * nb_mods;
                 //                printf("n=%d dpl=%d: cost=%" PRId64 "\n", nb_mods, dpl, (int64_t)cost);
                 if (cost < min_cost) {
                     min_cost = cost;
                     dpl_found = dpl;
                     nb_mods_found = nb_mods;
                     fft_len_log2_found = fft_len_log2;
                 }
                 break;
             }
             dpl--;
             if (dpl == 0)
                 break;
         }
     next: ;
     }
     if (!dpl_found)
         abort();
     /* limit dpl if possible to reduce fixed cost of limb/NTT conversion */
     if (dpl_found > (LIMB_BITS + NTT_MOD_LOG2_MIN) &&
         ((limb_t)(LIMB_BITS + NTT_MOD_LOG2_MIN) << fft_len_log2_found) >=
         len * LIMB_BITS) {
         dpl_found = LIMB_BITS + NTT_MOD_LOG2_MIN;
     }
     *pnb_mods = nb_mods_found;
     *pdpl = dpl_found;
     return fft_len_log2_found;
 }
bf_normalize_and_round()
int bf_normalize_and_round (bf_t * r, limb_t prec1, bf_flags_t flags)
Definition at line 592 of file libbf.c.
References __bf_round(), bf_resize(), clz(), bf_t::expn, bf_t::len, and bf_t::tab.
Referenced by __bf_div(), bf_add_internal(), bf_atof_internal(), bf_logic_op(), and bf_mul().
 {
     limb_t l, v, a;
     int shift, ret;
     slimb_t i;
     //    bf_print_str("bf_renorm", r);
     l = r->len;
     while (l > 0 && r->tab[l - 1] == 0)
         l--;
     if (l == 0) {
         /* zero */
         r->expn = BF_EXP_ZERO;
         bf_resize(r, 0); /* cannot fail */
         ret = 0;
     } else {
         r->expn -= (r->len - l) * LIMB_BITS;
         /* shift to have the MSB set to '1' */
         v = r->tab[l - 1];
         shift = clz(v);
         if (shift != 0) {
             v = 0;
             for(i = 0; i < l; i++) {
                 a = r->tab[i];
                 r->tab[i] = (a << shift) | (v >> (LIMB_BITS - shift));
                 v = a;
             }
             r->expn -= shift;
         }
         ret = __bf_round(r, prec1, flags, l, 0);
     }
     //    bf_print_str("r_final", r);
     return ret;
 }
bf_can_round()
int bf_can_round (const bf_t * a, slimb_t prec, bf_rnd_t rnd_mode, slimb_t k)
Definition at line 631 of file libbf.c.
References BF_RNDF, BF_RNDN, BF_RNDNA, bf_t::expn, FALSE, get_bit(), bf_t::len, bf_t::tab, and TRUE.
Referenced by bf_convert_to_radix().
 {
     BOOL is_rndn;
     slimb_t bit_pos, n;
     limb_t bit;
     if (a->expn == BF_EXP_INF || a->expn == BF_EXP_NAN)
         return FALSE;
     if (rnd_mode == BF_RNDF) {
         return (k >= (prec + 1));
     }
     if (a->expn == BF_EXP_ZERO)
         return FALSE;
     is_rndn = (rnd_mode == BF_RNDN || rnd_mode == BF_RNDNA);
     if (k < (prec + 2))
         return FALSE;
     bit_pos = a->len * LIMB_BITS - 1 - prec;
     n = k - prec;
     /* bit pattern for RNDN or RNDNA: 0111.. or 1000...
        for other rounding modes: 000... or 111...
     */
     bit = get_bit(a->tab, a->len, bit_pos);
     bit_pos--;
     n--;
     bit ^= is_rndn;
     /* XXX: slow, but a few iterations on average */
     while (n != 0) {
         if (get_bit(a->tab, a->len, bit_pos) != bit)
             return TRUE;
         bit_pos--;
         n--;
     }
     return FALSE;
 }
bf_mul_log2_radix()
slimb_t bf_mul_log2_radix (slimb_t a1, unsigned int radix, int is_inv, int is_ceil1)
Definition at line 3315 of file libbf.c.
References ceil_log2(), inv_log2_radix, and log2_radix.
Referenced by bf_convert_to_radix(), and bf_ftoa_internal().
 {
     int is_neg;
     limb_t a;
     BOOL is_ceil;
     is_ceil = is_ceil1;
     a = a1;
     if (a1 < 0) {
         a = -a;
         is_neg = 1;
     } else {
         is_neg = 0;
     }
     is_ceil ^= is_neg;
     if ((radix & (radix - 1)) == 0) {
         int radix_bits;
         /* radix is a power of two */
         radix_bits = ceil_log2(radix);
         if (is_inv) {
             if (is_ceil)
                 a += radix_bits - 1;
             a = a / radix_bits;
         } else {
             a = a * radix_bits;
         }
     } else {
         const uint32_t *tab;
         limb_t b0, b1;
         dlimb_t t;
         if (is_inv) {
             tab = inv_log2_radix[radix - 2];
 #if LIMB_BITS == 32
             b1 = tab[0];
             b0 = tab[1];
 #else
             b1 = ((limb_t)tab[0] << 32) | tab[1];
             b0 = (limb_t)tab[2] << 32;
 #endif
             t = (dlimb_t)b0 * (dlimb_t)a;
             t = (dlimb_t)b1 * (dlimb_t)a + (t >> LIMB_BITS);
             a = t >> (LIMB_BITS - 1);
         } else {
             b0 = log2_radix[radix - 2];
             t = (dlimb_t)b0 * (dlimb_t)a;
             a = t >> (LIMB_BITS - 3);
         }
         /* a = floor(result) and 'result' cannot be an integer */
         a += is_ceil;
     }
     if (is_neg)
         a = -a;
     return a;
 }
mp_mul()
int mp_mul (bf_context_t * s, limb_t * result, const limb_t * op1, limb_t op1_size, const limb_t * op2, limb_t op2_size)
Definition at line 1176 of file libbf.c.
References bf_min(), fft_mul(), mp_mul_basecase(), and bf_t::tab.
Referenced by mp_divnorm_large(), mp_recip(), and mp_sqrtrem_rec().
 {
 #ifdef USE_FFT_MUL
     if (unlikely(bf_min(op1_size, op2_size) >= FFT_MUL_THRESHOLD)) {
         bf_t r_s, *r = &r_s;
         r->tab = result;
         /* XXX: optimize memory usage in API */
         if (fft_mul(s, r, (limb_t *)op1, op1_size,
                     (limb_t *)op2, op2_size, FFT_MUL_R_NORESIZE))
             return -1;
     } else
 #endif
     {
         mp_mul_basecase(result, op1, op1_size, op2, op2_size);
     }
     return 0;
 }
mp_add()
limb_t mp_add (limb_t * res, const limb_t * op1, const limb_t * op2, limb_t n, limb_t carry)
Definition at line 1024 of file libbf.c.
Referenced by mp_divnorm(), mp_recip(), and mp_sqrtrem_rec().
 {
     slimb_t i;
     limb_t k, a, v, k1;
     k = carry;
     for(i=0;i<n;i++) {
         v = op1[i];
         a = v + op2[i];
         k1 = a < v;
         a = a + k;
         k = (a < k) | k1;
         res[i] = a;
     }
     return k;
 }
mp_add_ui()
limb_t mp_add_ui (limb_t * tab, limb_t b, size_t n)
Definition at line 1042 of file libbf.c.
Referenced by mp_divnorm_large(), and mp_sqrtrem_rec().
 {
     size_t i;
     limb_t k, a;
     k=b;
     for(i=0;i<n;i++) {
         if (k == 0)
             break;
         a = tab[i] + k;
         k = (a < k);
         tab[i] = a;
     }
     return k;
 }
mp_sqrtrem()
int mp_sqrtrem (bf_context_t * s, limb_t * tabs, limb_t * taba, limb_t n)
Definition at line 2050 of file libbf.c.
References bf_free(), and mp_sqrtrem_rec().
Referenced by bf_sqrt().
 {
     limb_t tmp_buf1[8];
     limb_t *tmp_buf;
     mp_size_t n2;
     int ret;
     n2 = n / 2 + 1;
     if (n2 <= countof(tmp_buf1)) {
         tmp_buf = tmp_buf1;
     } else {
         tmp_buf = bf_malloc(s, sizeof(limb_t) * n2);
         if (!tmp_buf)
             return -1;
     }
     ret = mp_sqrtrem_rec(s, tabs, taba, n, tmp_buf, taba + n);
     if (tmp_buf != tmp_buf1)
         bf_free(s, tmp_buf);
     return ret;
 }
mp_recip()
int mp_recip (bf_context_t * s, limb_t * tabr, const limb_t * taba, limb_t n)
Definition at line 1351 of file libbf.c.
References bf_free(), mp_add(), mp_divnorm(), mp_mul(), mp_neg(), mp_recip(), mp_scan_nz(), mp_sub(), and mp_sub_ui().
Referenced by mp_divnorm_large(), and mp_recip().
 {
     mp_size_t l, h, k, i;
     limb_t *tabxh, *tabt, c, *tabu;
     if (n <= 2) {
         /* return ceil(B^(2*n)/a) - 1 */
         /* XXX: could avoid allocation */
         tabu = bf_malloc(s, sizeof(limb_t) * (2 * n + 1));
         tabt = bf_malloc(s, sizeof(limb_t) * (n + 2));
         if (!tabt || !tabu)
             goto fail;
         for(i = 0; i < 2 * n; i++)
             tabu[i] = 0;
         tabu[2 * n] = 1;
         if (mp_divnorm(s, tabt, tabu, 2 * n + 1, taba, n))
             goto fail;
         for(i = 0; i < n + 1; i++)
             tabr[i] = tabt[i];
         if (mp_scan_nz(tabu, n) == 0) {
             /* only happens for a=B^n/2 */
             mp_sub_ui(tabr, 1, n + 1);
         }
     } else {
         l = (n - 1) / 2;
         h = n - l;
         /* n=2p  -> l=p-1, h = p + 1, k = p + 3
            n=2p+1-> l=p,  h = p + 1; k = p + 2
         */
         tabt = bf_malloc(s, sizeof(limb_t) * (n + h + 1));
         tabu = bf_malloc(s, sizeof(limb_t) * (n + 2 * h - l + 2));
         if (!tabt || !tabu)
             goto fail;
         tabxh = tabr + l;
         if (mp_recip(s, tabxh, taba + l, h))
             goto fail;
         if (mp_mul(s, tabt, taba, n, tabxh, h + 1)) /* n + h + 1 limbs */
             goto fail;
         while (tabt[n + h] != 0) {
             mp_sub_ui(tabxh, 1, h + 1);
             c = mp_sub(tabt, tabt, taba, n, 0);
             mp_sub_ui(tabt + n, c, h + 1);
         }
         /* T = B^(n+h) - T */
         mp_neg(tabt, tabt, n + h + 1, 0);
         tabt[n + h]++;
         if (mp_mul(s, tabu, tabt + l, n + h + 1 - l, tabxh, h + 1))
             goto fail;
         /* n + 2*h - l + 2 limbs */
         k = 2 * h - l;
         for(i = 0; i < l; i++)
             tabr[i] = tabu[i + k];
         mp_add(tabr + l, tabr + l, tabu + 2 * h, h, 0);
     }
     bf_free(s, tabt);
     bf_free(s, tabu);
     return 0;
  fail:
     bf_free(s, tabt);
     bf_free(s, tabu);
     return -1;
 }
bf_isqrt()
limb_t bf_isqrt (limb_t a)
Definition at line 1931 of file libbf.c.
References clz(), and mp_sqrtrem1().
Referenced by bf_atan_internal(), bf_exp_internal(), bf_log_internal(), and bf_sincos().
 {
     limb_t s, r;
     int k;
     if (a == 0)
         return 0;
     k = clz(a) & ~1;
     s = mp_sqrtrem1(&r, a << k);
     s >>= (k >> 1);
     return s;
 }
bf_const_log2()
int bf_const_log2 (bf_t * T, limb_t prec, bf_flags_t flags)
Definition at line 4187 of file libbf.c.
References bf_const_get(), bf_const_log2_internal(), bf_t::ctx, and bf_context_t::log2_cache.
Referenced by bf_exp_internal(), bf_log_internal(), and check_exp_underflow_overflow().
 {
     bf_context_t *s = T->ctx;
     return bf_const_get(T, prec, flags, &s->log2_cache, bf_const_log2_internal, 0);
 }
bf_const_pi()
int bf_const_pi (bf_t * T, limb_t prec, bf_flags_t flags)
Definition at line 4201 of file libbf.c.
References bf_const_pi_signed().
Referenced by bf_acos(), bf_atan2_internal(), bf_atan_internal(), and bf_sincos().
 {
     return bf_const_pi_signed(T, 0, prec, flags);
 }
bf_exp()
int bf_exp (bf_t * r, const bf_t * a, limb_t prec, bf_flags_t flags)
Definition at line 4400 of file libbf.c.
References bf_add_epsilon(), bf_exp_internal(), bf_set_inf(), bf_set_nan(), bf_set_ui(), bf_set_zero(), bf_ziv_rounding(), check_exp_underflow_overflow(), bf_t::ctx, bf_t::expn, bf_t::len, and bf_t::sign.
 {
     bf_context_t *s = r->ctx;
     int ret;
     assert(r != a);
     if (a->len == 0) {
         if (a->expn == BF_EXP_NAN) {
             bf_set_nan(r);
         } else if (a->expn == BF_EXP_INF) {
             if (a->sign)
                 bf_set_zero(r, 0);
             else
                 bf_set_inf(r, 0);
         } else {
             bf_set_ui(r, 1);
         }
         return 0;
     }
     ret = check_exp_underflow_overflow(s, r, a, a, prec, flags);
     if (ret)
         return ret;
     if (a->expn < 0 && (-a->expn) >= (prec + 2)) {
         /* small argument case: result = 1 + epsilon * sign(x) */
         bf_set_ui(r, 1);
         return bf_add_epsilon(r, r, -(prec + 2), a->sign, prec, flags);
     }
     return bf_ziv_rounding(r, a, prec, flags, bf_exp_internal, NULL);
 }
bf_log()
int bf_log (bf_t * r, const bf_t * a, limb_t prec, bf_flags_t flags)
Definition at line 4530 of file libbf.c.
References bf_cmp_eq(), bf_delete(), bf_init(), bf_log_internal(), bf_set_inf(), bf_set_nan(), bf_set_ui(), bf_set_zero(), bf_ziv_rounding(), bf_t::ctx, bf_t::expn, bf_t::len, and bf_t::sign.
Referenced by bf_pow(), and bf_pow_generic().
 {
     bf_context_t *s = r->ctx;
     bf_t T_s, *T = &T_s;
     assert(r != a);
     if (a->len == 0) {
         if (a->expn == BF_EXP_NAN) {
             bf_set_nan(r);
             return 0;
         } else if (a->expn == BF_EXP_INF) {
             if (a->sign) {
                 bf_set_nan(r);
                 return BF_ST_INVALID_OP;
             } else {
                 bf_set_inf(r, 0);
                 return 0;
             }
         } else {
             bf_set_inf(r, 1);
             return 0;
         }
     }
     if (a->sign) {
         bf_set_nan(r);
         return BF_ST_INVALID_OP;
     }
     bf_init(s, T);
     bf_set_ui(T, 1);
     if (bf_cmp_eq(a, T)) {
         bf_set_zero(r, 0);
         bf_delete(T);
         return 0;
     }
     bf_delete(T);
     return bf_ziv_rounding(r, a, prec, flags, bf_log_internal, NULL);
 }
bf_pow()
int bf_pow (bf_t * r, const bf_t * x, const bf_t * y, limb_t prec, bf_flags_t flags)
Definition at line 4656 of file libbf.c.
References bf_cmp_eq(), bf_cmpu(), bf_delete(), bf_get_exp_min(), bf_get_limb(), bf_init(), bf_log(), bf_mul(), bf_mul_2exp(), bf_mul_si(), bf_neg(), bf_pow_generic(), bf_pow_int(), bf_pow_ui(), BF_RNDD, BF_RNDF, BF_RNDU, BF_RNDZ, bf_set(), bf_set_inf(), bf_set_nan(), bf_set_overflow(), bf_set_ui(), bf_set_zero(), bf_ziv_rounding(), check_exact_power2n(), check_exp_underflow_overflow(), bf_t::ctx, bf_t::expn, bf_t::len, bf_t::sign, and bf_t::tab.
 {
     bf_context_t *s = r->ctx;
     bf_t T_s, *T = &T_s;
     bf_t ytmp_s;
     BOOL y_is_int, y_is_odd;
     int r_sign, ret, rnd_mode;
     slimb_t y_emin;
     if (x->len == 0 || y->len == 0) {
         if (y->expn == BF_EXP_ZERO) {
             /* pow(x, 0) = 1 */
             bf_set_ui(r, 1);
         } else if (x->expn == BF_EXP_NAN) {
             bf_set_nan(r);
         } else {
             int cmp_x_abs_1;
             bf_set_ui(r, 1);
             cmp_x_abs_1 = bf_cmpu(x, r);
             if (cmp_x_abs_1 == 0 && (flags & BF_POW_JS_QUIRKS) &&
                 (y->expn >= BF_EXP_INF)) {
                 bf_set_nan(r);
             } else if (cmp_x_abs_1 == 0 &&
                        (!x->sign || y->expn != BF_EXP_NAN)) {
                 /* pow(1, y) = 1 even if y = NaN */
                 /* pow(-1, +/-inf) = 1 */
             } else if (y->expn == BF_EXP_NAN) {
                 bf_set_nan(r);
             } else if (y->expn == BF_EXP_INF) {
                 if (y->sign == (cmp_x_abs_1 > 0)) {
                     bf_set_zero(r, 0);
                 } else {
                     bf_set_inf(r, 0);
                 }
             } else {
                 y_emin = bf_get_exp_min(y);
                 y_is_odd = (y_emin == 0);
                 if (y->sign == (x->expn == BF_EXP_ZERO)) {
                     bf_set_inf(r, y_is_odd & x->sign);
                     if (y->sign) {
                         /* pow(0, y) with y < 0 */
                         return BF_ST_DIVIDE_ZERO;
                     }
                 } else {
                     bf_set_zero(r, y_is_odd & x->sign);
                 }
             }
         }
         return 0;
     }
     bf_init(s, T);
     bf_set(T, x);
     y_emin = bf_get_exp_min(y);
     y_is_int = (y_emin >= 0);
     rnd_mode = flags & BF_RND_MASK;
     if (x->sign) {
         if (!y_is_int) {
             bf_set_nan(r);
             bf_delete(T);
             return BF_ST_INVALID_OP;
         }
         y_is_odd = (y_emin == 0);
         r_sign = y_is_odd;
         /* change the directed rounding mode if the sign of the result
            is changed */
         if (r_sign && (rnd_mode == BF_RNDD || rnd_mode == BF_RNDU))
             flags ^= 1;
         bf_neg(T);
     } else {
         r_sign = 0;
     }
     bf_set_ui(r, 1);
     if (bf_cmp_eq(T, r)) {
         /* abs(x) = 1: nothing more to do */
         ret = 0;
     } else {
         /* check the overflow/underflow cases */
         {
             bf_t al_s, *al = &al_s;
             bf_t ah_s, *ah = &ah_s;
             limb_t precl = LIMB_BITS;
             bf_init(s, al);
             bf_init(s, ah);
             /* compute bounds of log(abs(x)) * y with a low precision */
             /* XXX: compute bf_log() once */
             /* XXX: add a fast test before this slow test */
             bf_log(al, T, precl, BF_RNDD);
             bf_log(ah, T, precl, BF_RNDU);
             bf_mul(al, al, y, precl, BF_RNDD ^ y->sign);
             bf_mul(ah, ah, y, precl, BF_RNDU ^ y->sign);
             ret = check_exp_underflow_overflow(s, r, al, ah, prec, flags);
             bf_delete(al);
             bf_delete(ah);
             if (ret)
                 goto done;
         }
         if (y_is_int) {
             slimb_t T_bits, e;
         int_pow:
             T_bits = T->expn - bf_get_exp_min(T);
             if (T_bits == 1) {
                 /* pow(2^b, y) = 2^(b*y) */
                 bf_mul_si(T, y, T->expn - 1, LIMB_BITS, BF_RNDZ);
                 bf_get_limb(&e, T, 0);
                 bf_set_ui(r, 1);
                 ret = bf_mul_2exp(r, e, prec, flags);
             } else if (prec == BF_PREC_INF) {
                 slimb_t y1;
                 /* specific case for infinite precision (integer case) */
                 bf_get_limb(&y1, y, 0);
                 assert(!y->sign);
                 /* x must be an integer, so abs(x) >= 2 */
                 if (y1 >= ((slimb_t)1 << BF_EXP_BITS_MAX)) {
                     bf_delete(T);
                     return bf_set_overflow(r, 0, BF_PREC_INF, flags);
                 }
                 ret = bf_pow_ui(r, T, y1, BF_PREC_INF, BF_RNDZ);
             } else {
                 if (y->expn <= 31) {
                     /* small enough power: use exponentiation in all cases */
                 } else if (y->sign) {
                     /* cannot be exact */
                     goto general_case;
                 } else {
                     if (rnd_mode == BF_RNDF)
                         goto general_case; /* no need to track exact results */
                     /* see if the result has a chance to be exact:
                        if x=a*2^b (a odd), x^y=a^y*2^(b*y)
                        x^y needs a precision of at least floor_log2(a)*y bits
                     */
                     bf_mul_si(r, y, T_bits - 1, LIMB_BITS, BF_RNDZ);
                     bf_get_limb(&e, r, 0);
                     if (prec < e)
                         goto general_case;
                 }
                 ret = bf_ziv_rounding(r, T, prec, flags, bf_pow_int, (void *)y);
             }
         } else {
             if (rnd_mode != BF_RNDF) {
                 bf_t *y1;
                 if (y_emin < 0 && check_exact_power2n(r, T, -y_emin)) {
                     /* the problem is reduced to a power to an integer */
 #if 0
                     printf("\nn=%" PRId64 "\n", -(int64_t)y_emin);
                     bf_print_str("T", T);
                     bf_print_str("r", r);
 #endif
                     bf_set(T, r);
                     y1 = &ytmp_s;
                     y1->tab = y->tab;
                     y1->len = y->len;
                     y1->sign = y->sign;
                     y1->expn = y->expn - y_emin;
                     y = y1;
                     goto int_pow;
                 }
             }
         general_case:
             ret = bf_ziv_rounding(r, T, prec, flags, bf_pow_generic, (void *)y);
         }
     }
  done:
     bf_delete(T);
     r->sign = r_sign;
     return ret;
 }
bf_cos()
int bf_cos (bf_t * r, const bf_t * a, limb_t prec, bf_flags_t flags)
Definition at line 4943 of file libbf.c.
References bf_add_epsilon(), bf_cos_internal(), bf_set_nan(), bf_set_ui(), bf_ziv_rounding(), bf_t::expn, and bf_t::len.
 {
     if (a->len == 0) {
         if (a->expn == BF_EXP_NAN) {
             bf_set_nan(r);
             return 0;
         } else if (a->expn == BF_EXP_INF) {
             bf_set_nan(r);
             return BF_ST_INVALID_OP;
         } else {
             bf_set_ui(r, 1);
             return 0;
         }
     }
     /* small argument case: result = 1+r(x) with r(x) = -x^2/2 +
        O(X^4). We assume r(x) < 2^(2*EXP(x) - 1). */
     if (a->expn < 0) {
         slimb_t e;
         e = 2 * a->expn - 1;
         if (e < -(prec + 2)) {
             bf_set_ui(r, 1);
             return bf_add_epsilon(r, r, e, 1, prec, flags);
         }
     }
     return bf_ziv_rounding(r, a, prec, flags, bf_cos_internal, NULL);
 }
bf_sin()
int bf_sin (bf_t * r, const bf_t * a, limb_t prec, bf_flags_t flags)
Definition at line 4977 of file libbf.c.
References bf_add_epsilon(), bf_max(), bf_set(), bf_set_nan(), bf_set_zero(), bf_sin_internal(), bf_ziv_rounding(), bf_t::expn, bf_t::len, sat_add(), and bf_t::sign.
 {
     if (a->len == 0) {
         if (a->expn == BF_EXP_NAN) {
             bf_set_nan(r);
             return 0;
         } else if (a->expn == BF_EXP_INF) {
             bf_set_nan(r);
             return BF_ST_INVALID_OP;
         } else {
             bf_set_zero(r, a->sign);
             return 0;
         }
     }
     /* small argument case: result = x+r(x) with r(x) = -x^3/6 +
        O(X^5). We assume r(x) < 2^(3*EXP(x) - 2). */
     if (a->expn < 0) {
         slimb_t e;
         e = sat_add(2 * a->expn, a->expn - 2);
         if (e < a->expn - bf_max(prec + 2, a->len * LIMB_BITS + 2)) {
             bf_set(r, a);
             return bf_add_epsilon(r, r, e, 1 - a->sign, prec, flags);
         }
     }
     return bf_ziv_rounding(r, a, prec, flags, bf_sin_internal, NULL);
 }
bf_tan()
int bf_tan (bf_t * r, const bf_t * a, limb_t prec, bf_flags_t flags)
Definition at line 5021 of file libbf.c.
References bf_add_epsilon(), bf_max(), bf_set(), bf_set_nan(), bf_set_zero(), bf_tan_internal(), bf_ziv_rounding(), bf_t::expn, bf_t::len, sat_add(), and bf_t::sign.
 {
     assert(r != a);
     if (a->len == 0) {
         if (a->expn == BF_EXP_NAN) {
             bf_set_nan(r);
             return 0;
         } else if (a->expn == BF_EXP_INF) {
             bf_set_nan(r);
             return BF_ST_INVALID_OP;
         } else {
             bf_set_zero(r, a->sign);
             return 0;
         }
     }
     /* small argument case: result = x+r(x) with r(x) = x^3/3 +
        O(X^5). We assume r(x) < 2^(3*EXP(x) - 1). */
     if (a->expn < 0) {
         slimb_t e;
         e = sat_add(2 * a->expn, a->expn - 1);
         if (e < a->expn - bf_max(prec + 2, a->len * LIMB_BITS + 2)) {
             bf_set(r, a);
             return bf_add_epsilon(r, r, e, a->sign, prec, flags);
         }
     }
     return bf_ziv_rounding(r, a, prec, flags, bf_tan_internal, NULL);
 }
bf_atan()
int bf_atan (bf_t * r, const bf_t * a, limb_t prec, bf_flags_t flags)
Definition at line 5139 of file libbf.c.
References bf_add_epsilon(), bf_atan_internal(), bf_cmpu(), bf_const_pi_signed(), bf_delete(), bf_init(), bf_max(), bf_mul_2exp(), BF_RNDZ, bf_set(), bf_set_nan(), bf_set_ui(), bf_set_zero(), bf_ziv_rounding(), bf_t::ctx, bf_t::expn, FALSE, bf_t::len, sat_add(), and bf_t::sign.
Referenced by bf_atan2_internal().
 {
     bf_context_t *s = r->ctx;
     bf_t T_s, *T = &T_s;
     int res;
     if (a->len == 0) {
         if (a->expn == BF_EXP_NAN) {
             bf_set_nan(r);
             return 0;
         } else if (a->expn == BF_EXP_INF)  {
             /* -PI/2 or PI/2 */
             bf_const_pi_signed(r, a->sign, prec, flags);
             bf_mul_2exp(r, -1, BF_PREC_INF, BF_RNDZ);
             return BF_ST_INEXACT;
         } else {
             bf_set_zero(r, a->sign);
             return 0;
         }
     }
     bf_init(s, T);
     bf_set_ui(T, 1);
     res = bf_cmpu(a, T);
     bf_delete(T);
     if (res == 0) {
         /* short cut: abs(a) == 1 -> +/-pi/4 */
         bf_const_pi_signed(r, a->sign, prec, flags);
         bf_mul_2exp(r, -2, BF_PREC_INF, BF_RNDZ);
         return BF_ST_INEXACT;
     }
     /* small argument case: result = x+r(x) with r(x) = -x^3/3 +
        O(X^5). We assume r(x) < 2^(3*EXP(x) - 1). */
     if (a->expn < 0) {
         slimb_t e;
         e = sat_add(2 * a->expn, a->expn - 1);
         if (e < a->expn - bf_max(prec + 2, a->len * LIMB_BITS + 2)) {
             bf_set(r, a);
             return bf_add_epsilon(r, r, e, 1 - a->sign, prec, flags);
         }
     }
     return bf_ziv_rounding(r, a, prec, flags, bf_atan_internal, (void *)FALSE);
 }
bf_atan2()
int bf_atan2 (bf_t * r, const bf_t * y, const bf_t * x, limb_t prec, bf_flags_t flags)
Definition at line 5223 of file libbf.c.
References bf_atan2_internal(), and bf_ziv_rounding().
 {
     return bf_ziv_rounding(r, y, prec, flags, bf_atan2_internal, (void *)x);
 }
bf_asin()
int bf_asin (bf_t * r, const bf_t * a, limb_t prec, bf_flags_t flags)
Definition at line 5260 of file libbf.c.
References bf_add_epsilon(), bf_asin_internal(), bf_cmpu(), bf_delete(), bf_init(), bf_max(), bf_set(), bf_set_nan(), bf_set_ui(), bf_set_zero(), bf_ziv_rounding(), bf_t::ctx, bf_t::expn, FALSE, bf_t::len, sat_add(), and bf_t::sign.
 {
     bf_context_t *s = r->ctx;
     bf_t T_s, *T = &T_s;
     int res;
     if (a->len == 0) {
         if (a->expn == BF_EXP_NAN) {
             bf_set_nan(r);
             return 0;
         } else if (a->expn == BF_EXP_INF) {
             bf_set_nan(r);
             return BF_ST_INVALID_OP;
         } else {
             bf_set_zero(r, a->sign);
             return 0;
         }
     }
     bf_init(s, T);
     bf_set_ui(T, 1);
     res = bf_cmpu(a, T);
     bf_delete(T);
     if (res > 0) {
         bf_set_nan(r);
         return BF_ST_INVALID_OP;
     }
     /* small argument case: result = x+r(x) with r(x) = x^3/6 +
        O(X^5). We assume r(x) < 2^(3*EXP(x) - 2). */
     if (a->expn < 0) {
         slimb_t e;
         e = sat_add(2 * a->expn, a->expn - 2);
         if (e < a->expn - bf_max(prec + 2, a->len * LIMB_BITS + 2)) {
             bf_set(r, a);
             return bf_add_epsilon(r, r, e, a->sign, prec, flags);
         }
     }
     return bf_ziv_rounding(r, a, prec, flags, bf_asin_internal, (void *)FALSE);
 }
bf_acos()
int bf_acos (bf_t * r, const bf_t * a, limb_t prec, bf_flags_t flags)
Definition at line 5301 of file libbf.c.
References bf_asin_internal(), bf_cmpu(), bf_const_pi(), bf_delete(), bf_init(), bf_mul_2exp(), BF_RNDZ, bf_set_nan(), bf_set_ui(), bf_set_zero(), bf_ziv_rounding(), bf_t::ctx, bf_t::expn, bf_t::len, bf_t::sign, and TRUE.
 {
     bf_context_t *s = r->ctx;
     bf_t T_s, *T = &T_s;
     int res;
     if (a->len == 0) {
         if (a->expn == BF_EXP_NAN) {
             bf_set_nan(r);
             return 0;
         } else if (a->expn == BF_EXP_INF) {
             bf_set_nan(r);
             return BF_ST_INVALID_OP;
         } else {
             bf_const_pi(r, prec, flags);
             bf_mul_2exp(r, -1, BF_PREC_INF, BF_RNDZ);
             return BF_ST_INEXACT;
         }
     }
     bf_init(s, T);
     bf_set_ui(T, 1);
     res = bf_cmpu(a, T);
     bf_delete(T);
     if (res > 0) {
         bf_set_nan(r);
         return BF_ST_INVALID_OP;
     } else if (res == 0 && a->sign == 0) {
         bf_set_zero(r, 0);
         return 0;
     }
     return bf_ziv_rounding(r, a, prec, flags, bf_asin_internal, (void *)TRUE);
 }
bfdec_init()
static void bfdec_init (bf_context_t * s, bfdec_t * r) inline static
Definition at line 418 of file libbf.h.
References bf_init().
Referenced by bfdec_add_si(), bfdec_divrem(), bfdec_mul(), bfdec_mul_si(), and bfdec_rem().
 {
     bf_init(s, (bf_t *)r);
 }
bfdec_delete()
static void bfdec_delete (bfdec_t * r) inline static
Definition at line 422 of file libbf.h.
References bf_delete().
Referenced by bfdec_add_si(), bfdec_divrem(), bfdec_mul_si(), and bfdec_rem().
 {
     bf_delete((bf_t *)r);
 }
bfdec_neg()
static void bfdec_neg (bfdec_t * r) inline static
Definition at line 427 of file libbf.h.
References bfdec_t::sign.
 {
     r->sign ^= 1;
 }
bfdec_is_finite()
static int bfdec_is_finite (const bfdec_t * a) inline static
Definition at line 432 of file libbf.h.
References bfdec_t::expn.
 {
     return (a->expn < BF_EXP_INF);
 }
bfdec_is_nan()
static int bfdec_is_nan (const bfdec_t * a) inline static
Definition at line 437 of file libbf.h.
References bfdec_t::expn.
Referenced by bfdec_divrem().
 {
     return (a->expn == BF_EXP_NAN);
 }
bfdec_is_zero()
static int bfdec_is_zero (const bfdec_t * a) inline static
Definition at line 442 of file libbf.h.
References bfdec_t::expn.
 {
     return (a->expn == BF_EXP_ZERO);
 }
bfdec_memcpy()
static void bfdec_memcpy (bfdec_t * r, const bfdec_t * a) inline static
Definition at line 447 of file libbf.h.
References bf_memcpy().
 {
     bf_memcpy((bf_t *)r, (const bf_t *)a);
 }
bfdec_set_ui()
int bfdec_set_ui (bfdec_t * r, uint64_t a)
Definition at line 6556 of file libbf.c.
References bfdec_normalize_and_round(), bfdec_resize(), bfdec_set_nan(), bfdec_t::expn, bfdec_t::sign, and bfdec_t::tab.
Referenced by bfdec_pow_ui(), bfdec_set_si(), and bfdec_tdivremu().
 {
 #if LIMB_BITS == 32
     if (v >= BF_DEC_BASE * BF_DEC_BASE) {
         if (bfdec_resize(r, 3))
             goto fail;
         r->tab[0] = v % BF_DEC_BASE;
         v /= BF_DEC_BASE;
         r->tab[1] = v % BF_DEC_BASE;
         r->tab[2] = v / BF_DEC_BASE;
         r->expn = 3 * LIMB_DIGITS;
     } else
 #endif
     if (v >= BF_DEC_BASE) {
         if (bfdec_resize(r, 2))
             goto fail;
         r->tab[0] = v % BF_DEC_BASE;
         r->tab[1] = v / BF_DEC_BASE;
         r->expn = 2 * LIMB_DIGITS;
     } else {
         if (bfdec_resize(r, 1))
             goto fail;
         r->tab[0] = v;
         r->expn = LIMB_DIGITS;
     }
     r->sign = 0;
     return bfdec_normalize_and_round(r, BF_PREC_INF, 0);
  fail:
     bfdec_set_nan(r);
     return BF_ST_MEM_ERROR;
 }
bfdec_set_si()
int bfdec_set_si (bfdec_t * r, int64_t a)
Definition at line 6588 of file libbf.c.
References bfdec_set_ui(), and bfdec_t::sign.
Referenced by bfdec_add_si(), and bfdec_mul_si().
 {
     int ret;
     if (v < 0) {
         ret = bfdec_set_ui(r, -v);
         r->sign = 1;
     } else {
         ret = bfdec_set_ui(r, v);
     }
     return ret;
 }
bfdec_set_nan()
static void bfdec_set_nan (bfdec_t * r) inline static
Definition at line 455 of file libbf.h.
References bf_set_nan().
Referenced by __bfdec_div(), bfdec_add_internal(), bfdec_divrem(), bfdec_mul(), bfdec_set_ui(), and bfdec_sqrt().
 {
     bf_set_nan((bf_t *)r);
 }
bfdec_set_zero()
static void bfdec_set_zero (bfdec_t * r, int is_neg) inline static
Definition at line 459 of file libbf.h.
References bf_set_zero().
Referenced by __bfdec_div(), __bfdec_round(), bfdec_add_internal(), bfdec_divrem(), and bfdec_mul().
 {
     bf_set_zero((bf_t *)r, is_neg);
 }
bfdec_set_inf()
static void bfdec_set_inf (bfdec_t * r, int is_neg) inline static
Definition at line 463 of file libbf.h.
References bf_set_inf().
Referenced by __bfdec_div(), __bfdec_round(), bfdec_add_internal(), and bfdec_mul().
 {
     bf_set_inf((bf_t *)r, is_neg);
 }
bfdec_set()
static int bfdec_set (bfdec_t * r, const bfdec_t * a) inline static
Definition at line 467 of file libbf.h.
References bf_set().
Referenced by bfdec_add_internal(), bfdec_divrem(), bfdec_pow_ui(), bfdec_sqrt(), and bfdec_tdivremu().
 {
     return bf_set((bf_t *)r, (bf_t *)a);
 }
bfdec_move()
static void bfdec_move (bfdec_t * r, bfdec_t * a) inline static
Definition at line 471 of file libbf.h.
References bf_move().
Referenced by bfdec_mul().
 {
     bf_move((bf_t *)r, (bf_t *)a);
 }
bfdec_cmpu()
static int bfdec_cmpu (const bfdec_t * a, const bfdec_t * b) inline static
Definition at line 475 of file libbf.h.
References bf_cmpu().
Referenced by bfdec_add_internal(), bfdec_divrem(), and bfdec_tdivremu().
 {
     return bf_cmpu((const bf_t *)a, (const bf_t *)b);
 }
bfdec_cmp_full()
static int bfdec_cmp_full (const bfdec_t * a, const bfdec_t * b) inline static
Definition at line 479 of file libbf.h.
References bf_cmp_full().
 {
     return bf_cmp_full((const bf_t *)a, (const bf_t *)b);
 }
bfdec_cmp()
static int bfdec_cmp (const bfdec_t * a, const bfdec_t * b) inline static
Definition at line 483 of file libbf.h.
References bf_cmp().
Referenced by bfdec_cmp_eq(), bfdec_cmp_le(), and bfdec_cmp_lt().
 {
     return bf_cmp((const bf_t *)a, (const bf_t *)b);
 }
bfdec_cmp_eq()
static int bfdec_cmp_eq (const bfdec_t * a, const bfdec_t * b) inline static
Definition at line 487 of file libbf.h.
References bfdec_cmp().
 {
     return bfdec_cmp(a, b) == 0;
 }
bfdec_cmp_le()
static int bfdec_cmp_le (const bfdec_t * a, const bfdec_t * b) inline static
Definition at line 491 of file libbf.h.
References bfdec_cmp().
 {
     return bfdec_cmp(a, b) <= 0;
 }
bfdec_cmp_lt()
static int bfdec_cmp_lt (const bfdec_t * a, const bfdec_t * b) inline static
Definition at line 495 of file libbf.h.
References bfdec_cmp().
 {
     return bfdec_cmp(a, b) < 0;
 }
bfdec_add()
int bfdec_add (bfdec_t * r, const bfdec_t * a, const bfdec_t * b, limb_t prec, bf_flags_t flags)
Definition at line 6727 of file libbf.c.
References __bfdec_add(), and bf_op2().
Referenced by bfdec_add_si().
 {
     return bf_op2((bf_t *)r, (bf_t *)a, (bf_t *)b, prec, flags,
                   (bf_op2_func_t *)__bfdec_add);
 }
bfdec_sub()
int bfdec_sub (bfdec_t * r, const bfdec_t * a, const bfdec_t * b, limb_t prec, bf_flags_t flags)
Definition at line 6734 of file libbf.c.
References __bfdec_sub(), and bf_op2().
Referenced by bfdec_divrem(), and bfdec_tdivremu().
 {
     return bf_op2((bf_t *)r, (bf_t *)a, (bf_t *)b, prec, flags,
                   (bf_op2_func_t *)__bfdec_sub);
 }
bfdec_add_si()
int bfdec_add_si (bfdec_t * r, const bfdec_t * a, int64_t b1, limb_t prec, bf_flags_t flags)
Definition at line 6813 of file libbf.c.
References bfdec_add(), bfdec_delete(), bfdec_init(), bfdec_set_si(), and bfdec_t::ctx.
Referenced by bfdec_divrem().
 {
     bfdec_t b;
     int ret;
     bfdec_init(r->ctx, &b);
     ret = bfdec_set_si(&b, b1);
     ret |= bfdec_add(r, a, &b, prec, flags);
     bfdec_delete(&b);
     return ret;
 }
bfdec_mul()
int bfdec_mul (bfdec_t * r, const bfdec_t * a, const bfdec_t * b, limb_t prec, bf_flags_t flags)
Definition at line 6741 of file libbf.c.
References bfdec_init(), bfdec_move(), bfdec_normalize_and_round(), bfdec_resize(), bfdec_set_inf(), bfdec_set_nan(), bfdec_set_zero(), bfdec_t::ctx, bfdec_t::expn, bfdec_t::len, mp_mul_basecase_dec(), bfdec_t::sign, and bfdec_t::tab.
Referenced by bfdec_mul_si(), bfdec_pow_ui(), and bfdec_tdivremu().
 {
     int ret, r_sign;
     if (a->len < b->len) {
         const bfdec_t *tmp = a;
         a = b;
         b = tmp;
     }
     r_sign = a->sign ^ b->sign;
     /* here b->len <= a->len */
     if (b->len == 0) {
         if (a->expn == BF_EXP_NAN || b->expn == BF_EXP_NAN) {
             bfdec_set_nan(r);
             ret = 0;
         } else if (a->expn == BF_EXP_INF || b->expn == BF_EXP_INF) {
             if ((a->expn == BF_EXP_INF && b->expn == BF_EXP_ZERO) ||
                 (a->expn == BF_EXP_ZERO && b->expn == BF_EXP_INF)) {
                 bfdec_set_nan(r);
                 ret = BF_ST_INVALID_OP;
             } else {
                 bfdec_set_inf(r, r_sign);
                 ret = 0;
             }
         } else {
             bfdec_set_zero(r, r_sign);
             ret = 0;
         }
     } else {
         bfdec_t tmp, *r1 = NULL;
         limb_t a_len, b_len;
         limb_t *a_tab, *b_tab;
         a_len = a->len;
         b_len = b->len;
         a_tab = a->tab;
         b_tab = b->tab;
         if (r == a || r == b) {
             bfdec_init(r->ctx, &tmp);
             r1 = r;
             r = &tmp;
         }
         if (bfdec_resize(r, a_len + b_len)) {
             bfdec_set_nan(r);
             ret = BF_ST_MEM_ERROR;
             goto done;
         }
         mp_mul_basecase_dec(r->tab, a_tab, a_len, b_tab, b_len);
         r->sign = r_sign;
         r->expn = a->expn + b->expn;
         ret = bfdec_normalize_and_round(r, prec, flags);
     done:
         if (r == &tmp)
             bfdec_move(r1, &tmp);
     }
     return ret;
 }
bfdec_mul_si()
int bfdec_mul_si (bfdec_t * r, const bfdec_t * a, int64_t b1, limb_t prec, bf_flags_t flags)
Definition at line 6801 of file libbf.c.
References bfdec_delete(), bfdec_init(), bfdec_mul(), bfdec_set_si(), and bfdec_t::ctx.
Referenced by bfdec_divrem().
 {
     bfdec_t b;
     int ret;
     bfdec_init(r->ctx, &b);
     ret = bfdec_set_si(&b, b1);
     ret |= bfdec_mul(r, a, &b, prec, flags);
     bfdec_delete(&b);
     return ret;
 }
bfdec_div()
int bfdec_div (bfdec_t * r, const bfdec_t * a, const bfdec_t * b, limb_t prec, bf_flags_t flags)
Definition at line 6919 of file libbf.c.
References __bfdec_div(), and bf_op2().
Referenced by bfdec_tdivremu().
 {
     return bf_op2((bf_t *)r, (bf_t *)a, (bf_t *)b, prec, flags,
                   (bf_op2_func_t *)__bfdec_div);
 }
bfdec_divrem()
int bfdec_divrem (bfdec_t * q, bfdec_t * r, const bfdec_t * a, const bfdec_t * b, limb_t prec, bf_flags_t flags, int rnd_mode)
Definition at line 6949 of file libbf.c.
References BF_RNDA, BF_RNDD, BF_RNDN, BF_RNDNA, BF_RNDU, BF_RNDZ, bfdec_add_si(), bfdec_cmpu(), bfdec_delete(), bfdec_init(), bfdec_is_nan(), bfdec_mul_si(), bfdec_round(), bfdec_set(), bfdec_set_nan(), bfdec_set_zero(), bfdec_sub(), bfdec_tdivremu(), bfdec_t::ctx, bfdec_t::expn, FALSE, get_digit(), bfdec_t::len, bfdec_t::sign, bfdec_t::tab, and TRUE.
Referenced by bfdec_rem().
 {
     bf_context_t *s = q->ctx;
     bfdec_t a1_s, *a1 = &a1_s;
     bfdec_t b1_s, *b1 = &b1_s;
     bfdec_t r1_s, *r1 = &r1_s;
     int q_sign, res;
     BOOL is_ceil, is_rndn;
     assert(q != a && q != b);
     assert(r != a && r != b);
     assert(q != r);
     if (a->len == 0 || b->len == 0) {
         bfdec_set_zero(q, 0);
         if (a->expn == BF_EXP_NAN || b->expn == BF_EXP_NAN) {
             bfdec_set_nan(r);
             return 0;
         } else if (a->expn == BF_EXP_INF || b->expn == BF_EXP_ZERO) {
             bfdec_set_nan(r);
             return BF_ST_INVALID_OP;
         } else {
             bfdec_set(r, a);
             return bfdec_round(r, prec, flags);
         }
     }
     q_sign = a->sign ^ b->sign;
     is_rndn = (rnd_mode == BF_RNDN || rnd_mode == BF_RNDNA);
     switch(rnd_mode) {
     default:
     case BF_RNDZ:
     case BF_RNDN:
     case BF_RNDNA:
         is_ceil = FALSE;
         break;
     case BF_RNDD:
         is_ceil = q_sign;
         break;
     case BF_RNDU:
         is_ceil = q_sign ^ 1;
         break;
     case BF_RNDA:
         is_ceil = TRUE;
         break;
     case BF_DIVREM_EUCLIDIAN:
         is_ceil = a->sign;
         break;
     }
     a1->expn = a->expn;
     a1->tab = a->tab;
     a1->len = a->len;
     a1->sign = 0;
     b1->expn = b->expn;
     b1->tab = b->tab;
     b1->len = b->len;
     b1->sign = 0;
     //    bfdec_print_str("a1", a1);
     //    bfdec_print_str("b1", b1);
     /* XXX: could improve to avoid having a large 'q' */
     bfdec_tdivremu(s, q, r, a1, b1);
     if (bfdec_is_nan(q) || bfdec_is_nan(r))
         goto fail;
     //    bfdec_print_str("q", q);
     //    bfdec_print_str("r", r);
     if (r->len != 0) {
         if (is_rndn) {
             bfdec_init(s, r1);
             if (bfdec_set(r1, r))
                 goto fail;
             if (bfdec_mul_si(r1, r1, 2, BF_PREC_INF, BF_RNDZ)) {
                 bfdec_delete(r1);
                 goto fail;
             }
             res = bfdec_cmpu(r1, b);
             bfdec_delete(r1);
             if (res > 0 ||
                 (res == 0 &&
                  (rnd_mode == BF_RNDNA ||
                   (get_digit(q->tab, q->len, q->len * LIMB_DIGITS - q->expn) & 1) != 0))) {
                 goto do_sub_r;
             }
         } else if (is_ceil) {
         do_sub_r:
             res = bfdec_add_si(q, q, 1, BF_PREC_INF, BF_RNDZ);
             res |= bfdec_sub(r, r, b1, BF_PREC_INF, BF_RNDZ);
             if (res & BF_ST_MEM_ERROR)
                 goto fail;
         }
     }
     r->sign ^= a->sign;
     q->sign = q_sign;
     return bfdec_round(r, prec, flags);
  fail:
     bfdec_set_nan(q);
     bfdec_set_nan(r);
     return BF_ST_MEM_ERROR;
 }
bfdec_rem()
int bfdec_rem (bfdec_t * r, const bfdec_t * a, const bfdec_t * b, limb_t prec, bf_flags_t flags, int rnd_mode)
Definition at line 7054 of file libbf.c.
References bfdec_delete(), bfdec_divrem(), bfdec_init(), and bfdec_t::ctx.
 {
     bfdec_t q_s, *q = &q_s;
     int ret;
     bfdec_init(r->ctx, q);
     ret = bfdec_divrem(q, r, a, b, prec, flags, rnd_mode);
     bfdec_delete(q);
     return ret;
 }
bfdec_rint()
int bfdec_rint (bfdec_t * r, int rnd_mode)
Definition at line 7067 of file libbf.c.
References bfdec_round().
 {
     return bfdec_round(r, 0, rnd_mode | BF_FLAG_RADPNT_PREC);
 }
bfdec_sqrt()
int bfdec_sqrt (bfdec_t * r, const bfdec_t * a, limb_t prec, bf_flags_t flags)
Definition at line 7072 of file libbf.c.
References bf_free(), bf_max(), bf_min(), bfdec_resize(), bfdec_round(), bfdec_set(), bfdec_set_nan(), bfdec_t::ctx, bfdec_t::expn, floor_div(), bfdec_t::len, mp_div1_dec(), mp_mul1_dec(), mp_scan_nz(), mp_shr_dec(), mp_sqrtrem_dec(), bfdec_t::sign, and bfdec_t::tab.
 {
     bf_context_t *s = a->ctx;
     int ret, k;
     limb_t *a1, v;
     slimb_t n, n1, prec1;
     limb_t res;
     assert(r != a);
     if (a->len == 0) {
         if (a->expn == BF_EXP_NAN) {
             bfdec_set_nan(r);
         } else if (a->expn == BF_EXP_INF && a->sign) {
             goto invalid_op;
         } else {
             bfdec_set(r, a);
         }
         ret = 0;
     } else if (a->sign || prec == BF_PREC_INF) {
  invalid_op:
         bfdec_set_nan(r);
         ret = BF_ST_INVALID_OP;
     } else {
         if (flags & BF_FLAG_RADPNT_PREC) {
             prec1 = bf_max(floor_div(a->expn + 1, 2) + prec, 1);
         } else {
             prec1 = prec;
         }
         /* convert the mantissa to an integer with at least 2 *
            prec + 4 digits */
         n = (2 * (prec1 + 2) + 2 * LIMB_DIGITS - 1) / (2 * LIMB_DIGITS);
         if (bfdec_resize(r, n))
             goto fail;
         a1 = bf_malloc(s, sizeof(limb_t) * 2 * n);
         if (!a1)
             goto fail;
         n1 = bf_min(2 * n, a->len);
         memset(a1, 0, (2 * n - n1) * sizeof(limb_t));
         memcpy(a1 + 2 * n - n1, a->tab + a->len - n1, n1 * sizeof(limb_t));
         if (a->expn & 1) {
             res = mp_shr_dec(a1, a1, 2 * n, 1, 0);
         } else {
             res = 0;
         }
         /* normalize so that a1 >= B^(2*n)/4. Not need for n = 1
            because mp_sqrtrem2_dec already does it */
         k = 0;
         if (n > 1) {
             v = a1[2 * n - 1];
             while (v < BF_DEC_BASE / 4) {
                 k++;
                 v *= 4;
             }
             if (k != 0)
                 mp_mul1_dec(a1, a1, 2 * n, 1 << (2 * k), 0);
         }
         if (mp_sqrtrem_dec(s, r->tab, a1, n)) {
             bf_free(s, a1);
             goto fail;
         }
         if (k != 0)
             mp_div1_dec(r->tab, r->tab, n, 1 << k, 0);
         if (!res) {
             res = mp_scan_nz(a1, n + 1);
         }
         bf_free(s, a1);
         if (!res) {
             res = mp_scan_nz(a->tab, a->len - n1);
         }
         if (res != 0)
             r->tab[0] |= 1;
         r->sign = 0;
         r->expn = (a->expn + 1) >> 1;
         ret = bfdec_round(r, prec, flags);
     }
     return ret;
  fail:
     bfdec_set_nan(r);
     return BF_ST_MEM_ERROR;
 }
bfdec_round()
int bfdec_round (bfdec_t * r, limb_t prec, bf_flags_t flags)
Definition at line 6519 of file libbf.c.
References __bfdec_round(), and bfdec_t::len.
Referenced by bf_ftoa_internal(), bfdec_divrem(), bfdec_rint(), and bfdec_sqrt().
 {
     if (r->len == 0)
         return 0;
     return __bfdec_round(r, prec, flags, r->len);
 }
bfdec_get_int32()
int bfdec_get_int32 (int * pres, const bfdec_t * a)
Definition at line 7156 of file libbf.c.
References bfdec_t::expn, fast_shr_dec(), bfdec_t::len, bfdec_t::sign, and bfdec_t::tab.
 {
     uint32_t v;
     int ret;
     if (a->expn >= BF_EXP_INF) {
         ret = 0;
         if (a->expn == BF_EXP_INF) {
             v = (uint32_t)INT32_MAX + a->sign;
              /* XXX: return overflow ? */
         } else {
             v = INT32_MAX;
         }
     } else if (a->expn <= 0) {
         v = 0;
         ret = 0;
     } else if (a->expn <= 9) {
         v = fast_shr_dec(a->tab[a->len - 1], LIMB_DIGITS - a->expn);
         if (a->sign)
             v = -v;
         ret = 0;
     } else if (a->expn == 10) {
         uint64_t v1;
         uint32_t v_max;
 #if LIMB_BITS == 64
         v1 = fast_shr_dec(a->tab[a->len - 1], LIMB_DIGITS - a->expn);
 #else
         v1 = (uint64_t)a->tab[a->len - 1] * 10 +
             get_digit(a->tab, a->len, (a->len - 1) * LIMB_DIGITS - 1);
 #endif
         v_max = (uint32_t)INT32_MAX + a->sign;
         if (v1 > v_max) {
             v = v_max;
             ret = BF_ST_OVERFLOW;
         } else {
             v = v1;
             if (a->sign)
                 v = -v;
             ret = 0;
         }
     } else {
         v = (uint32_t)INT32_MAX + a->sign;
         ret = BF_ST_OVERFLOW;
     }
     *pres = v;
     return ret;
 }
bfdec_pow_ui()
int bfdec_pow_ui (bfdec_t * r, const bfdec_t * a, limb_t b)
Definition at line 7204 of file libbf.c.
References BF_RNDZ, bfdec_mul(), bfdec_set(), bfdec_set_ui(), and clz().
 {
     int ret, n_bits, i;
     assert(r != a);
     if (b == 0)
         return bfdec_set_ui(r, 1);
     ret = bfdec_set(r, a);
     n_bits = LIMB_BITS - clz(b);
     for(i = n_bits - 2; i >= 0; i--) {
         ret |= bfdec_mul(r, r, r, BF_PREC_INF, BF_RNDZ);
         if ((b >> i) & 1)
             ret |= bfdec_mul(r, r, a, BF_PREC_INF, BF_RNDZ);
     }
     return ret;
 }
bfdec_ftoa()
char* bfdec_ftoa (size_t * plen, const bfdec_t * a, limb_t prec, bf_flags_t flags)
Definition at line 7221 of file libbf.c.
References bf_ftoa_internal(), and TRUE.
 {
     return bf_ftoa_internal(plen, (const bf_t *)a, 10, prec, flags, TRUE);
 }
bfdec_atof()
int bfdec_atof (bfdec_t * r, const char * str, const char ** pnext, limb_t prec, bf_flags_t flags)
Definition at line 7226 of file libbf.c.
References bf_atof_internal(), and TRUE.
 {
     slimb_t dummy_exp;
     return bf_atof_internal((bf_t *)r, &dummy_exp, str, pnext, 10, prec,
                             flags, TRUE);
 }
bfdec_print_str()
void bfdec_print_str (const char * str, const bfdec_t * a)
Definition at line 6270 of file libbf.c.
References bfdec_t::expn, bfdec_t::len, bfdec_t::sign, and bfdec_t::tab.
 {
     slimb_t i;
     printf("%s=", str);
     if (a->expn == BF_EXP_NAN) {
         printf("NaN");
     } else {
         if (a->sign)
             putchar('-');
         if (a->expn == BF_EXP_ZERO) {
             putchar('0');
         } else if (a->expn == BF_EXP_INF) {
             printf("Inf");
         } else {
             printf("0.");
             for(i = a->len - 1; i >= 0; i--)
                 printf("%0*" PRIu_LIMB, LIMB_DIGITS, a->tab[i]);
             printf("e%" PRId_LIMB, a->expn);
         }
     }
     printf("\n");
 }
bfdec_resize()
static int bfdec_resize (bfdec_t * r, limb_t len) inline static
Definition at line 529 of file libbf.h.
References bf_resize().
Referenced by __bfdec_div(), __bfdec_round(), bfdec_add_internal(), bfdec_mul(), bfdec_normalize_and_round(), bfdec_set_ui(), and bfdec_sqrt().
 {
     return bf_resize((bf_t *)r, len);
 }
bfdec_normalize_and_round()
int bfdec_normalize_and_round (bfdec_t * r, limb_t prec1, bf_flags_t flags)
Definition at line 6527 of file libbf.c.
References __bfdec_round(), bfdec_resize(), clz_dec(), bfdec_t::expn, bfdec_t::len, mp_shl_dec(), and bfdec_t::tab.
Referenced by __bfdec_div(), bf_atof_internal(), bfdec_add_internal(), bfdec_mul(), and bfdec_set_ui().
 {
     limb_t l, v;
     int shift, ret;
     //    bfdec_print_str("bf_renorm", r);
     l = r->len;
     while (l > 0 && r->tab[l - 1] == 0)
         l--;
     if (l == 0) {
         /* zero */
         r->expn = BF_EXP_ZERO;
         bfdec_resize(r, 0); /* cannot fail */
         ret = 0;
     } else {
         r->expn -= (r->len - l) * LIMB_DIGITS;
         /* shift to have the MSB set to '1' */
         v = r->tab[l - 1];
         shift = clz_dec(v);
         if (shift != 0) {
             mp_shl_dec(r->tab, r->tab, l, shift, 0);
             r->expn -= shift;
         }
         ret = __bfdec_round(r, prec1, flags, l);
     }
     //    bf_print_str("r_final", r);
     return ret;
 }
Variable Documentation
mp_pow_dec
const limb_t mp_pow_dec[LIMB_DIGITS+1]
Definition at line 5494 of file libbf.c.
Referenced by __bfdec_round(), bf_pow_ui_ui(), bfdec_add_internal(), mp_shl_dec(), and mp_shr_dec().