QuickJSPP: quickjs/libregexp.h File Reference
libregexp.h File Reference
#include <stddef.h>
#include "libunicode.h"
Macros
#define LRE_BOOL int /* for documentation purposes */
#define LRE_FLAG_GLOBAL (1 << 0)
#define LRE_FLAG_IGNORECASE (1 << 1)
#define LRE_FLAG_MULTILINE (1 << 2)
#define LRE_FLAG_DOTALL (1 << 3)
#define LRE_FLAG_UTF16 (1 << 4)
#define LRE_FLAG_STICKY (1 << 5)
#define LRE_FLAG_NAMED_GROUPS (1 << 7) /* named groups are present in the regexp */
Functions
uint8_t * lre_compile (int *plen, char *error_msg, int error_msg_size, const char *buf, size_t buf_len, int re_flags, void *opaque)
int lre_get_capture_count (const uint8_t *bc_buf)
int lre_get_flags (const uint8_t *bc_buf)
const char * lre_get_groupnames (const uint8_t *bc_buf)
int lre_exec (uint8_t **capture, const uint8_t *bc_buf, const uint8_t *cbuf, int cindex, int clen, int cbuf_type, void *opaque)
int lre_parse_escape (const uint8_t **pp, int allow_utf16)
LRE_BOOL lre_is_space (int c)
LRE_BOOL lre_check_stack_overflow (void *opaque, size_t alloca_size)
void * lre_realloc (void *opaque, void *ptr, size_t size)
static int lre_js_is_ident_first (int c)
static int lre_js_is_ident_next (int c)
Variables
uint32_t const lre_id_start_table_ascii [4]
uint32_t const lre_id_continue_table_ascii [4]
Macro Definition Documentation
LRE_BOOL
#define LRE_BOOL int /* for documentation purposes */
Definition at line 31 of file libregexp.h.
LRE_FLAG_GLOBAL
#define LRE_FLAG_GLOBAL (1 << 0)
Definition at line 33 of file libregexp.h.
LRE_FLAG_IGNORECASE
#define LRE_FLAG_IGNORECASE (1 << 1)
Definition at line 34 of file libregexp.h.
LRE_FLAG_MULTILINE
#define LRE_FLAG_MULTILINE (1 << 2)
Definition at line 35 of file libregexp.h.
LRE_FLAG_DOTALL
#define LRE_FLAG_DOTALL (1 << 3)
Definition at line 36 of file libregexp.h.
LRE_FLAG_UTF16
#define LRE_FLAG_UTF16 (1 << 4)
Definition at line 37 of file libregexp.h.
LRE_FLAG_STICKY
#define LRE_FLAG_STICKY (1 << 5)
Definition at line 38 of file libregexp.h.
LRE_FLAG_NAMED_GROUPS
#define LRE_FLAG_NAMED_GROUPS (1 << 7) /* named groups are present in the regexp */
Definition at line 40 of file libregexp.h.
Function Documentation
lre_compile()
uint8_t* lre_compile (int * plen, char * error_msg, int error_msg_size, const char * buf, size_t buf_len, int re_flags, void * opaque)
Definition at line 1821 of file libregexp.c.
References __attribute__(), DynBuf::buf, REParseState::buf_end, REParseState::buf_ptr, REParseState::buf_start, REParseState::byte_code, REParseState::capture_count, compute_stack_size(), dbuf_error(), dbuf_free(), dbuf_init2(), dbuf_put(), dbuf_put_u32(), dbuf_putc(), REParseState::dotall, FALSE, REParseState::group_names, REParseState::has_named_captures, REParseState::ignore_case, REParseState::is_utf16, lre_realloc(), REParseState::opaque, pstrcpy(), put_u32(), re_emit_op(), re_emit_op_u32(), re_emit_op_u8(), REParseState::re_flags, re_parse_disjunction(), re_parse_out_of_memory(), DynBuf::size, and REParseState::total_capture_count.
Referenced by js_compile_regexp().
 {
     REParseState s_s, *s = &s_s;
     int stack_size;
     BOOL is_sticky;
     memset(s, 0, sizeof(*s));
     s->opaque = opaque;
     s->buf_ptr = (const uint8_t *)buf;
     s->buf_end = s->buf_ptr + buf_len;
     s->buf_start = s->buf_ptr;
     s->re_flags = re_flags;
     s->is_utf16 = ((re_flags & LRE_FLAG_UTF16) != 0);
     is_sticky = ((re_flags & LRE_FLAG_STICKY) != 0);
     s->ignore_case = ((re_flags & LRE_FLAG_IGNORECASE) != 0);
     s->dotall = ((re_flags & LRE_FLAG_DOTALL) != 0);
     s->capture_count = 1;
     s->total_capture_count = -1;
     s->has_named_captures = -1;
     dbuf_init2(&s->byte_code, opaque, lre_realloc);
     dbuf_init2(&s->group_names, opaque, lre_realloc);
     dbuf_putc(&s->byte_code, re_flags); /* first element is the flags */
     dbuf_putc(&s->byte_code, 0); /* second element is the number of captures */
     dbuf_putc(&s->byte_code, 0); /* stack size */
     dbuf_put_u32(&s->byte_code, 0); /* bytecode length */
     if (!is_sticky) {
         /* iterate thru all positions (about the same as .*?( ... ) )
            .  We do it without an explicit loop so that lock step
            thread execution will be possible in an optimized
            implementation */
         re_emit_op_u32(s, REOP_split_goto_first, 1 + 5);
         re_emit_op(s, REOP_any);
         re_emit_op_u32(s, REOP_goto, -(5 + 1 + 5));
     }
     re_emit_op_u8(s, REOP_save_start, 0);
     if (re_parse_disjunction(s, FALSE)) {
     error:
         dbuf_free(&s->byte_code);
         dbuf_free(&s->group_names);
         pstrcpy(error_msg, error_msg_size, s->u.error_msg);
         *plen = 0;
         return NULL;
     }
     re_emit_op_u8(s, REOP_save_end, 0);
     re_emit_op(s, REOP_match);
     if (*s->buf_ptr != '\0') {
         re_parse_error(s, "extraneous characters at the end");
         goto error;
     }
     if (dbuf_error(&s->byte_code)) {
         re_parse_out_of_memory(s);
         goto error;
     }
     stack_size = compute_stack_size(s->byte_code.buf, s->byte_code.size);
     if (stack_size < 0) {
         re_parse_error(s, "too many imbricated quantifiers");
         goto error;
     }
     s->byte_code.buf[RE_HEADER_CAPTURE_COUNT] = s->capture_count;
     s->byte_code.buf[RE_HEADER_STACK_SIZE] = stack_size;
     put_u32(s->byte_code.buf + 3, s->byte_code.size - RE_HEADER_LEN);
     /* add the named groups if needed */
     if (s->group_names.size > (s->capture_count - 1)) {
         dbuf_put(&s->byte_code, s->group_names.buf, s->group_names.size);
         s->byte_code.buf[RE_HEADER_FLAGS] |= LRE_FLAG_NAMED_GROUPS;
     }
     dbuf_free(&s->group_names);
 #ifdef DUMP_REOP
     lre_dump_bytecode(s->byte_code.buf, s->byte_code.size);
 #endif
     error_msg[0] = '\0';
     *plen = s->byte_code.size;
     return s->byte_code.buf;
 }
lre_get_capture_count()
int lre_get_capture_count (const uint8_t * bc_buf)
Definition at line 2537 of file libregexp.c.
Referenced by js_regexp_exec(), and JS_RegExpDelete().
 {
     return bc_buf[RE_HEADER_CAPTURE_COUNT];
 }
lre_get_flags()
int lre_get_flags (const uint8_t * bc_buf)
Definition at line 2542 of file libregexp.c.
Referenced by js_regexp_exec(), js_regexp_get_flag(), JS_RegExpDelete(), and lre_get_groupnames().
 {
     return bc_buf[RE_HEADER_FLAGS];
 }
lre_get_groupnames()
const char* lre_get_groupnames (const uint8_t * bc_buf)
Definition at line 2549 of file libregexp.c.
References get_u32(), and lre_get_flags().
Referenced by js_regexp_exec().
 {
     uint32_t re_bytecode_len;
     if ((lre_get_flags(bc_buf) & LRE_FLAG_NAMED_GROUPS) == 0)
         return NULL;
     re_bytecode_len = get_u32(bc_buf + 3);
     return (const char *)(bc_buf + 7 + re_bytecode_len);
 }
lre_exec()
int lre_exec (uint8_t ** capture, const uint8_t * bc_buf, const uint8_t * cbuf, int cindex, int clen, int cbuf_type, void * opaque)
Definition at line 2499 of file libregexp.c.
References REExecContext::capture_count, REExecContext::cbuf, REExecContext::cbuf_end, REExecContext::cbuf_type, FALSE, REExecContext::ignore_case, REExecContext::is_utf16, lre_exec_backtrack(), lre_realloc(), REExecContext::multi_line, REExecContext::opaque, REExecContext::stack_size_max, REExecContext::state_size, REExecContext::state_stack, REExecContext::state_stack_len, and REExecContext::state_stack_size.
Referenced by js_regexp_exec(), and JS_RegExpDelete().
 {
     REExecContext s_s, *s = &s_s;
     int re_flags, i, alloca_size, ret;
     StackInt *stack_buf;
     re_flags = bc_buf[RE_HEADER_FLAGS];
     s->multi_line = (re_flags & LRE_FLAG_MULTILINE) != 0;
     s->ignore_case = (re_flags & LRE_FLAG_IGNORECASE) != 0;
     s->is_utf16 = (re_flags & LRE_FLAG_UTF16) != 0;
     s->capture_count = bc_buf[RE_HEADER_CAPTURE_COUNT];
     s->stack_size_max = bc_buf[RE_HEADER_STACK_SIZE];
     s->cbuf = cbuf;
     s->cbuf_end = cbuf + (clen << cbuf_type);
     s->cbuf_type = cbuf_type;
     if (s->cbuf_type == 1 && s->is_utf16)
         s->cbuf_type = 2;
     s->opaque = opaque;
     s->state_size = sizeof(REExecState) +
         s->capture_count * sizeof(capture[0]) * 2 +
         s->stack_size_max * sizeof(stack_buf[0]);
     s->state_stack = NULL;
     s->state_stack_len = 0;
     s->state_stack_size = 0;
     for(i = 0; i < s->capture_count * 2; i++)
         capture[i] = NULL;
     alloca_size = s->stack_size_max * sizeof(stack_buf[0]);
     stack_buf = alloca(alloca_size);
     ret = lre_exec_backtrack(s, capture, stack_buf, 0, bc_buf + RE_HEADER_LEN,
                              cbuf + (cindex << cbuf_type), FALSE);
     lre_realloc(s->opaque, s->state_stack, 0);
     return ret;
 }
lre_parse_escape()
int lre_parse_escape (const uint8_t ** pp, int allow_utf16)
Definition at line 492 of file libregexp.c.
References from_hex(), and is_digit().
Referenced by get_class_atom(), js_parse_string(), next_token(), parse_ident(), and re_parse_group_name().
 {
     const uint8_t *p;
     uint32_t c;
     p = *pp;
     c = *p++;
     switch(c) {
     case 'b':
         c = '\b';
         break;
     case 'f':
         c = '\f';
         break;
     case 'n':
         c = '\n';
         break;
     case 'r':
         c = '\r';
         break;
     case 't':
         c = '\t';
         break;
     case 'v':
         c = '\v';
         break;
     case 'x':
     case 'u':
         {
             int h, n, i;
             uint32_t c1;
             if (*p == '{' && allow_utf16) {
                 p++;
                 c = 0;
                 for(;;) {
                     h = from_hex(*p++);
                     if (h < 0)
                         return -1;
                     c = (c << 4) | h;
                     if (c > 0x10FFFF)
                         return -1;
                     if (*p == '}')
                         break;
                 }
                 p++;
             } else {
                 if (c == 'x') {
                     n = 2;
                 } else {
                     n = 4;
                 }
                 c = 0;
                 for(i = 0; i < n; i++) {
                     h = from_hex(*p++);
                     if (h < 0) {
                         return -1;
                     }
                     c = (c << 4) | h;
                 }
                 if (c >= 0xd800 && c < 0xdc00 &&
                     allow_utf16 == 2 && p[0] == '\\' && p[1] == 'u') {
                     /* convert an escaped surrogate pair into a
                        unicode char */
                     c1 = 0;
                     for(i = 0; i < 4; i++) {
                         h = from_hex(p[2 + i]);
                         if (h < 0)
                             break;
                         c1 = (c1 << 4) | h;
                     }
                     if (i == 4 && c1 >= 0xdc00 && c1 < 0xe000) {
                         p += 6;
                         c = (((c & 0x3ff) << 10) | (c1 & 0x3ff)) + 0x10000;
                     }
                 }
             }
         }
         break;
     case '0': case '1': case '2': case '3':
     case '4': case '5': case '6': case '7':
         c -= '0';
         if (allow_utf16 == 2) {
             /* only accept \0 not followed by digit */
             if (c != 0 || is_digit(*p))
                 return -1;
         } else {
             /* parse a legacy octal sequence */
             uint32_t v;
             v = *p - '0';
             if (v > 7)
                 break;
             c = (c << 3) | v;
             p++;
             if (c >= 32)
                 break;
             v = *p - '0';
             if (v > 7)
                 break;
             c = (c << 3) | v;
             p++;
         }
         break;
     default:
         return -2;
     }
     *pp = p;
     return c;
 }
lre_is_space()
LRE_BOOL lre_is_space (int c)
Definition at line 173 of file libregexp.c.
References char_range_s, FALSE, and TRUE.
Referenced by js_string_trim(), next_token(), and skip_spaces().
 {
     int i, n, low, high;
     n = (countof(char_range_s) - 1) / 2;
     for(i = 0; i < n; i++) {
         low = char_range_s[2 * i + 1];
         if (c < low)
             return FALSE;
         high = char_range_s[2 * i + 2];
         if (c < high)
             return TRUE;
     }
     return FALSE;
 }
lre_check_stack_overflow()
LRE_BOOL lre_check_stack_overflow (void * opaque, size_t alloca_size)
Definition at line 42333 of file quickjs.c.
Referenced by re_parse_disjunction().
 {
     JSContext *ctx = opaque;
     return js_check_stack_overflow(ctx->rt, alloca_size);
 }
lre_realloc()
void* lre_realloc (void * opaque, void * ptr, size_t size)
Definition at line 42339 of file quickjs.c.
Referenced by cr_canonicalize(), cr_init_char_range(), lre_compile(), lre_exec(), parse_unicode_property(), and re_parse_char_class().
 {
     JSContext *ctx = opaque;
     /* No JS exception is raised here */
     return js_realloc_rt(ctx->rt, ptr, size);
 }
lre_js_is_ident_first()
static int lre_js_is_ident_first (int c) inline static
Definition at line 63 of file libregexp.h.
References lre_id_start_table_ascii, and lre_is_id_start().
Referenced by next_token(), re_parse_group_name(), and simple_next_token().
 {
     if ((uint32_t)c < 128) {
         return (lre_id_start_table_ascii[c >> 5] >> (c & 31)) & 1;
     } else {
 #ifdef CONFIG_ALL_UNICODE
         return lre_is_id_start(c);
 #else
         return !lre_is_space(c);
 #endif
     }
 }
lre_js_is_ident_next()
static int lre_js_is_ident_next (int c) inline static
Definition at line 76 of file libregexp.h.
References lre_id_continue_table_ascii, and lre_is_id_continue().
Referenced by js_parse_regexp(), next_token(), parse_ident(), re_parse_group_name(), and simple_next_token().
 {
     if ((uint32_t)c < 128) {
         return (lre_id_continue_table_ascii[c >> 5] >> (c & 31)) & 1;
     } else {
         /* ZWNJ and ZWJ are accepted in identifiers */
 #ifdef CONFIG_ALL_UNICODE
         return lre_is_id_continue(c) || c == 0x200C || c == 0x200D;
 #else
         return !lre_is_space(c) || c == 0x200C || c == 0x200D;
 #endif
     }
 }
Variable Documentation
lre_id_start_table_ascii
uint32_t const lre_id_start_table_ascii[4]
Definition at line 188 of file libregexp.c.
Referenced by lre_js_is_ident_first().
lre_id_continue_table_ascii
uint32_t const lre_id_continue_table_ascii[4]
Definition at line 193 of file libregexp.c.
Referenced by json_parse_ident(), and lre_js_is_ident_next().