QuickJSPP: quickjs/libunicode.h File Reference
libunicode.h File Reference
#include <inttypes.h>
Classes
struct CharRange
Macros
#define LRE_BOOL int /* for documentation purposes */
#define CONFIG_ALL_UNICODE
#define LRE_CC_RES_LEN_MAX 3
Enumerations
enum UnicodeNormalizationEnum { UNICODE_NFC, UNICODE_NFD, UNICODE_NFKC, UNICODE_NFKD }
enum CharRangeOpEnum { CR_OP_UNION, CR_OP_INTER, CR_OP_XOR }
Functions
int lre_case_conv (uint32_t *res, uint32_t c, int conv_type)
LRE_BOOL lre_is_cased (uint32_t c)
LRE_BOOL lre_is_case_ignorable (uint32_t c)
void cr_init (CharRange *cr, void *mem_opaque, void *(*realloc_func)(void *opaque, void *ptr, size_t size))
void cr_free (CharRange *cr)
int cr_realloc (CharRange *cr, int size)
int cr_copy (CharRange *cr, const CharRange *cr1)
static int cr_add_point (CharRange *cr, uint32_t v)
static int cr_add_interval (CharRange *cr, uint32_t c1, uint32_t c2)
int cr_union1 (CharRange *cr, const uint32_t *b_pt, int b_len)
static int cr_union_interval (CharRange *cr, uint32_t c1, uint32_t c2)
int cr_op (CharRange *cr, const uint32_t *a_pt, int a_len, const uint32_t *b_pt, int b_len, int op)
int cr_invert (CharRange *cr)
LRE_BOOL lre_is_id_start (uint32_t c)
LRE_BOOL lre_is_id_continue (uint32_t c)
int unicode_normalize (uint32_t **pdst, const uint32_t *src, int src_len, UnicodeNormalizationEnum n_type, void *opaque, void *(*realloc_func)(void *opaque, void *ptr, size_t size))
int unicode_script (CharRange *cr, const char *script_name, LRE_BOOL is_ext)
int unicode_general_category (CharRange *cr, const char *gc_name)
int unicode_prop (CharRange *cr, const char *prop_name)
Macro Definition Documentation
LRE_BOOL
#define LRE_BOOL int /* for documentation purposes */
Definition at line 29 of file libunicode.h.
CONFIG_ALL_UNICODE
#define CONFIG_ALL_UNICODE
Definition at line 32 of file libunicode.h.
LRE_CC_RES_LEN_MAX
#define LRE_CC_RES_LEN_MAX 3
Definition at line 34 of file libunicode.h.
Enumeration Type Documentation
UnicodeNormalizationEnum
enum UnicodeNormalizationEnum
Enumerator
UNICODE_NFC
UNICODE_NFD
UNICODE_NFKC
UNICODE_NFKD
Definition at line 36 of file libunicode.h.
              {
     UNICODE_NFC,
     UNICODE_NFD,
     UNICODE_NFKC,
     UNICODE_NFKD,
 } UnicodeNormalizationEnum;
CharRangeOpEnum
enum CharRangeOpEnum
Enumerator
CR_OP_UNION
CR_OP_INTER
CR_OP_XOR
Definition at line 57 of file libunicode.h.
              {
     CR_OP_UNION,
     CR_OP_INTER,
     CR_OP_XOR,
 } CharRangeOpEnum;
Function Documentation
lre_case_conv()
int lre_case_conv (uint32_t * res, uint32_t c, int conv_type)
Definition at line 56 of file libunicode.c.
References case_conv_ext, case_conv_table1, case_conv_table2, RUN_TYPE_L, RUN_TYPE_L_EXT2, RUN_TYPE_LF, RUN_TYPE_LF_EXT, RUN_TYPE_LSU, RUN_TYPE_U, RUN_TYPE_U2L_399_EXT2, RUN_TYPE_U_EXT, RUN_TYPE_U_EXT2, RUN_TYPE_U_EXT3, RUN_TYPE_UF, RUN_TYPE_UF_D1_EXT, RUN_TYPE_UF_D20, and RUN_TYPE_UL.
Referenced by js_string_toLowerCase(), and lre_canonicalize().
 {
     if (c < 128) {
         if (conv_type) {
             if (c >= 'A' && c <= 'Z') {
                 c = c - 'A' + 'a';
             }
         } else {
             if (c >= 'a' && c <= 'z') {
                 c = c - 'a' + 'A';
             }
         }
     } else {
         uint32_t v, code, data, type, len, a, is_lower;
         int idx, idx_min, idx_max;
         is_lower = (conv_type != 0);
         idx_min = 0;
         idx_max = countof(case_conv_table1) - 1;
         while (idx_min <= idx_max) {
             idx = (unsigned)(idx_max + idx_min) / 2;
             v = case_conv_table1[idx];
             code = v >> (32 - 17);
             len = (v >> (32 - 17 - 7)) & 0x7f;
             if (c < code) {
                 idx_max = idx - 1;
             } else if (c >= code + len) {
                 idx_min = idx + 1;
             } else {
                 type = (v >> (32 - 17 - 7 - 4)) & 0xf;
                 data = ((v & 0xf) << 8) | case_conv_table2[idx];
                 switch(type) {
                 case RUN_TYPE_U:
                 case RUN_TYPE_L:
                 case RUN_TYPE_UF:
                 case RUN_TYPE_LF:
                     if (conv_type == (type & 1) ||
                         (type >= RUN_TYPE_UF && conv_type == 2)) {
                         c = c - code + (case_conv_table1[data] >> (32 - 17));
                     }
                     break;
                 case RUN_TYPE_UL:
                     a = c - code;
                     if ((a & 1) != (1 - is_lower))
                         break;
                     c = (a ^ 1) + code;
                     break;
                 case RUN_TYPE_LSU:
                     a = c - code;
                     if (a == 1) {
                         c += 2 * is_lower - 1;
                     } else if (a == (1 - is_lower) * 2) {
                         c += (2 * is_lower - 1) * 2;
                     }
                     break;
                 case RUN_TYPE_U2L_399_EXT2:
                     if (!is_lower) {
                         res[0] = c - code + case_conv_ext[data >> 6];
                         res[1] = 0x399;
                         return 2;
                     } else {
                         c = c - code + case_conv_ext[data & 0x3f];
                     }
                     break;
                 case RUN_TYPE_UF_D20:
                     if (conv_type == 1)
                         break;
                     c = data + (conv_type == 2) * 0x20;
                     break;
                 case RUN_TYPE_UF_D1_EXT:
                     if (conv_type == 1)
                         break;
                     c = case_conv_ext[data] + (conv_type == 2);
                     break;
                 case RUN_TYPE_U_EXT:
                 case RUN_TYPE_LF_EXT:
                     if (is_lower != (type - RUN_TYPE_U_EXT))
                         break;
                     c = case_conv_ext[data];
                     break;
                 case RUN_TYPE_U_EXT2:
                 case RUN_TYPE_L_EXT2:
                     if (conv_type != (type - RUN_TYPE_U_EXT2))
                         break;
                     res[0] = c - code + case_conv_ext[data >> 6];
                     res[1] = case_conv_ext[data & 0x3f];
                     return 2;
                 default:
                 case RUN_TYPE_U_EXT3:
                     if (conv_type != 0)
                         break;
                     res[0] = case_conv_ext[data >> 8];
                     res[1] = case_conv_ext[(data >> 4) & 0xf];
                     res[2] = case_conv_ext[data & 0xf];
                     return 3;
                 }
                 break;
             }
         }
     }
     res[0] = c;
     return 1;
 }
lre_is_cased()
LRE_BOOL lre_is_cased (uint32_t c)
Definition at line 240 of file libunicode.c.
References case_conv_table1, lre_is_in_table(), TRUE, unicode_prop_Cased1_index, and unicode_prop_Cased1_table.
Referenced by test_final_sigma().
 {
     uint32_t v, code, len;
     int idx, idx_min, idx_max;
     idx_min = 0;
     idx_max = countof(case_conv_table1) - 1;
     while (idx_min <= idx_max) {
         idx = (unsigned)(idx_max + idx_min) / 2;
         v = case_conv_table1[idx];
         code = v >> (32 - 17);
         len = (v >> (32 - 17 - 7)) & 0x7f;
         if (c < code) {
             idx_max = idx - 1;
         } else if (c >= code + len) {
             idx_min = idx + 1;
         } else {
             return TRUE;
         }
     }
     return lre_is_in_table(c, unicode_prop_Cased1_table,
                            unicode_prop_Cased1_index,
                            sizeof(unicode_prop_Cased1_index) / 3);
 }
lre_is_case_ignorable()
LRE_BOOL lre_is_case_ignorable (uint32_t c)
Definition at line 265 of file libunicode.c.
References lre_is_in_table(), unicode_prop_Case_Ignorable_index, and unicode_prop_Case_Ignorable_table.
Referenced by test_final_sigma().
 {
     return lre_is_in_table(c, unicode_prop_Case_Ignorable_table,
                            unicode_prop_Case_Ignorable_index,
                            sizeof(unicode_prop_Case_Ignorable_index) / 3);
 }
cr_init()
void cr_init (CharRange * cr, void * mem_opaque, void *(*)(void *opaque, void *ptr, size_t size) realloc_func)
cr_free()
void cr_free (CharRange * cr)
Definition at line 294 of file libunicode.c.
References CharRange::mem_opaque, CharRange::points, and CharRange::realloc_func.
Referenced by cr_canonicalize(), cr_init_char_range(), cr_union1(), parse_unicode_property(), re_parse_char_class(), re_parse_term(), unicode_prop_ops(), and unicode_script().
 {
     cr->realloc_func(cr->mem_opaque, cr->points, 0);
 }
cr_realloc()
int cr_realloc (CharRange * cr, int size)
Definition at line 299 of file libunicode.c.
References max_int(), CharRange::points, and CharRange::size.
Referenced by cr_add_interval(), cr_add_point(), cr_copy(), and cr_invert().
 {
     int new_size;
     uint32_t *new_buf;
     if (size > cr->size) {
         new_size = max_int(size, cr->size * 3 / 2);
         new_buf = cr->realloc_func(cr->mem_opaque, cr->points,
                                    new_size * sizeof(cr->points[0]));
         if (!new_buf)
             return -1;
         cr->points = new_buf;
         cr->size = new_size;
     }
     return 0;
 }
cr_copy()
int cr_copy (CharRange * cr, const CharRange * cr1)
Definition at line 316 of file libunicode.c.
References cr_realloc(), CharRange::len, and CharRange::points.
Referenced by unicode_prop_ops().
 {
     if (cr_realloc(cr, cr1->len))
         return -1;
     memcpy(cr->points, cr1->points, sizeof(cr->points[0]) * cr1->len);
     cr->len = cr1->len;
     return 0;
 }
cr_add_point()
static int cr_add_point (CharRange * cr, uint32_t v) inline static
Definition at line 68 of file libunicode.h.
References cr_realloc(), CharRange::len, CharRange::points, and CharRange::size.
Referenced by cr_init_char_range(), and cr_op().
 {
     if (cr->len >= cr->size) {
         if (cr_realloc(cr, cr->len + 1))
             return -1;
     }
     cr->points[cr->len++] = v;
     return 0;
 }
cr_add_interval()
static int cr_add_interval (CharRange * cr, uint32_t c1, uint32_t c2) inline static
Definition at line 78 of file libunicode.h.
References cr_realloc(), CharRange::len, CharRange::points, and CharRange::size.
Referenced by unicode_case1(), unicode_general_category1(), unicode_prop(), unicode_prop1(), and unicode_script().
 {
     if ((cr->len + 2) > cr->size) {
         if (cr_realloc(cr, cr->len + 2))
             return -1;
     }
     cr->points[cr->len++] = c1;
     cr->points[cr->len++] = c2;
     return 0;
 }
cr_union1()
int cr_union1 (CharRange * cr, const uint32_t * b_pt, int b_len)
Definition at line 407 of file libunicode.c.
References cr_free(), cr_op(), CR_OP_UNION, CharRange::len, CharRange::points, and CharRange::size.
Referenced by cr_canonicalize(), cr_union_interval(), and re_parse_char_class().
 {
     CharRange a = *cr;
     int ret;
     cr->len = 0;
     cr->size = 0;
     cr->points = NULL;
     ret = cr_op(cr, a.points, a.len, b_pt, b_len, CR_OP_UNION);
     cr_free(&a);
     return ret;
 }
cr_union_interval()
static int cr_union_interval (CharRange * cr, uint32_t c1, uint32_t c2) inline static
Definition at line 91 of file libunicode.h.
References cr_union1().
Referenced by re_parse_char_class().
 {
     uint32_t b_pt[2];
     b_pt[0] = c1;
     b_pt[1] = c2 + 1;
     return cr_union1(cr, b_pt, 2);
 }
cr_op()
int cr_op (CharRange * cr, const uint32_t * a_pt, int a_len, const uint32_t * b_pt, int b_len, int op)
Definition at line 355 of file libunicode.c.
References cr_add_point(), cr_compress(), CR_OP_INTER, CR_OP_UNION, CR_OP_XOR, and CharRange::len.
Referenced by cr_canonicalize(), cr_union1(), unicode_prop_ops(), and unicode_script().
 {
     int a_idx, b_idx, is_in;
     uint32_t v;
     a_idx = 0;
     b_idx = 0;
     for(;;) {
         /* get one more point from a or b in increasing order */
         if (a_idx < a_len && b_idx < b_len) {
             if (a_pt[a_idx] < b_pt[b_idx]) {
                 goto a_add;
             } else if (a_pt[a_idx] == b_pt[b_idx]) {
                 v = a_pt[a_idx];
                 a_idx++;
                 b_idx++;
             } else {
                 goto b_add;
             }
         } else if (a_idx < a_len) {
         a_add:
             v = a_pt[a_idx++];
         } else if (b_idx < b_len) {
         b_add:
             v = b_pt[b_idx++];
         } else {
             break;
         }
         /* add the point if the in/out status changes */
         switch(op) {
         case CR_OP_UNION:
             is_in = (a_idx & 1) | (b_idx & 1);
             break;
         case CR_OP_INTER:
             is_in = (a_idx & 1) & (b_idx & 1);
             break;
         case CR_OP_XOR:
             is_in = (a_idx & 1) ^ (b_idx & 1);
             break;
         default:
             abort();
         }
         if (is_in != (cr->len & 1)) {
             if (cr_add_point(cr, v))
                 return -1;
         }
     }
     cr_compress(cr);
     return 0;
 }
cr_invert()
int cr_invert (CharRange * cr)
Definition at line 419 of file libunicode.c.
References cr_compress(), cr_realloc(), CharRange::len, and CharRange::points.
Referenced by cr_init_char_range(), parse_unicode_property(), re_parse_char_class(), unicode_prop_ops(), and unicode_script().
 {
     int len;
     len = cr->len;
     if (cr_realloc(cr, len + 2))
         return -1;
     memmove(cr->points + 1, cr->points, len * sizeof(cr->points[0]));
     cr->points[0] = 0;
     cr->points[len + 1] = UINT32_MAX;
     cr->len = len + 2;
     cr_compress(cr);
     return 0;
 }
lre_is_id_start()
LRE_BOOL lre_is_id_start (uint32_t c)
Definition at line 435 of file libunicode.c.
References lre_is_in_table(), unicode_prop_ID_Start_index, and unicode_prop_ID_Start_table.
Referenced by lre_is_id_continue(), and lre_js_is_ident_first().
 {
     return lre_is_in_table(c, unicode_prop_ID_Start_table,
                            unicode_prop_ID_Start_index,
                            sizeof(unicode_prop_ID_Start_index) / 3);
 }
lre_is_id_continue()
LRE_BOOL lre_is_id_continue (uint32_t c)
Definition at line 442 of file libunicode.c.
References lre_is_id_start(), lre_is_in_table(), unicode_prop_ID_Continue1_index, and unicode_prop_ID_Continue1_table.
Referenced by lre_js_is_ident_next().
 {
     return lre_is_id_start(c) ||
         lre_is_in_table(c, unicode_prop_ID_Continue1_table,
                         unicode_prop_ID_Continue1_index,
                         sizeof(unicode_prop_ID_Continue1_index) / 3);
 }
unicode_normalize()
int unicode_normalize (uint32_t ** pdst, const uint32_t * src, int src_len, UnicodeNormalizationEnum n_type, void * opaque, void *(*)(void *opaque, void *ptr, size_t size) realloc_func)
unicode_script()
int unicode_script (CharRange * cr, const char * script_name, LRE_BOOL is_ext)
unicode_general_category()
int unicode_general_category (CharRange * cr, const char * gc_name)
Definition at line 1341 of file libunicode.c.
References unicode_find_name(), unicode_gc_mask_table, and unicode_general_category1().
Referenced by parse_unicode_property().
 {
     int gc_idx;
     uint32_t gc_mask;
     gc_idx = unicode_find_name(unicode_gc_name_table, gc_name);
     if (gc_idx < 0)
         return -2;
     if (gc_idx <= UNICODE_GC_Co) {
         gc_mask = (uint64_t)1 << gc_idx;
     } else {
         gc_mask = unicode_gc_mask_table[gc_idx - UNICODE_GC_LC];
     }
     return unicode_general_category1(cr, gc_mask);
 }
unicode_prop()
int unicode_prop (CharRange * cr, const char * prop_name)
Definition at line 1360 of file libunicode.c.
References cr_add_interval(), POP_CASE, POP_END, POP_GC, POP_INTER, POP_INVERT, POP_PROP, POP_UNION, POP_XOR, unicode_case1(), unicode_find_name(), unicode_prop1(), and unicode_prop_ops().
Referenced by parse_unicode_property().
 {
     int prop_idx, ret;
     prop_idx = unicode_find_name(unicode_prop_name_table, prop_name);
     if (prop_idx < 0)
         return -2;
     prop_idx += UNICODE_PROP_ASCII_Hex_Digit;
     ret = 0;
     switch(prop_idx) {
     case UNICODE_PROP_ASCII:
         if (cr_add_interval(cr, 0x00, 0x7f + 1))
             return -1;
         break;
     case UNICODE_PROP_Any:
         if (cr_add_interval(cr, 0x00000, 0x10ffff + 1))
             return -1;
         break;
     case UNICODE_PROP_Assigned:
         ret = unicode_prop_ops(cr,
                                POP_GC, M(Cn),
                                POP_INVERT,
                                POP_END);
         break;
     case UNICODE_PROP_Math:
         ret = unicode_prop_ops(cr,
                                POP_GC, M(Sm),
                                POP_PROP, UNICODE_PROP_Other_Math,
                                POP_UNION,
                                POP_END);
         break;
     case UNICODE_PROP_Lowercase:
         ret = unicode_prop_ops(cr,
                                POP_GC, M(Ll),
                                POP_PROP, UNICODE_PROP_Other_Lowercase,
                                POP_UNION,
                                POP_END);
         break;
     case UNICODE_PROP_Uppercase:
         ret = unicode_prop_ops(cr,
                                POP_GC, M(Lu),
                                POP_PROP, UNICODE_PROP_Other_Uppercase,
                                POP_UNION,
                                POP_END);
         break;
     case UNICODE_PROP_Cased:
         ret = unicode_prop_ops(cr,
                                POP_GC, M(Lu) | M(Ll) | M(Lt),
                                POP_PROP, UNICODE_PROP_Other_Uppercase,
                                POP_UNION,
                                POP_PROP, UNICODE_PROP_Other_Lowercase,
                                POP_UNION,
                                POP_END);
         break;
     case UNICODE_PROP_Alphabetic:
         ret = unicode_prop_ops(cr,
                                POP_GC, M(Lu) | M(Ll) | M(Lt) | M(Lm) | M(Lo) | M(Nl),
                                POP_PROP, UNICODE_PROP_Other_Uppercase,
                                POP_UNION,
                                POP_PROP, UNICODE_PROP_Other_Lowercase,
                                POP_UNION,
                                POP_PROP, UNICODE_PROP_Other_Alphabetic,
                                POP_UNION,
                                POP_END);
         break;
     case UNICODE_PROP_Grapheme_Base:
         ret = unicode_prop_ops(cr,
                                POP_GC, M(Cc) | M(Cf) | M(Cs) | M(Co) | M(Cn) | M(Zl) | M(Zp) | M(Me) | M(Mn),
                                POP_PROP, UNICODE_PROP_Other_Grapheme_Extend,
                                POP_UNION,
                                POP_INVERT,
                                POP_END);
         break;
     case UNICODE_PROP_Grapheme_Extend:
         ret = unicode_prop_ops(cr,
                                POP_GC, M(Me) | M(Mn),
                                POP_PROP, UNICODE_PROP_Other_Grapheme_Extend,
                                POP_UNION,
                                POP_END);
         break;
     case UNICODE_PROP_XID_Start:
         ret = unicode_prop_ops(cr,
                                POP_GC, M(Lu) | M(Ll) | M(Lt) | M(Lm) | M(Lo) | M(Nl),
                                POP_PROP, UNICODE_PROP_Other_ID_Start,
                                POP_UNION,
                                POP_PROP, UNICODE_PROP_Pattern_Syntax,
                                POP_PROP, UNICODE_PROP_Pattern_White_Space,
                                POP_UNION,
                                POP_PROP, UNICODE_PROP_XID_Start1,
                                POP_UNION,
                                POP_INVERT,
                                POP_INTER,
                                POP_END);
         break;
     case UNICODE_PROP_XID_Continue:
         ret = unicode_prop_ops(cr,
                                POP_GC, M(Lu) | M(Ll) | M(Lt) | M(Lm) | M(Lo) | M(Nl) |
                                M(Mn) | M(Mc) | M(Nd) | M(Pc),
                                POP_PROP, UNICODE_PROP_Other_ID_Start,
                                POP_UNION,
                                POP_PROP, UNICODE_PROP_Other_ID_Continue,
                                POP_UNION,
                                POP_PROP, UNICODE_PROP_Pattern_Syntax,
                                POP_PROP, UNICODE_PROP_Pattern_White_Space,
                                POP_UNION,
                                POP_PROP, UNICODE_PROP_XID_Continue1,
                                POP_UNION,
                                POP_INVERT,
                                POP_INTER,
                                POP_END);
         break;
     case UNICODE_PROP_Changes_When_Uppercased:
         ret = unicode_case1(cr, CASE_U);
         break;
     case UNICODE_PROP_Changes_When_Lowercased:
         ret = unicode_case1(cr, CASE_L);
         break;
     case UNICODE_PROP_Changes_When_Casemapped:
         ret = unicode_case1(cr, CASE_U | CASE_L | CASE_F);
         break;
     case UNICODE_PROP_Changes_When_Titlecased:
         ret = unicode_prop_ops(cr,
                                POP_CASE, CASE_U,
                                POP_PROP, UNICODE_PROP_Changes_When_Titlecased1,
                                POP_XOR,
                                POP_END);
         break;
     case UNICODE_PROP_Changes_When_Casefolded:
         ret = unicode_prop_ops(cr,
                                POP_CASE, CASE_F,
                                POP_PROP, UNICODE_PROP_Changes_When_Casefolded1,
                                POP_XOR,
                                POP_END);
         break;
     case UNICODE_PROP_Changes_When_NFKC_Casefolded:
         ret = unicode_prop_ops(cr,
                                POP_CASE, CASE_F,
                                POP_PROP, UNICODE_PROP_Changes_When_NFKC_Casefolded1,
                                POP_XOR,
                                POP_END);
         break;
 #if 0
     case UNICODE_PROP_ID_Start:
         ret = unicode_prop_ops(cr,
                                POP_GC, M(Lu) | M(Ll) | M(Lt) | M(Lm) | M(Lo) | M(Nl),
                                POP_PROP, UNICODE_PROP_Other_ID_Start,
                                POP_UNION,
                                POP_PROP, UNICODE_PROP_Pattern_Syntax,
                                POP_PROP, UNICODE_PROP_Pattern_White_Space,
                                POP_UNION,
                                POP_INVERT,
                                POP_INTER,
                                POP_END);
         break;
     case UNICODE_PROP_ID_Continue:
         ret = unicode_prop_ops(cr,
                                POP_GC, M(Lu) | M(Ll) | M(Lt) | M(Lm) | M(Lo) | M(Nl) |
                                M(Mn) | M(Mc) | M(Nd) | M(Pc),
                                POP_PROP, UNICODE_PROP_Other_ID_Start,
                                POP_UNION,
                                POP_PROP, UNICODE_PROP_Other_ID_Continue,
                                POP_UNION,
                                POP_PROP, UNICODE_PROP_Pattern_Syntax,
                                POP_PROP, UNICODE_PROP_Pattern_White_Space,
                                POP_UNION,
                                POP_INVERT,
                                POP_INTER,
                                POP_END);
         break;
     case UNICODE_PROP_Case_Ignorable:
         ret = unicode_prop_ops(cr,
                                POP_GC, M(Mn) | M(Cf) | M(Lm) | M(Sk),
                                POP_PROP, UNICODE_PROP_Case_Ignorable1,
                                POP_XOR,
                                POP_END);
         break;
 #else
         /* we use the existing tables */
     case UNICODE_PROP_ID_Continue:
         ret = unicode_prop_ops(cr,
                                POP_PROP, UNICODE_PROP_ID_Start,
                                POP_PROP, UNICODE_PROP_ID_Continue1,
                                POP_XOR,
                                POP_END);
         break;
 #endif
     default:
         if (prop_idx >= countof(unicode_prop_table))
             return -2;
         ret = unicode_prop1(cr, prop_idx);
         break;
     }
     return ret;
 }