QuickJSPP: quickjs/list.h File Reference
list.h File Reference
#include <stddef.h>
Classes
struct list_head
Macros
#define LIST_HEAD_INIT(el) { &(el), &(el) }
#define list_entry(el, type, member) ((type *)((uint8_t *)(el) - offsetof(type, member)))
#define list_for_each(el, head) for(el = (head)->next; el != (head); el = el->next)
#define list_for_each_safe(el, el1, head)
#define list_for_each_prev(el, head) for(el = (head)->prev; el != (head); el = el->prev)
#define list_for_each_prev_safe(el, el1, head)
Functions
static void init_list_head (struct list_head *head)
static void __list_add (struct list_head *el, struct list_head *prev, struct list_head *next)
static void list_add (struct list_head *el, struct list_head *head)
static void list_add_tail (struct list_head *el, struct list_head *head)
static void list_del (struct list_head *el)
static int list_empty (struct list_head *el)
Macro Definition Documentation
LIST_HEAD_INIT
#define LIST_HEAD_INIT (el) { &(el), &(el) }
Definition at line 36 of file list.h.
list_entry
#define list_entry (el, type, member) ((type *)((uint8_t *)(el) - offsetof(type, member)))
Definition at line 39 of file list.h.
list_for_each
#define list_for_each (el, head) for(el = (head)->next; el != (head); el = el->next)
Definition at line 86 of file list.h.
list_for_each_safe
#define list_for_each_safe (el, el1, head)
Value:
for(el = (head)->next, el1 = el->next; el != (head); \
        el = el1, el1 = el->next)
Definition at line 89 of file list.h.
list_for_each_prev
#define list_for_each_prev (el, head) for(el = (head)->prev; el != (head); el = el->prev)
Definition at line 93 of file list.h.
list_for_each_prev_safe
#define list_for_each_prev_safe (el, el1, head)
Value:
for(el = (head)->prev, el1 = el->prev; el != (head); \
        el = el1, el1 = el->prev)
Definition at line 96 of file list.h.
Function Documentation
init_list_head()
static void init_list_head (struct list_head * head) inline static
Definition at line 42 of file list.h.
References list_head::next, and list_head::prev.
Referenced by async_func_init(), gc_decref(), gc_free_cycles(), js_array_buffer_constructor3(), js_async_generator_function_call(), js_atomics_notify(), JS_CallInternal(), JS_FreeRuntime(), js_map_constructor(), js_new_function_def(), js_new_message_pipe(), JS_NewContextRaw(), JS_NewRuntime2(), js_promise_constructor(), js_std_init_handlers(), and map_hash_resize().
 {
     head->prev = head;
     head->next = head;
 }
__list_add()
static void __list_add (struct list_head * el, struct list_head * prev, struct list_head * next) inline static
Definition at line 49 of file list.h.
References list_head::next, and list_head::prev.
Referenced by list_add(), and list_add_tail().
 {
     prev->next = el;
     el->prev = prev;
     el->next = next;
     next->prev = el;
 }
list_add()
static void list_add (struct list_head * el, struct list_head * head) inline static
Definition at line 59 of file list.h.
References __list_add(), and list_head::next.
 {
     __list_add(el, head, head->next);
 }
list_add_tail()
static void list_add_tail (struct list_head * el, struct list_head * head) inline static
Definition at line 65 of file list.h.
References __list_add(), and list_head::prev.
Referenced by add_gc_object(), compact_properties(), free_function_bytecode(), free_object(), gc_decref(), gc_decref_child(), gc_free_cycles(), gc_scan_incref_child(), get_var_ref(), js_atomics_notify(), js_atomics_wait(), js_dataview_constructor(), JS_EnqueueJob(), js_new_function_def(), js_new_module_def(), JS_NewContextRaw(), js_worker_postMessage(), map_add_record(), map_hash_resize(), resize_properties(), and typed_array_init().
 {
     __list_add(el, head->prev, head);
 }
list_del()
static void list_del (struct list_head * el) inline static
Definition at line 70 of file list.h.
References list_head::next, and list_head::prev.
Referenced by close_lexical_var(), compact_properties(), free_rw_handler(), free_sh(), free_var_ref(), gc_decref(), gc_decref_child(), gc_free_cycles(), gc_scan_incref_child(), handle_posted_message(), js_async_generator_resolve_or_reject(), js_atomics_notify(), js_atomics_wait(), js_create_function(), JS_ExecutePendingJob(), js_free_function_def(), js_free_module_def(), js_free_port(), JS_FreeContext(), js_typed_array_finalizer(), map_decref_record(), map_delete_record(), remove_gc_object(), reset_weak_ref(), resize_properties(), and unlink_timer().
 {
     struct list_head *prev, *next;
     prev = el->prev;
     next = el->next;
     prev->next = next;
     next->prev = prev;
     el->prev = NULL; /* fail safe */
     el->next = NULL; /* fail safe */
 }
list_empty()
static int list_empty (struct list_head * el) inline static
Definition at line 81 of file list.h.
References list_head::next.
Referenced by handle_posted_message(), js_async_generator_resume_next(), JS_CallInternal(), JS_ExecutePendingJob(), JS_FreeRuntime(), JS_IsJobPending(), and js_worker_postMessage().
 {
     return el->next == el;
 }