QuickJSPP: quickjs/quickjs-libc.h File Reference
quickjs-libc.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include "quickjs.h"
Functions
JSModuleDef * js_init_module_std (JSContext *ctx, const char *module_name)
JSModuleDef * js_init_module_os (JSContext *ctx, const char *module_name)
void js_std_add_helpers (JSContext *ctx, int argc, char **argv)
void js_std_loop (JSContext *ctx)
void js_std_init_handlers (JSRuntime *rt)
void js_std_free_handlers (JSRuntime *rt)
void js_std_dump_error (JSContext *ctx)
uint8_t * js_load_file (JSContext *ctx, size_t *pbuf_len, const char *filename)
int js_module_set_import_meta (JSContext *ctx, JSValueConst func_val, JS_BOOL use_realpath, JS_BOOL is_main)
JSModuleDef * js_module_loader (JSContext *ctx, const char *module_name, void *opaque)
void js_std_eval_binary (JSContext *ctx, const uint8_t *buf, size_t buf_len, int flags)
void js_std_promise_rejection_tracker (JSContext *ctx, JSValueConst promise, JSValueConst reason, JS_BOOL is_handled, void *opaque)
void js_std_set_worker_new_context_func (JSContext *(*func)(JSRuntime *rt))
Function Documentation
js_init_module_std()
JSModuleDef* js_init_module_std (JSContext * ctx, const char * module_name)
Definition at line 1554 of file quickjs-libc.c.
References JS_AddModuleExport(), JS_AddModuleExportList(), JS_NewCModule(), js_std_funcs, and js_std_init().
Referenced by main().
 {
     JSModuleDef *m;
     m = JS_NewCModule(ctx, module_name, js_std_init);
     if (!m)
         return NULL;
     JS_AddModuleExportList(ctx, m, js_std_funcs, countof(js_std_funcs));
     JS_AddModuleExport(ctx, m, "in");
     JS_AddModuleExport(ctx, m, "out");
     JS_AddModuleExport(ctx, m, "err");
     return m;
 }
js_init_module_os()
JSModuleDef* js_init_module_os (JSContext * ctx, const char * module_name)
Definition at line 3657 of file quickjs-libc.c.
References JS_AddModuleExport(), JS_AddModuleExportList(), JS_NewCModule(), js_os_funcs, and js_os_init().
Referenced by main().
 {
     JSModuleDef *m;
     m = JS_NewCModule(ctx, module_name, js_os_init);
     if (!m)
         return NULL;
     JS_AddModuleExportList(ctx, m, js_os_funcs, countof(js_os_funcs));
 #ifdef USE_WORKER
     JS_AddModuleExport(ctx, m, "Worker");
 #endif
     return m;
 }
js_std_add_helpers()
void js_std_add_helpers (JSContext * ctx, int argc, char ** argv)
Definition at line 3692 of file quickjs-libc.c.
References JS_FreeValue(), JS_GetGlobalObject(), js_loadScript(), JS_NewArray(), JS_NewCFunction(), JS_NewObject(), JS_NewString(), js_print(), JS_SetPropertyStr(), and JS_SetPropertyUint32().
Referenced by main(), and worker_func().
 {
     JSValue global_obj, console, args;
     int i;
     /* XXX: should these global definitions be enumerable? */
     global_obj = JS_GetGlobalObject(ctx);
     console = JS_NewObject(ctx);
     JS_SetPropertyStr(ctx, console, "log",
                       JS_NewCFunction(ctx, js_print, "log", 1));
     JS_SetPropertyStr(ctx, global_obj, "console", console);
     /* same methods as the mozilla JS shell */
     if (argc >= 0) {
         args = JS_NewArray(ctx);
         for(i = 0; i < argc; i++) {
             JS_SetPropertyUint32(ctx, args, i, JS_NewString(ctx, argv[i]));
         }
         JS_SetPropertyStr(ctx, global_obj, "scriptArgs", args);
     }
     JS_SetPropertyStr(ctx, global_obj, "print",
                       JS_NewCFunction(ctx, js_print, "print", 1));
     JS_SetPropertyStr(ctx, global_obj, "__loadScript",
                       JS_NewCFunction(ctx, js_loadScript, "__loadScript", 1));
     JS_FreeValue(ctx, global_obj);
 }
js_std_loop()
void js_std_loop (JSContext * ctx)
Definition at line 3833 of file quickjs-libc.c.
References JS_ExecutePendingJob(), JS_GetRuntime(), js_std_dump_error(), and os_poll_func.
Referenced by main(), and worker_func().
 {
     JSContext *ctx1;
     int err;
     for(;;) {
         /* execute the pending jobs */
         for(;;) {
             err = JS_ExecutePendingJob(JS_GetRuntime(ctx), &ctx1);
             if (err <= 0) {
                 if (err < 0) {
                     js_std_dump_error(ctx1);
                 }
                 break;
             }
         }
         if (!os_poll_func || os_poll_func(ctx))
             break;
     }
 }
js_std_init_handlers()
void js_std_init_handlers (JSRuntime * rt)
Definition at line 3722 of file quickjs-libc.c.
References init_list_head(), js_sab_alloc(), js_sab_dup(), js_sab_free(), JS_SetRuntimeOpaque(), JS_SetSharedArrayBufferFunctions(), JSThreadState::os_rw_handlers, JSThreadState::os_signal_handlers, JSThreadState::os_timers, JSThreadState::port_list, JSSharedArrayBufferFunctions::sab_alloc, JSSharedArrayBufferFunctions::sab_dup, and JSSharedArrayBufferFunctions::sab_free.
Referenced by main(), and worker_func().
 {
     JSThreadState *ts;
     ts = malloc(sizeof(*ts));
     if (!ts) {
         fprintf(stderr, "Could not allocate memory for the worker");
         exit(1);
     }
     memset(ts, 0, sizeof(*ts));
     init_list_head(&ts->os_rw_handlers);
     init_list_head(&ts->os_signal_handlers);
     init_list_head(&ts->os_timers);
     init_list_head(&ts->port_list);
     JS_SetRuntimeOpaque(rt, ts);
 #ifdef USE_WORKER
     /* set the SharedArrayBuffer memory handlers */
     {
         JSSharedArrayBufferFunctions sf;
         memset(&sf, 0, sizeof(sf));
         sf.sab_alloc = js_sab_alloc;
         sf.sab_free = js_sab_free;
         sf.sab_dup = js_sab_dup;
         JS_SetSharedArrayBufferFunctions(rt, &sf);
     }
 #endif
 }
js_std_free_handlers()
void js_std_free_handlers (JSRuntime * rt)
Definition at line 3752 of file quickjs-libc.c.
References JS_SetRuntimeOpaque().
Referenced by main(), and worker_func().
 {
     JSThreadState *ts = JS_GetRuntimeOpaque(rt);
     struct list_head *el, *el1;
     list_for_each_safe(el, el1, &ts->os_rw_handlers) {
         JSOSRWHandler *rh = list_entry(el, JSOSRWHandler, link);
         free_rw_handler(rt, rh);
     }
     list_for_each_safe(el, el1, &ts->os_signal_handlers) {
         JSOSSignalHandler *sh = list_entry(el, JSOSSignalHandler, link);
         free_sh(rt, sh);
     }
     list_for_each_safe(el, el1, &ts->os_timers) {
         JSOSTimer *th = list_entry(el, JSOSTimer, link);
         unlink_timer(rt, th);
         if (!th->has_object)
             free_timer(rt, th);
     }
 #ifdef USE_WORKER
     /* XXX: free port_list ? */
     js_free_message_pipe(ts->recv_pipe);
     js_free_message_pipe(ts->send_pipe);
 #endif
     free(ts);
     JS_SetRuntimeOpaque(rt, NULL); /* fail safe */
 }
js_std_dump_error()
void js_std_dump_error (JSContext * ctx)
Definition at line 3813 of file quickjs-libc.c.
References JS_FreeValue(), JS_GetException(), and js_std_dump_error1().
Referenced by call_handler(), handle_posted_message(), js_std_eval_binary(), js_std_loop(), and worker_func().
 {
     JSValue exception_val;
     exception_val = JS_GetException(ctx);
     js_std_dump_error1(ctx, exception_val);
     JS_FreeValue(ctx, exception_val);
 }
js_load_file()
uint8_t* js_load_file (JSContext * ctx, size_t * pbuf_len, const char * filename)
Definition at line 361 of file quickjs-libc.c.
References js_free().
Referenced by qjs::Context::evalFile(), js_loadScript(), js_module_loader(), and js_std_loadFile().
 {
     FILE *f;
     uint8_t *buf;
     size_t buf_len;
     long lret;
     f = fopen(filename, "rb");
     if (!f)
         return NULL;
     if (fseek(f, 0, SEEK_END) < 0)
         goto fail;
     lret = ftell(f);
     if (lret < 0)
         goto fail;
     /* XXX: on Linux, ftell() return LONG_MAX for directories */
     if (lret == LONG_MAX) {
         errno = EISDIR;
         goto fail;
     }
     buf_len = lret;
     if (fseek(f, 0, SEEK_SET) < 0)
         goto fail;
     if (ctx)
         buf = js_malloc(ctx, buf_len + 1);
     else
         buf = malloc(buf_len + 1);
     if (!buf)
         goto fail;
     if (fread(buf, 1, buf_len, f) != buf_len) {
         errno = EIO;
         if (ctx)
             js_free(ctx, buf);
         else
             free(buf);
     fail:
         fclose(f);
         return NULL;
     }
     buf[buf_len] = '\0';
     fclose(f);
     *pbuf_len = buf_len;
     return buf;
 }
js_module_set_import_meta()
int js_module_set_import_meta (JSContext * ctx, JSValueConst func_val, JS_BOOL use_realpath, JS_BOOL is_main)
Definition at line 514 of file quickjs-libc.c.
References JS_AtomToCString(), JS_DefinePropertyValueStr(), JS_FreeAtom(), JS_FreeCString(), JS_FreeValue(), JS_GetImportMeta(), JS_GetModuleName(), JS_IsException(), JS_NewBool(), JS_NewString(), JS_TAG_MODULE, pstrcat(), and pstrcpy().
Referenced by js_module_loader(), and js_std_eval_binary().
 {
     JSModuleDef *m;
     char buf[PATH_MAX + 16];
     JSValue meta_obj;
     JSAtom module_name_atom;
     const char *module_name;
     assert(JS_VALUE_GET_TAG(func_val) == JS_TAG_MODULE);
     m = JS_VALUE_GET_PTR(func_val);
     module_name_atom = JS_GetModuleName(ctx, m);
     module_name = JS_AtomToCString(ctx, module_name_atom);
     JS_FreeAtom(ctx, module_name_atom);
     if (!module_name)
         return -1;
     if (!strchr(module_name, ':')) {
         strcpy(buf, "file://");
 #if !defined(_WIN32)
         /* realpath() cannot be used with modules compiled with qjsc
            because the corresponding module source code is not
            necessarily present */
         if (use_realpath) {
             char *res = realpath(module_name, buf + strlen(buf));
             if (!res) {
                 JS_ThrowTypeError(ctx, "realpath failure");
                 JS_FreeCString(ctx, module_name);
                 return -1;
             }
         } else
 #endif
         {
             pstrcat(buf, sizeof(buf), module_name);
         }
     } else {
         pstrcpy(buf, sizeof(buf), module_name);
     }
     JS_FreeCString(ctx, module_name);
     meta_obj = JS_GetImportMeta(ctx, m);
     if (JS_IsException(meta_obj))
         return -1;
     JS_DefinePropertyValueStr(ctx, meta_obj, "url",
                               JS_NewString(ctx, buf),
                               JS_PROP_C_W_E);
     JS_DefinePropertyValueStr(ctx, meta_obj, "main",
                               JS_NewBool(ctx, is_main),
                               JS_PROP_C_W_E);
     JS_FreeValue(ctx, meta_obj);
     return 0;
 }
js_module_loader()
JSModuleDef* js_module_loader (JSContext * ctx, const char * module_name, void * opaque)
Definition at line 567 of file quickjs-libc.c.
References FALSE, has_suffix(), JS_Eval(), js_free(), JS_FreeValue(), JS_IsException(), js_load_file(), js_module_loader_so(), js_module_set_import_meta(), and TRUE.
Referenced by main(), and worker_func().
 {
     JSModuleDef *m;
     if (has_suffix(module_name, ".so")) {
         m = js_module_loader_so(ctx, module_name);
     } else {
         size_t buf_len;
         uint8_t *buf;
         JSValue func_val;
         buf = js_load_file(ctx, &buf_len, module_name);
         if (!buf) {
             JS_ThrowReferenceError(ctx, "could not load module filename '%s'",
                                    module_name);
             return NULL;
         }
         /* compile the module */
         func_val = JS_Eval(ctx, (char *)buf, buf_len, module_name,
                            JS_EVAL_TYPE_MODULE | JS_EVAL_FLAG_COMPILE_ONLY);
         js_free(ctx, buf);
         if (JS_IsException(func_val))
             return NULL;
         /* XXX: could propagate the exception */
         js_module_set_import_meta(ctx, func_val, TRUE, FALSE);
         /* the module is already referenced, so we must free it */
         m = JS_VALUE_GET_PTR(func_val);
         JS_FreeValue(ctx, func_val);
     }
     return m;
 }
js_std_eval_binary()
void js_std_eval_binary (JSContext * ctx, const uint8_t * buf, size_t buf_len, int flags)
Definition at line 3855 of file quickjs-libc.c.
References FALSE, JS_EvalFunction(), JS_FreeValue(), JS_IsException(), js_module_set_import_meta(), JS_ReadObject(), JS_ResolveModule(), js_std_dump_error(), JS_TAG_MODULE, and TRUE.
 {
     JSValue obj, val;
     obj = JS_ReadObject(ctx, buf, buf_len, JS_READ_OBJ_BYTECODE);
     if (JS_IsException(obj))
         goto exception;
     if (load_only) {
         if (JS_VALUE_GET_TAG(obj) == JS_TAG_MODULE) {
             js_module_set_import_meta(ctx, obj, FALSE, FALSE);
         }
     } else {
         if (JS_VALUE_GET_TAG(obj) == JS_TAG_MODULE) {
             if (JS_ResolveModule(ctx, obj) < 0) {
                 JS_FreeValue(ctx, obj);
                 goto exception;
             }
             js_module_set_import_meta(ctx, obj, FALSE, TRUE);
         }
         val = JS_EvalFunction(ctx, obj);
         if (JS_IsException(val)) {
         exception:
             js_std_dump_error(ctx);
             exit(1);
         }
         JS_FreeValue(ctx, val);
     }
 }
js_std_promise_rejection_tracker()
void js_std_promise_rejection_tracker (JSContext * ctx, JSValueConst promise, JSValueConst reason, JS_BOOL is_handled, void * opaque)
js_std_set_worker_new_context_func()
void js_std_set_worker_new_context_func (JSContext *(*)(JSRuntime *rt) func)
Definition at line 3516 of file quickjs-libc.c.
 {
 #ifdef USE_WORKER
     js_worker_new_context_func = func;
 #endif
 }