QuickJSPP: quickjs/quickjs.h File Reference
quickjs.h File Reference
#include <stdio.h>
#include <stdint.h>
Classes
struct JSRefCountHeader
union JSValueUnion
struct JSValue
struct JSMallocState
struct JSMallocFunctions
struct JSMemoryUsage
struct JSPropertyEnum
struct JSPropertyDescriptor
struct JSClassExoticMethods
struct JSClassDef
struct JSSharedArrayBufferFunctions
union JSCFunctionType
struct JSCFunctionListEntry
Macros
#define js_likely(x) (x)
#define js_unlikely(x) (x)
#define js_force_inline inline
#define __js_printf_like(a, b)
#define JS_BOOL int
#define JS_PTR64
#define JS_PTR64_DEF(a) a
#define JS_FLOAT64_NAN NAN
#define JSValueConst JSValue
#define JS_VALUE_GET_TAG(v) ((int32_t)(v).tag)
#define JS_VALUE_GET_NORM_TAG(v) JS_VALUE_GET_TAG(v)
#define JS_VALUE_GET_INT(v) ((v).u.int32)
#define JS_VALUE_GET_BOOL(v) ((v).u.int32)
#define JS_VALUE_GET_FLOAT64(v) ((v).u.float64)
#define JS_VALUE_GET_PTR(v) ((v).u.ptr)
#define JS_MKVAL(tag, val) (JSValue){ (JSValueUnion){ .int32 = val }, tag }
#define JS_MKPTR(tag, p) (JSValue){ (JSValueUnion){ .ptr = p }, tag }
#define JS_TAG_IS_FLOAT64(tag) ((unsigned)(tag) == JS_TAG_FLOAT64)
#define JS_NAN (JSValue){ .u.float64 = JS_FLOAT64_NAN, JS_TAG_FLOAT64 }
#define JS_VALUE_IS_BOTH_INT(v1, v2) ((JS_VALUE_GET_TAG(v1) | JS_VALUE_GET_TAG(v2)) == 0)
#define JS_VALUE_IS_BOTH_FLOAT(v1, v2) (JS_TAG_IS_FLOAT64(JS_VALUE_GET_TAG(v1)) && JS_TAG_IS_FLOAT64(JS_VALUE_GET_TAG(v2)))
#define JS_VALUE_GET_OBJ(v) ((JSObject *)JS_VALUE_GET_PTR(v))
#define JS_VALUE_GET_STRING(v) ((JSString *)JS_VALUE_GET_PTR(v))
#define JS_VALUE_HAS_REF_COUNT(v) ((unsigned)JS_VALUE_GET_TAG(v) >= (unsigned)JS_TAG_FIRST)
#define JS_NULL JS_MKVAL(JS_TAG_NULL, 0)
#define JS_UNDEFINED JS_MKVAL(JS_TAG_UNDEFINED, 0)
#define JS_FALSE JS_MKVAL(JS_TAG_BOOL, 0)
#define JS_TRUE JS_MKVAL(JS_TAG_BOOL, 1)
#define JS_EXCEPTION JS_MKVAL(JS_TAG_EXCEPTION, 0)
#define JS_UNINITIALIZED JS_MKVAL(JS_TAG_UNINITIALIZED, 0)
#define JS_PROP_CONFIGURABLE (1 << 0)
#define JS_PROP_WRITABLE (1 << 1)
#define JS_PROP_ENUMERABLE (1 << 2)
#define JS_PROP_C_W_E (JS_PROP_CONFIGURABLE | JS_PROP_WRITABLE | JS_PROP_ENUMERABLE)
#define JS_PROP_LENGTH (1 << 3) /* used internally in Arrays */
#define JS_PROP_TMASK (3 << 4) /* mask for NORMAL, GETSET, VARREF, AUTOINIT */
#define JS_PROP_NORMAL (0 << 4)
#define JS_PROP_GETSET (1 << 4)
#define JS_PROP_VARREF (2 << 4) /* used internally */
#define JS_PROP_AUTOINIT (3 << 4) /* used internally */
#define JS_PROP_HAS_SHIFT 8
#define JS_PROP_HAS_CONFIGURABLE (1 << 8)
#define JS_PROP_HAS_WRITABLE (1 << 9)
#define JS_PROP_HAS_ENUMERABLE (1 << 10)
#define JS_PROP_HAS_GET (1 << 11)
#define JS_PROP_HAS_SET (1 << 12)
#define JS_PROP_HAS_VALUE (1 << 13)
#define JS_PROP_THROW (1 << 14)
#define JS_PROP_THROW_STRICT (1 << 15)
#define JS_PROP_NO_ADD (1 << 16) /* internal use */
#define JS_PROP_NO_EXOTIC (1 << 17) /* internal use */
#define JS_DEFAULT_STACK_SIZE (256 * 1024)
#define JS_EVAL_TYPE_GLOBAL (0 << 0) /* global code (default) */
#define JS_EVAL_TYPE_MODULE (1 << 0) /* module code */
#define JS_EVAL_TYPE_DIRECT (2 << 0) /* direct call (internal use) */
#define JS_EVAL_TYPE_INDIRECT (3 << 0) /* indirect call (internal use) */
#define JS_EVAL_TYPE_MASK (3 << 0)
#define JS_EVAL_FLAG_STRICT (1 << 3) /* force 'strict' mode */
#define JS_EVAL_FLAG_STRIP (1 << 4) /* force 'strip' mode */
#define JS_EVAL_FLAG_COMPILE_ONLY (1 << 5)
#define JS_EVAL_FLAG_BACKTRACE_BARRIER (1 << 6)
#define JS_ATOM_NULL 0
#define JS_CALL_FLAG_CONSTRUCTOR (1 << 0)
#define JS_GPN_STRING_MASK (1 << 0)
#define JS_GPN_SYMBOL_MASK (1 << 1)
#define JS_GPN_PRIVATE_MASK (1 << 2)
#define JS_GPN_ENUM_ONLY (1 << 4)
#define JS_GPN_SET_ENUM (1 << 5)
#define JS_PARSE_JSON_EXT (1 << 0) /* allow extended JSON */
#define JS_WRITE_OBJ_BYTECODE (1 << 0) /* allow function/module */
#define JS_WRITE_OBJ_BSWAP (1 << 1) /* byte swapped output */
#define JS_WRITE_OBJ_SAB (1 << 2) /* allow SharedArrayBuffer */
#define JS_WRITE_OBJ_REFERENCE
#define JS_READ_OBJ_BYTECODE (1 << 0) /* allow function/module */
#define JS_READ_OBJ_ROM_DATA (1 << 1) /* avoid duplicating 'buf' data */
#define JS_READ_OBJ_SAB (1 << 2) /* allow SharedArrayBuffer */
#define JS_READ_OBJ_REFERENCE (1 << 3) /* allow object references */
#define JS_DEF_CFUNC 0
#define JS_DEF_CGETSET 1
#define JS_DEF_CGETSET_MAGIC 2
#define JS_DEF_PROP_STRING 3
#define JS_DEF_PROP_INT32 4
#define JS_DEF_PROP_INT64 5
#define JS_DEF_PROP_DOUBLE 6
#define JS_DEF_PROP_UNDEFINED 7
#define JS_DEF_OBJECT 8
#define JS_DEF_ALIAS 9
#define JS_CFUNC_DEF(name, length, func1) { name, JS_PROP_WRITABLE | JS_PROP_CONFIGURABLE, JS_DEF_CFUNC, 0, .u = { .func = { length, JS_CFUNC_generic, { .generic = func1 } } } }
#define JS_CFUNC_MAGIC_DEF(name, length, func1, magic) { name, JS_PROP_WRITABLE | JS_PROP_CONFIGURABLE, JS_DEF_CFUNC, magic, .u = { .func = { length, JS_CFUNC_generic_magic, { .generic_magic = func1 } } } }
#define JS_CFUNC_SPECIAL_DEF(name, length, cproto, func1) { name, JS_PROP_WRITABLE | JS_PROP_CONFIGURABLE, JS_DEF_CFUNC, 0, .u = { .func = { length, JS_CFUNC_ ## cproto, { .cproto = func1 } } } }
#define JS_ITERATOR_NEXT_DEF(name, length, func1, magic) { name, JS_PROP_WRITABLE | JS_PROP_CONFIGURABLE, JS_DEF_CFUNC, magic, .u = { .func = { length, JS_CFUNC_iterator_next, { .iterator_next = func1 } } } }
#define JS_CGETSET_DEF(name, fgetter, fsetter) { name, JS_PROP_CONFIGURABLE, JS_DEF_CGETSET, 0, .u = { .getset = { .get = { .getter = fgetter }, .set = { .setter = fsetter } } } }
#define JS_CGETSET_MAGIC_DEF(name, fgetter, fsetter, magic) { name, JS_PROP_CONFIGURABLE, JS_DEF_CGETSET_MAGIC, magic, .u = { .getset = { .get = { .getter_magic = fgetter }, .set = { .setter_magic = fsetter } } } }
#define JS_PROP_STRING_DEF(name, cstr, prop_flags) { name, prop_flags, JS_DEF_PROP_STRING, 0, .u = { .str = cstr } }
#define JS_PROP_INT32_DEF(name, val, prop_flags) { name, prop_flags, JS_DEF_PROP_INT32, 0, .u = { .i32 = val } }
#define JS_PROP_INT64_DEF(name, val, prop_flags) { name, prop_flags, JS_DEF_PROP_INT64, 0, .u = { .i64 = val } }
#define JS_PROP_DOUBLE_DEF(name, val, prop_flags) { name, prop_flags, JS_DEF_PROP_DOUBLE, 0, .u = { .f64 = val } }
#define JS_PROP_UNDEFINED_DEF(name, prop_flags) { name, prop_flags, JS_DEF_PROP_UNDEFINED, 0, .u = { .i32 = 0 } }
#define JS_OBJECT_DEF(name, tab, len, prop_flags) { name, prop_flags, JS_DEF_OBJECT, 0, .u = { .prop_list = { tab, len } } }
#define JS_ALIAS_DEF(name, from) { name, JS_PROP_WRITABLE | JS_PROP_CONFIGURABLE, JS_DEF_ALIAS, 0, .u = { .alias = { from, -1 } } }
#define JS_ALIAS_BASE_DEF(name, from, base) { name, JS_PROP_WRITABLE | JS_PROP_CONFIGURABLE, JS_DEF_ALIAS, 0, .u = { .alias = { from, base } } }
Typedefs
typedef struct JSRuntime JSRuntime
typedef struct JSContext JSContext
typedef struct JSObject JSObject
typedef struct JSClass JSClass
typedef uint32_t JSClassID
typedef uint32_t JSAtom
typedef struct JSRefCountHeader JSRefCountHeader
typedef union JSValueUnion JSValueUnion
typedef struct JSValue JSValue
typedef JSValue JSCFunction(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv)
typedef JSValue JSCFunctionMagic(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv, int magic)
typedef JSValue JSCFunctionData(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv, int magic, JSValue *func_data)
typedef struct JSMallocState JSMallocState
typedef struct JSMallocFunctions JSMallocFunctions
typedef struct JSGCObjectHeader JSGCObjectHeader
typedef void JS_MarkFunc(JSRuntime *rt, JSGCObjectHeader *gp)
typedef struct JSMemoryUsage JSMemoryUsage
typedef struct JSPropertyEnum JSPropertyEnum
typedef struct JSPropertyDescriptor JSPropertyDescriptor
typedef struct JSClassExoticMethods JSClassExoticMethods
typedef void JSClassFinalizer(JSRuntime *rt, JSValue val)
typedef void JSClassGCMark(JSRuntime *rt, JSValueConst val, JS_MarkFunc *mark_func)
typedef JSValue JSClassCall(JSContext *ctx, JSValueConst func_obj, JSValueConst this_val, int argc, JSValueConst *argv, int flags)
typedef struct JSClassDef JSClassDef
typedef void JSFreeArrayBufferDataFunc(JSRuntime *rt, void *opaque, void *ptr)
typedef void JSHostPromiseRejectionTracker(JSContext *ctx, JSValueConst promise, JSValueConst reason, JS_BOOL is_handled, void *opaque)
typedef int JSInterruptHandler(JSRuntime *rt, void *opaque)
typedef struct JSModuleDef JSModuleDef
typedef char * JSModuleNormalizeFunc(JSContext *ctx, const char *module_base_name, const char *module_name, void *opaque)
typedef JSModuleDef * JSModuleLoaderFunc(JSContext *ctx, const char *module_name, void *opaque)
typedef JSValue JSJobFunc(JSContext *ctx, int argc, JSValueConst *argv)
typedef enum JSCFunctionEnum JSCFunctionEnum
typedef union JSCFunctionType JSCFunctionType
typedef struct JSCFunctionListEntry JSCFunctionListEntry
typedef int JSModuleInitFunc(JSContext *ctx, JSModuleDef *m)
Enumerations
enum {
JS_TAG_FIRST = -11, JS_TAG_BIG_DECIMAL = -11, JS_TAG_BIG_INT = -10, JS_TAG_BIG_FLOAT = -9,
JS_TAG_SYMBOL = -8, JS_TAG_STRING = -7, JS_TAG_MODULE = -3, JS_TAG_FUNCTION_BYTECODE = -2,
JS_TAG_OBJECT = -1, JS_TAG_INT = 0, JS_TAG_BOOL = 1, JS_TAG_NULL = 2,
JS_TAG_UNDEFINED = 3, JS_TAG_UNINITIALIZED = 4, JS_TAG_CATCH_OFFSET = 5, JS_TAG_EXCEPTION = 6,
JS_TAG_FLOAT64 = 7
}
enum JSCFunctionEnum {
JS_CFUNC_generic, JS_CFUNC_generic_magic, JS_CFUNC_constructor, JS_CFUNC_constructor_magic,
JS_CFUNC_constructor_or_func, JS_CFUNC_constructor_or_func_magic, JS_CFUNC_f_f, JS_CFUNC_f_f_f,
JS_CFUNC_getter, JS_CFUNC_setter, JS_CFUNC_getter_magic, JS_CFUNC_setter_magic,
JS_CFUNC_iterator_next
}
Functions
static JSValue __JS_NewFloat64 (JSContext *ctx, double d)
static JS_BOOL JS_VALUE_IS_NAN (JSValue v)
JSRuntime * JS_NewRuntime (void)
void JS_SetRuntimeInfo (JSRuntime *rt, const char *info)
void JS_SetMemoryLimit (JSRuntime *rt, size_t limit)
void JS_SetGCThreshold (JSRuntime *rt, size_t gc_threshold)
void JS_SetMaxStackSize (JSRuntime *rt, size_t stack_size)
JSRuntime * JS_NewRuntime2 (const JSMallocFunctions *mf, void *opaque)
void JS_FreeRuntime (JSRuntime *rt)
void * JS_GetRuntimeOpaque (JSRuntime *rt)
void JS_SetRuntimeOpaque (JSRuntime *rt, void *opaque)
void JS_MarkValue (JSRuntime *rt, JSValueConst val, JS_MarkFunc *mark_func)
void JS_RunGC (JSRuntime *rt)
JS_BOOL JS_IsLiveObject (JSRuntime *rt, JSValueConst obj)
JSContext * JS_NewContext (JSRuntime *rt)
void JS_FreeContext (JSContext *s)
JSContext * JS_DupContext (JSContext *ctx)
void * JS_GetContextOpaque (JSContext *ctx)
void JS_SetContextOpaque (JSContext *ctx, void *opaque)
JSRuntime * JS_GetRuntime (JSContext *ctx)
void JS_SetClassProto (JSContext *ctx, JSClassID class_id, JSValue obj)
JSValue JS_GetClassProto (JSContext *ctx, JSClassID class_id)
JSContext * JS_NewContextRaw (JSRuntime *rt)
void JS_AddIntrinsicBaseObjects (JSContext *ctx)
void JS_AddIntrinsicDate (JSContext *ctx)
void JS_AddIntrinsicEval (JSContext *ctx)
void JS_AddIntrinsicStringNormalize (JSContext *ctx)
void JS_AddIntrinsicRegExpCompiler (JSContext *ctx)
void JS_AddIntrinsicRegExp (JSContext *ctx)
void JS_AddIntrinsicJSON (JSContext *ctx)
void JS_AddIntrinsicProxy (JSContext *ctx)
void JS_AddIntrinsicMapSet (JSContext *ctx)
void JS_AddIntrinsicTypedArrays (JSContext *ctx)
void JS_AddIntrinsicPromise (JSContext *ctx)
void JS_AddIntrinsicBigInt (JSContext *ctx)
void JS_AddIntrinsicBigFloat (JSContext *ctx)
void JS_AddIntrinsicBigDecimal (JSContext *ctx)
void JS_AddIntrinsicOperators (JSContext *ctx)
void JS_EnableBignumExt (JSContext *ctx, JS_BOOL enable)
JSValue js_string_codePointRange (JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv)
void * js_malloc_rt (JSRuntime *rt, size_t size)
void js_free_rt (JSRuntime *rt, void *ptr)
void * js_realloc_rt (JSRuntime *rt, void *ptr, size_t size)
size_t js_malloc_usable_size_rt (JSRuntime *rt, const void *ptr)
void * js_mallocz_rt (JSRuntime *rt, size_t size)
void * js_malloc (JSContext *ctx, size_t size)
void js_free (JSContext *ctx, void *ptr)
void * js_realloc (JSContext *ctx, void *ptr, size_t size)
size_t js_malloc_usable_size (JSContext *ctx, const void *ptr)
void * js_realloc2 (JSContext *ctx, void *ptr, size_t size, size_t *pslack)
void * js_mallocz (JSContext *ctx, size_t size)
char * js_strdup (JSContext *ctx, const char *str)
char * js_strndup (JSContext *ctx, const char *s, size_t n)
void JS_ComputeMemoryUsage (JSRuntime *rt, JSMemoryUsage *s)
void JS_DumpMemoryUsage (FILE *fp, const JSMemoryUsage *s, JSRuntime *rt)
JSAtom JS_NewAtomLen (JSContext *ctx, const char *str, size_t len)
JSAtom JS_NewAtom (JSContext *ctx, const char *str)
JSAtom JS_NewAtomUInt32 (JSContext *ctx, uint32_t n)
JSAtom JS_DupAtom (JSContext *ctx, JSAtom v)
void JS_FreeAtom (JSContext *ctx, JSAtom v)
void JS_FreeAtomRT (JSRuntime *rt, JSAtom v)
JSValue JS_AtomToValue (JSContext *ctx, JSAtom atom)
JSValue JS_AtomToString (JSContext *ctx, JSAtom atom)
const char * JS_AtomToCString (JSContext *ctx, JSAtom atom)
JSAtom JS_ValueToAtom (JSContext *ctx, JSValueConst val)
JSClassID JS_NewClassID (JSClassID *pclass_id)
JSClassID JS_GetClassID (JSValueConst v)
int JS_NewClass (JSRuntime *rt, JSClassID class_id, const JSClassDef *class_def)
int JS_IsRegisteredClass (JSRuntime *rt, JSClassID class_id)
static js_force_inline JSValue JS_NewBool (JSContext *ctx, JS_BOOL val)
static js_force_inline JSValue JS_NewInt32 (JSContext *ctx, int32_t val)
static js_force_inline JSValue JS_NewCatchOffset (JSContext *ctx, int32_t val)
static js_force_inline JSValue JS_NewInt64 (JSContext *ctx, int64_t val)
static js_force_inline JSValue JS_NewUint32 (JSContext *ctx, uint32_t val)
JSValue JS_NewBigInt64 (JSContext *ctx, int64_t v)
JSValue JS_NewBigUint64 (JSContext *ctx, uint64_t v)
static js_force_inline JSValue JS_NewFloat64 (JSContext *ctx, double d)
static JS_BOOL JS_IsNumber (JSValueConst v)
static JS_BOOL JS_IsBigInt (JSContext *ctx, JSValueConst v)
static JS_BOOL JS_IsBigFloat (JSValueConst v)
static JS_BOOL JS_IsBigDecimal (JSValueConst v)
static JS_BOOL JS_IsBool (JSValueConst v)
static JS_BOOL JS_IsNull (JSValueConst v)
static JS_BOOL JS_IsUndefined (JSValueConst v)
static JS_BOOL JS_IsException (JSValueConst v)
static JS_BOOL JS_IsUninitialized (JSValueConst v)
static JS_BOOL JS_IsString (JSValueConst v)
static JS_BOOL JS_IsSymbol (JSValueConst v)
static JS_BOOL JS_IsObject (JSValueConst v)
JSValue JS_Throw (JSContext *ctx, JSValue obj)
JSValue JS_GetException (JSContext *ctx)
JS_BOOL JS_IsError (JSContext *ctx, JSValueConst val)
void JS_ResetUncatchableError (JSContext *ctx)
JSValue JS_NewError (JSContext *ctx)
JSValue __js_printf_like (2, 3) JS_ThrowSyntaxError(JSContext *ctx
JSValue const char JSValue const char JSValue const char JSValue const char JSValue const char JSValue JS_ThrowOutOfMemory (JSContext *ctx)
void __JS_FreeValue (JSContext *ctx, JSValue v)
static void JS_FreeValue (JSContext *ctx, JSValue v)
void __JS_FreeValueRT (JSRuntime *rt, JSValue v)
static void JS_FreeValueRT (JSRuntime *rt, JSValue v)
static JSValue JS_DupValue (JSContext *ctx, JSValueConst v)
static JSValue JS_DupValueRT (JSRuntime *rt, JSValueConst v)
int JS_ToBool (JSContext *ctx, JSValueConst val)
int JS_ToInt32 (JSContext *ctx, int32_t *pres, JSValueConst val)
static int JS_ToUint32 (JSContext *ctx, uint32_t *pres, JSValueConst val)
int JS_ToInt64 (JSContext *ctx, int64_t *pres, JSValueConst val)
int JS_ToIndex (JSContext *ctx, uint64_t *plen, JSValueConst val)
int JS_ToFloat64 (JSContext *ctx, double *pres, JSValueConst val)
int JS_ToBigInt64 (JSContext *ctx, int64_t *pres, JSValueConst val)
int JS_ToInt64Ext (JSContext *ctx, int64_t *pres, JSValueConst val)
JSValue JS_NewStringLen (JSContext *ctx, const char *str1, size_t len1)
JSValue JS_NewString (JSContext *ctx, const char *str)
JSValue JS_NewAtomString (JSContext *ctx, const char *str)
JSValue JS_ToString (JSContext *ctx, JSValueConst val)
JSValue JS_ToPropertyKey (JSContext *ctx, JSValueConst val)
const char * JS_ToCStringLen2 (JSContext *ctx, size_t *plen, JSValueConst val1, JS_BOOL cesu8)
static const char * JS_ToCStringLen (JSContext *ctx, size_t *plen, JSValueConst val1)
static const char * JS_ToCString (JSContext *ctx, JSValueConst val1)
void JS_FreeCString (JSContext *ctx, const char *ptr)
JSValue JS_NewObjectProtoClass (JSContext *ctx, JSValueConst proto, JSClassID class_id)
JSValue JS_NewObjectClass (JSContext *ctx, int class_id)
JSValue JS_NewObjectProto (JSContext *ctx, JSValueConst proto)
JSValue JS_NewObject (JSContext *ctx)
JS_BOOL JS_IsFunction (JSContext *ctx, JSValueConst val)
JS_BOOL JS_IsConstructor (JSContext *ctx, JSValueConst val)
JS_BOOL JS_SetConstructorBit (JSContext *ctx, JSValueConst func_obj, JS_BOOL val)
JSValue JS_NewArray (JSContext *ctx)
int JS_IsArray (JSContext *ctx, JSValueConst val)
JSValue JS_GetPropertyInternal (JSContext *ctx, JSValueConst obj, JSAtom prop, JSValueConst receiver, JS_BOOL throw_ref_error)
static js_force_inline JSValue JS_GetProperty (JSContext *ctx, JSValueConst this_obj, JSAtom prop)
JSValue JS_GetPropertyStr (JSContext *ctx, JSValueConst this_obj, const char *prop)
JSValue JS_GetPropertyUint32 (JSContext *ctx, JSValueConst this_obj, uint32_t idx)
int JS_SetPropertyInternal (JSContext *ctx, JSValueConst this_obj, JSAtom prop, JSValue val, int flags)
static int JS_SetProperty (JSContext *ctx, JSValueConst this_obj, JSAtom prop, JSValue val)
int JS_SetPropertyUint32 (JSContext *ctx, JSValueConst this_obj, uint32_t idx, JSValue val)
int JS_SetPropertyInt64 (JSContext *ctx, JSValueConst this_obj, int64_t idx, JSValue val)
int JS_SetPropertyStr (JSContext *ctx, JSValueConst this_obj, const char *prop, JSValue val)
int JS_HasProperty (JSContext *ctx, JSValueConst this_obj, JSAtom prop)
int JS_IsExtensible (JSContext *ctx, JSValueConst obj)
int JS_PreventExtensions (JSContext *ctx, JSValueConst obj)
int JS_DeleteProperty (JSContext *ctx, JSValueConst obj, JSAtom prop, int flags)
int JS_SetPrototype (JSContext *ctx, JSValueConst obj, JSValueConst proto_val)
JSValue JS_GetPrototype (JSContext *ctx, JSValueConst val)
int JS_GetOwnPropertyNames (JSContext *ctx, JSPropertyEnum **ptab, uint32_t *plen, JSValueConst obj, int flags)
int JS_GetOwnProperty (JSContext *ctx, JSPropertyDescriptor *desc, JSValueConst obj, JSAtom prop)
JSValue JS_Call (JSContext *ctx, JSValueConst func_obj, JSValueConst this_obj, int argc, JSValueConst *argv)
JSValue JS_Invoke (JSContext *ctx, JSValueConst this_val, JSAtom atom, int argc, JSValueConst *argv)
JSValue JS_CallConstructor (JSContext *ctx, JSValueConst func_obj, int argc, JSValueConst *argv)
JSValue JS_CallConstructor2 (JSContext *ctx, JSValueConst func_obj, JSValueConst new_target, int argc, JSValueConst *argv)
JS_BOOL JS_DetectModule (const char *input, size_t input_len)
JSValue JS_Eval (JSContext *ctx, const char *input, size_t input_len, const char *filename, int eval_flags)
JSValue JS_EvalThis (JSContext *ctx, JSValueConst this_obj, const char *input, size_t input_len, const char *filename, int eval_flags)
JSValue JS_GetGlobalObject (JSContext *ctx)
int JS_IsInstanceOf (JSContext *ctx, JSValueConst val, JSValueConst obj)
int JS_DefineProperty (JSContext *ctx, JSValueConst this_obj, JSAtom prop, JSValueConst val, JSValueConst getter, JSValueConst setter, int flags)
int JS_DefinePropertyValue (JSContext *ctx, JSValueConst this_obj, JSAtom prop, JSValue val, int flags)
int JS_DefinePropertyValueUint32 (JSContext *ctx, JSValueConst this_obj, uint32_t idx, JSValue val, int flags)
int JS_DefinePropertyValueStr (JSContext *ctx, JSValueConst this_obj, const char *prop, JSValue val, int flags)
int JS_DefinePropertyGetSet (JSContext *ctx, JSValueConst this_obj, JSAtom prop, JSValue getter, JSValue setter, int flags)
void JS_SetOpaque (JSValue obj, void *opaque)
void * JS_GetOpaque (JSValueConst obj, JSClassID class_id)
void * JS_GetOpaque2 (JSContext *ctx, JSValueConst obj, JSClassID class_id)
JSValue JS_ParseJSON (JSContext *ctx, const char *buf, size_t buf_len, const char *filename)
JSValue JS_ParseJSON2 (JSContext *ctx, const char *buf, size_t buf_len, const char *filename, int flags)
JSValue JS_JSONStringify (JSContext *ctx, JSValueConst obj, JSValueConst replacer, JSValueConst space0)
JSValue JS_NewArrayBuffer (JSContext *ctx, uint8_t *buf, size_t len, JSFreeArrayBufferDataFunc *free_func, void *opaque, JS_BOOL is_shared)
JSValue JS_NewArrayBufferCopy (JSContext *ctx, const uint8_t *buf, size_t len)
void JS_DetachArrayBuffer (JSContext *ctx, JSValueConst obj)
uint8_t * JS_GetArrayBuffer (JSContext *ctx, size_t *psize, JSValueConst obj)
JSValue JS_GetTypedArrayBuffer (JSContext *ctx, JSValueConst obj, size_t *pbyte_offset, size_t *pbyte_length, size_t *pbytes_per_element)
void JS_SetSharedArrayBufferFunctions (JSRuntime *rt, const JSSharedArrayBufferFunctions *sf)
JSValue JS_NewPromiseCapability (JSContext *ctx, JSValue *resolving_funcs)
void JS_SetHostPromiseRejectionTracker (JSRuntime *rt, JSHostPromiseRejectionTracker *cb, void *opaque)
void JS_SetInterruptHandler (JSRuntime *rt, JSInterruptHandler *cb, void *opaque)
void JS_SetCanBlock (JSRuntime *rt, JS_BOOL can_block)
void JS_SetIsHTMLDDA (JSContext *ctx, JSValueConst obj)
void JS_SetModuleLoaderFunc (JSRuntime *rt, JSModuleNormalizeFunc *module_normalize, JSModuleLoaderFunc *module_loader, void *opaque)
JSValue JS_GetImportMeta (JSContext *ctx, JSModuleDef *m)
JSAtom JS_GetModuleName (JSContext *ctx, JSModuleDef *m)
int JS_EnqueueJob (JSContext *ctx, JSJobFunc *job_func, int argc, JSValueConst *argv)
JS_BOOL JS_IsJobPending (JSRuntime *rt)
int JS_ExecutePendingJob (JSRuntime *rt, JSContext **pctx)
uint8_t * JS_WriteObject (JSContext *ctx, size_t *psize, JSValueConst obj, int flags)
uint8_t * JS_WriteObject2 (JSContext *ctx, size_t *psize, JSValueConst obj, int flags, uint8_t ***psab_tab, size_t *psab_tab_len)
JSValue JS_ReadObject (JSContext *ctx, const uint8_t *buf, size_t buf_len, int flags)
JSValue JS_EvalFunction (JSContext *ctx, JSValue fun_obj)
int JS_ResolveModule (JSContext *ctx, JSValueConst obj)
JSAtom JS_GetScriptOrModuleName (JSContext *ctx, int n_stack_levels)
JSModuleDef * JS_RunModule (JSContext *ctx, const char *basename, const char *filename)
JSValue JS_NewCFunction2 (JSContext *ctx, JSCFunction *func, const char *name, int length, JSCFunctionEnum cproto, int magic)
JSValue JS_NewCFunctionData (JSContext *ctx, JSCFunctionData *func, int length, int magic, int data_len, JSValueConst *data)
static JSValue JS_NewCFunction (JSContext *ctx, JSCFunction *func, const char *name, int length)
static JSValue JS_NewCFunctionMagic (JSContext *ctx, JSCFunctionMagic *func, const char *name, int length, JSCFunctionEnum cproto, int magic)
void JS_SetConstructor (JSContext *ctx, JSValueConst func_obj, JSValueConst proto)
void JS_SetPropertyFunctionList (JSContext *ctx, JSValueConst obj, const JSCFunctionListEntry *tab, int len)
JSModuleDef * JS_NewCModule (JSContext *ctx, const char *name_str, JSModuleInitFunc *func)
int JS_AddModuleExport (JSContext *ctx, JSModuleDef *m, const char *name_str)
int JS_AddModuleExportList (JSContext *ctx, JSModuleDef *m, const JSCFunctionListEntry *tab, int len)
int JS_SetModuleExport (JSContext *ctx, JSModuleDef *m, const char *export_name, JSValue val)
int JS_SetModuleExportList (JSContext *ctx, JSModuleDef *m, const JSCFunctionListEntry *tab, int len)
Variables
JSValue const char * fmt
Macro Definition Documentation
js_likely
#define js_likely (x) (x)
Definition at line 41 of file quickjs.h.
js_unlikely
#define js_unlikely (x) (x)
Definition at line 42 of file quickjs.h.
js_force_inline
#define js_force_inline inline
Definition at line 43 of file quickjs.h.
__js_printf_like
#define __js_printf_like (a, b)
Definition at line 44 of file quickjs.h.
JS_BOOL
#define JS_BOOL int
Definition at line 47 of file quickjs.h.
JS_PTR64
#define JS_PTR64
Definition at line 57 of file quickjs.h.
JS_PTR64_DEF
#define JS_PTR64_DEF (a) a
Definition at line 58 of file quickjs.h.
JS_FLOAT64_NAN
#define JS_FLOAT64_NAN NAN
Definition at line 94 of file quickjs.h.
JSValueConst
#define JSValueConst JSValue
Definition at line 208 of file quickjs.h.
JS_VALUE_GET_TAG
#define JS_VALUE_GET_TAG (v) ((int32_t)(v).tag)
Definition at line 210 of file quickjs.h.
JS_VALUE_GET_NORM_TAG
#define JS_VALUE_GET_NORM_TAG (v) JS_VALUE_GET_TAG(v)
Definition at line 212 of file quickjs.h.
JS_VALUE_GET_INT
#define JS_VALUE_GET_INT (v) ((v).u.int32)
Definition at line 213 of file quickjs.h.
JS_VALUE_GET_BOOL
#define JS_VALUE_GET_BOOL (v) ((v).u.int32)
Definition at line 214 of file quickjs.h.
JS_VALUE_GET_FLOAT64
#define JS_VALUE_GET_FLOAT64 (v) ((v).u.float64)
Definition at line 215 of file quickjs.h.
JS_VALUE_GET_PTR
#define JS_VALUE_GET_PTR (v) ((v).u.ptr)
Definition at line 216 of file quickjs.h.
JS_MKVAL
#define JS_MKVAL (tag, val) (JSValue){ (JSValueUnion){ .int32 = val }, tag }
Definition at line 218 of file quickjs.h.
JS_MKPTR
#define JS_MKPTR (tag, p) (JSValue){ (JSValueUnion){ .ptr = p }, tag }
Definition at line 219 of file quickjs.h.
JS_TAG_IS_FLOAT64
#define JS_TAG_IS_FLOAT64 (tag) ((unsigned)(tag) == JS_TAG_FLOAT64)
Definition at line 221 of file quickjs.h.
JS_NAN
#define JS_NAN (JSValue){ .u.float64 = JS_FLOAT64_NAN, JS_TAG_FLOAT64 }
Definition at line 223 of file quickjs.h.
JS_VALUE_IS_BOTH_INT
#define JS_VALUE_IS_BOTH_INT (v1, v2) ((JS_VALUE_GET_TAG(v1) | JS_VALUE_GET_TAG(v2)) == 0)
Definition at line 247 of file quickjs.h.
JS_VALUE_IS_BOTH_FLOAT
#define JS_VALUE_IS_BOTH_FLOAT (v1, v2) (JS_TAG_IS_FLOAT64(JS_VALUE_GET_TAG(v1)) && JS_TAG_IS_FLOAT64(JS_VALUE_GET_TAG(v2)))
Definition at line 248 of file quickjs.h.
JS_VALUE_GET_OBJ
#define JS_VALUE_GET_OBJ (v) ((JSObject *)JS_VALUE_GET_PTR(v))
Definition at line 250 of file quickjs.h.
JS_VALUE_GET_STRING
#define JS_VALUE_GET_STRING (v) ((JSString *)JS_VALUE_GET_PTR(v))
Definition at line 251 of file quickjs.h.
JS_VALUE_HAS_REF_COUNT
#define JS_VALUE_HAS_REF_COUNT (v) ((unsigned)JS_VALUE_GET_TAG(v) >= (unsigned)JS_TAG_FIRST)
Definition at line 252 of file quickjs.h.
JS_NULL
#define JS_NULL JS_MKVAL(JS_TAG_NULL, 0)
Definition at line 255 of file quickjs.h.
JS_UNDEFINED
#define JS_UNDEFINED JS_MKVAL(JS_TAG_UNDEFINED, 0)
Definition at line 256 of file quickjs.h.
JS_FALSE
#define JS_FALSE JS_MKVAL(JS_TAG_BOOL, 0)
Definition at line 257 of file quickjs.h.
JS_TRUE
#define JS_TRUE JS_MKVAL(JS_TAG_BOOL, 1)
Definition at line 258 of file quickjs.h.
JS_EXCEPTION
#define JS_EXCEPTION JS_MKVAL(JS_TAG_EXCEPTION, 0)
Definition at line 259 of file quickjs.h.
JS_UNINITIALIZED
#define JS_UNINITIALIZED JS_MKVAL(JS_TAG_UNINITIALIZED, 0)
Definition at line 260 of file quickjs.h.
JS_PROP_CONFIGURABLE
#define JS_PROP_CONFIGURABLE (1 << 0)
Definition at line 263 of file quickjs.h.
JS_PROP_WRITABLE
#define JS_PROP_WRITABLE (1 << 1)
Definition at line 264 of file quickjs.h.
JS_PROP_ENUMERABLE
#define JS_PROP_ENUMERABLE (1 << 2)
Definition at line 265 of file quickjs.h.
JS_PROP_C_W_E
#define JS_PROP_C_W_E (JS_PROP_CONFIGURABLE | JS_PROP_WRITABLE | JS_PROP_ENUMERABLE)
Definition at line 266 of file quickjs.h.
JS_PROP_LENGTH
#define JS_PROP_LENGTH (1 << 3) /* used internally in Arrays */
Definition at line 267 of file quickjs.h.
JS_PROP_TMASK
#define JS_PROP_TMASK (3 << 4) /* mask for NORMAL, GETSET, VARREF, AUTOINIT */
Definition at line 268 of file quickjs.h.
JS_PROP_NORMAL
#define JS_PROP_NORMAL (0 << 4)
Definition at line 269 of file quickjs.h.
JS_PROP_GETSET
#define JS_PROP_GETSET (1 << 4)
Definition at line 270 of file quickjs.h.
JS_PROP_VARREF
#define JS_PROP_VARREF (2 << 4) /* used internally */
Definition at line 271 of file quickjs.h.
JS_PROP_AUTOINIT
#define JS_PROP_AUTOINIT (3 << 4) /* used internally */
Definition at line 272 of file quickjs.h.
JS_PROP_HAS_SHIFT
#define JS_PROP_HAS_SHIFT 8
Definition at line 275 of file quickjs.h.
JS_PROP_HAS_CONFIGURABLE
#define JS_PROP_HAS_CONFIGURABLE (1 << 8)
Definition at line 276 of file quickjs.h.
JS_PROP_HAS_WRITABLE
#define JS_PROP_HAS_WRITABLE (1 << 9)
Definition at line 277 of file quickjs.h.
JS_PROP_HAS_ENUMERABLE
#define JS_PROP_HAS_ENUMERABLE (1 << 10)
Definition at line 278 of file quickjs.h.
JS_PROP_HAS_GET
#define JS_PROP_HAS_GET (1 << 11)
Definition at line 279 of file quickjs.h.
JS_PROP_HAS_SET
#define JS_PROP_HAS_SET (1 << 12)
Definition at line 280 of file quickjs.h.
JS_PROP_HAS_VALUE
#define JS_PROP_HAS_VALUE (1 << 13)
Definition at line 281 of file quickjs.h.
JS_PROP_THROW
#define JS_PROP_THROW (1 << 14)
Definition at line 285 of file quickjs.h.
JS_PROP_THROW_STRICT
#define JS_PROP_THROW_STRICT (1 << 15)
Definition at line 288 of file quickjs.h.
JS_PROP_NO_ADD
#define JS_PROP_NO_ADD (1 << 16) /* internal use */
Definition at line 290 of file quickjs.h.
JS_PROP_NO_EXOTIC
#define JS_PROP_NO_EXOTIC (1 << 17) /* internal use */
Definition at line 291 of file quickjs.h.
JS_DEFAULT_STACK_SIZE
#define JS_DEFAULT_STACK_SIZE (256 * 1024)
Definition at line 293 of file quickjs.h.
JS_EVAL_TYPE_GLOBAL
#define JS_EVAL_TYPE_GLOBAL (0 << 0) /* global code (default) */
Definition at line 296 of file quickjs.h.
JS_EVAL_TYPE_MODULE
#define JS_EVAL_TYPE_MODULE (1 << 0) /* module code */
Definition at line 297 of file quickjs.h.
JS_EVAL_TYPE_DIRECT
#define JS_EVAL_TYPE_DIRECT (2 << 0) /* direct call (internal use) */
Definition at line 298 of file quickjs.h.
JS_EVAL_TYPE_INDIRECT
#define JS_EVAL_TYPE_INDIRECT (3 << 0) /* indirect call (internal use) */
Definition at line 299 of file quickjs.h.
JS_EVAL_TYPE_MASK
#define JS_EVAL_TYPE_MASK (3 << 0)
Definition at line 300 of file quickjs.h.
JS_EVAL_FLAG_STRICT
#define JS_EVAL_FLAG_STRICT (1 << 3) /* force 'strict' mode */
Definition at line 302 of file quickjs.h.
JS_EVAL_FLAG_STRIP
#define JS_EVAL_FLAG_STRIP (1 << 4) /* force 'strip' mode */
Definition at line 303 of file quickjs.h.
JS_EVAL_FLAG_COMPILE_ONLY
#define JS_EVAL_FLAG_COMPILE_ONLY (1 << 5)
Definition at line 307 of file quickjs.h.
JS_EVAL_FLAG_BACKTRACE_BARRIER
#define JS_EVAL_FLAG_BACKTRACE_BARRIER (1 << 6)
Definition at line 309 of file quickjs.h.
JS_ATOM_NULL
#define JS_ATOM_NULL 0
Definition at line 415 of file quickjs.h.
JS_CALL_FLAG_CONSTRUCTOR
#define JS_CALL_FLAG_CONSTRUCTOR (1 << 0)
Definition at line 475 of file quickjs.h.
JS_GPN_STRING_MASK
#define JS_GPN_STRING_MASK (1 << 0)
Definition at line 754 of file quickjs.h.
JS_GPN_SYMBOL_MASK
#define JS_GPN_SYMBOL_MASK (1 << 1)
Definition at line 755 of file quickjs.h.
JS_GPN_PRIVATE_MASK
#define JS_GPN_PRIVATE_MASK (1 << 2)
Definition at line 756 of file quickjs.h.
JS_GPN_ENUM_ONLY
#define JS_GPN_ENUM_ONLY (1 << 4)
Definition at line 758 of file quickjs.h.
JS_GPN_SET_ENUM
#define JS_GPN_SET_ENUM (1 << 5)
Definition at line 760 of file quickjs.h.
JS_PARSE_JSON_EXT
#define JS_PARSE_JSON_EXT (1 << 0) /* allow extended JSON */
Definition at line 805 of file quickjs.h.
JS_WRITE_OBJ_BYTECODE
#define JS_WRITE_OBJ_BYTECODE (1 << 0) /* allow function/module */
Definition at line 875 of file quickjs.h.
JS_WRITE_OBJ_BSWAP
#define JS_WRITE_OBJ_BSWAP (1 << 1) /* byte swapped output */
Definition at line 876 of file quickjs.h.
JS_WRITE_OBJ_SAB
#define JS_WRITE_OBJ_SAB (1 << 2) /* allow SharedArrayBuffer */
Definition at line 877 of file quickjs.h.
JS_WRITE_OBJ_REFERENCE
#define JS_WRITE_OBJ_REFERENCE
Value:
(1 << 3) /* allow object references to
                                           encode arbitrary object
                                           graph */
Definition at line 878 of file quickjs.h.
JS_READ_OBJ_BYTECODE
#define JS_READ_OBJ_BYTECODE (1 << 0) /* allow function/module */
Definition at line 886 of file quickjs.h.
JS_READ_OBJ_ROM_DATA
#define JS_READ_OBJ_ROM_DATA (1 << 1) /* avoid duplicating 'buf' data */
Definition at line 887 of file quickjs.h.
JS_READ_OBJ_SAB
#define JS_READ_OBJ_SAB (1 << 2) /* allow SharedArrayBuffer */
Definition at line 888 of file quickjs.h.
JS_READ_OBJ_REFERENCE
#define JS_READ_OBJ_REFERENCE (1 << 3) /* allow object references */
Definition at line 889 of file quickjs.h.
JS_DEF_CFUNC
#define JS_DEF_CFUNC 0
Definition at line 992 of file quickjs.h.
JS_DEF_CGETSET
#define JS_DEF_CGETSET 1
Definition at line 993 of file quickjs.h.
JS_DEF_CGETSET_MAGIC
#define JS_DEF_CGETSET_MAGIC 2
Definition at line 994 of file quickjs.h.
JS_DEF_PROP_STRING
#define JS_DEF_PROP_STRING 3
Definition at line 995 of file quickjs.h.
JS_DEF_PROP_INT32
#define JS_DEF_PROP_INT32 4
Definition at line 996 of file quickjs.h.
JS_DEF_PROP_INT64
#define JS_DEF_PROP_INT64 5
Definition at line 997 of file quickjs.h.
JS_DEF_PROP_DOUBLE
#define JS_DEF_PROP_DOUBLE 6
Definition at line 998 of file quickjs.h.
JS_DEF_PROP_UNDEFINED
#define JS_DEF_PROP_UNDEFINED 7
Definition at line 999 of file quickjs.h.
JS_DEF_OBJECT
#define JS_DEF_OBJECT 8
Definition at line 1000 of file quickjs.h.
JS_DEF_ALIAS
#define JS_DEF_ALIAS 9
Definition at line 1001 of file quickjs.h.
JS_CFUNC_DEF
#define JS_CFUNC_DEF (name, length, func1) { name, JS_PROP_WRITABLE | JS_PROP_CONFIGURABLE, JS_DEF_CFUNC, 0, .u = { .func = { length, JS_CFUNC_generic, { .generic = func1 } } } }
Definition at line 1004 of file quickjs.h.
JS_CFUNC_MAGIC_DEF
#define JS_CFUNC_MAGIC_DEF (name, length, func1, magic) { name, JS_PROP_WRITABLE | JS_PROP_CONFIGURABLE, JS_DEF_CFUNC, magic, .u = { .func = { length, JS_CFUNC_generic_magic, { .generic_magic = func1 } } } }
Definition at line 1005 of file quickjs.h.
JS_CFUNC_SPECIAL_DEF
#define JS_CFUNC_SPECIAL_DEF (name, length, cproto, func1) { name, JS_PROP_WRITABLE | JS_PROP_CONFIGURABLE, JS_DEF_CFUNC, 0, .u = { .func = { length, JS_CFUNC_ ## cproto, { .cproto = func1 } } } }
Definition at line 1006 of file quickjs.h.
JS_ITERATOR_NEXT_DEF
#define JS_ITERATOR_NEXT_DEF (name, length, func1, magic) { name, JS_PROP_WRITABLE | JS_PROP_CONFIGURABLE, JS_DEF_CFUNC, magic, .u = { .func = { length, JS_CFUNC_iterator_next, { .iterator_next = func1 } } } }
Definition at line 1007 of file quickjs.h.
JS_CGETSET_DEF
#define JS_CGETSET_DEF (name, fgetter, fsetter) { name, JS_PROP_CONFIGURABLE, JS_DEF_CGETSET, 0, .u = { .getset = { .get = { .getter = fgetter }, .set = { .setter = fsetter } } } }
Definition at line 1008 of file quickjs.h.
JS_CGETSET_MAGIC_DEF
#define JS_CGETSET_MAGIC_DEF (name, fgetter, fsetter, magic) { name, JS_PROP_CONFIGURABLE, JS_DEF_CGETSET_MAGIC, magic, .u = { .getset = { .get = { .getter_magic = fgetter }, .set = { .setter_magic = fsetter } } } }
Definition at line 1009 of file quickjs.h.
JS_PROP_STRING_DEF
#define JS_PROP_STRING_DEF (name, cstr, prop_flags) { name, prop_flags, JS_DEF_PROP_STRING, 0, .u = { .str = cstr } }
Definition at line 1010 of file quickjs.h.
JS_PROP_INT32_DEF
#define JS_PROP_INT32_DEF (name, val, prop_flags) { name, prop_flags, JS_DEF_PROP_INT32, 0, .u = { .i32 = val } }
Definition at line 1011 of file quickjs.h.
JS_PROP_INT64_DEF
#define JS_PROP_INT64_DEF (name, val, prop_flags) { name, prop_flags, JS_DEF_PROP_INT64, 0, .u = { .i64 = val } }
Definition at line 1012 of file quickjs.h.
JS_PROP_DOUBLE_DEF
#define JS_PROP_DOUBLE_DEF (name, val, prop_flags) { name, prop_flags, JS_DEF_PROP_DOUBLE, 0, .u = { .f64 = val } }
Definition at line 1013 of file quickjs.h.
JS_PROP_UNDEFINED_DEF
#define JS_PROP_UNDEFINED_DEF (name, prop_flags) { name, prop_flags, JS_DEF_PROP_UNDEFINED, 0, .u = { .i32 = 0 } }
Definition at line 1014 of file quickjs.h.
JS_OBJECT_DEF
#define JS_OBJECT_DEF (name, tab, len, prop_flags) { name, prop_flags, JS_DEF_OBJECT, 0, .u = { .prop_list = { tab, len } } }
Definition at line 1015 of file quickjs.h.
JS_ALIAS_DEF
#define JS_ALIAS_DEF (name, from) { name, JS_PROP_WRITABLE | JS_PROP_CONFIGURABLE, JS_DEF_ALIAS, 0, .u = { .alias = { from, -1 } } }
Definition at line 1016 of file quickjs.h.
JS_ALIAS_BASE_DEF
#define JS_ALIAS_BASE_DEF (name, from, base) { name, JS_PROP_WRITABLE | JS_PROP_CONFIGURABLE, JS_DEF_ALIAS, 0, .u = { .alias = { from, base } } }
Definition at line 1017 of file quickjs.h.
Typedef Documentation
JSRuntime
typedef struct JSRuntime JSRuntime
Definition at line 49 of file quickjs.h.
JSContext
typedef struct JSContext JSContext
Definition at line 50 of file quickjs.h.
JSObject
typedef struct JSObject JSObject
Definition at line 51 of file quickjs.h.
JSClass
typedef struct JSClass JSClass
Definition at line 52 of file quickjs.h.
JSClassID
typedef uint32_t JSClassID
Definition at line 53 of file quickjs.h.
JSAtom
typedef uint32_t JSAtom
Definition at line 54 of file quickjs.h.
JSRefCountHeader
typedef struct JSRefCountHeader JSRefCountHeader
JSValueUnion
typedef union JSValueUnion JSValueUnion
JSValue
typedef struct JSValue JSValue
JSCFunction
typedef JSValue JSCFunction(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv)
Definition at line 311 of file quickjs.h.
JSCFunctionMagic
typedef JSValue JSCFunctionMagic(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv, int magic)
Definition at line 312 of file quickjs.h.
JSCFunctionData
typedef JSValue JSCFunctionData(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv, int magic, JSValue *func_data)
Definition at line 313 of file quickjs.h.
JSMallocState
typedef struct JSMallocState JSMallocState
JSMallocFunctions
typedef struct JSMallocFunctions JSMallocFunctions
JSGCObjectHeader
typedef struct JSGCObjectHeader JSGCObjectHeader
Definition at line 329 of file quickjs.h.
JS_MarkFunc
typedef void JS_MarkFunc(JSRuntime *rt, JSGCObjectHeader *gp)
Definition at line 341 of file quickjs.h.
JSMemoryUsage
typedef struct JSMemoryUsage JSMemoryUsage
JSPropertyEnum
typedef struct JSPropertyEnum JSPropertyEnum
JSPropertyDescriptor
typedef struct JSPropertyDescriptor JSPropertyDescriptor
JSClassExoticMethods
typedef struct JSClassExoticMethods JSClassExoticMethods
JSClassFinalizer
typedef void JSClassFinalizer(JSRuntime *rt, JSValue val)
Definition at line 472 of file quickjs.h.
JSClassGCMark
typedef void JSClassGCMark(JSRuntime *rt, JSValueConst val, JS_MarkFunc *mark_func)
Definition at line 473 of file quickjs.h.
JSClassCall
typedef JSValue JSClassCall(JSContext *ctx, JSValueConst func_obj, JSValueConst this_val, int argc, JSValueConst *argv, int flags)
Definition at line 476 of file quickjs.h.
JSClassDef
typedef struct JSClassDef JSClassDef
JSFreeArrayBufferDataFunc
typedef void JSFreeArrayBufferDataFunc(JSRuntime *rt, void *opaque, void *ptr)
Definition at line 811 of file quickjs.h.
JSHostPromiseRejectionTracker
typedef void JSHostPromiseRejectionTracker(JSContext *ctx, JSValueConst promise, JSValueConst reason, JS_BOOL is_handled, void *opaque)
Definition at line 834 of file quickjs.h.
JSInterruptHandler
typedef int JSInterruptHandler(JSRuntime *rt, void *opaque)
Definition at line 840 of file quickjs.h.
JSModuleDef
typedef struct JSModuleDef JSModuleDef
Definition at line 847 of file quickjs.h.
JSModuleNormalizeFunc
typedef char* JSModuleNormalizeFunc(JSContext *ctx, const char *module_base_name, const char *module_name, void *opaque)
Definition at line 851 of file quickjs.h.
JSModuleLoaderFunc
typedef JSModuleDef* JSModuleLoaderFunc(JSContext *ctx, const char *module_name, void *opaque)
Definition at line 854 of file quickjs.h.
JSJobFunc
typedef JSValue JSJobFunc(JSContext *ctx, int argc, JSValueConst *argv)
Definition at line 868 of file quickjs.h.
JSCFunctionEnum
typedef enum JSCFunctionEnum JSCFunctionEnum
JSCFunctionType
typedef union JSCFunctionType JSCFunctionType
JSCFunctionListEntry
typedef struct JSCFunctionListEntry JSCFunctionListEntry
JSModuleInitFunc
typedef int JSModuleInitFunc(JSContext *ctx, JSModuleDef *m)
Definition at line 1025 of file quickjs.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
JS_TAG_FIRST
JS_TAG_BIG_DECIMAL
JS_TAG_BIG_INT
JS_TAG_BIG_FLOAT
JS_TAG_SYMBOL
JS_TAG_STRING
JS_TAG_MODULE
JS_TAG_FUNCTION_BYTECODE
JS_TAG_OBJECT
JS_TAG_INT
JS_TAG_BOOL
JS_TAG_NULL
JS_TAG_UNDEFINED
JS_TAG_UNINITIALIZED
JS_TAG_CATCH_OFFSET
JS_TAG_EXCEPTION
JS_TAG_FLOAT64
Definition at line 67 of file quickjs.h.
      {
     /* all tags with a reference count are negative */
     JS_TAG_FIRST       = -11, /* first negative tag */
     JS_TAG_BIG_DECIMAL = -11,
     JS_TAG_BIG_INT     = -10,
     JS_TAG_BIG_FLOAT   = -9,
     JS_TAG_SYMBOL      = -8,
     JS_TAG_STRING      = -7,
     JS_TAG_MODULE      = -3, /* used internally */
     JS_TAG_FUNCTION_BYTECODE = -2, /* used internally */
     JS_TAG_OBJECT      = -1,
     JS_TAG_INT         = 0,
     JS_TAG_BOOL        = 1,
     JS_TAG_NULL        = 2,
     JS_TAG_UNDEFINED   = 3,
     JS_TAG_UNINITIALIZED = 4,
     JS_TAG_CATCH_OFFSET = 5,
     JS_TAG_EXCEPTION   = 6,
     JS_TAG_FLOAT64     = 7,
     /* any larger tag is FLOAT64 if JS_NAN_BOXING */
 };
JSCFunctionEnum
enum JSCFunctionEnum
Enumerator
JS_CFUNC_generic
JS_CFUNC_generic_magic
JS_CFUNC_constructor
JS_CFUNC_constructor_magic
JS_CFUNC_constructor_or_func
JS_CFUNC_constructor_or_func_magic
JS_CFUNC_f_f
JS_CFUNC_f_f_f
JS_CFUNC_getter
JS_CFUNC_setter
JS_CFUNC_getter_magic
JS_CFUNC_setter_magic
JS_CFUNC_iterator_next
Definition at line 906 of file quickjs.h.
                              {  /* XXX: should rename for namespace isolation */
     JS_CFUNC_generic,
     JS_CFUNC_generic_magic,
     JS_CFUNC_constructor,
     JS_CFUNC_constructor_magic,
     JS_CFUNC_constructor_or_func,
     JS_CFUNC_constructor_or_func_magic,
     JS_CFUNC_f_f,
     JS_CFUNC_f_f_f,
     JS_CFUNC_getter,
     JS_CFUNC_setter,
     JS_CFUNC_getter_magic,
     JS_CFUNC_setter_magic,
     JS_CFUNC_iterator_next,
 } JSCFunctionEnum;
Function Documentation
__JS_NewFloat64()
static JSValue __JS_NewFloat64 (JSContext * ctx, double d) inline static
Definition at line 225 of file quickjs.h.
References JSValueUnion::float64, JS_TAG_FLOAT64, JSValue::tag, and JSValue::u.
Referenced by JS_AtomIsNumericIndex1(), JS_CallInternal(), js_dataview_getValue(), JS_GetPropertyValue(), JS_InstantiateFunctionListItem(), js_math_min_max(), js_math_random(), JS_NewFloat64(), JS_NewInt64(), JS_NewUint32(), js_number_toExponential(), js_number_toFixed(), js_number_toPrecision(), JS_ReadObjectRec(), JS_SetModuleExportList(), js_TA_get_float32(), and js_TA_get_float64().
 {
     JSValue v;
     v.tag = JS_TAG_FLOAT64;
     v.u.float64 = d;
     return v;
 }
JS_VALUE_IS_NAN()
static JS_BOOL JS_VALUE_IS_NAN (JSValue v) inline static
Definition at line 233 of file quickjs.h.
References JSValueUnion::float64, JS_TAG_FLOAT64, JSValue::tag, and JSValue::u.
Referenced by next_token().
 {
     union {
         double d;
         uint64_t u64;
     } u;
     if (v.tag != JS_TAG_FLOAT64)
         return 0;
     u.d = v.u.float64;
     return (u.u64 & 0x7fffffffffffffff) > 0x7ff0000000000000;
 }
JS_NewRuntime()
JSRuntime* JS_NewRuntime (void)
Definition at line 1763 of file quickjs.c.
References def_malloc_funcs, and JS_NewRuntime2().
Referenced by qjs::Runtime::Runtime(), and worker_func().
 {
     return JS_NewRuntime2(&def_malloc_funcs, NULL);
 }
JS_SetRuntimeInfo()
void JS_SetRuntimeInfo (JSRuntime * rt, const char * info)
Definition at line 1917 of file quickjs.c.
References JSRuntime::rt_info.
 {
     if (rt)
         rt->rt_info = s;
 }
JS_SetMemoryLimit()
void JS_SetMemoryLimit (JSRuntime * rt, size_t limit)
Definition at line 1768 of file quickjs.c.
References JSMallocState::malloc_limit, and JSRuntime::malloc_state.
 {
     rt->malloc_state.malloc_limit = limit;
 }
JS_SetGCThreshold()
void JS_SetGCThreshold (JSRuntime * rt, size_t gc_threshold)
Definition at line 1774 of file quickjs.c.
References JSRuntime::malloc_gc_threshold.
 {
     rt->malloc_gc_threshold = gc_threshold;
 }
JS_SetMaxStackSize()
void JS_SetMaxStackSize (JSRuntime * rt, size_t stack_size)
Definition at line 2341 of file quickjs.c.
References JSRuntime::stack_size.
 {
     rt->stack_size = stack_size;
 }
JS_NewRuntime2()
JSRuntime* JS_NewRuntime2 (const JSMallocFunctions * mf, void * opaque)
Definition at line 1596 of file quickjs.c.
References JSClass::call, JSRuntime::class_array, JSRuntime::context_list, JSRuntime::current_exception, JSClass::exotic, JSRuntime::gc_obj_list, JSRuntime::gc_phase, JSRuntime::gc_zero_ref_count_list, init_class_range(), init_list_head(), init_shape_hash(), JSRuntime::job_list, js_arguments_exotic_methods, js_c_function_data_call(), js_call_bound_function(), js_call_c_function(), JS_CLASS_ARGUMENTS, JS_CLASS_BOUND_FUNCTION, JS_CLASS_C_FUNCTION, JS_CLASS_C_FUNCTION_DATA, JS_CLASS_GENERATOR_FUNCTION, JS_CLASS_MODULE_NS, JS_CLASS_OBJECT, JS_CLASS_STRING, JS_FreeRuntime(), JS_GC_PHASE_NONE, js_generator_function_call(), js_get_stack_pointer(), JS_InitAtoms(), js_malloc_usable_size_unknown(), js_module_ns_exotic_methods, js_std_class_def, js_string_exotic_methods, JSRuntime::malloc_gc_threshold, JSMallocState::malloc_limit, JSRuntime::malloc_state, JSRuntime::mf, JSMallocState::opaque, JSRuntime::stack_size, and JSRuntime::stack_top.
Referenced by JS_NewRuntime().
 {
     JSRuntime *rt;
     JSMallocState ms;
     memset(&ms, 0, sizeof(ms));
     ms.opaque = opaque;
     ms.malloc_limit = -1;
     rt = mf->js_malloc(&ms, sizeof(JSRuntime));
     if (!rt)
         return NULL;
     memset(rt, 0, sizeof(*rt));
     rt->mf = *mf;
     if (!rt->mf.js_malloc_usable_size) {
         /* use dummy function if none provided */
         rt->mf.js_malloc_usable_size = js_malloc_usable_size_unknown;
     }
     rt->malloc_state = ms;
     rt->malloc_gc_threshold = 256 * 1024;
 #ifdef CONFIG_BIGNUM
     bf_context_init(&rt->bf_ctx, js_bf_realloc, rt);
     set_dummy_numeric_ops(&rt->bigint_ops);
     set_dummy_numeric_ops(&rt->bigfloat_ops);
     set_dummy_numeric_ops(&rt->bigdecimal_ops);
 #endif
     init_list_head(&rt->context_list);
     init_list_head(&rt->gc_obj_list);
     init_list_head(&rt->gc_zero_ref_count_list);
     rt->gc_phase = JS_GC_PHASE_NONE;
 #ifdef DUMP_LEAKS
     init_list_head(&rt->string_list);
 #endif
     init_list_head(&rt->job_list);
     if (JS_InitAtoms(rt))
         goto fail;
     /* create the object, array and function classes */
     if (init_class_range(rt, js_std_class_def, JS_CLASS_OBJECT,
                          countof(js_std_class_def)) < 0)
         goto fail;
     rt->class_array[JS_CLASS_ARGUMENTS].exotic = &js_arguments_exotic_methods;
     rt->class_array[JS_CLASS_STRING].exotic = &js_string_exotic_methods;
     rt->class_array[JS_CLASS_MODULE_NS].exotic = &js_module_ns_exotic_methods;
     rt->class_array[JS_CLASS_C_FUNCTION].call = js_call_c_function;
     rt->class_array[JS_CLASS_C_FUNCTION_DATA].call = js_c_function_data_call;
     rt->class_array[JS_CLASS_BOUND_FUNCTION].call = js_call_bound_function;
     rt->class_array[JS_CLASS_GENERATOR_FUNCTION].call = js_generator_function_call;
     if (init_shape_hash(rt))
         goto fail;
     rt->stack_top = js_get_stack_pointer();
     rt->stack_size = JS_DEFAULT_STACK_SIZE;
     rt->current_exception = JS_NULL;
     return rt;
  fail:
     JS_FreeRuntime(rt);
     return NULL;
 }
JS_FreeRuntime()
void JS_FreeRuntime (JSRuntime * rt)
Definition at line 1923 of file quickjs.c.
References JSJobEntry::argc, JSJobEntry::argv, JSRuntime::atom_array, JSRuntime::atom_hash, atom_is_free(), JSRuntime::atom_size, JSRuntime::class_array, JSRuntime::class_count, JSClass::class_id, JSClass::class_name, JSRuntime::current_exception, JSRuntime::gc_obj_list, init_list_head(), JSRuntime::job_list, JSMallocFunctions::js_free, js_free_rt(), JS_FreeAtomRT(), JS_FreeValueRT(), JS_RunGC(), JSJobEntry::link, list_empty(), JSRuntime::malloc_state, JSRuntime::mf, and JSRuntime::shape_hash.
Referenced by JS_NewRuntime2(), worker_func(), and qjs::Runtime::~Runtime().
 {
     struct list_head *el, *el1;
     int i;
     JS_FreeValueRT(rt, rt->current_exception);
     list_for_each_safe(el, el1, &rt->job_list) {
         JSJobEntry *e = list_entry(el, JSJobEntry, link);
         for(i = 0; i < e->argc; i++)
             JS_FreeValueRT(rt, e->argv[i]);
         js_free_rt(rt, e);
     }
     init_list_head(&rt->job_list);
     JS_RunGC(rt);
 #ifdef DUMP_LEAKS
     /* leaking objects */
     {
         BOOL header_done;
         JSGCObjectHeader *p;
         int count;
         /* remove the internal refcounts to display only the object
            referenced externally */
         list_for_each(el, &rt->gc_obj_list) {
             p = list_entry(el, JSGCObjectHeader, link);
             p->mark = 0;
         }
         gc_decref(rt);
         header_done = FALSE;
         list_for_each(el, &rt->gc_obj_list) {
             p = list_entry(el, JSGCObjectHeader, link);
             if (p->ref_count != 0) {
                 if (!header_done) {
                     printf("Object leaks:\n");
                     JS_DumpObjectHeader(rt);
                     header_done = TRUE;
                 }
                 JS_DumpGCObject(rt, p);
             }
         }
         count = 0;
         list_for_each(el, &rt->gc_obj_list) {
             p = list_entry(el, JSGCObjectHeader, link);
             if (p->ref_count == 0) {
                 count++;
             }
         }
         if (count != 0)
             printf("Secondary object leaks: %d\n", count);
     }
 #endif
     assert(list_empty(&rt->gc_obj_list));
     /* free the classes */
     for(i = 0; i < rt->class_count; i++) {
         JSClass *cl = &rt->class_array[i];
         if (cl->class_id != 0) {
             JS_FreeAtomRT(rt, cl->class_name);
         }
     }
     js_free_rt(rt, rt->class_array);
 #ifdef CONFIG_BIGNUM
     bf_context_end(&rt->bf_ctx);
 #endif
 #ifdef DUMP_LEAKS
     /* only the atoms defined in JS_InitAtoms() should be left */
     {
         BOOL header_done = FALSE;
         for(i = 0; i < rt->atom_size; i++) {
             JSAtomStruct *p = rt->atom_array[i];
             if (!atom_is_free(p) /* && p->str*/) {
                 if (i >= JS_ATOM_END || p->header.ref_count != 1) {
                     if (!header_done) {
                         header_done = TRUE;
                         if (rt->rt_info) {
                             printf("%s:1: atom leakage:", rt->rt_info);
                         } else {
                             printf("Atom leaks:\n"
                                    "    %6s %6s %s\n",
                                    "ID", "REFCNT", "NAME");
                         }
                     }
                     if (rt->rt_info) {
                         printf(" ");
                     } else {
                         printf("    %6u %6u ", i, p->header.ref_count);
                     }
                     switch (p->atom_type) {
                     case JS_ATOM_TYPE_STRING:
                         JS_DumpString(rt, p);
                         break;
                     case JS_ATOM_TYPE_GLOBAL_SYMBOL:
                         printf("Symbol.for(");
                         JS_DumpString(rt, p);
                         printf(")");
                         break;
                     case JS_ATOM_TYPE_SYMBOL:
                         if (p->hash == JS_ATOM_HASH_SYMBOL) {
                             printf("Symbol(");
                             JS_DumpString(rt, p);
                             printf(")");
                         } else {
                             printf("Private(");
                             JS_DumpString(rt, p);
                             printf(")");
                         }
                         break;
                     }
                     if (rt->rt_info) {
                         printf(":%u", p->header.ref_count);
                     } else {
                         printf("\n");
                     }
                 }
             }
         }
         if (rt->rt_info && header_done)
             printf("\n");
     }
 #endif
     /* free the atoms */
     for(i = 0; i < rt->atom_size; i++) {
         JSAtomStruct *p = rt->atom_array[i];
         if (!atom_is_free(p)) {
 #ifdef DUMP_LEAKS
             list_del(&p->link);
 #endif
             js_free_rt(rt, p);
         }
     }
     js_free_rt(rt, rt->atom_array);
     js_free_rt(rt, rt->atom_hash);
     js_free_rt(rt, rt->shape_hash);
 #ifdef DUMP_LEAKS
     if (!list_empty(&rt->string_list)) {
         if (rt->rt_info) {
             printf("%s:1: string leakage:", rt->rt_info);
         } else {
             printf("String leaks:\n"
                    "    %6s %s\n",
                    "REFCNT", "VALUE");
         }
         list_for_each_safe(el, el1, &rt->string_list) {
             JSString *str = list_entry(el, JSString, link);
             if (rt->rt_info) {
                 printf(" ");
             } else {
                 printf("    %6u ", str->header.ref_count);
             }
             JS_DumpString(rt, str);
             if (rt->rt_info) {
                 printf(":%u", str->header.ref_count);
             } else {
                 printf("\n");
             }
             list_del(&str->link);
             js_free_rt(rt, str);
         }
         if (rt->rt_info)
             printf("\n");
     }
     {
         JSMallocState *s = &rt->malloc_state;
         if (s->malloc_count > 1) {
             if (rt->rt_info)
                 printf("%s:1: ", rt->rt_info);
             printf("Memory leak: %"PRIu64" bytes lost in %"PRIu64" block%s\n",
                    (uint64_t)(s->malloc_size - sizeof(JSRuntime)),
                    (uint64_t)(s->malloc_count - 1), &"s"[s->malloc_count == 2]);
         }
     }
 #endif
     {
         JSMallocState ms = rt->malloc_state;
         rt->mf.js_free(&ms, rt);
     }
 }
JS_GetRuntimeOpaque()
void* JS_GetRuntimeOpaque (JSRuntime * rt)
Definition at line 1662 of file quickjs.c.
References JSRuntime::user_opaque.
 {
     return rt->user_opaque;
 }
JS_SetRuntimeOpaque()
void JS_SetRuntimeOpaque (JSRuntime * rt, void * opaque)
Definition at line 1667 of file quickjs.c.
References JSRuntime::user_opaque.
Referenced by js_std_free_handlers(), and js_std_init_handlers().
 {
     rt->user_opaque = opaque;
 }
JS_MarkValue()
void JS_MarkValue (JSRuntime * rt, JSValueConst val, JS_MarkFunc * mark_func)
Definition at line 5547 of file quickjs.c.
Referenced by async_func_mark(), js_array_iterator_mark(), js_array_mark(), js_bound_function_mark(), js_bytecode_function_mark(), js_for_in_iterator_mark(), js_map_iterator_mark(), js_map_mark(), js_mark_module_def(), JS_MarkContext(), js_object_data_mark(), js_promise_resolve_function_mark(), js_regexp_string_iterator_mark(), js_typed_array_mark(), and mark_children().
 {
     if (JS_VALUE_HAS_REF_COUNT(val)) {
         switch(JS_VALUE_GET_TAG(val)) {
         case JS_TAG_OBJECT:
         case JS_TAG_FUNCTION_BYTECODE:
             mark_func(rt, JS_VALUE_GET_PTR(val));
             break;
         default:
             break;
         }
     }
 }
JS_RunGC()
void JS_RunGC (JSRuntime * rt)
Definition at line 5774 of file quickjs.c.
References gc_decref(), gc_free_cycles(), and gc_scan().
Referenced by JS_FreeRuntime(), js_std_gc(), and js_trigger_gc().
 {
     /* decrement the reference of the children of each object. mark =
        1 after this pass. */
     gc_decref(rt);
     /* keep the GC objects with a non zero refcount and their childs */
     gc_scan(rt);
     /* free the GC objects in a cycle */
     gc_free_cycles(rt);
 }
JS_IsLiveObject()
JS_BOOL JS_IsLiveObject (JSRuntime * rt, JSValueConst obj)
Definition at line 5790 of file quickjs.c.
References FALSE, and JS_IsObject().
Referenced by js_map_iterator_finalizer(), and js_typed_array_finalizer().
 {
     JSObject *p;
     if (!JS_IsObject(obj))
         return FALSE;
     p = JS_VALUE_GET_OBJ(obj);
     return !p->free_mark;
 }
JS_NewContext()
JSContext* JS_NewContext (JSRuntime * rt)
Definition at line 2146 of file quickjs.c.
References JS_AddIntrinsicBaseObjects(), JS_AddIntrinsicDate(), JS_AddIntrinsicEval(), JS_AddIntrinsicJSON(), JS_AddIntrinsicMapSet(), JS_AddIntrinsicPromise(), JS_AddIntrinsicProxy(), JS_AddIntrinsicRegExp(), JS_AddIntrinsicStringNormalize(), JS_AddIntrinsicTypedArrays(), and JS_NewContextRaw().
Referenced by qjs::Context::Context().
 {
     JSContext *ctx;
     ctx = JS_NewContextRaw(rt);
     if (!ctx)
         return NULL;
     JS_AddIntrinsicBaseObjects(ctx);
     JS_AddIntrinsicDate(ctx);
     JS_AddIntrinsicEval(ctx);
     JS_AddIntrinsicStringNormalize(ctx);
     JS_AddIntrinsicRegExp(ctx);
     JS_AddIntrinsicJSON(ctx);
     JS_AddIntrinsicProxy(ctx);
     JS_AddIntrinsicMapSet(ctx);
     JS_AddIntrinsicTypedArrays(ctx);
     JS_AddIntrinsicPromise(ctx);
 #ifdef CONFIG_BIGNUM
     JS_AddIntrinsicBigInt(ctx);
 #endif
     return ctx;
 }
JS_FreeContext()
void JS_FreeContext (JSContext * s)
Definition at line 2269 of file quickjs.c.
References JSContext::array_ctor, JSContext::array_proto_values, JSContext::array_shape, JSContext::async_iterator_proto, JSRuntime::class_count, JSContext::class_proto, JSContext::eval_obj, JSContext::function_ctor, JSContext::function_proto, JSContext::global_obj, JSContext::global_var_obj, JSContext::header, JSContext::iterator_proto, JS_FREE_MODULE_ALL, js_free_modules(), js_free_rt(), js_free_shape_null(), JS_FreeValue(), JS_NATIVE_ERROR_COUNT, JSContext::link, list_del(), JSContext::native_error_proto, JSContext::promise_ctor, JSGCObjectHeader::ref_count, JSContext::regexp_ctor, remove_gc_object(), JSContext::rt, and JSContext::throw_type_error.
Referenced by free_function_bytecode(), js_autoinit_free(), js_c_function_finalizer(), worker_func(), and qjs::Context::~Context().
 {
     JSRuntime *rt = ctx->rt;
     int i;
     if (--ctx->header.ref_count > 0)
         return;
     assert(ctx->header.ref_count == 0);
 #ifdef DUMP_ATOMS
     JS_DumpAtoms(ctx->rt);
 #endif
 #ifdef DUMP_SHAPES
     JS_DumpShapes(ctx->rt);
 #endif
 #ifdef DUMP_OBJECTS
     {
         struct list_head *el;
         JSGCObjectHeader *p;
         printf("JSObjects: {\n");
         JS_DumpObjectHeader(ctx->rt);
         list_for_each(el, &rt->gc_obj_list) {
             p = list_entry(el, JSGCObjectHeader, link);
             JS_DumpGCObject(rt, p);
         }
         printf("}\n");
     }
 #endif
 #ifdef DUMP_MEM
     {
         JSMemoryUsage stats;
         JS_ComputeMemoryUsage(rt, &stats);
         JS_DumpMemoryUsage(stdout, &stats, rt);
     }
 #endif
     js_free_modules(ctx, JS_FREE_MODULE_ALL);
     JS_FreeValue(ctx, ctx->global_obj);
     JS_FreeValue(ctx, ctx->global_var_obj);
     JS_FreeValue(ctx, ctx->throw_type_error);
     JS_FreeValue(ctx, ctx->eval_obj);
     JS_FreeValue(ctx, ctx->array_proto_values);
     for(i = 0; i < JS_NATIVE_ERROR_COUNT; i++) {
         JS_FreeValue(ctx, ctx->native_error_proto[i]);
     }
     for(i = 0; i < rt->class_count; i++) {
         JS_FreeValue(ctx, ctx->class_proto[i]);
     }
     js_free_rt(rt, ctx->class_proto);
     JS_FreeValue(ctx, ctx->iterator_proto);
     JS_FreeValue(ctx, ctx->async_iterator_proto);
     JS_FreeValue(ctx, ctx->promise_ctor);
     JS_FreeValue(ctx, ctx->array_ctor);
     JS_FreeValue(ctx, ctx->regexp_ctor);
     JS_FreeValue(ctx, ctx->function_ctor);
     JS_FreeValue(ctx, ctx->function_proto);
     js_free_shape_null(ctx->rt, ctx->array_shape);
     list_del(&ctx->link);
     remove_gc_object(&ctx->header);
     js_free_rt(ctx->rt, ctx);
 }
JS_DupContext()
JSContext* JS_DupContext (JSContext * ctx)
Definition at line 2224 of file quickjs.c.
References JSContext::header, and JSGCObjectHeader::ref_count.
Referenced by js_create_function(), JS_DefineAutoInitProperty(), JS_NewCFunction3(), and JS_ReadFunctionTag().
 {
     ctx->header.ref_count++;
     return ctx;
 }
JS_GetContextOpaque()
void* JS_GetContextOpaque (JSContext * ctx)
Definition at line 2170 of file quickjs.c.
References JSContext::user_opaque.
Referenced by qjs::Context::get().
 {
     return ctx->user_opaque;
 }
JS_SetContextOpaque()
void JS_SetContextOpaque (JSContext * ctx, void * opaque)
Definition at line 2175 of file quickjs.c.
References JSContext::user_opaque.
Referenced by qjs::Context::init().
 {
     ctx->user_opaque = opaque;
 }
JS_GetRuntime()
JSRuntime* JS_GetRuntime (JSContext * ctx)
Definition at line 2336 of file quickjs.c.
References JSContext::rt.
Referenced by js_evalScript(), js_os_init(), js_os_poll(), js_os_setReadHandler(), js_os_setTimeout(), js_os_signal(), js_std_dbuf_init(), js_std_gc(), js_std_init(), js_std_loop(), js_worker_ctor(), js_worker_set_onmessage(), qjs::js_traits< std::shared_ptr< T > >::register_class(), qjs::js_traits< detail::function >::register_class(), and qjs::js_traits< std::function< R(Args...)> >::wrap().
 {
     return ctx->rt;
 }
JS_SetClassProto()
void JS_SetClassProto (JSContext * ctx, JSClassID class_id, JSValue obj)
Definition at line 2190 of file quickjs.c.
References JSRuntime::class_count, JSContext::class_proto, JSContext::rt, and set_value().
Referenced by js_os_init(), js_std_init(), and qjs::js_traits< std::shared_ptr< T > >::register_class().
 {
     JSRuntime *rt = ctx->rt;
     assert(class_id < rt->class_count);
     set_value(ctx, &ctx->class_proto[class_id], obj);
 }
JS_GetClassProto()
JSValue JS_GetClassProto (JSContext * ctx, JSClassID class_id)
Definition at line 2197 of file quickjs.c.
References JSRuntime::class_count, JSContext::class_proto, JS_DupValue(), and JSContext::rt.
Referenced by js_worker_ctor_internal().
 {
     JSRuntime *rt = ctx->rt;
     assert(class_id < rt->class_count);
     return JS_DupValue(ctx, ctx->class_proto[class_id]);
 }
JS_NewContextRaw()
JSContext* JS_NewContextRaw (JSRuntime * rt)
Definition at line 2111 of file quickjs.c.
References add_gc_object(), JSContext::array_ctor, JSRuntime::class_count, JSContext::class_proto, JSRuntime::context_list, JSContext::header, init_list_head(), JS_AddIntrinsicBasicObjects(), js_free_rt(), JS_GC_OBJ_TYPE_JS_CONTEXT, JSContext::link, list_add_tail(), JSContext::loaded_modules, JSContext::promise_ctor, JSGCObjectHeader::ref_count, JSContext::regexp_ctor, and JSContext::rt.
Referenced by JS_NewContext().
 {
     JSContext *ctx;
     int i;
     ctx = js_mallocz_rt(rt, sizeof(JSContext));
     if (!ctx)
         return NULL;
     ctx->header.ref_count = 1;
     add_gc_object(rt, &ctx->header, JS_GC_OBJ_TYPE_JS_CONTEXT);
     ctx->class_proto = js_malloc_rt(rt, sizeof(ctx->class_proto[0]) *
                                     rt->class_count);
     if (!ctx->class_proto) {
         js_free_rt(rt, ctx);
         return NULL;
     }
     ctx->rt = rt;
     list_add_tail(&ctx->link, &rt->context_list);
 #ifdef CONFIG_BIGNUM
     ctx->bf_ctx = &rt->bf_ctx;
     ctx->fp_env.prec = 113;
     ctx->fp_env.flags = bf_set_exp_bits(15) | BF_RNDN | BF_FLAG_SUBNORMAL;
 #endif
     for(i = 0; i < rt->class_count; i++)
         ctx->class_proto[i] = JS_NULL;
     ctx->array_ctor = JS_NULL;
     ctx->regexp_ctor = JS_NULL;
     ctx->promise_ctor = JS_NULL;
     init_list_head(&ctx->loaded_modules);
     JS_AddIntrinsicBasicObjects(ctx);
     return ctx;
 }
JS_AddIntrinsicBaseObjects()
void JS_AddIntrinsicBaseObjects (JSContext * ctx)
Definition at line 50665 of file quickjs.c.
References JSContext::array_ctor, JSContext::array_proto_values, JSContext::class_proto, JSContext::eval_obj, FALSE, JSContext::function_ctor, JSContext::function_proto, JSContext::global_obj, JSContext::global_var_obj, JSContext::iterator_proto, JS_AGGREGATE_ERROR, js_array_constructor(), js_array_funcs, js_array_iterator_proto_funcs, js_array_proto_funcs, JS_AtomGetStr(), JS_AtomToString(), JS_AtomToValue(), js_boolean_constructor(), js_boolean_proto_funcs, JS_CFUNC_constructor_or_func_magic, JS_CLASS_ARRAY, JS_CLASS_ARRAY_ITERATOR, JS_CLASS_BOOLEAN, JS_CLASS_ERROR, JS_CLASS_GENERATOR, JS_CLASS_GENERATOR_FUNCTION, JS_CLASS_NUMBER, JS_CLASS_OBJECT, JS_CLASS_STRING, JS_CLASS_STRING_ITERATOR, JS_CLASS_SYMBOL, JS_DefineProperty(), JS_DefinePropertyValue(), JS_DefinePropertyValueStr(), JS_DupValue(), js_error_constructor(), JS_FreeValue(), JS_FUNC_GENERATOR, JS_FUNC_NORMAL, js_function_constructor(), js_function_proto_caller(), js_function_proto_funcs, js_generator_function_proto_funcs, js_generator_proto_funcs, JS_GetProperty(), js_global_eval(), js_global_funcs, js_iterator_proto_funcs, js_math_obj, JS_NATIVE_ERROR_COUNT, JS_NewBool(), JS_NewCFunction(), JS_NewCFunction3(), JS_NewCFunctionMagic(), JS_NewGlobalCConstructor(), JS_NewGlobalCConstructor2(), JS_NewInt32(), JS_NewObject(), JS_NewObjectProto(), JS_NewObjectProtoClass(), js_number_constructor(), js_number_funcs, js_number_proto_funcs, js_object_constructor(), js_object_funcs, js_object_proto_funcs, js_object_seal(), js_random_init(), js_reflect_obj, JS_SetConstructor2(), JS_SetObjectData(), JS_SetPropertyFunctionList(), js_string_constructor(), js_string_funcs, js_string_iterator_proto_funcs, js_string_proto_funcs, js_symbol_constructor(), js_symbol_funcs, js_symbol_proto_funcs, js_throw_type_error(), native_error_name, JSContext::native_error_proto, and JSContext::throw_type_error.
Referenced by JS_NewContext().
 {
     int i;
     JSValueConst obj, number_obj;
     JSValue obj1;
     ctx->throw_type_error = JS_NewCFunction(ctx, js_throw_type_error, NULL, 0);
     /* add caller and arguments properties to throw a TypeError */
     obj1 = JS_NewCFunction(ctx, js_function_proto_caller, NULL, 0);
     JS_DefineProperty(ctx, ctx->function_proto, JS_ATOM_caller, JS_UNDEFINED,
                       obj1, ctx->throw_type_error,
                       JS_PROP_HAS_GET | JS_PROP_HAS_SET |
                       JS_PROP_HAS_CONFIGURABLE | JS_PROP_CONFIGURABLE);
     JS_DefineProperty(ctx, ctx->function_proto, JS_ATOM_arguments, JS_UNDEFINED,
                       obj1, ctx->throw_type_error,
                       JS_PROP_HAS_GET | JS_PROP_HAS_SET |
                       JS_PROP_HAS_CONFIGURABLE | JS_PROP_CONFIGURABLE);
     JS_FreeValue(ctx, obj1);
     JS_FreeValue(ctx, js_object_seal(ctx, JS_UNDEFINED, 1, (JSValueConst *)&ctx->throw_type_error, 1));
     ctx->global_obj = JS_NewObject(ctx);
     ctx->global_var_obj = JS_NewObjectProto(ctx, JS_NULL);
     /* Object */
     obj = JS_NewGlobalCConstructor(ctx, "Object", js_object_constructor, 1,
                                    ctx->class_proto[JS_CLASS_OBJECT]);
     JS_SetPropertyFunctionList(ctx, obj, js_object_funcs, countof(js_object_funcs));
     JS_SetPropertyFunctionList(ctx, ctx->class_proto[JS_CLASS_OBJECT],
                                js_object_proto_funcs, countof(js_object_proto_funcs));
     /* Function */
     JS_SetPropertyFunctionList(ctx, ctx->function_proto, js_function_proto_funcs, countof(js_function_proto_funcs));
     ctx->function_ctor = JS_NewCFunctionMagic(ctx, js_function_constructor,
                                               "Function", 1, JS_CFUNC_constructor_or_func_magic,
                                               JS_FUNC_NORMAL);
     JS_NewGlobalCConstructor2(ctx, JS_DupValue(ctx, ctx->function_ctor), "Function",
                               ctx->function_proto);
     /* Error */
     obj1 = JS_NewCFunctionMagic(ctx, js_error_constructor,
                                 "Error", 1, JS_CFUNC_constructor_or_func_magic, -1);
     JS_NewGlobalCConstructor2(ctx, obj1,
                               "Error", ctx->class_proto[JS_CLASS_ERROR]);
     for(i = 0; i < JS_NATIVE_ERROR_COUNT; i++) {
         JSValue func_obj;
         int n_args;
         n_args = 1 + (i == JS_AGGREGATE_ERROR);
         func_obj = JS_NewCFunction3(ctx, (JSCFunction *)js_error_constructor,
                                     native_error_name[i], n_args,
                                     JS_CFUNC_constructor_or_func_magic, i, obj1);
         JS_NewGlobalCConstructor2(ctx, func_obj, native_error_name[i],
                                   ctx->native_error_proto[i]);
     }
     /* Iterator prototype */
     ctx->iterator_proto = JS_NewObject(ctx);
     JS_SetPropertyFunctionList(ctx, ctx->iterator_proto,
                                js_iterator_proto_funcs,
                                countof(js_iterator_proto_funcs));
     /* Array */
     JS_SetPropertyFunctionList(ctx, ctx->class_proto[JS_CLASS_ARRAY],
                                js_array_proto_funcs,
                                countof(js_array_proto_funcs));
     obj = JS_NewGlobalCConstructor(ctx, "Array", js_array_constructor, 1,
                                    ctx->class_proto[JS_CLASS_ARRAY]);
     ctx->array_ctor = JS_DupValue(ctx, obj);
     JS_SetPropertyFunctionList(ctx, obj, js_array_funcs,
                                countof(js_array_funcs));
     /* XXX: create auto_initializer */
     {
         /* initialize Array.prototype[Symbol.unscopables] */
         char const unscopables[] = "copyWithin" "\0" "entries" "\0" "fill" "\0" "find" "\0"
             "findIndex" "\0" "flat" "\0" "flatMap" "\0" "includes" "\0" "keys" "\0" "values" "\0";
         const char *p = unscopables;
         obj1 = JS_NewObjectProto(ctx, JS_NULL);
         for(p = unscopables; *p; p += strlen(p) + 1) {
             JS_DefinePropertyValueStr(ctx, obj1, p, JS_TRUE, JS_PROP_C_W_E);
         }
         JS_DefinePropertyValue(ctx, ctx->class_proto[JS_CLASS_ARRAY],
                                JS_ATOM_Symbol_unscopables, obj1,
                                JS_PROP_CONFIGURABLE);
     }
     /* needed to initialize arguments[Symbol.iterator] */
     ctx->array_proto_values =
         JS_GetProperty(ctx, ctx->class_proto[JS_CLASS_ARRAY], JS_ATOM_values);
     ctx->class_proto[JS_CLASS_ARRAY_ITERATOR] = JS_NewObjectProto(ctx, ctx->iterator_proto);
     JS_SetPropertyFunctionList(ctx, ctx->class_proto[JS_CLASS_ARRAY_ITERATOR],
                                js_array_iterator_proto_funcs,
                                countof(js_array_iterator_proto_funcs));
     /* parseFloat and parseInteger must be defined before Number
        because of the Number.parseFloat and Number.parseInteger
        aliases */
     JS_SetPropertyFunctionList(ctx, ctx->global_obj, js_global_funcs,
                                countof(js_global_funcs));
     /* Number */
     ctx->class_proto[JS_CLASS_NUMBER] = JS_NewObjectProtoClass(ctx, ctx->class_proto[JS_CLASS_OBJECT],
                                                                JS_CLASS_NUMBER);
     JS_SetObjectData(ctx, ctx->class_proto[JS_CLASS_NUMBER], JS_NewInt32(ctx, 0));
     JS_SetPropertyFunctionList(ctx, ctx->class_proto[JS_CLASS_NUMBER],
                                js_number_proto_funcs,
                                countof(js_number_proto_funcs));
     number_obj = JS_NewGlobalCConstructor(ctx, "Number", js_number_constructor, 1,
                                           ctx->class_proto[JS_CLASS_NUMBER]);
     JS_SetPropertyFunctionList(ctx, number_obj, js_number_funcs, countof(js_number_funcs));
     /* Boolean */
     ctx->class_proto[JS_CLASS_BOOLEAN] = JS_NewObjectProtoClass(ctx, ctx->class_proto[JS_CLASS_OBJECT],
                                                                 JS_CLASS_BOOLEAN);
     JS_SetObjectData(ctx, ctx->class_proto[JS_CLASS_BOOLEAN], JS_NewBool(ctx, FALSE));
     JS_SetPropertyFunctionList(ctx, ctx->class_proto[JS_CLASS_BOOLEAN], js_boolean_proto_funcs,
                                countof(js_boolean_proto_funcs));
     JS_NewGlobalCConstructor(ctx, "Boolean", js_boolean_constructor, 1,
                              ctx->class_proto[JS_CLASS_BOOLEAN]);
     /* String */
     ctx->class_proto[JS_CLASS_STRING] = JS_NewObjectProtoClass(ctx, ctx->class_proto[JS_CLASS_OBJECT],
                                                                JS_CLASS_STRING);
     JS_SetObjectData(ctx, ctx->class_proto[JS_CLASS_STRING], JS_AtomToString(ctx, JS_ATOM_empty_string));
     obj = JS_NewGlobalCConstructor(ctx, "String", js_string_constructor, 1,
                                    ctx->class_proto[JS_CLASS_STRING]);
     JS_SetPropertyFunctionList(ctx, obj, js_string_funcs,
                                countof(js_string_funcs));
     JS_SetPropertyFunctionList(ctx, ctx->class_proto[JS_CLASS_STRING], js_string_proto_funcs,
                                countof(js_string_proto_funcs));
     ctx->class_proto[JS_CLASS_STRING_ITERATOR] = JS_NewObjectProto(ctx, ctx->iterator_proto);
     JS_SetPropertyFunctionList(ctx, ctx->class_proto[JS_CLASS_STRING_ITERATOR],
                                js_string_iterator_proto_funcs,
                                countof(js_string_iterator_proto_funcs));
     /* Math: create as autoinit object */
     js_random_init(ctx);
     JS_SetPropertyFunctionList(ctx, ctx->global_obj, js_math_obj, countof(js_math_obj));
     /* ES6 Reflect: create as autoinit object */
     JS_SetPropertyFunctionList(ctx, ctx->global_obj, js_reflect_obj, countof(js_reflect_obj));
     /* ES6 Symbol */
     ctx->class_proto[JS_CLASS_SYMBOL] = JS_NewObject(ctx);
     JS_SetPropertyFunctionList(ctx, ctx->class_proto[JS_CLASS_SYMBOL], js_symbol_proto_funcs,
                                countof(js_symbol_proto_funcs));
     obj = JS_NewGlobalCConstructor(ctx, "Symbol", js_symbol_constructor, 0,
                                    ctx->class_proto[JS_CLASS_SYMBOL]);
     JS_SetPropertyFunctionList(ctx, obj, js_symbol_funcs,
                                countof(js_symbol_funcs));
     for(i = JS_ATOM_Symbol_toPrimitive; i < JS_ATOM_END; i++) {
         char buf[ATOM_GET_STR_BUF_SIZE];
         const char *str, *p;
         str = JS_AtomGetStr(ctx, buf, sizeof(buf), i);
         /* skip "Symbol." */
         p = strchr(str, '.');
         if (p)
             str = p + 1;
         JS_DefinePropertyValueStr(ctx, obj, str, JS_AtomToValue(ctx, i), 0);
     }
     /* ES6 Generator */
     ctx->class_proto[JS_CLASS_GENERATOR] = JS_NewObjectProto(ctx, ctx->iterator_proto);
     JS_SetPropertyFunctionList(ctx, ctx->class_proto[JS_CLASS_GENERATOR],
                                js_generator_proto_funcs,
                                countof(js_generator_proto_funcs));
     ctx->class_proto[JS_CLASS_GENERATOR_FUNCTION] = JS_NewObjectProto(ctx, ctx->function_proto);
     obj1 = JS_NewCFunctionMagic(ctx, js_function_constructor,
                                 "GeneratorFunction", 1,
                                 JS_CFUNC_constructor_or_func_magic, JS_FUNC_GENERATOR);
     JS_SetPropertyFunctionList(ctx,
                                ctx->class_proto[JS_CLASS_GENERATOR_FUNCTION],
                                js_generator_function_proto_funcs,
                                countof(js_generator_function_proto_funcs));
     JS_SetConstructor2(ctx, ctx->class_proto[JS_CLASS_GENERATOR_FUNCTION],
                        ctx->class_proto[JS_CLASS_GENERATOR],
                        JS_PROP_CONFIGURABLE, JS_PROP_CONFIGURABLE);
     JS_SetConstructor2(ctx, obj1, ctx->class_proto[JS_CLASS_GENERATOR_FUNCTION],
                        0, JS_PROP_CONFIGURABLE);
     JS_FreeValue(ctx, obj1);
     /* global properties */
     ctx->eval_obj = JS_NewCFunction(ctx, js_global_eval, "eval", 1);
     JS_DefinePropertyValue(ctx, ctx->global_obj, JS_ATOM_eval,
                            JS_DupValue(ctx, ctx->eval_obj),
                            JS_PROP_WRITABLE | JS_PROP_CONFIGURABLE);
     JS_DefinePropertyValue(ctx, ctx->global_obj, JS_ATOM_globalThis,
                            JS_DupValue(ctx, ctx->global_obj),
                            JS_PROP_CONFIGURABLE | JS_PROP_WRITABLE);
 }
JS_AddIntrinsicDate()
void JS_AddIntrinsicDate (JSContext * ctx)
Definition at line 48547 of file quickjs.c.
References JSContext::class_proto, JS_CLASS_DATE, js_date_constructor(), js_date_funcs, js_date_proto_funcs, JS_NewGlobalCConstructor(), JS_NewObject(), and JS_SetPropertyFunctionList().
Referenced by JS_NewContext().
 {
     JSValueConst obj;
     /* Date */
     ctx->class_proto[JS_CLASS_DATE] = JS_NewObject(ctx);
     JS_SetPropertyFunctionList(ctx, ctx->class_proto[JS_CLASS_DATE], js_date_proto_funcs,
                                countof(js_date_proto_funcs));
     obj = JS_NewGlobalCConstructor(ctx, "Date", js_date_constructor, 7,
                                    ctx->class_proto[JS_CLASS_DATE]);
     JS_SetPropertyFunctionList(ctx, obj, js_date_funcs, countof(js_date_funcs));
 }
JS_AddIntrinsicEval()
void JS_AddIntrinsicEval (JSContext * ctx)
Definition at line 48562 of file quickjs.c.
References __JS_EvalInternal().
Referenced by JS_NewContext().
 {
     ctx->eval_internal = __JS_EvalInternal;
 }
JS_AddIntrinsicStringNormalize()
void JS_AddIntrinsicStringNormalize (JSContext * ctx)
Definition at line 41520 of file quickjs.c.
References JSContext::class_proto, JS_CLASS_STRING, JS_SetPropertyFunctionList(), and js_string_proto_normalize.
Referenced by JS_NewContext().
 {
 #ifdef CONFIG_ALL_UNICODE
     JS_SetPropertyFunctionList(ctx, ctx->class_proto[JS_CLASS_STRING], js_string_proto_normalize,
                                countof(js_string_proto_normalize));
 #endif
 }
JS_AddIntrinsicRegExpCompiler()
void JS_AddIntrinsicRegExpCompiler (JSContext * ctx)
Definition at line 43324 of file quickjs.c.
References js_compile_regexp().
Referenced by JS_AddIntrinsicRegExp().
 {
     ctx->compile_regexp = js_compile_regexp;
 }
JS_AddIntrinsicRegExp()
void JS_AddIntrinsicRegExp (JSContext * ctx)
Definition at line 43329 of file quickjs.c.
References JSContext::class_proto, JSContext::iterator_proto, JS_AddIntrinsicRegExpCompiler(), JS_CLASS_REGEXP, JS_CLASS_REGEXP_STRING_ITERATOR, JS_DupValue(), JS_NewGlobalCConstructor(), JS_NewObject(), JS_NewObjectProto(), js_regexp_constructor(), js_regexp_funcs, js_regexp_proto_funcs, js_regexp_string_iterator_proto_funcs, JS_SetPropertyFunctionList(), and JSContext::regexp_ctor.
Referenced by JS_NewContext().
 {
     JSValueConst obj;
     JS_AddIntrinsicRegExpCompiler(ctx);
     ctx->class_proto[JS_CLASS_REGEXP] = JS_NewObject(ctx);
     JS_SetPropertyFunctionList(ctx, ctx->class_proto[JS_CLASS_REGEXP], js_regexp_proto_funcs,
                                countof(js_regexp_proto_funcs));
     obj = JS_NewGlobalCConstructor(ctx, "RegExp", js_regexp_constructor, 2,
                                    ctx->class_proto[JS_CLASS_REGEXP]);
     ctx->regexp_ctor = JS_DupValue(ctx, obj);
     JS_SetPropertyFunctionList(ctx, obj, js_regexp_funcs, countof(js_regexp_funcs));
     ctx->class_proto[JS_CLASS_REGEXP_STRING_ITERATOR] =
         JS_NewObjectProto(ctx, ctx->iterator_proto);
     JS_SetPropertyFunctionList(ctx, ctx->class_proto[JS_CLASS_REGEXP_STRING_ITERATOR],
                                js_regexp_string_iterator_proto_funcs,
                                countof(js_regexp_string_iterator_proto_funcs));
 }
JS_AddIntrinsicJSON()
void JS_AddIntrinsicJSON (JSContext * ctx)
Definition at line 44045 of file quickjs.c.
References JSContext::global_obj, js_json_obj, and JS_SetPropertyFunctionList().
Referenced by JS_NewContext().
 {
     /* add JSON as autoinit object */
     JS_SetPropertyFunctionList(ctx, ctx->global_obj, js_json_obj, countof(js_json_obj));
 }
JS_AddIntrinsicProxy()
void JS_AddIntrinsicProxy (JSContext * ctx)
Definition at line 45151 of file quickjs.c.
References JSClass::call, JSRuntime::class_array, JSClass::exotic, JSContext::global_obj, init_class_range(), JS_CFUNC_constructor, JS_CLASS_PROXY, JS_DefinePropertyValueStr(), JS_IsRegisteredClass(), JS_NewCFunction2(), js_proxy_call(), js_proxy_class_def, js_proxy_constructor(), js_proxy_exotic_methods, js_proxy_funcs, JS_SetConstructorBit(), JS_SetPropertyFunctionList(), JSContext::rt, and TRUE.
Referenced by JS_NewContext().
 {
     JSRuntime *rt = ctx->rt;
     JSValue obj1;
     if (!JS_IsRegisteredClass(rt, JS_CLASS_PROXY)) {
         init_class_range(rt, js_proxy_class_def, JS_CLASS_PROXY,
                          countof(js_proxy_class_def));
         rt->class_array[JS_CLASS_PROXY].exotic = &js_proxy_exotic_methods;
         rt->class_array[JS_CLASS_PROXY].call = js_proxy_call;
     }
     obj1 = JS_NewCFunction2(ctx, js_proxy_constructor, "Proxy", 2,
                             JS_CFUNC_constructor, 0);
     JS_SetConstructorBit(ctx, obj1, TRUE);
     JS_SetPropertyFunctionList(ctx, obj1, js_proxy_funcs,
                                countof(js_proxy_funcs));
     JS_DefinePropertyValueStr(ctx, ctx->global_obj, "Proxy",
                               obj1, JS_PROP_WRITABLE | JS_PROP_CONFIGURABLE);
 }
JS_AddIntrinsicMapSet()
void JS_AddIntrinsicMapSet (JSContext * ctx)
Definition at line 46031 of file quickjs.c.
References JSContext::class_proto, JSContext::iterator_proto, JS_AtomGetStr(), JS_CFUNC_constructor_magic, JS_CLASS_MAP, JS_CLASS_MAP_ITERATOR, js_map_constructor(), js_map_funcs, js_map_proto_funcs_count, js_map_proto_funcs_ptr, JS_NewCFunctionMagic(), JS_NewGlobalCConstructor2(), JS_NewObject(), JS_NewObjectProto(), and JS_SetPropertyFunctionList().
Referenced by JS_NewContext().
 {
     int i;
     JSValue obj1;
     char buf[ATOM_GET_STR_BUF_SIZE];
     for(i = 0; i < 4; i++) {
         const char *name = JS_AtomGetStr(ctx, buf, sizeof(buf),
                                          JS_ATOM_Map + i);
         ctx->class_proto[JS_CLASS_MAP + i] = JS_NewObject(ctx);
         JS_SetPropertyFunctionList(ctx, ctx->class_proto[JS_CLASS_MAP + i],
                                    js_map_proto_funcs_ptr[i],
                                    js_map_proto_funcs_count[i]);
         obj1 = JS_NewCFunctionMagic(ctx, js_map_constructor, name, 0,
                                     JS_CFUNC_constructor_magic, i);
         if (i < 2) {
             JS_SetPropertyFunctionList(ctx, obj1, js_map_funcs,
                                        countof(js_map_funcs));
         }
         JS_NewGlobalCConstructor2(ctx, obj1, name, ctx->class_proto[JS_CLASS_MAP + i]);
     }
     for(i = 0; i < 2; i++) {
         ctx->class_proto[JS_CLASS_MAP_ITERATOR + i] =
             JS_NewObjectProto(ctx, ctx->iterator_proto);
         JS_SetPropertyFunctionList(ctx, ctx->class_proto[JS_CLASS_MAP_ITERATOR + i],
                                    js_map_proto_funcs_ptr[i + 4],
                                    js_map_proto_funcs_count[i + 4]);
     }
 }
JS_AddIntrinsicTypedArrays()
void JS_AddIntrinsicTypedArrays (JSContext * ctx)
Definition at line 53716 of file quickjs.c.
References JSContext::class_proto, JS_AddIntrinsicAtomics(), js_array_buffer_constructor(), js_array_buffer_funcs, js_array_buffer_proto_funcs, JS_AtomGetStr(), JS_CFUNC_constructor_magic, JS_CLASS_ARRAY, JS_CLASS_ARRAY_BUFFER, JS_CLASS_DATAVIEW, JS_CLASS_SHARED_ARRAY_BUFFER, JS_CLASS_UINT8C_ARRAY, js_dataview_constructor(), js_dataview_proto_funcs, JS_DefinePropertyValue(), JS_FreeValue(), JS_GetProperty(), JS_NewCFunction(), JS_NewCFunction3(), JS_NewGlobalCConstructor2(), JS_NewGlobalCConstructorOnly(), JS_NewObject(), JS_NewObjectProto(), JS_SetConstructor(), JS_SetPropertyFunctionList(), js_shared_array_buffer_constructor(), js_shared_array_buffer_funcs, js_shared_array_buffer_proto_funcs, js_typed_array_base_constructor(), js_typed_array_base_funcs, js_typed_array_base_proto_funcs, and js_typed_array_constructor().
Referenced by JS_NewContext().
 {
     JSValue typed_array_base_proto, typed_array_base_func;
     JSValueConst array_buffer_func, shared_array_buffer_func;
     int i;
     ctx->class_proto[JS_CLASS_ARRAY_BUFFER] = JS_NewObject(ctx);
     JS_SetPropertyFunctionList(ctx, ctx->class_proto[JS_CLASS_ARRAY_BUFFER],
                                js_array_buffer_proto_funcs,
                                countof(js_array_buffer_proto_funcs));
     array_buffer_func = JS_NewGlobalCConstructorOnly(ctx, "ArrayBuffer",
                                                  js_array_buffer_constructor, 1,
                                                  ctx->class_proto[JS_CLASS_ARRAY_BUFFER]);
     JS_SetPropertyFunctionList(ctx, array_buffer_func,
                                js_array_buffer_funcs,
                                countof(js_array_buffer_funcs));
     ctx->class_proto[JS_CLASS_SHARED_ARRAY_BUFFER] = JS_NewObject(ctx);
     JS_SetPropertyFunctionList(ctx, ctx->class_proto[JS_CLASS_SHARED_ARRAY_BUFFER],
                                js_shared_array_buffer_proto_funcs,
                                countof(js_shared_array_buffer_proto_funcs));
     shared_array_buffer_func = JS_NewGlobalCConstructorOnly(ctx, "SharedArrayBuffer",
                                                  js_shared_array_buffer_constructor, 1,
                                                  ctx->class_proto[JS_CLASS_SHARED_ARRAY_BUFFER]);
     JS_SetPropertyFunctionList(ctx, shared_array_buffer_func,
                                js_shared_array_buffer_funcs,
                                countof(js_shared_array_buffer_funcs));
     typed_array_base_proto = JS_NewObject(ctx);
     JS_SetPropertyFunctionList(ctx, typed_array_base_proto,
                                js_typed_array_base_proto_funcs,
                                countof(js_typed_array_base_proto_funcs));
     /* TypedArray.prototype.toString must be the same object as Array.prototype.toString */
     JSValue obj = JS_GetProperty(ctx, ctx->class_proto[JS_CLASS_ARRAY], JS_ATOM_toString);
     /* XXX: should use alias method in JSCFunctionListEntry */ //@@@
     JS_DefinePropertyValue(ctx, typed_array_base_proto, JS_ATOM_toString, obj,
                            JS_PROP_WRITABLE | JS_PROP_CONFIGURABLE);
     typed_array_base_func = JS_NewCFunction(ctx, js_typed_array_base_constructor,
                                             "TypedArray", 0);
     JS_SetPropertyFunctionList(ctx, typed_array_base_func,
                                js_typed_array_base_funcs,
                                countof(js_typed_array_base_funcs));
     JS_SetConstructor(ctx, typed_array_base_func, typed_array_base_proto);
     for(i = JS_CLASS_UINT8C_ARRAY; i < JS_CLASS_UINT8C_ARRAY + JS_TYPED_ARRAY_COUNT; i++) {
         JSValue func_obj;
         char buf[ATOM_GET_STR_BUF_SIZE];
         const char *name;
         ctx->class_proto[i] = JS_NewObjectProto(ctx, typed_array_base_proto);
         JS_DefinePropertyValueStr(ctx, ctx->class_proto[i],
                                   "BYTES_PER_ELEMENT",
                                   JS_NewInt32(ctx, 1 << typed_array_size_log2(i)),
                                   0);
         name = JS_AtomGetStr(ctx, buf, sizeof(buf),
                              JS_ATOM_Uint8ClampedArray + i - JS_CLASS_UINT8C_ARRAY);
         func_obj = JS_NewCFunction3(ctx, (JSCFunction *)js_typed_array_constructor,
                                     name, 3, JS_CFUNC_constructor_magic, i,
                                     typed_array_base_func);
         JS_NewGlobalCConstructor2(ctx, func_obj, name, ctx->class_proto[i]);
         JS_DefinePropertyValueStr(ctx, func_obj,
                                   "BYTES_PER_ELEMENT",
                                   JS_NewInt32(ctx, 1 << typed_array_size_log2(i)),
                                   0);
     }
     JS_FreeValue(ctx, typed_array_base_proto);
     JS_FreeValue(ctx, typed_array_base_func);
     /* DataView */
     ctx->class_proto[JS_CLASS_DATAVIEW] = JS_NewObject(ctx);
     JS_SetPropertyFunctionList(ctx, ctx->class_proto[JS_CLASS_DATAVIEW],
                                js_dataview_proto_funcs,
                                countof(js_dataview_proto_funcs));
     JS_NewGlobalCConstructorOnly(ctx, "DataView",
                                  js_dataview_constructor, 1,
                                  ctx->class_proto[JS_CLASS_DATAVIEW]);
     /* Atomics */
 #ifdef CONFIG_ATOMICS
     JS_AddIntrinsicAtomics(ctx);
 #endif
 }
JS_AddIntrinsicPromise()
void JS_AddIntrinsicPromise (JSContext * ctx)
Definition at line 47300 of file quickjs.c.
References JSContext::async_iterator_proto, JSClass::call, JSRuntime::class_array, JSContext::class_proto, JSContext::function_ctor, JSContext::function_proto, init_class_range(), js_async_class_def, js_async_from_sync_iterator_proto_funcs, js_async_function_call(), js_async_function_proto_funcs, js_async_function_resolve_call(), js_async_generator_function_call(), js_async_generator_function_proto_funcs, js_async_generator_proto_funcs, js_async_iterator_proto_funcs, JS_CFUNC_constructor, JS_CFUNC_constructor_or_func_magic, JS_CLASS_ASYNC_FROM_SYNC_ITERATOR, JS_CLASS_ASYNC_FUNCTION, JS_CLASS_ASYNC_FUNCTION_REJECT, JS_CLASS_ASYNC_FUNCTION_RESOLVE, JS_CLASS_ASYNC_GENERATOR, JS_CLASS_ASYNC_GENERATOR_FUNCTION, JS_CLASS_PROMISE, JS_CLASS_PROMISE_REJECT_FUNCTION, JS_CLASS_PROMISE_RESOLVE_FUNCTION, JS_DupValue(), JS_FreeValue(), JS_FUNC_ASYNC, JS_FUNC_ASYNC_GENERATOR, js_function_constructor(), JS_IsRegisteredClass(), JS_NewCFunction2(), JS_NewCFunction3(), JS_NewGlobalCConstructor2(), JS_NewObject(), JS_NewObjectProto(), js_promise_constructor(), js_promise_funcs, js_promise_proto_funcs, js_promise_resolve_function_call(), JS_SetConstructor2(), JS_SetPropertyFunctionList(), JSContext::promise_ctor, and JSContext::rt.
Referenced by JS_NewContext().
 {
     JSRuntime *rt = ctx->rt;
     JSValue obj1;
     if (!JS_IsRegisteredClass(rt, JS_CLASS_PROMISE)) {
         init_class_range(rt, js_async_class_def, JS_CLASS_PROMISE,
                          countof(js_async_class_def));
         rt->class_array[JS_CLASS_PROMISE_RESOLVE_FUNCTION].call = js_promise_resolve_function_call;
         rt->class_array[JS_CLASS_PROMISE_REJECT_FUNCTION].call = js_promise_resolve_function_call;
         rt->class_array[JS_CLASS_ASYNC_FUNCTION].call = js_async_function_call;
         rt->class_array[JS_CLASS_ASYNC_FUNCTION_RESOLVE].call = js_async_function_resolve_call;
         rt->class_array[JS_CLASS_ASYNC_FUNCTION_REJECT].call = js_async_function_resolve_call;
         rt->class_array[JS_CLASS_ASYNC_GENERATOR_FUNCTION].call = js_async_generator_function_call;
     }
     /* Promise */
     ctx->class_proto[JS_CLASS_PROMISE] = JS_NewObject(ctx);
     JS_SetPropertyFunctionList(ctx, ctx->class_proto[JS_CLASS_PROMISE],
                                js_promise_proto_funcs,
                                countof(js_promise_proto_funcs));
     obj1 = JS_NewCFunction2(ctx, js_promise_constructor, "Promise", 1,
                             JS_CFUNC_constructor, 0);
     ctx->promise_ctor = JS_DupValue(ctx, obj1);
     JS_SetPropertyFunctionList(ctx, obj1,
                                js_promise_funcs,
                                countof(js_promise_funcs));
     JS_NewGlobalCConstructor2(ctx, obj1, "Promise",
                               ctx->class_proto[JS_CLASS_PROMISE]);
     /* AsyncFunction */
     ctx->class_proto[JS_CLASS_ASYNC_FUNCTION] = JS_NewObjectProto(ctx, ctx->function_proto);
     obj1 = JS_NewCFunction3(ctx, (JSCFunction *)js_function_constructor,
                             "AsyncFunction", 1,
                             JS_CFUNC_constructor_or_func_magic, JS_FUNC_ASYNC,
                             ctx->function_ctor);
     JS_SetPropertyFunctionList(ctx,
                                ctx->class_proto[JS_CLASS_ASYNC_FUNCTION],
                                js_async_function_proto_funcs,
                                countof(js_async_function_proto_funcs));
     JS_SetConstructor2(ctx, obj1, ctx->class_proto[JS_CLASS_ASYNC_FUNCTION],
                        0, JS_PROP_CONFIGURABLE);
     JS_FreeValue(ctx, obj1);
     /* AsyncIteratorPrototype */
     ctx->async_iterator_proto = JS_NewObject(ctx);
     JS_SetPropertyFunctionList(ctx, ctx->async_iterator_proto,
                                js_async_iterator_proto_funcs,
                                countof(js_async_iterator_proto_funcs));
     /* AsyncFromSyncIteratorPrototype */
     ctx->class_proto[JS_CLASS_ASYNC_FROM_SYNC_ITERATOR] =
         JS_NewObjectProto(ctx, ctx->async_iterator_proto);
     JS_SetPropertyFunctionList(ctx, ctx->class_proto[JS_CLASS_ASYNC_FROM_SYNC_ITERATOR],
                                js_async_from_sync_iterator_proto_funcs,
                                countof(js_async_from_sync_iterator_proto_funcs));
     /* AsyncGeneratorPrototype */
     ctx->class_proto[JS_CLASS_ASYNC_GENERATOR] =
         JS_NewObjectProto(ctx, ctx->async_iterator_proto);
     JS_SetPropertyFunctionList(ctx,
                                ctx->class_proto[JS_CLASS_ASYNC_GENERATOR],
                                js_async_generator_proto_funcs,
                                countof(js_async_generator_proto_funcs));
     /* AsyncGeneratorFunction */
     ctx->class_proto[JS_CLASS_ASYNC_GENERATOR_FUNCTION] =
         JS_NewObjectProto(ctx, ctx->function_proto);
     obj1 = JS_NewCFunction3(ctx, (JSCFunction *)js_function_constructor,
                             "AsyncGeneratorFunction", 1,
                             JS_CFUNC_constructor_or_func_magic,
                             JS_FUNC_ASYNC_GENERATOR,
                             ctx->function_ctor);
     JS_SetPropertyFunctionList(ctx,
                                ctx->class_proto[JS_CLASS_ASYNC_GENERATOR_FUNCTION],
                                js_async_generator_function_proto_funcs,
                                countof(js_async_generator_function_proto_funcs));
     JS_SetConstructor2(ctx, ctx->class_proto[JS_CLASS_ASYNC_GENERATOR_FUNCTION],
                        ctx->class_proto[JS_CLASS_ASYNC_GENERATOR],
                        JS_PROP_CONFIGURABLE, JS_PROP_CONFIGURABLE);
     JS_SetConstructor2(ctx, obj1, ctx->class_proto[JS_CLASS_ASYNC_GENERATOR_FUNCTION],
                        0, JS_PROP_CONFIGURABLE);
     JS_FreeValue(ctx, obj1);
 }
JS_AddIntrinsicBigInt()
void JS_AddIntrinsicBigInt (JSContext * ctx)
JS_AddIntrinsicBigFloat()
void JS_AddIntrinsicBigFloat (JSContext * ctx)
JS_AddIntrinsicBigDecimal()
void JS_AddIntrinsicBigDecimal (JSContext * ctx)
JS_AddIntrinsicOperators()
void JS_AddIntrinsicOperators (JSContext * ctx)
JS_EnableBignumExt()
void JS_EnableBignumExt (JSContext * ctx, JS_BOOL enable)
js_string_codePointRange()
JSValue js_string_codePointRange (JSContext * ctx, JSValueConst this_val, int argc, JSValueConst * argv)
Definition at line 40118 of file quickjs.c.
References JS_ToUint32(), max_uint32(), min_uint32(), string_buffer_end(), string_buffer_init2(), and string_buffer_putc().
 {
     uint32_t start, end, i, n;
     StringBuffer b_s, *b = &b_s;
     if (JS_ToUint32(ctx, &start, argv[0]) ||
         JS_ToUint32(ctx, &end, argv[1]))
         return JS_EXCEPTION;
     end = min_uint32(end, 0x10ffff + 1);
     if (start > end) {
         start = end;
     }
     n = end - start;
     if (end > 0x10000) {
         n += end - max_uint32(start, 0x10000);
     }
     if (string_buffer_init2(ctx, b, n, end >= 0x100))
         return JS_EXCEPTION;
     for(i = start; i < end; i++) {
         string_buffer_putc(b, i);
     }
     return string_buffer_end(b);
 }
js_malloc_rt()
void* js_malloc_rt (JSRuntime * rt, size_t size)
Definition at line 1282 of file quickjs.c.
References JSMallocFunctions::js_malloc, JSRuntime::malloc_state, and JSRuntime::mf.
Referenced by qjs::detail::function::create(), JS_DumpMemoryUsage(), js_malloc(), and js_mallocz_rt().
 {
     return rt->mf.js_malloc(&rt->malloc_state, size);
 }
js_free_rt()
void js_free_rt (JSRuntime * rt, void * ptr)
Definition at line 1287 of file quickjs.c.
References JSMallocFunctions::js_free, JSRuntime::malloc_state, and JSRuntime::mf.
Referenced by __JS_FreeValueRT(), __JS_NewAtom(), async_func_free(), free_function_bytecode(), free_object(), free_rw_handler(), free_sh(), free_timer(), free_var_ref(), gc_free_cycles(), js_array_buffer_finalizer(), js_array_buffer_free(), js_array_finalizer(), js_array_iterator_finalizer(), js_async_function_free0(), js_async_generator_free(), js_atof(), js_bound_function_finalizer(), js_bytecode_function_finalizer(), JS_DumpMemoryUsage(), js_for_in_iterator_finalizer(), js_free(), js_free_port(), js_free_shape0(), js_free_string(), JS_FreeAtomStruct(), JS_FreeContext(), JS_FreeRuntime(), js_map_finalizer(), js_map_iterator_finalizer(), JS_NewContextRaw(), js_promise_resolve_function_finalizer(), js_promise_resolve_function_free_resolved(), js_regexp_string_iterator_finalizer(), JS_ResizeAtomHash(), js_typed_array_finalizer(), map_decref_record(), map_delete_record(), promise_reaction_data_free(), qjs::js_traits< detail::function >::register_class(), reset_weak_ref(), and resize_shape_hash().
 {
     rt->mf.js_free(&rt->malloc_state, ptr);
 }
js_realloc_rt()
void* js_realloc_rt (JSRuntime * rt, void * ptr, size_t size)
Definition at line 1292 of file quickjs.c.
References JSMallocFunctions::js_realloc, JSRuntime::malloc_state, and JSRuntime::mf.
Referenced by js_dbuf_init(), js_realloc2(), js_std_dbuf_init(), and js_string_normalize().
 {
     return rt->mf.js_realloc(&rt->malloc_state, ptr, size);
 }
js_malloc_usable_size_rt()
size_t js_malloc_usable_size_rt (JSRuntime * rt, const void * ptr)
Definition at line 1297 of file quickjs.c.
References JSRuntime::mf.
Referenced by JS_DumpMemoryUsage(), js_malloc_usable_size(), and js_realloc2().
 {
     return rt->mf.js_malloc_usable_size(ptr);
 }
js_mallocz_rt()
void* js_mallocz_rt (JSRuntime * rt, size_t size)
Definition at line 1302 of file quickjs.c.
References js_malloc_rt().
Referenced by js_mallocz().
 {
     void *ptr;
     ptr = js_malloc_rt(rt, size);
     if (!ptr)
         return NULL;
     return memset(ptr, 0, size);
 }
js_malloc()
void* js_malloc (JSContext * ctx, size_t size)
Definition at line 1321 of file quickjs.c.
References js_malloc_rt(), JS_ThrowOutOfMemory(), and JSContext::rt.
Referenced by compact_properties(), js_clone_shape(), js_new_shape2(), js_typed_array_sort(), and resize_properties().
 {
     void *ptr;
     ptr = js_malloc_rt(ctx->rt, size);
     if (unlikely(!ptr)) {
         JS_ThrowOutOfMemory(ctx);
         return NULL;
     }
     return ptr;
 }
js_free()
void js_free (JSContext * ctx, void * ptr)
Definition at line 1344 of file quickjs.c.
References js_free_rt(), and JSContext::rt.
Referenced by bc_reader_free(), build_envp(), build_for_in_iterator(), compact_properties(), compute_stack_size(), convert_fast_array_to_array(), qjs::Context::evalFile(), free_arg_list(), instantiate_hoisted_definitions(), js_array_buffer_constructor3(), js_array_sort(), js_async_generator_resolve_or_reject(), js_atom_concat_str(), js_build_module_ns(), js_compile_regexp(), js_create_function(), JS_ExecutePendingJob(), js_free_function_def(), js_free_module_def(), js_free_prop_enum(), js_generator_function_call(), JS_GetOwnPropertyNamesInternal(), js_host_resolve_imported_module(), js_load_file(), js_loadScript(), js_module_loader(), js_module_loader_so(), JS_NewObjectFromShape(), js_object_list_end(), js_object_list_resize_hash(), js_os_exec(), js_parse_class(), js_regexp_exec(), JS_RegExpDelete(), js_resolve_export(), js_std_loadFile(), js_std_urlGet(), js_string_normalize(), js_typed_array_sort(), js_worker_postMessage(), JS_WriteFunctionBytecode(), JS_WriteObject2(), json_parse_ident(), parse_ident(), resize_properties(), resolve_labels(), string_buffer_end(), string_buffer_free(), string_buffer_set_error(), and value_buffer_free().
 {
     js_free_rt(ctx->rt, ptr);
 }
js_realloc()
void* js_realloc (JSContext * ctx, void * ptr, size_t size)
Definition at line 1350 of file quickjs.c.
Referenced by resize_properties().
 {
     void *ret;
     ret = js_realloc_rt(ctx->rt, ptr, size);
     if (unlikely(!ret && size != 0)) {
         JS_ThrowOutOfMemory(ctx);
         return NULL;
     }
     return ret;
 }
js_malloc_usable_size()
size_t js_malloc_usable_size (JSContext * ctx, const void * ptr)
Definition at line 1377 of file quickjs.c.
References js_malloc_usable_size_rt(), and JSContext::rt.
Referenced by JS_ConcatString().
 {
     return js_malloc_usable_size_rt(ctx->rt, ptr);
 }
js_realloc2()
void* js_realloc2 (JSContext * ctx, void * ptr, size_t size, size_t * pslack)
Definition at line 1362 of file quickjs.c.
References js_malloc_usable_size_rt(), js_realloc_rt(), JS_ThrowOutOfMemory(), and JSContext::rt.
Referenced by js_realloc_array().
 {
     void *ret;
     ret = js_realloc_rt(ctx->rt, ptr, size);
     if (unlikely(!ret && size != 0)) {
         JS_ThrowOutOfMemory(ctx);
         return NULL;
     }
     if (pslack) {
         size_t new_size = js_malloc_usable_size_rt(ctx->rt, ret);
         *pslack = (new_size > size) ? new_size - size : 0;
     }
     return ret;
 }
js_mallocz()
void* js_mallocz (JSContext * ctx, size_t size)
Definition at line 1333 of file quickjs.c.
References js_mallocz_rt(), JS_ThrowOutOfMemory(), and JSContext::rt.
 {
     void *ptr;
     ptr = js_mallocz_rt(ctx->rt, size);
     if (unlikely(!ptr)) {
         JS_ThrowOutOfMemory(ctx);
         return NULL;
     }
     return ptr;
 }
js_strdup()
char* js_strdup (JSContext * ctx, const char * str)
Definition at line 1394 of file quickjs.c.
References js_strndup().
Referenced by js_default_module_normalize_name().
 {
     return js_strndup(ctx, str, strlen(str));
 }
js_strndup()
char* js_strndup (JSContext * ctx, const char * s, size_t n)
Definition at line 1383 of file quickjs.c.
Referenced by js_parse_class(), js_parse_function_decl2(), and js_strdup().
 {
     char *ptr;
     ptr = js_malloc(ctx, n + 1);
     if (ptr) {
         memcpy(ptr, s, n);
         ptr[n] = '\0';
     }
     return ptr;
 }
JS_ComputeMemoryUsage()
void JS_ComputeMemoryUsage (JSRuntime * rt, JSMemoryUsage * s)
Definition at line 5879 of file quickjs.c.
References JSBoundFunction::argc, JSBoundFunction::argv, JSMemoryUsage::array_count, JSContext::array_shape, JSShapeProperty::atom, JSRuntime::atom_array, JSRuntime::atom_count, JSMemoryUsage::atom_count, JSRuntime::atom_hash, JSRuntime::atom_hash_size, atom_is_free(), JSRuntime::atom_size, JSMemoryUsage::atom_size, JSMemoryUsage::binary_object_count, JSContext::binary_object_count, JSMemoryUsage::binary_object_size, JSContext::binary_object_size, JSArrayBuffer::byte_length, JSRegExp::bytecode, JSMemoryUsage::c_func_count, JSRuntime::class_count, JSFunctionBytecode::closure_var_count, compute_bytecode_size(), compute_jsstring_size(), compute_value_size(), JSRuntime::context_list, JSArrayBuffer::data, JSCFunctionDataRecord::data, JSCFunctionDataRecord::data_len, JSModuleDef::export_entries, JSModuleDef::export_entries_count, JSExportEntry::export_type, JSMemoryUsage::fast_array_count, JSMemoryUsage::fast_array_elements, JSShapeProperty::flags, JSModuleDef::func_obj, JSRuntime::gc_obj_list, JSGCObjectHeader::gc_obj_type, get_shape_prop(), get_shape_size(), JSModuleDef::import_entries, JSModuleDef::import_entries_count, JSShape::is_hashed, JSString::is_wide_char, JS_CLASS_ARGUMENTS, JS_CLASS_ARRAY, JS_CLASS_ARRAY_BUFFER, JS_CLASS_ARRAY_ITERATOR, JS_CLASS_ASYNC_FROM_SYNC_ITERATOR, JS_CLASS_ASYNC_FUNCTION_REJECT, JS_CLASS_ASYNC_FUNCTION_RESOLVE, JS_CLASS_ASYNC_GENERATOR, JS_CLASS_BOOLEAN, JS_CLASS_BOUND_FUNCTION, JS_CLASS_BYTECODE_FUNCTION, JS_CLASS_C_FUNCTION, JS_CLASS_C_FUNCTION_DATA, JS_CLASS_DATAVIEW, JS_CLASS_DATE, JS_CLASS_FLOAT32_ARRAY, JS_CLASS_FLOAT64_ARRAY, JS_CLASS_FOR_IN_ITERATOR, JS_CLASS_GENERATOR, JS_CLASS_INT16_ARRAY, JS_CLASS_INT32_ARRAY, JS_CLASS_INT8_ARRAY, JS_CLASS_MAP, JS_CLASS_MAP_ITERATOR, JS_CLASS_NUMBER, JS_CLASS_PROMISE, JS_CLASS_PROMISE_REJECT_FUNCTION, JS_CLASS_PROMISE_RESOLVE_FUNCTION, JS_CLASS_PROXY, JS_CLASS_REGEXP, JS_CLASS_SET, JS_CLASS_SET_ITERATOR, JS_CLASS_SHARED_ARRAY_BUFFER, JS_CLASS_STRING, JS_CLASS_STRING_ITERATOR, JS_CLASS_SYMBOL, JS_CLASS_UINT16_ARRAY, JS_CLASS_UINT32_ARRAY, JS_CLASS_UINT8_ARRAY, JS_CLASS_UINT8C_ARRAY, JS_CLASS_WEAKMAP, JS_CLASS_WEAKSET, JS_EXPORT_TYPE_LOCAL, JSMemoryUsage::js_func_code_size, JSMemoryUsage_helper::js_func_code_size, JSMemoryUsage::js_func_count, JSMemoryUsage_helper::js_func_count, JSMemoryUsage::js_func_pc2line_count, JSMemoryUsage_helper::js_func_pc2line_count, JSMemoryUsage::js_func_pc2line_size, JSMemoryUsage_helper::js_func_pc2line_size, JSMemoryUsage::js_func_size, JSMemoryUsage_helper::js_func_size, JS_GC_OBJ_TYPE_FUNCTION_BYTECODE, JS_GC_OBJ_TYPE_JS_OBJECT, JSString::len, JSGCObjectHeader::link, JSContext::link, JSModuleDef::link, JSContext::loaded_modules, JSMallocState::malloc_count, JSMemoryUsage::malloc_count, JSMallocState::malloc_limit, JSMemoryUsage::malloc_limit, JSMallocState::malloc_size, JSMemoryUsage::malloc_size, JSRuntime::malloc_state, JSMemoryUsage::memory_used_count, JSMemoryUsage_helper::memory_used_count, JSMemoryUsage::memory_used_size, JSModuleDef::module_ns, JSForInIterator::obj, JSMemoryUsage::obj_count, JSMemoryUsage::obj_size, JSRegExp::pattern, JSObject::prop, JSMemoryUsage::prop_count, JSShape::prop_count, JSShape::prop_hash_mask, JSMemoryUsage::prop_size, JSShape::prop_size, JSVarRef::pvalue, JSGCObjectHeader::ref_count, JSModuleDef::req_module_entries, JSModuleDef::req_module_entries_count, JSObject::shape, JSMemoryUsage::shape_count, JSRuntime::shape_hash, JSShape::shape_hash_next, JSRuntime::shape_hash_size, JSMemoryUsage::shape_size, JSModuleDef::star_export_entries, JSModuleDef::star_export_entries_count, JSMemoryUsage::str_count, JSMemoryUsage_helper::str_count, JSMemoryUsage::str_size, JSMemoryUsage_helper::str_size, and JSVarRef::value.
 {
     struct list_head *el, *el1;
     int i;
     JSMemoryUsage_helper mem = { 0 }, *hp = &mem;
     memset(s, 0, sizeof(*s));
     s->malloc_count = rt->malloc_state.malloc_count;
     s->malloc_size = rt->malloc_state.malloc_size;
     s->malloc_limit = rt->malloc_state.malloc_limit;
     s->memory_used_count = 2; /* rt + rt->class_array */
     s->memory_used_size = sizeof(JSRuntime) + sizeof(JSValue) * rt->class_count;
     list_for_each(el, &rt->context_list) {
         JSContext *ctx = list_entry(el, JSContext, link);
         JSShape *sh = ctx->array_shape;
         s->memory_used_count += 2; /* ctx + ctx->class_proto */
         s->memory_used_size += sizeof(JSContext) +
             sizeof(JSValue) * rt->class_count;
         s->binary_object_count += ctx->binary_object_count;
         s->binary_object_size += ctx->binary_object_size;
         /* the hashed shapes are counted separately */
         if (sh && !sh->is_hashed) {
             int hash_size = sh->prop_hash_mask + 1;
             s->shape_count++;
             s->shape_size += get_shape_size(hash_size, sh->prop_size);
         }
         list_for_each(el1, &ctx->loaded_modules) {
             JSModuleDef *m = list_entry(el1, JSModuleDef, link);
             s->memory_used_count += 1;
             s->memory_used_size += sizeof(*m);
             if (m->req_module_entries) {
                 s->memory_used_count += 1;
                 s->memory_used_size += m->req_module_entries_count * sizeof(*m->req_module_entries);
             }
             if (m->export_entries) {
                 s->memory_used_count += 1;
                 s->memory_used_size += m->export_entries_count * sizeof(*m->export_entries);
                 for (i = 0; i < m->export_entries_count; i++) {
                     JSExportEntry *me = &m->export_entries[i];
                     if (me->export_type == JS_EXPORT_TYPE_LOCAL && me->u.local.var_ref) {
                         /* potential multiple count */
                         s->memory_used_count += 1;
                         compute_value_size(me->u.local.var_ref->value, hp);
                     }
                 }
             }
             if (m->star_export_entries) {
                 s->memory_used_count += 1;
                 s->memory_used_size += m->star_export_entries_count * sizeof(*m->star_export_entries);
             }
             if (m->import_entries) {
                 s->memory_used_count += 1;
                 s->memory_used_size += m->import_entries_count * sizeof(*m->import_entries);
             }
             compute_value_size(m->module_ns, hp);
             compute_value_size(m->func_obj, hp);
         }
     }
     list_for_each(el, &rt->gc_obj_list) {
         JSGCObjectHeader *gp = list_entry(el, JSGCObjectHeader, link);
         JSObject *p;
         JSShape *sh;
         JSShapeProperty *prs;
         /* XXX: could count the other GC object types too */
         if (gp->gc_obj_type == JS_GC_OBJ_TYPE_FUNCTION_BYTECODE) {
             compute_bytecode_size((JSFunctionBytecode *)gp, hp);
             continue;
         } else if (gp->gc_obj_type != JS_GC_OBJ_TYPE_JS_OBJECT) {
             continue;
         }
         p = (JSObject *)gp;
         sh = p->shape;
         s->obj_count++;
         if (p->prop) {
             s->memory_used_count++;
             s->prop_size += sh->prop_size * sizeof(*p->prop);
             s->prop_count += sh->prop_count;
             prs = get_shape_prop(sh);
             for(i = 0; i < sh->prop_count; i++) {
                 JSProperty *pr = &p->prop[i];
                 if (prs->atom != JS_ATOM_NULL && !(prs->flags & JS_PROP_TMASK)) {
                     compute_value_size(pr->u.value, hp);
                 }
                 prs++;
             }
         }
         /* the hashed shapes are counted separately */
         if (!sh->is_hashed) {
             int hash_size = sh->prop_hash_mask + 1;
             s->shape_count++;
             s->shape_size += get_shape_size(hash_size, sh->prop_size);
         }
         switch(p->class_id) {
         case JS_CLASS_ARRAY:             /* u.array | length */
         case JS_CLASS_ARGUMENTS:         /* u.array | length */
             s->array_count++;
             if (p->fast_array) {
                 s->fast_array_count++;
                 if (p->u.array.u.values) {
                     s->memory_used_count++;
                     s->memory_used_size += p->u.array.count *
                         sizeof(*p->u.array.u.values);
                     s->fast_array_elements += p->u.array.count;
                     for (i = 0; i < p->u.array.count; i++) {
                         compute_value_size(p->u.array.u.values[i], hp);
                     }
                 }
             }
             break;
         case JS_CLASS_NUMBER:            /* u.object_data */
         case JS_CLASS_STRING:            /* u.object_data */
         case JS_CLASS_BOOLEAN:           /* u.object_data */
         case JS_CLASS_SYMBOL:            /* u.object_data */
         case JS_CLASS_DATE:              /* u.object_data */
 #ifdef CONFIG_BIGNUM
         case JS_CLASS_BIG_INT:           /* u.object_data */
         case JS_CLASS_BIG_FLOAT:         /* u.object_data */
         case JS_CLASS_BIG_DECIMAL:         /* u.object_data */
 #endif
             compute_value_size(p->u.object_data, hp);
             break;
         case JS_CLASS_C_FUNCTION:        /* u.cfunc */
             s->c_func_count++;
             break;
         case JS_CLASS_BYTECODE_FUNCTION: /* u.func */
             {
                 JSFunctionBytecode *b = p->u.func.function_bytecode;
                 JSVarRef **var_refs = p->u.func.var_refs;
                 /* home_object: object will be accounted for in list scan */
                 if (var_refs) {
                     s->memory_used_count++;
                     s->js_func_size += b->closure_var_count * sizeof(*var_refs);
                     for (i = 0; i < b->closure_var_count; i++) {
                         if (var_refs[i]) {
                             double ref_count = var_refs[i]->header.ref_count;
                             s->memory_used_count += 1 / ref_count;
                             s->js_func_size += sizeof(*var_refs[i]) / ref_count;
                             /* handle non object closed values */
                             if (var_refs[i]->pvalue == &var_refs[i]->value) {
                                 /* potential multiple count */
                                 compute_value_size(var_refs[i]->value, hp);
                             }
                         }
                     }
                 }
             }
             break;
         case JS_CLASS_BOUND_FUNCTION:    /* u.bound_function */
             {
                 JSBoundFunction *bf = p->u.bound_function;
                 /* func_obj and this_val are objects */
                 for (i = 0; i < bf->argc; i++) {
                     compute_value_size(bf->argv[i], hp);
                 }
                 s->memory_used_count += 1;
                 s->memory_used_size += sizeof(*bf) + bf->argc * sizeof(*bf->argv);
             }
             break;
         case JS_CLASS_C_FUNCTION_DATA:   /* u.c_function_data_record */
             {
                 JSCFunctionDataRecord *fd = p->u.c_function_data_record;
                 if (fd) {
                     for (i = 0; i < fd->data_len; i++) {
                         compute_value_size(fd->data[i], hp);
                     }
                     s->memory_used_count += 1;
                     s->memory_used_size += sizeof(*fd) + fd->data_len * sizeof(*fd->data);
                 }
             }
             break;
         case JS_CLASS_REGEXP:            /* u.regexp */
             compute_jsstring_size(p->u.regexp.pattern, hp);
             compute_jsstring_size(p->u.regexp.bytecode, hp);
             break;
         case JS_CLASS_FOR_IN_ITERATOR:   /* u.for_in_iterator */
             {
                 JSForInIterator *it = p->u.for_in_iterator;
                 if (it) {
                     compute_value_size(it->obj, hp);
                     s->memory_used_count += 1;
                     s->memory_used_size += sizeof(*it);
                 }
             }
             break;
         case JS_CLASS_ARRAY_BUFFER:      /* u.array_buffer */
         case JS_CLASS_SHARED_ARRAY_BUFFER: /* u.array_buffer */
             {
                 JSArrayBuffer *abuf = p->u.array_buffer;
                 if (abuf) {
                     s->memory_used_count += 1;
                     s->memory_used_size += sizeof(*abuf);
                     if (abuf->data) {
                         s->memory_used_count += 1;
                         s->memory_used_size += abuf->byte_length;
                     }
                 }
             }
             break;
         case JS_CLASS_GENERATOR:         /* u.generator_data */
         case JS_CLASS_UINT8C_ARRAY:      /* u.typed_array / u.array */
         case JS_CLASS_INT8_ARRAY:        /* u.typed_array / u.array */
         case JS_CLASS_UINT8_ARRAY:       /* u.typed_array / u.array */
         case JS_CLASS_INT16_ARRAY:       /* u.typed_array / u.array */
         case JS_CLASS_UINT16_ARRAY:      /* u.typed_array / u.array */
         case JS_CLASS_INT32_ARRAY:       /* u.typed_array / u.array */
         case JS_CLASS_UINT32_ARRAY:      /* u.typed_array / u.array */
 #ifdef CONFIG_BIGNUM
         case JS_CLASS_BIG_INT64_ARRAY:   /* u.typed_array / u.array */
         case JS_CLASS_BIG_UINT64_ARRAY:  /* u.typed_array / u.array */
 #endif
         case JS_CLASS_FLOAT32_ARRAY:     /* u.typed_array / u.array */
         case JS_CLASS_FLOAT64_ARRAY:     /* u.typed_array / u.array */
         case JS_CLASS_DATAVIEW:          /* u.typed_array */
 #ifdef CONFIG_BIGNUM
         case JS_CLASS_FLOAT_ENV:         /* u.float_env */
 #endif
         case JS_CLASS_MAP:               /* u.map_state */
         case JS_CLASS_SET:               /* u.map_state */
         case JS_CLASS_WEAKMAP:           /* u.map_state */
         case JS_CLASS_WEAKSET:           /* u.map_state */
         case JS_CLASS_MAP_ITERATOR:      /* u.map_iterator_data */
         case JS_CLASS_SET_ITERATOR:      /* u.map_iterator_data */
         case JS_CLASS_ARRAY_ITERATOR:    /* u.array_iterator_data */
         case JS_CLASS_STRING_ITERATOR:   /* u.array_iterator_data */
         case JS_CLASS_PROXY:             /* u.proxy_data */
         case JS_CLASS_PROMISE:           /* u.promise_data */
         case JS_CLASS_PROMISE_RESOLVE_FUNCTION:  /* u.promise_function_data */
         case JS_CLASS_PROMISE_REJECT_FUNCTION:   /* u.promise_function_data */
         case JS_CLASS_ASYNC_FUNCTION_RESOLVE:    /* u.async_function_data */
         case JS_CLASS_ASYNC_FUNCTION_REJECT:     /* u.async_function_data */
         case JS_CLASS_ASYNC_FROM_SYNC_ITERATOR:  /* u.async_from_sync_iterator_data */
         case JS_CLASS_ASYNC_GENERATOR:   /* u.async_generator_data */
             /* TODO */
         default:
             /* XXX: class definition should have an opaque block size */
             if (p->u.opaque) {
                 s->memory_used_count += 1;
             }
             break;
         }
     }
     s->obj_size += s->obj_count * sizeof(JSObject);
     /* hashed shapes */
     s->memory_used_count++; /* rt->shape_hash */
     s->memory_used_size += sizeof(rt->shape_hash[0]) * rt->shape_hash_size;
     for(i = 0; i < rt->shape_hash_size; i++) {
         JSShape *sh;
         for(sh = rt->shape_hash[i]; sh != NULL; sh = sh->shape_hash_next) {
             int hash_size = sh->prop_hash_mask + 1;
             s->shape_count++;
             s->shape_size += get_shape_size(hash_size, sh->prop_size);
         }
     }
     /* atoms */
     s->memory_used_count += 2; /* rt->atom_array, rt->atom_hash */
     s->atom_count = rt->atom_count;
     s->atom_size = sizeof(rt->atom_array[0]) * rt->atom_size +
         sizeof(rt->atom_hash[0]) * rt->atom_hash_size;
     for(i = 0; i < rt->atom_size; i++) {
         JSAtomStruct *p = rt->atom_array[i];
         if (!atom_is_free(p)) {
             s->atom_size += (sizeof(*p) + (p->len << p->is_wide_char) +
                              1 - p->is_wide_char);
         }
     }
     s->str_count = round(mem.str_count);
     s->str_size = round(mem.str_size);
     s->js_func_count = mem.js_func_count;
     s->js_func_size = round(mem.js_func_size);
     s->js_func_code_size = mem.js_func_code_size;
     s->js_func_pc2line_count = mem.js_func_pc2line_count;
     s->js_func_pc2line_size = mem.js_func_pc2line_size;
     s->memory_used_count += round(mem.memory_used_count) +
         s->atom_count + s->str_count +
         s->obj_count + s->shape_count +
         s->js_func_count + s->js_func_pc2line_count;
     s->memory_used_size += s->atom_size + s->str_size +
         s->obj_size + s->prop_size + s->shape_size +
         s->js_func_size + s->js_func_code_size + s->js_func_pc2line_size;
 }
JS_DumpMemoryUsage()
void JS_DumpMemoryUsage (FILE * fp, const JSMemoryUsage * s, JSRuntime * rt)
Definition at line 6169 of file quickjs.c.
References JSMemoryUsage::array_count, JSMemoryUsage::atom_count, JSMemoryUsage::atom_size, JSMemoryUsage::binary_object_count, JSMemoryUsage::binary_object_size, JSMemoryUsage::c_func_count, JSClassShortDef::class_name, JSMemoryUsage::fast_array_count, JSMemoryUsage::fast_array_elements, JSRuntime::gc_obj_list, JSGCObjectHeader::gc_obj_type, JS_AtomGetStrRT(), JS_CLASS_INIT_COUNT, js_free_rt(), JSMemoryUsage::js_func_code_size, JSMemoryUsage::js_func_count, JSMemoryUsage::js_func_pc2line_count, JSMemoryUsage::js_func_pc2line_size, JSMemoryUsage::js_func_size, JS_GC_OBJ_TYPE_JS_OBJECT, js_malloc_rt(), js_malloc_usable_size_rt(), js_std_class_def, JSGCObjectHeader::link, JSMemoryUsage::malloc_count, JSMemoryUsage::malloc_size, JSMemoryUsage::memory_used_count, JSMemoryUsage::memory_used_size, min_uint32(), JSMemoryUsage::obj_count, JSMemoryUsage::obj_size, JSMemoryUsage::prop_count, JSMemoryUsage::prop_size, JSMemoryUsage::shape_count, JSMemoryUsage::shape_size, JSMemoryUsage::str_count, and JSMemoryUsage::str_size.
 {
     fprintf(fp, "QuickJS memory usage -- "
 #ifdef CONFIG_BIGNUM
             "BigNum "
 #endif
             CONFIG_VERSION " version, %d-bit, malloc limit: %"PRId64"\n\n",
             (int)sizeof(void *) * 8, (int64_t)(ssize_t)s->malloc_limit);
 #if 1
     if (rt) {
         static const struct {
             const char *name;
             size_t size;
         } object_types[] = {
             { "JSRuntime", sizeof(JSRuntime) },
             { "JSContext", sizeof(JSContext) },
             { "JSObject", sizeof(JSObject) },
             { "JSString", sizeof(JSString) },
             { "JSFunctionBytecode", sizeof(JSFunctionBytecode) },
         };
         int i, usage_size_ok = 0;
         for(i = 0; i < countof(object_types); i++) {
             unsigned int size = object_types[i].size;
             void *p = js_malloc_rt(rt, size);
             if (p) {
                 unsigned int size1 = js_malloc_usable_size_rt(rt, p);
                 if (size1 >= size) {
                     usage_size_ok = 1;
                     fprintf(fp, "  %3u + %-2u  %s\n",
                             size, size1 - size, object_types[i].name);
                 }
                 js_free_rt(rt, p);
             }
         }
         if (!usage_size_ok) {
             fprintf(fp, "  malloc_usable_size unavailable\n");
         }
         {
             int obj_classes[JS_CLASS_INIT_COUNT + 1] = { 0 };
             int class_id;
             struct list_head *el;
             list_for_each(el, &rt->gc_obj_list) {
                 JSGCObjectHeader *gp = list_entry(el, JSGCObjectHeader, link);
                 JSObject *p;
                 if (gp->gc_obj_type == JS_GC_OBJ_TYPE_JS_OBJECT) {
                     p = (JSObject *)gp;
                     obj_classes[min_uint32(p->class_id, JS_CLASS_INIT_COUNT)]++;
                 }
             }
             fprintf(fp, "\n" "JSObject classes\n");
             if (obj_classes[0])
                 fprintf(fp, "  %5d  %2.0d %s\n", obj_classes[0], 0, "none");
             for (class_id = 1; class_id < JS_CLASS_INIT_COUNT; class_id++) {
                 if (obj_classes[class_id]) {
                     char buf[ATOM_GET_STR_BUF_SIZE];
                     fprintf(fp, "  %5d  %2.0d %s\n", obj_classes[class_id], class_id,
                             JS_AtomGetStrRT(rt, buf, sizeof(buf), js_std_class_def[class_id - 1].class_name));
                 }
             }
             if (obj_classes[JS_CLASS_INIT_COUNT])
                 fprintf(fp, "  %5d  %2.0d %s\n", obj_classes[JS_CLASS_INIT_COUNT], 0, "other");
         }
         fprintf(fp, "\n");
     }
 #endif
     fprintf(fp, "%-20s %8s %8s\n", "NAME", "COUNT", "SIZE");
     if (s->malloc_count) {
         fprintf(fp, "%-20s %8"PRId64" %8"PRId64"  (%0.1f per block)\n",
                 "memory allocated", s->malloc_count, s->malloc_size,
                 (double)s->malloc_size / s->malloc_count);
         fprintf(fp, "%-20s %8"PRId64" %8"PRId64"  (%d overhead, %0.1f average slack)\n",
                 "memory used", s->memory_used_count, s->memory_used_size,
                 MALLOC_OVERHEAD, ((double)(s->malloc_size - s->memory_used_size) /
                                   s->memory_used_count));
     }
     if (s->atom_count) {
         fprintf(fp, "%-20s %8"PRId64" %8"PRId64"  (%0.1f per atom)\n",
                 "atoms", s->atom_count, s->atom_size,
                 (double)s->atom_size / s->atom_count);
     }
     if (s->str_count) {
         fprintf(fp, "%-20s %8"PRId64" %8"PRId64"  (%0.1f per string)\n",
                 "strings", s->str_count, s->str_size,
                 (double)s->str_size / s->str_count);
     }
     if (s->obj_count) {
         fprintf(fp, "%-20s %8"PRId64" %8"PRId64"  (%0.1f per object)\n",
                 "objects", s->obj_count, s->obj_size,
                 (double)s->obj_size / s->obj_count);
         fprintf(fp, "%-20s %8"PRId64" %8"PRId64"  (%0.1f per object)\n",
                 "  properties", s->prop_count, s->prop_size,
                 (double)s->prop_count / s->obj_count);
         fprintf(fp, "%-20s %8"PRId64" %8"PRId64"  (%0.1f per shape)\n",
                 "  shapes", s->shape_count, s->shape_size,
                 (double)s->shape_size / s->shape_count);
     }
     if (s->js_func_count) {
         fprintf(fp, "%-20s %8"PRId64" %8"PRId64"\n",
                 "bytecode functions", s->js_func_count, s->js_func_size);
         fprintf(fp, "%-20s %8"PRId64" %8"PRId64"  (%0.1f per function)\n",
                 "  bytecode", s->js_func_count, s->js_func_code_size,
                 (double)s->js_func_code_size / s->js_func_count);
         if (s->js_func_pc2line_count) {
             fprintf(fp, "%-20s %8"PRId64" %8"PRId64"  (%0.1f per function)\n",
                     "  pc2line", s->js_func_pc2line_count,
                     s->js_func_pc2line_size,
                     (double)s->js_func_pc2line_size / s->js_func_pc2line_count);
         }
     }
     if (s->c_func_count) {
         fprintf(fp, "%-20s %8"PRId64"\n", "C functions", s->c_func_count);
     }
     if (s->array_count) {
         fprintf(fp, "%-20s %8"PRId64"\n", "arrays", s->array_count);
         if (s->fast_array_count) {
             fprintf(fp, "%-20s %8"PRId64"\n", "  fast arrays", s->fast_array_count);
             fprintf(fp, "%-20s %8"PRId64" %8"PRId64"  (%0.1f per fast array)\n",
                     "  elements", s->fast_array_elements,
                     s->fast_array_elements * (int)sizeof(JSValue),
                     (double)s->fast_array_elements / s->fast_array_count);
         }
     }
     if (s->binary_object_count) {
         fprintf(fp, "%-20s %8"PRId64" %8"PRId64"\n",
                 "binary objects", s->binary_object_count, s->binary_object_size);
     }
 }
JS_NewAtomLen()
JSAtom JS_NewAtomLen (JSContext * ctx, const char * str, size_t len)
Definition at line 2932 of file quickjs.c.
References __JS_FindAtom(), is_digit(), JS_ATOM_TYPE_STRING, JS_IsException(), JS_NewAtomStr(), JS_NewStringLen(), and JSContext::rt.
Referenced by js_atom_concat_str(), JS_NewAtom(), js_std_getenviron(), json_parse_ident(), and parse_ident().
 {
     JSValue val;
     if (len == 0 || !is_digit(*str)) {
         JSAtom atom = __JS_FindAtom(ctx->rt, str, len, JS_ATOM_TYPE_STRING);
         if (atom)
             return atom;
     }
     val = JS_NewStringLen(ctx, str, len);
     if (JS_IsException(val))
         return JS_ATOM_NULL;
     return JS_NewAtomStr(ctx, JS_VALUE_GET_STRING(val));
 }
JS_NewAtom()
JSAtom JS_NewAtom (JSContext * ctx, const char * str)
Definition at line 2947 of file quickjs.c.
References JS_NewAtomLen().
Referenced by __JS_EvalInternal(), qjs::Value::add_getter(), qjs::Value::add_getter_setter(), find_atom(), JS_AddModuleExport(), JS_DefinePropertyValueStr(), JS_GetPropertyStr(), js_host_resolve_imported_module(), js_new_function_def(), JS_NewAtomString(), JS_NewCFunction3(), JS_NewCModule(), JS_SetModuleExport(), and JS_SetPropertyStr().
 {
     return JS_NewAtomLen(ctx, str, strlen(str));
 }
JS_NewAtomUInt32()
JSAtom JS_NewAtomUInt32 (JSContext * ctx, uint32_t n)
Definition at line 2952 of file quickjs.c.
References __JS_AtomFromUInt32(), __JS_NewAtom(), JS_ATOM_TYPE_STRING, JS_IsException(), JS_NewString(), and JSContext::rt.
Referenced by internalize_json_property(), and set_array_length().
 {
     if (n <= JS_ATOM_MAX_INT) {
         return __JS_AtomFromUInt32(n);
     } else {
         char buf[11];
         JSValue val;
         snprintf(buf, sizeof(buf), "%u", n);
         val = JS_NewString(ctx, buf);
         if (JS_IsException(val))
             return JS_ATOM_NULL;
         return __JS_NewAtom(ctx->rt, JS_VALUE_GET_STRING(val),
                             JS_ATOM_TYPE_STRING);
     }
 }
JS_DupAtom()
JSAtom JS_DupAtom (JSContext * ctx, JSAtom v)
Definition at line 2605 of file quickjs.c.
References __JS_AtomIsConst(), JSRuntime::atom_array, JSString::header, JSRefCountHeader::ref_count, and JSContext::rt.
Referenced by __JS_EvalInternal(), add_arg(), add_closure_var(), add_closure_variables(), add_export_entry2(), add_global_var(), add_import(), add_req_module_entry(), add_resolve_entry(), add_shape_property(), add_var(), bc_idx_to_atom(), emit_atom(), find_atom(), instantiate_hoisted_definitions(), internalize_json_property(), js_clone_shape(), JS_GetModuleName(), JS_GetOwnPropertyNamesInternal(), JS_GetScriptOrModuleName(), js_parse_class(), js_parse_destructuring_element(), js_parse_destructuring_var(), js_parse_export(), js_parse_for_in_of(), js_parse_function_decl2(), js_parse_import(), js_parse_postfix_expr(), js_parse_property_name(), js_parse_statement_or_decl(), js_parse_var(), JS_ReadFunctionBytecode(), json_parse_value(), optimize_scope_make_global_ref(), resolve_scope_private_field(), resolve_scope_var(), resolve_variables(), set_closure_from_var(), set_object_name(), and var_object_test().
 {
     JSRuntime *rt;
     JSAtomStruct *p;
     if (!__JS_AtomIsConst(v)) {
         rt = ctx->rt;
         p = rt->atom_array[v];
         p->header.ref_count++;
     }
     return v;
 }
JS_FreeAtom()
void JS_FreeAtom (JSContext * ctx, JSAtom v)
Definition at line 3225 of file quickjs.c.
References __JS_AtomIsConst(), __JS_FreeAtom(), and JSContext::rt.
Referenced by qjs::Value::add_getter(), qjs::Value::add_getter_setter(), bc_reader_free(), build_envp(), delete_property(), free_token(), instantiate_hoisted_definitions(), internalize_json_property(), JS_AddBrand(), JS_AddModuleExport(), JS_CallInternal(), js_create_function(), js_date_Symbol_toPrimitive(), JS_DefineObjectNameComputed(), JS_DefinePropertyValueStr(), JS_DefinePropertyValueValue(), JS_DeletePropertyInt64(), js_dynamic_import(), js_free_function_def(), js_free_module_def(), js_free_prop_enum(), JS_GetOwnPropertyNamesInternal(), JS_GetPropertyInt64(), JS_GetPropertyStr(), JS_GetPropertyValue(), js_host_resolve_imported_module(), js_import_meta(), JS_InstantiateFunctionListItem(), js_module_set_import_meta(), js_new_module_def(), JS_NewAtomString(), JS_NewCFunction3(), js_object___defineGetter__(), js_object___lookupGetter__(), js_object_defineProperty(), js_object_getOwnPropertyDescriptor(), js_object_hasOwnProperty(), js_object_propertyIsEnumerable(), js_operator_delete(), js_operator_in(), js_parse_assign_expr2(), js_parse_class(), js_parse_delete(), js_parse_destructuring_element(), js_parse_destructuring_var(), js_parse_export(), js_parse_for_in_of(), js_parse_from_clause(), js_parse_function_decl2(), js_parse_import(), js_parse_object_literal(), js_parse_property_name(), js_parse_statement_or_decl(), js_parse_var(), JS_ReadObjectTag(), js_reflect_deleteProperty(), js_reflect_get(), js_reflect_has(), js_reflect_set(), js_resolve_export(), JS_SetModuleExport(), JS_SetPropertyFunctionList(), JS_SetPropertyInt64(), JS_SetPropertyStr(), JS_SetPropertyValue(), js_std_getenviron(), JS_TryGetPropertyInt64(), js_worker_ctor(), json_parse_value(), put_lvalue(), resolve_labels(), resolve_scope_private_field(), resolve_variables(), set_array_length(), set_object_name(), and skip_dead_code().
 {
     if (!__JS_AtomIsConst(v))
         __JS_FreeAtom(ctx->rt, v);
 }
JS_FreeAtomRT()
void JS_FreeAtomRT (JSRuntime * rt, JSAtom v)
Definition at line 3231 of file quickjs.c.
References __JS_AtomIsConst(), and __JS_FreeAtom().
Referenced by free_bytecode_atoms(), free_function_bytecode(), js_free_shape0(), JS_FreeRuntime(), and JS_NewClass().
 {
     if (!__JS_AtomIsConst(v))
         __JS_FreeAtom(rt, v);
 }
JS_AtomToValue()
JSValue JS_AtomToValue (JSContext * ctx, JSAtom atom)
Definition at line 3093 of file quickjs.c.
References __JS_AtomToValue(), and FALSE.
Referenced by internalize_json_property(), JS_AddIntrinsicBaseObjects(), JS_CallInternal(), js_dynamic_import(), js_for_in_next(), JS_GetGlobalVarRef(), JS_GetOwnPropertyNames2(), js_object_getOwnPropertyDescriptors(), js_parse_delete(), js_parse_postfix_expr(), js_proxy_define_own_property(), js_proxy_delete_property(), js_proxy_get(), js_proxy_get_own_property(), js_proxy_has(), and js_proxy_set().
 {
     return __JS_AtomToValue(ctx, atom, FALSE);
 }
JS_AtomToString()
JSValue JS_AtomToString (JSContext * ctx, JSAtom atom)
Definition at line 3098 of file quickjs.c.
References __JS_AtomToValue(), and TRUE.
Referenced by JS_AddIntrinsicBaseObjects(), JS_AddIntrinsicBasicObjects(), js_atom_concat_str(), js_atomics_wait(), JS_AtomToCString(), js_boolean_toString(), js_build_module_ns(), JS_CallInternal(), JS_DefineObjectName(), js_error_toString(), js_function_bind(), js_function_proto_fileName(), js_function_set_properties(), js_function_toString(), js_get_function_name(), JS_JSONStringify(), js_new_string8(), JS_NewAtomString(), js_object___getClass(), js_object_toString(), js_regexp_compile(), js_regexp_constructor(), js_string_constructor(), js_symbol_get_description(), JS_ToPrimitiveFree(), JS_ToStringInternal(), js_typed_array_get_toStringTag(), and string_buffer_end().
 {
     return __JS_AtomToValue(ctx, atom, TRUE);
 }
JS_AtomToCString()
const char* JS_AtomToCString (JSContext * ctx, JSAtom atom)
Definition at line 3292 of file quickjs.c.
References JS_AtomToString(), JS_FreeValue(), JS_IsException(), and JS_ToCString().
Referenced by build_backtrace(), build_envp(), js_host_resolve_imported_module_atom(), js_module_set_import_meta(), and js_worker_ctor().
 {
     JSValue str;
     const char *cstr;
     str = JS_AtomToString(ctx, atom);
     if (JS_IsException(str))
         return NULL;
     cstr = JS_ToCString(ctx, str);
     JS_FreeValue(ctx, str);
     return cstr;
 }
JS_ValueToAtom()
JSAtom JS_ValueToAtom (JSContext * ctx, JSValueConst val)
Definition at line 7798 of file quickjs.c.
References __JS_AtomFromUInt32(), JS_IsException(), JS_NewAtomStr(), js_symbol_to_atom(), JS_TAG_INT, JS_TAG_SYMBOL, and JS_ToPropertyKey().
Referenced by JS_CallInternal(), js_date_Symbol_toPrimitive(), JS_DefineObjectNameComputed(), JS_DefinePropertyValueValue(), JS_GetPropertyValue(), js_object___defineGetter__(), js_object___lookupGetter__(), js_object_defineProperty(), js_object_getOwnPropertyDescriptor(), js_object_hasOwnProperty(), js_object_propertyIsEnumerable(), js_operator_delete(), js_operator_in(), js_parse_from_clause(), js_parse_import(), js_parse_property_name(), js_proxy_get_own_property_names(), js_reflect_deleteProperty(), js_reflect_get(), js_reflect_has(), js_reflect_set(), JS_SetPropertyValue(), and json_parse_value().
 {
     JSAtom atom;
     uint32_t tag;
     tag = JS_VALUE_GET_TAG(val);
     if (tag == JS_TAG_INT &&
         (uint32_t)JS_VALUE_GET_INT(val) <= JS_ATOM_MAX_INT) {
         /* fast path for integer values */
         atom = __JS_AtomFromUInt32(JS_VALUE_GET_INT(val));
     } else if (tag == JS_TAG_SYMBOL) {
         JSAtomStruct *p = JS_VALUE_GET_PTR(val);
         atom = JS_DupAtom(ctx, js_get_atom_index(ctx->rt, p));
     } else {
         JSValue str;
         str = JS_ToPropertyKey(ctx, val);
         if (JS_IsException(str))
             return JS_ATOM_NULL;
         if (JS_VALUE_GET_TAG(str) == JS_TAG_SYMBOL) {
             atom = js_symbol_to_atom(ctx, str);
         } else {
             atom = JS_NewAtomStr(ctx, JS_VALUE_GET_STRING(str));
         }
     }
     return atom;
 }
JS_NewClassID()
JSClassID JS_NewClassID (JSClassID * pclass_id)
Definition at line 3353 of file quickjs.c.
References js_class_id_alloc.
Referenced by js_os_init(), js_std_init(), qjs::js_traits< std::shared_ptr< T > >::register_class(), and qjs::js_traits< detail::function >::register_class().
 {
     JSClassID class_id;
     /* XXX: make it thread safe */
     class_id = *pclass_id;
     if (class_id == 0) {
         class_id = js_class_id_alloc++;
         *pclass_id = class_id;
     }
     return class_id;
 }
JS_GetClassID()
JSClassID JS_GetClassID (JSValueConst v)
JS_NewClass()
int JS_NewClass (JSRuntime * rt, JSClassID class_id, const JSClassDef * class_def)
Definition at line 3420 of file quickjs.c.
References __JS_FindAtom(), __JS_NewAtomInit(), JSClassDef::class_name, JS_ATOM_TYPE_STRING, JS_FreeAtomRT(), and JS_NewClass1().
Referenced by js_os_init(), js_std_init(), qjs::js_traits< std::shared_ptr< T > >::register_class(), and qjs::js_traits< detail::function >::register_class().
 {
     int ret, len;
     JSAtom name;
     len = strlen(class_def->class_name);
     name = __JS_FindAtom(rt, class_def->class_name, len, JS_ATOM_TYPE_STRING);
     if (name == JS_ATOM_NULL) {
         name = __JS_NewAtomInit(rt, class_def->class_name, len, JS_ATOM_TYPE_STRING);
         if (name == JS_ATOM_NULL)
             return -1;
     }
     ret = JS_NewClass1(rt, class_id, class_def, name);
     JS_FreeAtomRT(rt, name);
     return ret;
 }
JS_IsRegisteredClass()
int JS_IsRegisteredClass (JSRuntime * rt, JSClassID class_id)
Definition at line 3365 of file quickjs.c.
References JSRuntime::class_array, JSRuntime::class_count, and JSClass::class_id.
Referenced by JS_AddIntrinsicPromise(), JS_AddIntrinsicProxy(), qjs::js_traits< std::shared_ptr< T > >::register_class(), and qjs::js_traits< detail::function >::register_class().
 {
     return (class_id < rt->class_count &&
             rt->class_array[class_id].class_id != 0);
 }
JS_NewBool()
static js_force_inline JSValue JS_NewBool (JSContext * ctx, JS_BOOL val) static
Definition at line 502 of file quickjs.h.
References JS_TAG_BOOL.
Referenced by JS_AddIntrinsicBaseObjects(), js_array_buffer_isView(), js_array_includes(), js_array_isArray(), js_async_from_sync_iterator_unwrap_func_create(), js_atomics_isLockFree(), js_boolean_constructor(), JS_CallInternal(), js_create_desc(), js_create_iterator_result(), js_eq_slow(), js_for_of_next(), js_function_hasInstance(), js_global_isFinite(), js_global_isNaN(), js_iterator_get_value_done(), js_map_has(), js_module_set_import_meta(), js_number_isInteger(), js_number_isSafeInteger(), js_object_defineProperty(), js_object_getOwnPropertyDescriptor(), js_object_hasOwnProperty(), js_object_is(), js_object_isExtensible(), js_object_isPrototypeOf(), js_object_isSealed(), js_object_preventExtensions(), js_object_propertyIsEnumerable(), js_operator_delete(), js_operator_in(), js_operator_instanceof(), js_os_isatty(), js_promise_all(), js_promise_all_resolve_element(), JS_ReadObjectRec(), js_reflect_deleteProperty(), js_reflect_has(), js_reflect_set(), js_reflect_setPrototypeOf(), js_regexp_get_flag(), js_regexp_test(), js_relational_slow(), js_std_file_eof(), js_std_file_error(), js_strict_eq_slow(), js_string_includes(), js_typed_array_indexOf(), json_parse_value(), perform_promise_then(), and qjs::wrap().
 {
     return JS_MKVAL(JS_TAG_BOOL, (val != 0));
 }
JS_NewInt32()
static js_force_inline JSValue JS_NewInt32 (JSContext * ctx, int32_t val) static
Definition at line 507 of file quickjs.h.
References JS_TAG_INT.
Referenced by add_fast_array_element(), build_backtrace(), JS_AddIntrinsicBaseObjects(), js_append_enumerate(), js_array_concat(), js_array_every(), js_array_find(), js_array_flatten(), js_array_from(), js_array_of(), js_async_generator_resume_next(), js_atomics_notify(), js_atomics_op(), JS_AtomIsNumericIndex1(), js_binary_logic_slow(), js_build_arguments(), js_build_mapped_arguments(), JS_CallInternal(), js_dataview_getValue(), JS_DefineProperty(), js_eq_slow(), js_function_bind(), js_function_proto_lineNumber(), js_function_set_properties(), JS_GetPropertyInt64(), JS_GetPropertyInternal(), JS_GetPropertyValue(), JS_InstantiateFunctionListItem(), js_math_clz32(), js_math_imul(), js_math_min_max(), JS_NewInt64(), JS_NewObjectFromShape(), JS_NewUint32(), js_not_slow(), js_number_constructor(), js_op_define_class(), js_os_chdir(), js_os_close(), js_os_dup(), js_os_dup2(), js_os_exec(), js_os_kill(), js_os_mkdir(), js_os_open(), js_os_pipe(), js_os_remove(), js_os_rename(), js_os_sleep(), js_os_stat(), js_os_symlink(), js_os_ttyGetWinSize(), js_os_utimes(), js_os_waitpid(), js_printf_internal(), js_promise_all(), JS_ReadObjectRec(), js_regexp_compile(), js_regexp_constructor_internal(), js_regexp_exec(), js_regexp_Symbol_match(), js_regexp_Symbol_replace(), js_regexp_Symbol_search(), js_regexp_Symbol_split(), JS_RegExpDelete(), js_set_error_object(), JS_SetModuleExportList(), JS_SetPropertyInt64(), JS_SetPropertyInternal(), js_std_file_close(), js_std_file_fileno(), js_std_file_getByte(), js_std_file_putByte(), js_std_file_seek(), js_std_urlGet(), js_string_charCodeAt(), js_string_codePointAt(), js_string_constructor(), js_string_indexOf(), js_string_localeCompare(), js_string_replace(), js_TA_get_int16(), js_TA_get_int32(), js_TA_get_int8(), js_TA_get_uint16(), js_TA_get_uint8(), JS_ToIntegerFree(), JS_ToNumberHintFree(), JS_ToObject(), JS_TryGetPropertyInt64(), js_typed_array_find(), js_typed_array_from(), js_typed_array_get_byteLength(), js_typed_array_get_byteOffset(), js_typed_array_get_length(), js_typed_array_indexOf(), js_typed_array_of(), js_typed_array_slice(), js_typed_array_subarray(), make_obj_error(), map_normalize_key(), and remainingElementsCount_add().
 {
     return JS_MKVAL(JS_TAG_INT, val);
 }
JS_NewCatchOffset()
static js_force_inline JSValue JS_NewCatchOffset (JSContext * ctx, int32_t val) static
Definition at line 512 of file quickjs.h.
References JS_TAG_CATCH_OFFSET.
Referenced by JS_CallInternal().
 {
     return JS_MKVAL(JS_TAG_CATCH_OFFSET, val);
 }
JS_NewInt64()
static js_force_inline JSValue JS_NewInt64 (JSContext * ctx, int64_t val) static
Definition at line 517 of file quickjs.h.
References __JS_NewFloat64(), and JS_NewInt32().
Referenced by js___date_clock(), js_array_buffer_slice(), js_array_concat(), js_array_every(), js_array_find(), js_array_from(), js_array_indexOf(), js_array_lastIndexOf(), js_array_pop(), js_array_push(), js_array_reduce(), js_array_slice(), JS_CreateDataPropertyUint32(), js_date_getTimezoneOffset(), js_Date_now(), JS_DefinePropertyValueInt64(), JS_FlattenIntoArray(), JS_InstantiateFunctionListItem(), js_json_to_str(), js_os_read_write(), js_os_seek(), js_os_stat(), JS_ReadTypedArray(), js_regexp_string_iterator_next(), js_regexp_Symbol_match(), js_regexp_Symbol_matchAll(), js_regexp_Symbol_replace(), JS_SetModuleExportList(), js_std_file_read_write(), js_std_file_tell(), and js_typed_array_from().
 {
     JSValue v;
     if (val == (int32_t)val) {
         v = JS_NewInt32(ctx, val);
     } else {
         v = __JS_NewFloat64(ctx, val);
     }
     return v;
 }
JS_NewUint32()
static js_force_inline JSValue JS_NewUint32 (JSContext * ctx, uint32_t val) static
Definition at line 528 of file quickjs.h.
References __JS_NewFloat64(), and JS_NewInt32().
Referenced by js_array_constructor(), js_array_from(), js_array_iterator_next(), js_array_of(), js_atomics_op(), JS_CallInternal(), JS_CreateProperty(), js_dataview_getValue(), JS_DefineProperty(), JS_DefinePropertyValueUint32(), JS_GetPropertyUint32(), JS_GetPropertyValue(), JS_SetPropertyUint32(), js_shr_slow(), js_TA_get_uint32(), and set_array_length().
 {
     JSValue v;
     if (val <= 0x7fffffff) {
         v = JS_NewInt32(ctx, val);
     } else {
         v = __JS_NewFloat64(ctx, val);
     }
     return v;
 }
JS_NewBigInt64()
JSValue JS_NewBigInt64 (JSContext * ctx, int64_t v)
Definition at line 14132 of file quickjs.c.
References JS_ThrowUnsupportedBigint().
Referenced by js_os_seek(), and js_std_file_tell().
 {
     return JS_ThrowUnsupportedBigint(ctx);
 }
JS_NewBigUint64()
JSValue JS_NewBigUint64 (JSContext * ctx, uint64_t v)
Definition at line 14137 of file quickjs.c.
References JS_ThrowUnsupportedBigint().
 {
     return JS_ThrowUnsupportedBigint(ctx);
 }
JS_NewFloat64()
static js_force_inline JSValue JS_NewFloat64 (JSContext * ctx, double d) static
Definition at line 542 of file quickjs.h.
References __JS_NewFloat64(), and JS_TAG_INT.
Referenced by get_date_field(), js_add_slow(), js_atof(), js_binary_arith_slow(), js_call_c_function(), JS_CallInternal(), js_date_constructor(), js_date_getTime(), js_Date_parse(), js_date_setYear(), js_Date_UTC(), js_function_bind(), js_math_hypot(), js_math_min_max(), js_post_inc_slow(), JS_SetThisTimeValue(), JS_ToIntegerFree(), js_unary_arith_slow(), and qjs::js_traits< double >::wrap().
 {
     JSValue v;
     int32_t val;
     union {
         double d;
         uint64_t u;
     } u, t;
     u.d = d;
     val = (int32_t)d;
     t.d = val;
     /* -0 cannot be represented as integer, so we compare the bit
         representation */
     if (u.u == t.u) {
         v = JS_MKVAL(JS_TAG_INT, val);
     } else {
         v = __JS_NewFloat64(ctx, d);
     }
     return v;
 }
JS_IsNumber()
static JS_BOOL JS_IsNumber (JSValueConst v) inline static
Definition at line 563 of file quickjs.h.
References JS_TAG_INT.
Referenced by js_array_constructor(), js_date_constructor(), js_date_toJSON(), JS_JSONStringify(), js_number_isFinite(), js_number_isNaN(), js_number_isSafeInteger(), JS_NumberIsInteger(), JS_ReadDate(), js_thisNumberValue(), and JS_ThisTimeValue().
 {
     int tag = JS_VALUE_GET_TAG(v);
     return tag == JS_TAG_INT || JS_TAG_IS_FLOAT64(tag);
 }
JS_IsBigInt()
static JS_BOOL JS_IsBigInt (JSContext * ctx, JSValueConst v) inline static
Definition at line 569 of file quickjs.h.
References JS_TAG_BIG_INT.
Referenced by js_os_seek(), and JS_ToInt64Ext().
 {
     int tag = JS_VALUE_GET_TAG(v);
     return tag == JS_TAG_BIG_INT;
 }
JS_IsBigFloat()
static JS_BOOL JS_IsBigFloat (JSValueConst v) inline static
Definition at line 575 of file quickjs.h.
References JS_TAG_BIG_FLOAT.
 {
     int tag = JS_VALUE_GET_TAG(v);
     return tag == JS_TAG_BIG_FLOAT;
 }
JS_IsBigDecimal()
static JS_BOOL JS_IsBigDecimal (JSValueConst v) inline static
Definition at line 581 of file quickjs.h.
References JS_TAG_BIG_DECIMAL.
 {
     int tag = JS_VALUE_GET_TAG(v);
     return tag == JS_TAG_BIG_DECIMAL;
 }
JS_IsBool()
static JS_BOOL JS_IsBool (JSValueConst v) inline static
Definition at line 587 of file quickjs.h.
References JS_TAG_BOOL.
 {
     return JS_VALUE_GET_TAG(v) == JS_TAG_BOOL;
 }
JS_IsNull()
static JS_BOOL JS_IsNull (JSValueConst v) inline static
Definition at line 592 of file quickjs.h.
References JS_TAG_NULL.
Referenced by check_regexp_g_flag(), get_proxy_method(), js_array_join(), JS_ArraySpeciesCreate(), js_async_from_sync_iterator_next(), JS_CallInternal(), JS_GetIterator(), JS_IsInstanceOf(), JS_IteratorClose(), js_map_constructor(), js_object___lookupGetter__(), js_object_assign(), js_object_create(), js_object_isPrototypeOf(), js_object_set___proto__(), js_object_toString(), js_op_define_class(), JS_OrdinaryIsInstanceOf(), js_os_setReadHandler(), js_os_signal(), js_regexp_string_iterator_next(), js_regexp_Symbol_match(), js_regexp_Symbol_replace(), js_regexp_Symbol_search(), js_regexp_Symbol_split(), js_regexp_test(), JS_RegExpExec(), JS_SpeciesConstructor(), js_std_urlGet(), js_string_match(), js_string_replace(), js_string_split(), JS_ToLocaleStringFree(), JS_ToPrimitiveFree(), js_typed_array_constructor_obj(), js_worker_set_onmessage(), and qjs::js_traits< std::optional< T > >::unwrap().
 {
     return JS_VALUE_GET_TAG(v) == JS_TAG_NULL;
 }
JS_IsUndefined()
static JS_BOOL JS_IsUndefined (JSValueConst v) inline static
Definition at line 597 of file quickjs.h.
References JS_TAG_UNDEFINED.
Referenced by check_regexp_g_flag(), get_bool_option(), internalize_json_property(), js_array_buffer_slice(), js_array_copyWithin(), js_array_fill(), js_array_flatten(), js_array_from(), js_array_iterator_next(), js_array_join(), js_array_slice(), js_array_sort(), JS_ArraySpeciesCreate(), js_async_from_sync_iterator_next(), js_async_function_resume(), js_async_generator_resume_next(), js_atomics_notify(), JS_AtomIsNumericIndex(), js_boolean_constructor(), JS_CallInternal(), js_compile_regexp(), js_create_from_ctor(), js_dataview_constructor(), js_date_constructor(), JS_DefineProperty(), js_error_constructor(), js_error_toString(), JS_FlattenIntoArray(), js_for_of_next(), js_function_constructor(), js_function_toString(), js_get_module_ns(), JS_GetImportMeta(), JS_GetIterator(), js_is_regexp(), JS_isConcatSpreadable(), JS_IsInstanceOf(), JS_IteratorClose(), js_json_check(), js_json_to_str(), JS_JSONStringify(), js_map_constructor(), js_map_iterator_next(), js_new_promise_capability(), js_number_constructor(), js_number_toExponential(), js_number_toPrecision(), js_number_toString(), js_obj_to_desc(), js_object_assign(), js_object_constructor(), js_object_create(), js_object_getOwnPropertyDescriptors(), js_object_set___proto__(), js_object_toString(), js_os_exec(), js_os_open(), js_os_signal(), js_promise_executor(), js_proxy_call(), js_proxy_call_constructor(), js_proxy_define_own_property(), js_proxy_delete_property(), js_proxy_get(), js_proxy_get_own_property(), js_proxy_get_own_property_names(), js_proxy_getPrototypeOf(), js_proxy_has(), js_proxy_isExtensible(), js_proxy_preventExtensions(), js_proxy_set(), js_proxy_setPrototypeOf(), JS_ReadArray(), js_regexp_compile(), js_regexp_constructor(), js_regexp_Symbol_replace(), js_regexp_Symbol_split(), js_set_error_object(), JS_SetPropertyGeneric(), JS_SetPropertyInternal(), JS_SpeciesConstructor(), js_std_dump_error1(), js_std_file_readAsString(), js_string___GetSubstitution(), js_string_constructor(), js_string_includes(), js_string_iterator_next(), js_string_match(), js_string_normalize(), js_string_pad(), js_string_replace(), js_string_slice(), js_string_split(), js_string_substr(), js_string_substring(), js_symbol_constructor(), JS_ToLocaleStringFree(), JS_ToPrimitiveFree(), js_typed_array___speciesCreate(), js_typed_array_constructor(), js_typed_array_constructor_obj(), js_typed_array_copyWithin(), js_typed_array_fill(), js_typed_array_from(), js_typed_array_join(), js_typed_array_slice(), js_typed_array_sort(), js_typed_array_subarray(), js_worker_ctor_internal(), and promise_reaction_job().
 {
     return JS_VALUE_GET_TAG(v) == JS_TAG_UNDEFINED;
 }
JS_IsException()
static JS_BOOL JS_IsException (JSValueConst v) inline static
Definition at line 602 of file quickjs.h.
References JS_TAG_EXCEPTION.
Referenced by __JS_EvalInternal(), __JS_ToFloat64Free(), build_arg_list(), build_envp(), build_for_in_iterator(), call_handler(), call_setter(), check_exception_free(), check_regexp_g_flag(), exported_names_cmp(), get_bool_option(), get_proxy_method(), handle_posted_message(), internalize_json_property(), iterator_to_array(), js_add_slow(), JS_AddBrand(), js_aggregate_error_constructor(), js_append_enumerate(), js_array_buffer_constructor3(), js_array_buffer_slice(), js_array_cmp_generic(), js_array_concat(), js_array_constructor(), js_array_every(), js_array_find(), js_array_flatten(), js_array_from(), js_array_from_iterator(), js_array_includes(), js_array_iterator_next(), js_array_join(), js_array_of(), js_array_pop(), js_array_reduce(), js_array_slice(), js_array_toString(), JS_ArraySpeciesCreate(), js_async_from_sync_iterator_next(), js_async_function_call(), js_async_function_resolve_create(), js_async_function_resume(), js_async_generator_await(), js_async_generator_completed_return(), js_async_generator_function_call(), js_async_generator_next(), js_async_generator_resolve_function_create(), js_async_generator_resume_next(), js_atom_concat_str(), js_atomics_store(), JS_AtomIsNumericIndex(), JS_AtomIsNumericIndex1(), JS_AtomToCString(), JS_AutoInitProperty(), js_boolean_constructor(), js_boolean_toString(), js_build_arguments(), js_build_mapped_arguments(), js_build_module_ns(), js_build_rest(), js_call_c_function(), JS_CallConstructorInternal(), JS_CallInternal(), js_closure(), JS_ConcatString(), JS_ConcatString3(), JS_CopyDataProperties(), js_create_array(), js_create_array_iterator(), js_create_desc(), js_create_from_ctor(), js_create_function(), js_create_iterator_result(), js_create_map_iterator(), js_create_module_bytecode_function(), js_create_resolving_functions(), JS_CreateAsyncFromSyncIterator(), js_dataview_constructor(), js_date_constructor(), js_Date_parse(), js_date_toJSON(), JS_DefineObjectNameComputed(), JS_DefineProperty(), JS_DeleteProperty(), js_dynamic_import(), js_dynamic_import_job(), js_eq_slow(), js_error_constructor(), js_error_toString(), JS_EvalFunctionInternal(), js_evalScript(), js_evaluate_module(), JS_ExecutePendingJob(), JS_FlattenIntoArray(), js_for_in_start(), js_for_of_next(), js_for_of_start(), js_function_bind(), js_function_constructor(), js_generator_function_call(), js_get_length32(), js_get_length64(), js_get_module_ns(), JS_GetImportMeta(), JS_GetIterator(), JS_GetIterator2(), JS_GetOwnPropertyNames2(), js_global_decodeURI(), js_global_encodeURI(), js_global_escape(), js_global_unescape(), js_has_unscopable(), js_instantiate_prototype(), JS_Invoke(), js_is_regexp(), js_is_standard_regexp(), JS_isConcatSpreadable(), JS_IsInstanceOf(), js_iterator_get_value_done(), JS_IteratorClose(), JS_IteratorGetCompleteValue(), JS_IteratorNext(), JS_IteratorNext2(), js_json_check(), js_json_parse(), js_json_to_str(), JS_JSONStringify(), js_link_module(), js_map_constructor(), js_method_set_properties(), js_module_loader(), js_module_set_import_meta(), js_new_promise_capability(), js_new_std_file(), JS_NewAtomInt64(), JS_NewAtomLen(), JS_NewAtomUInt32(), JS_NewCFunction3(), JS_NewCFunctionData(), js_number_constructor(), js_number_toExponential(), js_number_toFixed(), js_number_toPrecision(), js_number_toString(), js_obj_to_desc(), js_object___defineGetter__(), js_object___lookupGetter__(), js_object_assign(), js_object_create(), js_object_fromEntries(), js_object_get___proto__(), js_object_getOwnPropertyDescriptor(), js_object_getOwnPropertyDescriptors(), js_object_hasOwnProperty(), js_object_isPrototypeOf(), js_object_propertyIsEnumerable(), js_object_toString(), JS_ObjectDefineProperties(), js_op_define_class(), JS_OrdinaryIsInstanceOf(), js_os_exec(), js_os_pipe(), js_os_readdir(), js_os_setTimeout(), js_os_stat(), js_os_ttyGetWinSize(), js_os_waitpid(), js_parse_postfix_expr(), js_parse_template(), JS_ParseJSON2(), js_promise_all(), js_promise_all_resolve_element(), js_promise_constructor(), js_promise_finally(), js_promise_race(), js_promise_resolve(), js_promise_resolve_function_call(), js_promise_resolve_thenable_job(), js_promise_then(), js_promise_then_finally_func(), js_proxy_call(), js_proxy_call_constructor(), js_proxy_constructor(), js_proxy_define_own_property(), js_proxy_delete_property(), js_proxy_get(), js_proxy_get_own_property(), js_proxy_get_own_property_names(), js_proxy_getPrototypeOf(), js_proxy_has(), js_proxy_isExtensible(), js_proxy_preventExtensions(), js_proxy_revocable(), js_proxy_set(), js_proxy_setPrototypeOf(), JS_ReadArray(), JS_ReadArrayBuffer(), JS_ReadDate(), JS_ReadFunctionTag(), JS_ReadModule(), JS_ReadObjectTag(), JS_ReadObjectValue(), JS_ReadSharedArrayBuffer(), JS_ReadTypedArray(), js_regexp_compile(), js_regexp_constructor(), js_regexp_constructor_internal(), js_regexp_exec(), js_regexp_string_iterator_next(), js_regexp_Symbol_match(), js_regexp_Symbol_matchAll(), js_regexp_Symbol_replace(), js_regexp_Symbol_search(), js_regexp_Symbol_split(), js_regexp_test(), JS_RegExpDelete(), JS_RegExpExec(), js_relational_slow(), JS_RunModule(), JS_SetObjectData(), JS_SetPropertyInternal(), JS_SpeciesConstructor(), js_std_eval_binary(), js_std_getenviron(), js_std_urlGet(), js_string___GetSubstitution(), js_string_charAt(), js_string_charCodeAt(), js_string_codePointAt(), js_string_concat(), js_string_constructor(), js_string_CreateHTML(), js_string_includes(), js_string_indexOf(), js_string_localeCompare(), js_string_match(), js_string_normalize(), js_string_pad(), js_string_raw(), js_string_repeat(), js_string_replace(), js_string_slice(), js_string_split(), js_string_substr(), js_string_substring(), js_string_toLowerCase(), js_string_trim(), js_symbol_constructor(), js_symbol_for(), js_symbol_get_description(), js_symbol_toString(), js_TA_cmp_generic(), JS_ThrowError2(), JS_ToArrayLengthFree(), JS_ToCStringLen2(), JS_ToInt32Free(), JS_ToInt32SatFree(), JS_ToInt64Free(), JS_ToInt64SatFree(), JS_ToIntegerFree(), JS_ToNumberHintFree(), JS_ToObject(), JS_ToPrimitiveFree(), JS_ToQuotedString(), JS_ToStringInternal(), JS_ToUint8ClampFree(), JS_ToUTF32String(), JS_TryGetPropertyInt64(), js_typed_array___speciesCreate(), js_typed_array_constructor(), js_typed_array_constructor_obj(), js_typed_array_constructor_ta(), js_typed_array_create(), js_typed_array_find(), js_typed_array_from(), js_typed_array_join(), js_typed_array_of(), js_typed_array_set_internal(), js_typed_array_slice(), js_typed_array_subarray(), JS_ValueToAtom(), js_worker_ctor(), js_worker_ctor_internal(), JS_WriteArray(), json_next_token(), json_parse_value(), make_obj_error(), next_token(), promise_reaction_job(), remainingElementsCount_add(), string_buffer_concat_value(), string_buffer_concat_value_free(), qjs::js_traits< void >::unwrap(), qjs::js_traits< std::function< R(Args...)> >::unwrap(), qjs::Value::Value(), qjs::js_traits< ctor_wrapper< T, Args... > >::wrap(), qjs::js_traits< std::shared_ptr< T > >::wrap(), and qjs::js_traits< std::function< R(Args...)> >::wrap().
 {
     return js_unlikely(JS_VALUE_GET_TAG(v) == JS_TAG_EXCEPTION);
 }
JS_IsUninitialized()
static JS_BOOL JS_IsUninitialized (JSValueConst v) inline static
Definition at line 607 of file quickjs.h.
References JS_TAG_UNINITIALIZED.
Referenced by JS_CallInternal(), JS_GetGlobalVar(), JS_GetGlobalVarRef(), JS_GetOwnPropertyInternal(), JS_GetOwnPropertyNamesInternal(), JS_GetPropertyInternal(), and JS_SetGlobalVar().
 {
     return js_unlikely(JS_VALUE_GET_TAG(v) == JS_TAG_UNINITIALIZED);
 }
JS_IsString()
static JS_BOOL JS_IsString (JSValueConst v) inline static
Definition at line 612 of file quickjs.h.
References JS_TAG_STRING.
Referenced by js_date_constructor(), js_date_Symbol_toPrimitive(), js_dynamic_import_job(), JS_EvalObject(), js_function_bind(), JS_JSONStringify(), js_object_toString(), js_printf_internal(), js_proxy_get_own_property_names(), and js_string___GetSubstitution().
 {
     return JS_VALUE_GET_TAG(v) == JS_TAG_STRING;
 }
JS_IsSymbol()
static JS_BOOL JS_IsSymbol (JSValueConst v) inline static
Definition at line 617 of file quickjs.h.
References JS_TAG_SYMBOL.
Referenced by js_proxy_get_own_property_names(), js_string_constructor(), and js_symbol_keyFor().
 {
     return JS_VALUE_GET_TAG(v) == JS_TAG_SYMBOL;
 }
JS_IsObject()
static JS_BOOL JS_IsObject (JSValueConst v) inline static
Definition at line 622 of file quickjs.h.
References JS_TAG_OBJECT.
Referenced by internalize_json_property(), JS_ArraySpeciesCreate(), JS_CallInternal(), js_create_from_ctor(), js_date_Symbol_toPrimitive(), JS_DefineObjectName(), JS_DefineObjectNameComputed(), js_error_constructor(), js_error_toString(), js_function_constructor(), JS_GetIterator2(), js_has_unscopable(), js_is_regexp(), JS_isConcatSpreadable(), JS_IsInstanceOf(), JS_IsLiveObject(), js_iterator_get_value_done(), JS_IteratorClose(), JS_IteratorNext2(), js_json_check(), JS_JSONStringify(), js_map_constructor(), js_obj_to_desc(), js_object_create(), js_object_fromEntries(), js_object_isPrototypeOf(), js_object_isSealed(), js_object_seal(), js_object_set___proto__(), JS_ObjectDefineProperties(), js_op_define_class(), js_promise_all(), js_promise_race(), js_promise_resolve(), js_promise_resolve_function_call(), js_proxy_get_own_property(), js_regexp_Symbol_match(), js_regexp_Symbol_matchAll(), js_regexp_Symbol_replace(), js_regexp_Symbol_search(), js_regexp_Symbol_split(), js_regexp_toString(), JS_RegExpExec(), JS_SetPropertyGeneric(), and JS_SpeciesConstructor().
 {
     return JS_VALUE_GET_TAG(v) == JS_TAG_OBJECT;
 }
JS_Throw()
JSValue JS_Throw (JSContext * ctx, JSValue obj)
Definition at line 6304 of file quickjs.c.
References JSRuntime::current_exception, JS_FreeValue(), and JSContext::rt.
Referenced by js_async_function_resolve_call(), js_async_generator_resolve_function(), js_async_generator_resume_next(), JS_CallInternal(), js_evaluate_module(), JS_IteratorClose(), js_promise_finally_thrower(), JS_ThrowError2(), and promise_reaction_job().
 {
     JSRuntime *rt = ctx->rt;
     JS_FreeValue(ctx, rt->current_exception);
     rt->current_exception = obj;
     return JS_EXCEPTION;
 }
JS_GetException()
JSValue JS_GetException (JSContext * ctx)
Definition at line 6313 of file quickjs.c.
References JSRuntime::current_exception, and JSContext::rt.
Referenced by qjs::Context::getException(), js_async_from_sync_iterator_next(), js_async_function_resume(), js_async_generator_next(), js_async_generator_resume_next(), js_dynamic_import_job(), js_promise_all(), js_promise_constructor(), js_promise_race(), js_promise_resolve_function_call(), js_promise_resolve_thenable_job(), js_std_dump_error(), promise_reaction_job(), and qjs::js_traits< std::optional< T > >::unwrap().
 {
     JSValue val;
     JSRuntime *rt = ctx->rt;
     val = rt->current_exception;
     rt->current_exception = JS_NULL;
     return val;
 }
JS_IsError()
JS_BOOL JS_IsError (JSContext * ctx, JSValueConst val)
Definition at line 9707 of file quickjs.c.
References FALSE, JS_CLASS_ERROR, and JS_TAG_OBJECT.
Referenced by qjs::Value::isError(), and js_std_dump_error1().
 {
     JSObject *p;
     if (JS_VALUE_GET_TAG(val) != JS_TAG_OBJECT)
         return FALSE;
     p = JS_VALUE_GET_OBJ(val);
     return (p->class_id == JS_CLASS_ERROR);
 }
JS_ResetUncatchableError()
void JS_ResetUncatchableError (JSContext * ctx)
Definition at line 9736 of file quickjs.c.
References JSRuntime::current_exception, FALSE, JS_SetUncatchableError(), and JSContext::rt.
Referenced by js_evalScript().
 {
     JS_SetUncatchableError(ctx, ctx->rt->current_exception, FALSE);
 }
JS_NewError()
JSValue JS_NewError (JSContext * ctx)
Definition at line 6542 of file quickjs.c.
References JS_CLASS_ERROR, and JS_NewObjectClass().
 {
     return JS_NewObjectClass(ctx, JS_CLASS_ERROR);
 }
__js_printf_like()
JSValue const char JSValue const char JSValue const char JSValue const char JSValue __js_printf_like (2 , 3)
JS_ThrowOutOfMemory()
JSValue JS_ThrowOutOfMemory (JSContext * ctx)
Definition at line 6687 of file quickjs.c.
References __attribute__(), FALSE, JSRuntime::in_out_of_memory, JSContext::rt, and TRUE.
Referenced by js_alloc_string(), js_atof(), js_malloc(), js_mallocz(), JS_NewSymbol(), js_printf_internal(), js_realloc2(), js_std_file_getline(), js_worker_ctor(), resolve_labels(), and resolve_variables().
 {
     JSRuntime *rt = ctx->rt;
     if (!rt->in_out_of_memory) {
         rt->in_out_of_memory = TRUE;
         JS_ThrowInternalError(ctx, "out of memory");
         rt->in_out_of_memory = FALSE;
     }
     return JS_EXCEPTION;
 }
__JS_FreeValue()
void __JS_FreeValue (JSContext * ctx, JSValue v)
Definition at line 5527 of file quickjs.c.
References __JS_FreeValueRT(), and JSContext::rt.
Referenced by JS_FreeValue().
 {
     __JS_FreeValueRT(ctx->rt, v);
 }
JS_FreeValue()
static void JS_FreeValue (JSContext * ctx, JSValue v) inline static
Definition at line 640 of file quickjs.h.
References __JS_FreeValue(), and JSRefCountHeader::ref_count.
Referenced by add_fast_array_element(), build_envp(), build_for_in_iterator(), call_handler(), call_setter(), check_exception_free(), check_regexp_g_flag(), delete_property(), free_arg_list(), free_token(), get_bool_option(), handle_posted_message(), internalize_json_property(), iterator_to_array(), js_add_slow(), JS_AddBrand(), JS_AddIntrinsicBaseObjects(), JS_AddIntrinsicPromise(), JS_AddIntrinsicTypedArrays(), js_append_enumerate(), js_array_buffer_constructor3(), js_array_buffer_slice(), js_array_concat(), js_array_constructor(), js_array_copyWithin(), js_array_every(), js_array_fill(), js_array_find(), js_array_flatten(), js_array_from(), js_array_from_iterator(), js_array_includes(), js_array_indexOf(), js_array_iterator_next(), js_array_join(), js_array_lastIndexOf(), js_array_of(), js_array_pop(), js_array_push(), js_array_reduce(), js_array_reverse(), js_array_slice(), js_array_sort(), js_array_toString(), JS_ArraySpeciesCreate(), js_async_from_sync_iterator_next(), js_async_function_call(), js_async_function_resolve_create(), js_async_function_resume(), js_async_generator_await(), js_async_generator_completed_return(), js_async_generator_function_call(), js_async_generator_next(), js_async_generator_resolve(), js_async_generator_resolve_function_create(), js_async_generator_resolve_or_reject(), js_async_generator_resume_next(), js_atom_concat_str(), js_atomics_store(), JS_AtomIsNumericIndex(), JS_AtomIsNumericIndex1(), JS_AtomToCString(), js_binary_arith_slow(), js_binary_logic_slow(), js_build_arguments(), js_build_mapped_arguments(), js_build_module_ns(), js_build_rest(), JS_CallConstructorInternal(), JS_CallFree(), JS_CallInternal(), js_closure(), js_closure2(), JS_ConcatString(), JS_ConcatString3(), js_create_array(), js_create_array_iterator(), js_create_from_ctor(), js_create_iterator_result(), js_create_map_iterator(), js_create_module_bytecode_function(), js_create_resolving_functions(), JS_CreateAsyncFromSyncIterator(), js_dataview_constructor(), js_date_constructor(), js_Date_parse(), js_date_toJSON(), JS_DefinePrivateField(), JS_DefineProperty(), JS_DefinePropertyGetSet(), JS_DefinePropertyValue(), JS_DefinePropertyValueValue(), JS_DeleteProperty(), js_dynamic_import(), js_dynamic_import_job(), js_eq_slow(), js_error_constructor(), js_error_toString(), JS_EvalFunctionInternal(), js_evaluate_module(), JS_ExecutePendingJob(), JS_FlattenIntoArray(), js_for_of_next(), js_for_of_start(), js_free_desc(), js_free_function_def(), js_free_module_def(), JS_FreeContext(), JS_FreeCString(), js_function_bind(), js_function_constructor(), js_generator_function_call(), JS_GetIterator(), JS_GetIterator2(), JS_GetOwnPropertyNames2(), JS_GetPropertyInternal(), JS_GetPropertyValue(), JS_GetPrototypeFree(), js_global_decodeURI(), js_global_encodeURI(), js_global_escape(), js_global_unescape(), js_has_unscopable(), JS_HasProperty(), js_instantiate_prototype(), JS_InvokeFree(), js_is_standard_regexp(), js_iterator_get_value_done(), JS_IteratorClose(), JS_IteratorNext(), JS_IteratorNext2(), js_json_check(), js_json_parse(), js_json_to_str(), JS_JSONStringify(), js_link_module(), js_map_constructor(), js_map_iterator_next(), js_map_set(), js_method_set_home_object(), js_module_loader(), js_module_set_import_meta(), js_new_promise_capability(), js_new_std_file(), JS_NewCFunctionData(), JS_NewGlobalCConstructor2(), js_number_toString(), js_obj_to_desc(), js_object___defineGetter__(), js_object___lookupGetter__(), js_object_assign(), js_object_create(), js_object_fromEntries(), js_object_get___proto__(), js_object_getOwnPropertyDescriptor(), js_object_getOwnPropertyDescriptors(), js_object_hasOwnProperty(), js_object_isPrototypeOf(), js_object_propertyIsEnumerable(), js_object_toString(), JS_ObjectDefineProperties(), js_op_define_class(), js_operator_delete(), js_operator_in(), js_operator_instanceof(), JS_OrdinaryIsInstanceOf(), js_os_exec(), js_os_setReadHandler(), js_os_setTimeout(), js_os_signal(), js_parse_delete(), js_parse_postfix_expr(), js_parse_template(), JS_ParseJSON2(), js_promise_all(), js_promise_all_resolve_element(), js_promise_constructor(), js_promise_finally(), js_promise_race(), js_promise_resolve(), js_promise_resolve_function_call(), js_promise_resolve_thenable_job(), js_promise_then(), js_promise_then_finally_func(), js_proxy_call(), js_proxy_call_constructor(), js_proxy_constructor(), js_proxy_define_own_property(), js_proxy_delete_property(), js_proxy_get(), js_proxy_get_own_property(), js_proxy_get_own_property_names(), js_proxy_getPrototypeOf(), js_proxy_has(), js_proxy_revocable(), js_proxy_revoke(), js_proxy_set(), js_proxy_setPrototypeOf(), JS_ReadArray(), JS_ReadArrayBuffer(), JS_ReadDate(), JS_ReadFunctionTag(), JS_ReadObjectTag(), JS_ReadObjectValue(), JS_ReadSharedArrayBuffer(), JS_ReadTypedArray(), js_regexp_compile(), js_regexp_constructor(), js_regexp_constructor_internal(), js_regexp_exec(), js_regexp_string_iterator_next(), js_regexp_Symbol_match(), js_regexp_Symbol_matchAll(), js_regexp_Symbol_replace(), js_regexp_Symbol_search(), js_regexp_Symbol_split(), js_regexp_test(), JS_RegExpDelete(), JS_RegExpExec(), js_relational_slow(), JS_RunModule(), JS_SetGlobalVar(), JS_SetModuleExport(), JS_SetObjectData(), JS_SetPrivateField(), JS_SetPropertyGeneric(), JS_SetPropertyInt64(), JS_SetPropertyInternal(), JS_SetPropertyValue(), JS_SetPrototypeInternal(), JS_SetThisTimeValue(), js_shr_slow(), JS_SpeciesConstructor(), js_std_add_helpers(), js_std_dump_error(), js_std_dump_error1(), js_std_eval_binary(), js_std_getenviron(), js_std_urlGet(), js_strict_eq2(), js_string_charAt(), js_string_charCodeAt(), js_string_codePointAt(), js_string_CreateHTML(), js_string_includes(), js_string_indexOf(), js_string_iterator_next(), js_string_localeCompare(), js_string_match(), js_string_normalize(), js_string_pad(), js_string_raw(), js_string_repeat(), js_string_replace(), js_string_slice(), js_string_split(), js_string_substr(), js_string_substring(), js_string_toLowerCase(), js_string_trim(), js_symbol_get_description(), js_symbol_toString(), js_TA_cmp_generic(), JS_Throw(), JS_ToArrayLengthFree(), JS_ToBoolFree(), JS_ToCStringLen2(), JS_ToLengthFree(), JS_ToNumberHintFree(), JS_ToObjectFree(), JS_ToPrimitiveFree(), JS_ToQuotedString(), JS_ToQuotedStringFree(), JS_ToStringFree(), JS_ToStringInternal(), JS_ToUTF32String(), js_typed_array___speciesCreate(), js_typed_array_constructor(), js_typed_array_constructor_obj(), js_typed_array_constructor_ta(), js_typed_array_create(), js_typed_array_find(), js_typed_array_from(), js_typed_array_join(), js_typed_array_of(), js_typed_array_set_internal(), js_typed_array_slice(), js_typed_array_subarray(), js_worker_ctor(), js_worker_ctor_internal(), js_worker_set_onmessage(), JS_WriteArray(), json_parse_value(), next_token(), promise_reaction_job(), set_array_length(), set_value(), string_buffer_concat_value(), string_buffer_concat_value_free(), typed_array_init(), qjs::js_traits< std::function< R(Args...)> >::unwrap(), qjs::js_traits< std::optional< T > >::unwrap(), qjs::detail::unwrap_free(), qjs::js_traits< std::variant< Ts... > >::unwrapObj(), value_buffer_append(), value_buffer_free(), qjs::js_traits< ctor_wrapper< T, Args... > >::wrap(), and qjs::Value::~Value().
 {
     if (JS_VALUE_HAS_REF_COUNT(v)) {
         JSRefCountHeader *p = (JSRefCountHeader *)JS_VALUE_GET_PTR(v);
         if (--p->ref_count <= 0) {
             __JS_FreeValue(ctx, v);
         }
     }
 }
__JS_FreeValueRT()
void __JS_FreeValueRT (JSRuntime * rt, JSValue v)
Definition at line 5452 of file quickjs.c.
References JSString::atom_type, free_zero_refcount(), JSRuntime::gc_phase, js_free_rt(), JS_FreeAtomStruct(), JS_GC_PHASE_NONE, JS_GC_PHASE_REMOVE_CYCLES, JS_TAG_FUNCTION_BYTECODE, JS_TAG_MODULE, JS_TAG_OBJECT, JS_TAG_STRING, and JS_TAG_SYMBOL.
Referenced by __JS_FreeValue(), and JS_FreeValueRT().
 {
     uint32_t tag = JS_VALUE_GET_TAG(v);
 #ifdef DUMP_FREE
     {
         printf("Freeing ");
         if (tag == JS_TAG_OBJECT) {
             JS_DumpObject(rt, JS_VALUE_GET_OBJ(v));
         } else {
             JS_DumpValueShort(rt, v);
             printf("\n");
         }
     }
 #endif
     switch(tag) {
     case JS_TAG_STRING:
         {
             JSString *p = JS_VALUE_GET_STRING(v);
             if (p->atom_type) {
                 JS_FreeAtomStruct(rt, p);
             } else {
 #ifdef DUMP_LEAKS
                 list_del(&p->link);
 #endif
                 js_free_rt(rt, p);
             }
         }
         break;
     case JS_TAG_OBJECT:
     case JS_TAG_FUNCTION_BYTECODE:
         {
             JSGCObjectHeader *p = JS_VALUE_GET_PTR(v);
             if (rt->gc_phase != JS_GC_PHASE_REMOVE_CYCLES) {
                 list_del(&p->link);
                 list_add(&p->link, &rt->gc_zero_ref_count_list);
                 if (rt->gc_phase == JS_GC_PHASE_NONE) {
                     free_zero_refcount(rt);
                 }
             }
         }
         break;
     case JS_TAG_MODULE:
         abort(); /* never freed here */
         break;
 #ifdef CONFIG_BIGNUM
     case JS_TAG_BIG_INT:
     case JS_TAG_BIG_FLOAT:
         {
             JSBigFloat *bf = JS_VALUE_GET_PTR(v);
             bf_delete(&bf->num);
             js_free_rt(rt, bf);
         }
         break;
     case JS_TAG_BIG_DECIMAL:
         {
             JSBigDecimal *bf = JS_VALUE_GET_PTR(v);
             bfdec_delete(&bf->num);
             js_free_rt(rt, bf);
         }
         break;
 #endif
     case JS_TAG_SYMBOL:
         {
             JSAtomStruct *p = JS_VALUE_GET_PTR(v);
             JS_FreeAtomStruct(rt, p);
         }
         break;
     default:
         printf("__JS_FreeValue: unknown tag=%d\n", tag);
         abort();
     }
 }
JS_FreeValueRT()
static void JS_FreeValueRT (JSRuntime * rt, JSValue v) inline static
Definition at line 650 of file quickjs.h.
References __JS_FreeValueRT(), and JSRefCountHeader::ref_count.
Referenced by async_func_free(), free_function_bytecode(), free_property(), free_rw_handler(), free_sh(), free_timer(), free_var_ref(), js_array_finalizer(), js_array_iterator_finalizer(), js_async_function_free0(), js_async_generator_free(), js_bound_function_finalizer(), js_bytecode_function_finalizer(), js_for_in_iterator_finalizer(), js_free_port(), js_free_shape0(), JS_FreeRuntime(), js_map_finalizer(), js_map_iterator_finalizer(), js_object_data_finalizer(), js_promise_resolve_function_finalizer(), js_regexp_finalizer(), js_regexp_string_iterator_finalizer(), js_typed_array_finalizer(), map_delete_record(), promise_reaction_data_free(), and reset_weak_ref().
 {
     if (JS_VALUE_HAS_REF_COUNT(v)) {
         JSRefCountHeader *p = (JSRefCountHeader *)JS_VALUE_GET_PTR(v);
         if (--p->ref_count <= 0) {
             __JS_FreeValueRT(rt, v);
         }
     }
 }
JS_DupValue()
static JSValue JS_DupValue (JSContext * ctx, JSValueConst v) inline static
Definition at line 660 of file quickjs.h.
References JSRefCountHeader::ref_count.
Referenced by __JS_AtomToValue(), __JS_EvalInternal(), async_func_init(), build_arg_list(), call_handler(), call_setter(), close_lexical_var(), emit_push_const(), handle_posted_message(), JS_AddBrand(), JS_AddIntrinsicBaseObjects(), JS_AddIntrinsicBasicObjects(), JS_AddIntrinsicPromise(), JS_AddIntrinsicRegExp(), js_aggregate_error_constructor(), js_append_enumerate(), js_array_concat(), js_array_constructor(), js_array_every(), js_array_fill(), js_array_from(), js_array_includes(), js_array_indexOf(), js_array_lastIndexOf(), js_array_of(), js_array_push(), js_array_reduce(), js_array_slice(), js_async_from_sync_iterator_next(), js_async_from_sync_iterator_unwrap(), js_async_function_resolve_call(), js_async_generator_next(), js_async_generator_resolve(), js_async_generator_resolve_function(), js_async_generator_resume_next(), js_atomics_store(), js_build_arguments(), js_build_mapped_arguments(), js_build_rest(), JS_CallInternal(), js_clone_shape(), js_create_array(), js_create_desc(), js_create_from_ctor(), js_create_map_iterator(), js_create_resolving_functions(), JS_CreateAsyncFromSyncIterator(), JS_CreateProperty(), js_dataview_constructor(), JS_DefineProperty(), JS_EnqueueJob(), js_error_constructor(), JS_EvalObject(), js_evaluate_module(), js_function_bind(), js_get_module_ns(), js_get_this(), JS_GetClassProto(), JS_GetGlobalObject(), JS_GetGlobalVar(), JS_GetGlobalVarRef(), JS_GetImportMeta(), JS_GetOwnPropertyInternal(), JS_GetPrivateField(), JS_GetPropertyInternal(), JS_GetPropertyValue(), JS_GetPrototype(), JS_GetTypedArrayBuffer(), JS_HasProperty(), js_instantiate_prototype(), js_iterator_proto_iterator(), js_json_to_str(), JS_JSONStringify(), js_map_get(), js_map_iterator_next(), js_map_set(), js_method_set_home_object(), js_new_promise_capability(), js_new_shape2(), JS_NewCFunctionData(), JS_NewGlobalCConstructor2(), JS_NewSymbolFromAtom(), js_object___lookupGetter__(), js_object_defineProperties(), js_object_defineProperty(), js_object_getOwnPropertyDescriptor(), js_object_isPrototypeOf(), js_object_preventExtensions(), js_object_seal(), js_object_setPrototypeOf(), js_op_define_class(), JS_OrdinaryIsInstanceOf(), js_os_setReadHandler(), js_os_setTimeout(), js_os_signal(), js_parse_template(), js_promise_all(), js_promise_all_resolve_element(), js_promise_executor(), js_promise_finally(), js_promise_finally_thrower(), js_promise_finally_value_thunk(), js_promise_resolve(), js_proxy_constructor(), js_proxy_set(), JS_ReadModule(), JS_ReadObjectRec(), js_reflect_set(), js_regexp_compile(), js_regexp_constructor(), js_regexp_exec(), js_regexp_Symbol_replace(), JS_RunModule(), js_same_value(), js_same_value_zero(), JS_SetConstructor2(), JS_SetPropertyGeneric(), JS_SetPropertyInternal(), JS_SetPrototypeInternal(), JS_SetThisTimeValue(), JS_SpeciesConstructor(), js_string_concat(), js_sub_string(), js_symbol_keyFor(), js_thisBooleanValue(), js_thisNumberValue(), js_thisStringValue(), js_thisSymbolValue(), JS_ToBool(), JS_ToCStringLen2(), JS_ToFloat64(), JS_ToInt32(), JS_ToInt32Clamp(), JS_ToInt32Sat(), JS_ToInt64(), JS_ToInt64Clamp(), JS_ToInt64Sat(), JS_ToNumber(), JS_ToNumeric(), JS_ToObject(), JS_ToPrimitive(), JS_ToStringInternal(), js_typed_array_constructor(), js_typed_array_constructor_obj(), js_typed_array_copyWithin(), js_typed_array_create(), js_typed_array_fill(), js_typed_array_from(), js_typed_array_get_buffer(), js_typed_array_of(), js_typed_array_reverse(), js_typed_array_sort(), js_worker_get_onmessage(), js_worker_set_onmessage(), json_parse_value(), map_add_record(), qjs::Context::Module::Module(), perform_promise_then(), promise_reaction_job(), qjs::js_traits< JSValue >::unwrap(), qjs::js_traits< Value >::unwrap(), qjs::js_traits< std::vector< T > >::unwrap(), qjs::js_traits< std::pair< U, V > >::unwrap(), and qjs::Value::Value().
 {
     if (JS_VALUE_HAS_REF_COUNT(v)) {
         JSRefCountHeader *p = (JSRefCountHeader *)JS_VALUE_GET_PTR(v);
         p->ref_count++;
     }
     return (JSValue)v;
 }
JS_DupValueRT()
static JSValue JS_DupValueRT (JSRuntime * rt, JSValueConst v) inline static
Definition at line 669 of file quickjs.h.
References JSRefCountHeader::ref_count.
Referenced by close_var_refs().
 {
     if (JS_VALUE_HAS_REF_COUNT(v)) {
         JSRefCountHeader *p = (JSRefCountHeader *)JS_VALUE_GET_PTR(v);
         p->ref_count++;
     }
     return (JSValue)v;
 }
JS_ToBool()
int JS_ToBool (JSContext * ctx, JSValueConst val)
Definition at line 9931 of file quickjs.c.
References JS_DupValue(), and JS_ToBoolFree().
Referenced by get_bool_option(), js_async_from_sync_iterator_unwrap(), js_boolean_constructor(), js_dataview_getValue(), js_dataview_setValue(), js_promise_all_resolve_element(), and promise_reaction_job().
 {
     return JS_ToBoolFree(ctx, JS_DupValue(ctx, val));
 }
JS_ToInt32()
int JS_ToInt32 (JSContext * ctx, int32_t * pres, JSValueConst val)
Definition at line 10878 of file quickjs.c.
References JS_DupValue(), and JS_ToInt32Free().
Referenced by js_atomics_wait(), js_math_imul(), js_os_close(), js_os_dup(), js_os_dup2(), js_os_exec(), js_os_isatty(), js_os_kill(), js_os_mkdir(), js_os_open(), js_os_read_write(), js_os_seek(), js_os_setReadHandler(), js_os_ttyGetWinSize(), js_os_ttySetRaw(), js_os_waitpid(), js_parseInt(), js_printf_internal(), js_promise_all_resolve_element(), js_std_exit(), js_std_fdopen(), js_std_file_putByte(), js_std_file_seek(), js_std_strerror(), js_string_fromCharCode(), and JS_ToUint32().
 {
     return JS_ToInt32Free(ctx, pres, JS_DupValue(ctx, val));
 }
JS_ToUint32()
static int JS_ToUint32 (JSContext * ctx, uint32_t * pres, JSValueConst val) inline static
Definition at line 680 of file quickjs.h.
References JS_ToInt32().
Referenced by js_atomics_op(), js_atomics_store(), JS_CreateProperty(), js_dataview_setValue(), js_math_clz32(), js_os_exec(), js_os_signal(), js_regexp_Symbol_split(), js_string___GetSubstitution(), js_string_codePointRange(), js_string_split(), JS_ToArrayLengthFree(), js_typed_array_fill(), and set_array_length().
 {
     return JS_ToInt32(ctx, (int32_t*)pres, val);
 }
JS_ToInt64()
int JS_ToInt64 (JSContext * ctx, int64_t * pres, JSValueConst val)
Definition at line 10803 of file quickjs.c.
References JS_DupValue(), and JS_ToInt64Free().
Referenced by js_os_setTimeout(), js_os_sleep(), js_os_utimes(), and JS_ToInt64Ext().
 {
     return JS_ToInt64Free(ctx, pres, JS_DupValue(ctx, val));
 }
JS_ToIndex()
int JS_ToIndex (JSContext * ctx, uint64_t * plen, JSValueConst val)
Definition at line 11033 of file quickjs.c.
References JS_ToInt64Sat().
Referenced by js_array_buffer_constructor(), js_atomics_get_ptr(), js_dataview_constructor(), js_dataview_getValue(), js_dataview_setValue(), js_os_read_write(), js_shared_array_buffer_constructor(), js_std_file_read_write(), js_std_file_readAsString(), and js_typed_array_constructor().
 {
     int64_t v;
     if (JS_ToInt64Sat(ctx, &v, val))
         return -1;
     if (v < 0 || v > MAX_SAFE_INTEGER) {
         JS_ThrowRangeError(ctx, "invalid array index");
         *plen = 0;
         return -1;
     }
     *plen = v;
     return 0;
 }
JS_ToFloat64()
int JS_ToFloat64 (JSContext * ctx, double * pres, JSValueConst val)
Definition at line 10521 of file quickjs.c.
References JS_DupValue(), and JS_ToFloat64Free().
Referenced by __attribute(), js_atomics_wait(), js_call_c_function(), js_dataview_setValue(), js_date_constructor(), js_date_setTime(), js_date_setYear(), js_date_toJSON(), js_Date_UTC(), js_global_isFinite(), js_global_isNaN(), js_math_hypot(), js_math_min_max(), js_number_isSafeInteger(), JS_NumberIsInteger(), js_printf_internal(), js_string_fromCodePoint(), js_string_indexOf(), JS_ThisTimeValue(), js_typed_array_fill(), js_typed_array_indexOf(), set_date_field(), and qjs::js_traits< double >::unwrap().
 {
     return JS_ToFloat64Free(ctx, pres, JS_DupValue(ctx, val));
 }
JS_ToBigInt64()
int JS_ToBigInt64 (JSContext * ctx, int64_t * pres, JSValueConst val)
Definition at line 14142 of file quickjs.c.
References JS_ThrowUnsupportedBigint().
Referenced by JS_ToInt64Ext().
 {
     JS_ThrowUnsupportedBigint(ctx);
     *pres = 0;
     return -1;
 }
JS_ToInt64Ext()
int JS_ToInt64Ext (JSContext * ctx, int64_t * pres, JSValueConst val)
Definition at line 10808 of file quickjs.c.
References JS_IsBigInt(), JS_ToBigInt64(), and JS_ToInt64().
Referenced by js_os_seek(), js_printf_internal(), and js_std_file_seek().
 {
     if (JS_IsBigInt(ctx, val))
         return JS_ToBigInt64(ctx, pres, val);
     else
         return JS_ToInt64(ctx, pres, val);
 }
JS_NewStringLen()
JSValue JS_NewStringLen (JSContext * ctx, const char * str1, size_t len1)
Definition at line 3843 of file quickjs.c.
References __attribute__(), js_new_string8(), string_buffer_end(), string_buffer_free(), string_buffer_init(), string_buffer_putc16(), string_buffer_putc8(), string_buffer_write8(), and unicode_from_utf8().
Referenced by get_date_string(), js_function_toString(), JS_JSONStringify(), JS_NewAtomLen(), JS_NewString(), js_printf_internal(), js_regexp_get_flags(), js_std_file_getline(), js_std_file_readAsString(), js_std_loadFile(), js_std_urlGet(), qjs::js_traits< std::string_view >::wrap(), and qjs::js_traits< std::string >::wrap().
 {
     const uint8_t *p, *p_end, *p_start, *p_next;
     uint32_t c;
     StringBuffer b_s, *b = &b_s;
     size_t len1;
     p_start = (const uint8_t *)buf;
     p_end = p_start + buf_len;
     p = p_start;
     while (p < p_end && *p < 128)
         p++;
     len1 = p - p_start;
     if (len1 > JS_STRING_LEN_MAX)
         return JS_ThrowInternalError(ctx, "string too long");
     if (p == p_end) {
         /* ASCII string */
         return js_new_string8(ctx, (const uint8_t *)buf, buf_len);
     } else {
         if (string_buffer_init(ctx, b, buf_len))
             goto fail;
         string_buffer_write8(b, p_start, len1);
         while (p < p_end) {
             if (*p < 128) {
                 string_buffer_putc8(b, *p++);
             } else {
                 /* parse utf-8 sequence, return 0xFFFFFFFF for error */
                 c = unicode_from_utf8(p, p_end - p, &p_next);
                 if (c < 0x10000) {
                     p = p_next;
                 } else if (c <= 0x10FFFF) {
                     p = p_next;
                     /* surrogate pair */
                     c -= 0x10000;
                     string_buffer_putc16(b, (c >> 10) + 0xd800);
                     c = (c & 0x3ff) + 0xdc00;
                 } else {
                     /* invalid char */
                     c = 0xfffd;
                     /* skip the invalid chars */
                     /* XXX: seems incorrect. Why not just use c = *p++; ? */
                     while (p < p_end && (*p >= 0x80 && *p < 0xc0))
                         p++;
                     if (p < p_end) {
                         p++;
                         while (p < p_end && (*p >= 0x80 && *p < 0xc0))
                             p++;
                     }
                 }
                 string_buffer_putc16(b, c);
             }
         }
     }
     return string_buffer_end(b);
  fail:
     string_buffer_free(b);
     return JS_EXCEPTION;
 }
JS_NewString()
JSValue JS_NewString (JSContext * ctx, const char * str)
Definition at line 3934 of file quickjs.c.
References JS_NewStringLen().
Referenced by __JS_AtomToValue(), build_backtrace(), get_date_string(), js_dtoa(), js_json_to_str(), js_module_set_import_meta(), JS_NewAtomInt64(), JS_NewAtomUInt32(), js_object_toString(), js_os_readdir(), js_promise_all_resolve_element(), js_regexp_get_source(), JS_SetModuleExportList(), js_std_add_helpers(), js_std_getenv(), js_std_getenviron(), js_std_strerror(), js_string_match(), JS_ThrowError2(), JS_ToStringInternal(), make_string_error(), and qjs::js_traits< const char * >::wrap().
 {
     return JS_NewStringLen(ctx, str, strlen(str));
 }
JS_NewAtomString()
JSValue JS_NewAtomString (JSContext * ctx, const char * str)
Definition at line 3939 of file quickjs.c.
References JS_AtomToString(), JS_FreeAtom(), and JS_NewAtom().
Referenced by JS_AddIntrinsicBasicObjects().
 {
     JSAtom atom = JS_NewAtom(ctx, str);
     if (atom == JS_ATOM_NULL)
         return JS_EXCEPTION;
     JSValue val = JS_AtomToString(ctx, atom);
     JS_FreeAtom(ctx, atom);
     return val;
 }
JS_ToString()
JSValue JS_ToString (JSContext * ctx, JSValueConst val)
Definition at line 11557 of file quickjs.c.
References FALSE, and JS_ToStringInternal().
Referenced by js_array_cmp_generic(), js_array_join(), JS_AtomIsNumericIndex1(), js_Date_parse(), js_error_constructor(), js_global_decodeURI(), js_global_encodeURI(), js_global_escape(), js_global_unescape(), js_regexp_compile(), js_regexp_constructor(), js_regexp_exec(), js_regexp_Symbol_match(), js_regexp_Symbol_matchAll(), js_regexp_Symbol_replace(), js_regexp_Symbol_search(), js_regexp_Symbol_split(), JS_RegExpDelete(), js_string_constructor(), js_string_includes(), js_string_indexOf(), js_string_localeCompare(), js_string_match(), js_string_pad(), js_string_replace(), js_string_split(), js_symbol_constructor(), js_symbol_for(), JS_ToCStringLen2(), JS_ToStringCheckObject(), JS_ToStringFree(), JS_ToUTF32String(), js_typed_array_join(), and string_buffer_concat_value().
 {
     return JS_ToStringInternal(ctx, val, FALSE);
 }
JS_ToPropertyKey()
JSValue JS_ToPropertyKey (JSContext * ctx, JSValueConst val)
Definition at line 11577 of file quickjs.c.
References JS_ToStringInternal(), and TRUE.
Referenced by JS_CallInternal(), and JS_ValueToAtom().
 {
     return JS_ToStringInternal(ctx, val, TRUE);
 }
JS_ToCStringLen2()
const char* JS_ToCStringLen2 (JSContext * ctx, size_t * plen, JSValueConst val1, JS_BOOL cesu8)
JS_ToCStringLen()
static const char* JS_ToCStringLen (JSContext * ctx, size_t * plen, JSValueConst val1) inline static
Definition at line 698 of file quickjs.h.
References JS_ToCStringLen2().
Referenced by js_atom_concat_str(), js_compile_regexp(), JS_EvalObject(), js_evalScript(), js_json_parse(), js_print(), js_printf_internal(), js_std_file_puts(), js_std_parseExtJSON(), js_string_normalize(), JS_ToNumberHintFree(), and qjs::js_traits< std::string_view >::unwrap().
 {
     return JS_ToCStringLen2(ctx, plen, val1, 0);
 }
JS_ToCString()
static const char* JS_ToCString (JSContext * ctx, JSValueConst val1) inline static
Definition at line 702 of file quickjs.h.
References JS_ToCStringLen2().
Referenced by __attribute(), build_envp(), get_func_name(), JS_AtomToCString(), js_dump_obj(), js_dynamic_import_job(), js_loadScript(), js_os_chdir(), js_os_exec(), js_os_mkdir(), js_os_open(), js_os_readdir(), js_os_readlink(), js_os_realpath(), js_os_remove(), js_os_rename(), js_os_stat(), js_os_symlink(), js_os_utimes(), js_parseFloat(), js_parseInt(), js_printf_internal(), js_std_fdopen(), js_std_getenv(), js_std_loadFile(), js_std_open(), js_std_popen(), js_std_setenv(), js_std_unsetenv(), js_std_urlGet(), and js_worker_ctor().
 {
     return JS_ToCStringLen2(ctx, NULL, val1, 0);
 }
JS_FreeCString()
void JS_FreeCString (JSContext * ctx, const char * ptr)
Definition at line 4049 of file quickjs.c.
References JS_FreeValue(), and JS_TAG_STRING.
Referenced by __attribute(), build_backtrace(), build_envp(), js_atom_concat_str(), js_compile_regexp(), js_dump_obj(), js_dynamic_import_job(), JS_EvalObject(), js_evalScript(), js_host_resolve_imported_module_atom(), js_json_parse(), js_loadScript(), js_module_set_import_meta(), js_os_chdir(), js_os_exec(), js_os_mkdir(), js_os_open(), js_os_readdir(), js_os_readlink(), js_os_realpath(), js_os_remove(), js_os_rename(), js_os_stat(), js_os_symlink(), js_os_utimes(), js_parseFloat(), js_parseInt(), js_print(), js_printf_internal(), js_std_fdopen(), js_std_file_puts(), js_std_getenv(), js_std_loadFile(), js_std_open(), js_std_parseExtJSON(), js_std_popen(), js_std_setenv(), js_std_unsetenv(), js_std_urlGet(), js_string_normalize(), JS_ToNumberHintFree(), js_worker_ctor(), and qjs::detail::js_string::~js_string().
 {
     JSString *p;
     if (!ptr)
         return;
     /* purposely removing constness */
     p = (JSString *)(void *)(ptr - offsetof(JSString, u));
     JS_FreeValue(ctx, JS_MKPTR(JS_TAG_STRING, p));
 }
JS_NewObjectProtoClass()
JSValue JS_NewObjectProtoClass (JSContext * ctx, JSValueConst proto, JSClassID class_id)
Definition at line 4815 of file quickjs.c.
References find_hashed_shape_proto(), get_proto_obj(), js_dup_shape(), js_new_shape(), JS_NewObjectFromShape(), and JSContext::rt.
Referenced by build_for_in_iterator(), JS_AddIntrinsicBaseObjects(), JS_AddIntrinsicBasicObjects(), js_aggregate_error_constructor(), js_async_function_resolve_create(), js_build_arguments(), js_build_mapped_arguments(), js_create_from_ctor(), js_create_module_bytecode_function(), js_create_resolving_functions(), js_error_constructor(), js_function_bind(), JS_NewCFunction3(), JS_NewCFunctionData(), JS_NewObject(), JS_NewObjectClass(), JS_NewObjectProto(), js_op_define_class(), js_proxy_constructor(), JS_ReadDate(), JS_ThrowError2(), and js_worker_ctor_internal().
 {
     JSShape *sh;
     JSObject *proto;
     proto = get_proto_obj(proto_val);
     sh = find_hashed_shape_proto(ctx->rt, proto);
     if (likely(sh)) {
         sh = js_dup_shape(sh);
     } else {
         sh = js_new_shape(ctx, proto);
         if (!sh)
             return JS_EXCEPTION;
     }
     return JS_NewObjectFromShape(ctx, sh, class_id);
 }
JS_NewObjectClass()
JSValue JS_NewObjectClass (JSContext * ctx, int class_id)
Definition at line 4886 of file quickjs.c.
References JSContext::class_proto, and JS_NewObjectProtoClass().
Referenced by js_build_module_ns(), js_closure(), js_create_array_iterator(), js_create_map_iterator(), JS_CreateAsyncFromSyncIterator(), js_new_std_file(), JS_NewError(), js_os_setTimeout(), js_regexp_Symbol_matchAll(), JS_ToObject(), qjs::js_traits< std::shared_ptr< T > >::wrap(), and qjs::js_traits< std::function< R(Args...)> >::wrap().
 {
     return JS_NewObjectProtoClass(ctx, ctx->class_proto[class_id], class_id);
 }
JS_NewObjectProto()
JSValue JS_NewObjectProto (JSContext * ctx, JSValueConst proto)
Definition at line 4891 of file quickjs.c.
References JS_CLASS_OBJECT, and JS_NewObjectProtoClass().
Referenced by JS_AddIntrinsicBaseObjects(), JS_AddIntrinsicBasicObjects(), JS_AddIntrinsicMapSet(), JS_AddIntrinsicPromise(), JS_AddIntrinsicRegExp(), JS_AddIntrinsicTypedArrays(), JS_CallInternal(), js_closure(), JS_GetImportMeta(), js_object_create(), js_op_define_class(), and js_regexp_exec().
 {
     return JS_NewObjectProtoClass(ctx, proto, JS_CLASS_OBJECT);
 }
JS_NewObject()
JSValue JS_NewObject (JSContext * ctx)
Definition at line 4902 of file quickjs.c.
References JSContext::class_proto, JS_CLASS_OBJECT, and JS_NewObjectProtoClass().
Referenced by handle_posted_message(), JS_AddIntrinsicBaseObjects(), JS_AddIntrinsicBasicObjects(), JS_AddIntrinsicDate(), JS_AddIntrinsicMapSet(), JS_AddIntrinsicPromise(), JS_AddIntrinsicRegExp(), JS_AddIntrinsicTypedArrays(), JS_CallInternal(), js_create_desc(), js_create_iterator_result(), js_instantiate_prototype(), js_json_parse(), JS_JSONStringify(), js_object_constructor(), js_object_fromEntries(), js_object_getOwnPropertyDescriptor(), js_object_getOwnPropertyDescriptors(), js_os_init(), js_os_stat(), js_promise_all_resolve_element(), js_proxy_revocable(), JS_ReadObjectTag(), JS_SetModuleExportList(), js_std_add_helpers(), js_std_getenviron(), js_std_init(), js_std_urlGet(), json_parse_value(), and qjs::Context::newObject().
 {
     /* inline JS_NewObjectClass(ctx, JS_CLASS_OBJECT); */
     return JS_NewObjectProtoClass(ctx, ctx->class_proto[JS_CLASS_OBJECT], JS_CLASS_OBJECT);
 }
JS_IsFunction()
JS_BOOL JS_IsFunction (JSContext * ctx, JSValueConst val)
Definition at line 9660 of file quickjs.c.
References JSClass::call, JSRuntime::class_array, FALSE, JSProxyData::is_func, JS_CLASS_BYTECODE_FUNCTION, JS_CLASS_PROXY, JS_TAG_OBJECT, JSContext::rt, and TRUE.
Referenced by check_function(), js_array_toString(), JS_CreateProperty(), js_date_toJSON(), JS_DefineProperty(), JS_GetIterator(), JS_IsInstanceOf(), js_json_check(), js_json_parse(), JS_JSONStringify(), js_map_constructor(), js_obj_to_desc(), js_object___getClass(), js_object_toString(), js_operator_typeof(), JS_OrdinaryIsInstanceOf(), js_os_setReadHandler(), js_os_setTimeout(), js_os_signal(), js_promise_finally(), js_promise_resolve_function_call(), js_proxy_constructor(), js_regexp_Symbol_replace(), JS_RegExpExec(), js_string_replace(), JS_ToPrimitiveFree(), js_worker_set_onmessage(), and perform_promise_then().
 {
     JSObject *p;
     if (JS_VALUE_GET_TAG(val) != JS_TAG_OBJECT)
         return FALSE;
     p = JS_VALUE_GET_OBJ(val);
     switch(p->class_id) {
     case JS_CLASS_BYTECODE_FUNCTION:
         return TRUE;
     case JS_CLASS_PROXY:
         return p->u.proxy_data->is_func;
     default:
         return (ctx->rt->class_array[p->class_id].call != NULL);
     }
 }
JS_IsConstructor()
JS_BOOL JS_IsConstructor (JSContext * ctx, JSValueConst val)
Definition at line 9688 of file quickjs.c.
References FALSE, and JS_TAG_OBJECT.
Referenced by js_array_from(), js_array_of(), JS_ArraySpeciesCreate(), js_function_bind(), js_op_define_class(), js_proxy_call_constructor(), js_proxy_constructor(), js_reflect_construct(), and JS_SpeciesConstructor().
 {
     JSObject *p;
     if (JS_VALUE_GET_TAG(val) != JS_TAG_OBJECT)
         return FALSE;
     p = JS_VALUE_GET_OBJ(val);
     return p->is_constructor;
 }
JS_SetConstructorBit()
JS_BOOL JS_SetConstructorBit (JSContext * ctx, JSValueConst func_obj, JS_BOOL val)
JS_NewArray()
JSValue JS_NewArray (JSContext * ctx)
Definition at line 4896 of file quickjs.c.
References JSContext::array_shape, JS_CLASS_ARRAY, js_dup_shape(), and JS_NewObjectFromShape().
Referenced by iterator_to_array(), js_array_every(), js_array_from(), js_array_from_iterator(), js_array_of(), js_build_rest(), JS_CallInternal(), js_create_array(), JS_GetOwnPropertyNames2(), JS_JSONStringify(), js_os_pipe(), js_os_readdir(), js_os_ttyGetWinSize(), js_os_waitpid(), js_parse_template(), js_promise_all(), JS_ReadArray(), js_regexp_exec(), js_regexp_Symbol_match(), js_regexp_Symbol_replace(), js_regexp_Symbol_split(), js_std_add_helpers(), js_string_split(), js_typed_array_from(), json_parse_value(), make_obj_error(), qjs::js_traits< std::vector< T > >::wrap(), and qjs::js_traits< std::pair< U, V > >::wrap().
 {
     return JS_NewObjectFromShape(ctx, js_dup_shape(ctx->array_shape),
                                  JS_CLASS_ARRAY);
 }
JS_IsArray()
int JS_IsArray (JSContext * ctx, JSValueConst val)
Definition at line 11923 of file quickjs.c.
References FALSE, JS_CLASS_ARRAY, JS_CLASS_PROXY, js_proxy_isArray(), and JS_TAG_OBJECT.
Referenced by internalize_json_property(), qjs::js_traits< std::variant< Ts... > >::isCompatible(), js_array_isArray(), JS_ArraySpeciesCreate(), JS_FlattenIntoArray(), JS_isConcatSpreadable(), js_json_to_str(), JS_JSONStringify(), js_object_toString(), qjs::js_traits< std::vector< T > >::unwrap(), qjs::js_traits< std::pair< U, V > >::unwrap(), and qjs::js_traits< std::variant< Ts... > >::unwrapObj().
 {
     JSObject *p;
     if (JS_VALUE_GET_TAG(val) == JS_TAG_OBJECT) {
         p = JS_VALUE_GET_OBJ(val);
         if (unlikely(p->class_id == JS_CLASS_PROXY))
             return js_proxy_isArray(ctx, val);
         else
             return p->class_id == JS_CLASS_ARRAY;
     } else {
         return FALSE;
     }
 }
JS_GetPropertyInternal()
JSValue JS_GetPropertyInternal (JSContext * ctx, JSValueConst obj, JSAtom prop, JSValueConst receiver, JS_BOOL throw_ref_error)
JS_GetProperty()
static js_force_inline JSValue JS_GetProperty (JSContext * ctx, JSValueConst this_obj, JSAtom prop) static
Definition at line 723 of file quickjs.h.
References JS_GetPropertyInternal().
Referenced by build_envp(), check_regexp_g_flag(), internalize_json_property(), iterator_to_array(), JS_AddIntrinsicBaseObjects(), JS_AddIntrinsicTypedArrays(), js_append_enumerate(), js_array_from(), js_array_from_iterator(), js_array_toString(), JS_ArraySpeciesCreate(), js_async_from_sync_iterator_next(), JS_CallInternal(), JS_CopyDataProperties(), js_create_from_ctor(), JS_CreateAsyncFromSyncIterator(), js_error_constructor(), js_error_toString(), js_for_of_start(), js_function_bind(), js_function_constructor(), js_function_toString(), js_get_length32(), js_get_length64(), JS_GetIterator(), JS_GetOwnPropertyNames2(), JS_GetPropertyInt64(), JS_GetPropertyStr(), JS_GetPropertyValue(), js_has_unscopable(), JS_InstantiateFunctionListItem(), JS_Invoke(), js_is_regexp(), js_is_standard_regexp(), JS_isConcatSpreadable(), JS_IsInstanceOf(), JS_IteratorClose(), JS_IteratorGetCompleteValue(), JS_IteratorNext(), js_json_check(), js_map_constructor(), js_obj_to_desc(), js_object_fromEntries(), js_object_toString(), JS_ObjectDefineProperties(), js_op_define_class(), JS_OrdinaryIsInstanceOf(), js_promise_all(), js_promise_race(), js_promise_resolve(), js_promise_resolve_function_call(), js_regexp_constructor(), js_regexp_exec(), js_regexp_get_flags(), js_regexp_string_iterator_next(), js_regexp_Symbol_match(), js_regexp_Symbol_matchAll(), js_regexp_Symbol_replace(), js_regexp_Symbol_search(), js_regexp_Symbol_split(), js_regexp_toString(), JS_RegExpDelete(), JS_RegExpExec(), JS_SpeciesConstructor(), js_string_match(), js_string_raw(), js_string_replace(), js_string_split(), JS_ToPrimitiveFree(), JS_TryGetPropertyInt64(), js_typed_array_constructor_obj(), js_typed_array_from(), and JS_WriteArray().
 {
     return JS_GetPropertyInternal(ctx, this_obj, prop, this_obj, 0);
 }
JS_GetPropertyStr()
JSValue JS_GetPropertyStr (JSContext * ctx, JSValueConst this_obj, const char * prop)
Definition at line 7942 of file quickjs.c.
References JS_FreeAtom(), JS_GetProperty(), and JS_NewAtom().
Referenced by get_bool_option(), qjs::js_property_traits< const char * >::get_property(), js_date_toJSON(), js_os_exec(), js_regexp_get_flags(), js_std_dump_error1(), js_worker_ctor_internal(), and qjs::js_traits< ctor_wrapper< T, Args... > >::wrap().
 {
     JSAtom atom;
     JSValue ret;
     atom = JS_NewAtom(ctx, prop);
     ret = JS_GetProperty(ctx, this_obj, atom);
     JS_FreeAtom(ctx, atom);
     return ret;
 }
JS_GetPropertyUint32()
JSValue JS_GetPropertyUint32 (JSContext * ctx, JSValueConst this_obj, uint32_t idx)
Definition at line 7882 of file quickjs.c.
References JS_GetPropertyValue(), and JS_NewUint32().
Referenced by build_arg_list(), qjs::js_property_traits< uint32_t >::get_property(), js_array_iterator_next(), js_array_join(), JS_GetOwnPropertyInternal(), JS_GetPropertyInternal(), js_map_constructor(), js_object_fromEntries(), js_os_exec(), js_proxy_get_own_property_names(), js_typed_array_constructor_obj(), js_typed_array_constructor_ta(), js_typed_array_join(), js_typed_array_set_internal(), JS_WriteArray(), remainingElementsCount_add(), and qjs::js_traits< std::variant< Ts... > >::unwrapObj().
 {
     return JS_GetPropertyValue(ctx, this_obj, JS_NewUint32(ctx, idx));
 }
JS_SetPropertyInternal()
int JS_SetPropertyInternal (JSContext * ctx, JSValueConst this_obj, JSAtom prop, JSValue val, int flags)
Definition at line 8377 of file quickjs.c.
References __attribute__(), __JS_AtomIsTaggedInt(), __JS_AtomToUInt32(), add_fast_array_element(), add_property(), call_setter(), JSRuntime::class_array, JSClass::exotic, find_own_property(), JSPropertyDescriptor::flags, JSShapeProperty::flags, JSClassExoticMethods::get_own_property, JSPropertyDescriptor::getter, JS_AtomIsNumericIndex(), JS_AutoInitProperty(), JS_CLASS_ARRAY, JS_CLASS_FLOAT64_ARRAY, JS_CLASS_MODULE_NS, JS_CLASS_UINT8C_ARRAY, JS_CreateProperty(), JS_DefineProperty(), JS_DupValue(), JS_FreeValue(), JS_GetPrototypePrimitive(), JS_IsException(), JS_IsUndefined(), JS_NewInt32(), JS_SetPropertyValue(), JS_TAG_NULL, JS_TAG_OBJECT, JS_TAG_UNDEFINED, JS_ThrowReferenceErrorNotDefined(), JS_ThrowTypeErrorReadOnly(), JS_ToNumberFree(), JSShape::proto, JSVarRef::pvalue, JSContext::rt, set_array_length(), JSClassExoticMethods::set_property, set_value(), JSPropertyDescriptor::setter, JSObject::shape, TRUE, and JSPropertyDescriptor::value.
Referenced by build_for_in_iterator(), JS_CallInternal(), JS_SetGlobalVar(), JS_SetProperty(), JS_SetPropertyStr(), and JS_SetPropertyValue().
 {
     JSObject *p, *p1;
     JSShapeProperty *prs;
     JSProperty *pr;
     uint32_t tag;
     JSPropertyDescriptor desc;
     int ret;
 #if 0
     printf("JS_SetPropertyInternal: "); print_atom(ctx, prop); printf("\n");
 #endif
     tag = JS_VALUE_GET_TAG(this_obj);
     if (unlikely(tag != JS_TAG_OBJECT)) {
         switch(tag) {
         case JS_TAG_NULL:
             JS_FreeValue(ctx, val);
             JS_ThrowTypeErrorAtom(ctx, "cannot set property '%s' of null", prop);
             return -1;
         case JS_TAG_UNDEFINED:
             JS_FreeValue(ctx, val);
             JS_ThrowTypeErrorAtom(ctx, "cannot set property '%s' of undefined", prop);
             return -1;
         default:
             /* even on a primitive type we can have setters on the prototype */
             p = NULL;
             p1 = JS_VALUE_GET_OBJ(JS_GetPrototypePrimitive(ctx, this_obj));
             goto prototype_lookup;
         }
     }
     p = JS_VALUE_GET_OBJ(this_obj);
 retry:
     prs = find_own_property(&pr, p, prop);
     if (prs) {
         if (likely((prs->flags & (JS_PROP_TMASK | JS_PROP_WRITABLE |
                                   JS_PROP_LENGTH)) == JS_PROP_WRITABLE)) {
             /* fast case */
             set_value(ctx, &pr->u.value, val);
             return TRUE;
         } else if (prs->flags & JS_PROP_LENGTH) {
             assert(p->class_id == JS_CLASS_ARRAY);
             assert(prop == JS_ATOM_length);
             return set_array_length(ctx, p, val, flags);
         } else if ((prs->flags & JS_PROP_TMASK) == JS_PROP_GETSET) {
             return call_setter(ctx, pr->u.getset.setter, this_obj, val, flags);
         } else if ((prs->flags & JS_PROP_TMASK) == JS_PROP_VARREF) {
             /* JS_PROP_WRITABLE is always true for variable
                references, but they are write protected in module name
                spaces. */
             if (p->class_id == JS_CLASS_MODULE_NS)
                 goto read_only_prop;
             set_value(ctx, pr->u.var_ref->pvalue, val);
             return TRUE;
         } else if ((prs->flags & JS_PROP_TMASK) == JS_PROP_AUTOINIT) {
             /* Instantiate property and retry (potentially useless) */
             if (JS_AutoInitProperty(ctx, p, prop, pr, prs)) {
                 JS_FreeValue(ctx, val);
                 return -1;
             }
             goto retry;
         } else {
             goto read_only_prop;
         }
     }
     p1 = p;
     for(;;) {
         if (p1->is_exotic) {
             if (p1->fast_array) {
                 if (__JS_AtomIsTaggedInt(prop)) {
                     uint32_t idx = __JS_AtomToUInt32(prop);
                     if (idx < p1->u.array.count) {
                         if (unlikely(p == p1))
                             return JS_SetPropertyValue(ctx, this_obj, JS_NewInt32(ctx, idx), val, flags);
                         else
                             break;
                     } else if (p1->class_id >= JS_CLASS_UINT8C_ARRAY &&
                                p1->class_id <= JS_CLASS_FLOAT64_ARRAY) {
                         goto typed_array_oob;
                     }
                 } else if (p1->class_id >= JS_CLASS_UINT8C_ARRAY &&
                            p1->class_id <= JS_CLASS_FLOAT64_ARRAY) {
                     ret = JS_AtomIsNumericIndex(ctx, prop);
                     if (ret != 0) {
                         if (ret < 0) {
                             JS_FreeValue(ctx, val);
                             return -1;
                         }
                     typed_array_oob:
                         val = JS_ToNumberFree(ctx, val);
                         JS_FreeValue(ctx, val);
                         if (JS_IsException(val))
                             return -1;
                         return JS_ThrowTypeErrorOrFalse(ctx, flags, "out-of-bound numeric index");
                     }
                 }
             } else {
                 const JSClassExoticMethods *em = ctx->rt->class_array[p1->class_id].exotic;
                 if (em) {
                     JSValue obj1;
                     if (em->set_property) {
                         /* set_property can free the prototype */
                         obj1 = JS_DupValue(ctx, JS_MKPTR(JS_TAG_OBJECT, p1));
                         ret = em->set_property(ctx, obj1, prop,
                                                val, this_obj, flags);
                         JS_FreeValue(ctx, obj1);
                         JS_FreeValue(ctx, val);
                         return ret;
                     }
                     if (em->get_own_property) {
                         /* get_own_property can free the prototype */
                         obj1 = JS_DupValue(ctx, JS_MKPTR(JS_TAG_OBJECT, p1));
                         ret = em->get_own_property(ctx, &desc,
                                                    obj1, prop);
                         JS_FreeValue(ctx, obj1);
                         if (ret < 0) {
                             JS_FreeValue(ctx, val);
                             return ret;
                         }
                         if (ret) {
                             if (desc.flags & JS_PROP_GETSET) {
                                 JSObject *setter;
                                 if (JS_IsUndefined(desc.setter))
                                     setter = NULL;
                                 else
                                     setter = JS_VALUE_GET_OBJ(desc.setter);
                                 ret = call_setter(ctx, setter, this_obj, val, flags);
                                 JS_FreeValue(ctx, desc.getter);
                                 JS_FreeValue(ctx, desc.setter);
                                 return ret;
                             } else {
                                 JS_FreeValue(ctx, desc.value);
                                 if (!(desc.flags & JS_PROP_WRITABLE))
                                     goto read_only_prop;
                                 if (likely(p == p1)) {
                                     ret = JS_DefineProperty(ctx, this_obj, prop, val,
                                                             JS_UNDEFINED, JS_UNDEFINED,
                                                             JS_PROP_HAS_VALUE);
                                     JS_FreeValue(ctx, val);
                                     return ret;
                                 } else {
                                     break;
                                 }
                             }
                         }
                     }
                 }
             }
         }
         p1 = p1->shape->proto;
     prototype_lookup:
         if (!p1)
             break;
     retry2:
         prs = find_own_property(&pr, p1, prop);
         if (prs) {
             if ((prs->flags & JS_PROP_TMASK) == JS_PROP_GETSET) {
                 return call_setter(ctx, pr->u.getset.setter, this_obj, val, flags);
             } else if ((prs->flags & JS_PROP_TMASK) == JS_PROP_AUTOINIT) {
                 /* Instantiate property and retry (potentially useless) */
                 if (JS_AutoInitProperty(ctx, p1, prop, pr, prs))
                     return -1;
                 goto retry2;
             } else if (!(prs->flags & JS_PROP_WRITABLE)) {
             read_only_prop:
                 JS_FreeValue(ctx, val);
                 return JS_ThrowTypeErrorReadOnly(ctx, flags, prop);
             }
         }
     }
     if (unlikely(flags & JS_PROP_NO_ADD)) {
         JS_FreeValue(ctx, val);
         JS_ThrowReferenceErrorNotDefined(ctx, prop);
         return -1;
     }
     if (unlikely(!p)) {
         JS_FreeValue(ctx, val);
         return JS_ThrowTypeErrorOrFalse(ctx, flags, "not an object");
     }
     if (unlikely(!p->extensible)) {
         JS_FreeValue(ctx, val);
         return JS_ThrowTypeErrorOrFalse(ctx, flags, "object is not extensible");
     }
     if (p->is_exotic) {
         if (p->class_id == JS_CLASS_ARRAY && p->fast_array &&
             __JS_AtomIsTaggedInt(prop)) {
             uint32_t idx = __JS_AtomToUInt32(prop);
             if (idx == p->u.array.count) {
                 /* fast case */
                 return add_fast_array_element(ctx, p, val, flags);
             } else {
                 goto generic_create_prop;
             }
         } else {
         generic_create_prop:
             ret = JS_CreateProperty(ctx, p, prop, val, JS_UNDEFINED, JS_UNDEFINED,
                                     flags |
                                     JS_PROP_HAS_VALUE |
                                     JS_PROP_HAS_ENUMERABLE |
                                     JS_PROP_HAS_WRITABLE |
                                     JS_PROP_HAS_CONFIGURABLE |
                                     JS_PROP_C_W_E);
             JS_FreeValue(ctx, val);
             return ret;
         }
     }
     pr = add_property(ctx, p, prop, JS_PROP_C_W_E);
     if (unlikely(!pr)) {
         JS_FreeValue(ctx, val);
         return -1;
     }
     pr->u.value = val;
     return TRUE;
 }
JS_SetProperty()
static int JS_SetProperty (JSContext * ctx, JSValueConst this_obj, JSAtom prop, JSValue val) inline static
Definition at line 736 of file quickjs.h.
References JS_SetPropertyInternal().
Referenced by js_array_concat(), js_array_constructor(), js_array_from(), js_array_of(), js_array_pop(), js_array_push(), js_array_slice(), JS_CopyDataProperties(), js_regexp_compile(), js_regexp_exec(), js_regexp_string_iterator_next(), js_regexp_Symbol_match(), js_regexp_Symbol_matchAll(), js_regexp_Symbol_replace(), js_regexp_Symbol_search(), js_regexp_Symbol_split(), JS_RegExpDelete(), and JS_SetPropertyInt64().
 {
     return JS_SetPropertyInternal(ctx, this_obj, prop, val, JS_PROP_THROW);
 }
JS_SetPropertyUint32()
int JS_SetPropertyUint32 (JSContext * ctx, JSValueConst this_obj, uint32_t idx, JSValue val)
Definition at line 8730 of file quickjs.c.
References JS_NewUint32(), and JS_SetPropertyValue().
Referenced by js_array_constructor(), js_std_add_helpers(), js_typed_array_constructor_obj(), js_typed_array_constructor_ta(), js_typed_array_of(), js_typed_array_set_internal(), remainingElementsCount_add(), and qjs::js_property_traits< uint32_t >::set_property().
 {
     return JS_SetPropertyValue(ctx, this_obj, JS_NewUint32(ctx, idx), val,
                                JS_PROP_THROW);
 }
JS_SetPropertyInt64()
int JS_SetPropertyInt64 (JSContext * ctx, JSValueConst this_obj, int64_t idx, JSValue val)
Definition at line 8737 of file quickjs.c.
References JS_FreeAtom(), JS_FreeValue(), JS_NewAtomInt64(), JS_NewInt32(), JS_SetProperty(), and JS_SetPropertyValue().
Referenced by js_array_fill(), js_array_push(), js_array_reverse(), js_array_slice(), js_array_sort(), JS_CopySubArray(), JS_JSONStringify(), js_regexp_Symbol_match(), and js_typed_array_from().
 {
     JSAtom prop;
     int res;
     if ((uint64_t)idx <= INT32_MAX) {
         /* fast path for fast arrays */
         return JS_SetPropertyValue(ctx, this_obj, JS_NewInt32(ctx, idx), val,
                                    JS_PROP_THROW);
     }
     prop = JS_NewAtomInt64(ctx, idx);
     if (prop == JS_ATOM_NULL) {
         JS_FreeValue(ctx, val);
         return -1;
     }
     res = JS_SetProperty(ctx, this_obj, prop, val);
     JS_FreeAtom(ctx, prop);
     return res;
 }
JS_SetPropertyStr()
int JS_SetPropertyStr (JSContext * ctx, JSValueConst this_obj, const char * prop, JSValue val)
Definition at line 8758 of file quickjs.c.
References JS_FreeAtom(), JS_NewAtom(), and JS_SetPropertyInternal().
Referenced by js_set_error_object(), js_std_add_helpers(), and qjs::js_property_traits< const char * >::set_property().
 {
     JSAtom atom;
     int ret;
     atom = JS_NewAtom(ctx, prop);
     ret = JS_SetPropertyInternal(ctx, this_obj, atom, val, JS_PROP_THROW);
     JS_FreeAtom(ctx, atom);
     return ret;
 }
JS_HasProperty()
int JS_HasProperty (JSContext * ctx, JSValueConst this_obj, JSAtom prop)
Definition at line 7748 of file quickjs.c.
References JSRuntime::class_array, JSClass::exotic, FALSE, JSClassExoticMethods::has_property, JS_AtomIsNumericIndex(), JS_CLASS_FLOAT64_ARRAY, JS_CLASS_UINT8C_ARRAY, JS_DupValue(), JS_FreeValue(), JS_GetOwnPropertyInternal(), JS_TAG_OBJECT, JSShape::proto, JSContext::rt, and JSObject::shape.
Referenced by JS_CallInternal(), JS_CheckGlobalVar(), js_for_in_next(), JS_GetGlobalVarRef(), js_obj_to_desc(), js_operator_in(), js_proxy_has(), js_reflect_has(), and JS_TryGetPropertyInt64().
 {
     JSObject *p;
     int ret;
     JSValue obj1;
     if (unlikely(JS_VALUE_GET_TAG(obj) != JS_TAG_OBJECT))
         return FALSE;
     p = JS_VALUE_GET_OBJ(obj);
     for(;;) {
         if (p->is_exotic) {
             const JSClassExoticMethods *em = ctx->rt->class_array[p->class_id].exotic;
             if (em && em->has_property) {
                 /* has_property can free the prototype */
                 obj1 = JS_DupValue(ctx, JS_MKPTR(JS_TAG_OBJECT, p));
                 ret = em->has_property(ctx, obj1, prop);
                 JS_FreeValue(ctx, obj1);
                 return ret;
             }
         }
         /* JS_GetOwnPropertyInternal can free the prototype */
         JS_DupValue(ctx, JS_MKPTR(JS_TAG_OBJECT, p));
         ret = JS_GetOwnPropertyInternal(ctx, NULL, p, prop);
         JS_FreeValue(ctx, JS_MKPTR(JS_TAG_OBJECT, p));
         if (ret != 0)
             return ret;
         if (p->class_id >= JS_CLASS_UINT8C_ARRAY &&
             p->class_id <= JS_CLASS_FLOAT64_ARRAY) {
             ret = JS_AtomIsNumericIndex(ctx, prop);
             if (ret != 0) {
                 if (ret < 0)
                     return -1;
                 return FALSE;
             }
         }
         p = p->shape->proto;
         if (!p)
             break;
     }
     return FALSE;
 }
JS_IsExtensible()
int JS_IsExtensible (JSContext * ctx, JSValueConst obj)
Definition at line 7720 of file quickjs.c.
References FALSE, JS_CLASS_PROXY, js_proxy_isExtensible(), and JS_TAG_OBJECT.
Referenced by JS_CreateProperty(), js_object_isExtensible(), js_object_isSealed(), js_proxy_delete_property(), js_proxy_get_own_property(), js_proxy_get_own_property_names(), js_proxy_getPrototypeOf(), js_proxy_isExtensible(), js_proxy_preventExtensions(), and js_proxy_setPrototypeOf().
 {
     JSObject *p;
     if (unlikely(JS_VALUE_GET_TAG(obj) != JS_TAG_OBJECT))
         return FALSE;
     p = JS_VALUE_GET_OBJ(obj);
     if (unlikely(p->class_id == JS_CLASS_PROXY))
         return js_proxy_isExtensible(ctx, obj);
     else
         return p->extensible;
 }
JS_PreventExtensions()
int JS_PreventExtensions (JSContext * ctx, JSValueConst obj)
Definition at line 7734 of file quickjs.c.
References FALSE, JS_CLASS_PROXY, js_proxy_preventExtensions(), JS_TAG_OBJECT, and TRUE.
Referenced by js_object_preventExtensions(), js_object_seal(), js_proxy_preventExtensions(), and JS_ReadArray().
 {
     JSObject *p;
     if (unlikely(JS_VALUE_GET_TAG(obj) != JS_TAG_OBJECT))
         return FALSE;
     p = JS_VALUE_GET_OBJ(obj);
     if (unlikely(p->class_id == JS_CLASS_PROXY))
         return js_proxy_preventExtensions(ctx, obj);
     p->extensible = FALSE;
     return TRUE;
 }
JS_DeleteProperty()
int JS_DeleteProperty (JSContext * ctx, JSValueConst obj, JSAtom prop, int flags)
Definition at line 9621 of file quickjs.c.
References delete_property(), FALSE, is_strict_mode(), JS_FreeValue(), JS_IsException(), and JS_ToObject().
Referenced by internalize_json_property(), JS_CallInternal(), JS_DeletePropertyInt64(), js_operator_delete(), js_proxy_delete_property(), and js_reflect_deleteProperty().
 {
     JSValue obj1;
     JSObject *p;
     int res;
     obj1 = JS_ToObject(ctx, obj);
     if (JS_IsException(obj1))
         return -1;
     p = JS_VALUE_GET_OBJ(obj1);
     res = delete_property(ctx, p, prop);
     JS_FreeValue(ctx, obj1);
     if (res != FALSE)
         return res;
     if ((flags & JS_PROP_THROW) ||
         ((flags & JS_PROP_THROW_STRICT) && is_strict_mode(ctx))) {
         JS_ThrowTypeError(ctx, "could not delete property");
         return -1;
     }
     return FALSE;
 }
JS_SetPrototype()
int JS_SetPrototype (JSContext * ctx, JSValueConst obj, JSValueConst proto_val)
Definition at line 6847 of file quickjs.c.
References JS_SetPrototypeInternal(), and TRUE.
 {
     return JS_SetPrototypeInternal(ctx, obj, proto_val, TRUE);
 }
JS_GetPrototype()
JSValue JS_GetPrototype (JSContext * ctx, JSValueConst val)
Definition at line 6891 of file quickjs.c.
References JS_CLASS_PROXY, JS_DupValue(), JS_GetPrototypePrimitive(), js_proxy_getPrototypeOf(), JS_TAG_OBJECT, JSShape::proto, and JSObject::shape.
Referenced by JS_CallInternal(), JS_GetPrototypeFree(), js_object_get___proto__(), js_object_getPrototypeOf(), js_proxy_getPrototypeOf(), and js_proxy_setPrototypeOf().
 {
     JSValue val;
     if (JS_VALUE_GET_TAG(obj) == JS_TAG_OBJECT) {
         JSObject *p;
         p = JS_VALUE_GET_OBJ(obj);
         if (unlikely(p->class_id == JS_CLASS_PROXY)) {
             val = js_proxy_getPrototypeOf(ctx, obj);
         } else {
             p = p->shape->proto;
             if (!p)
                 val = JS_NULL;
             else
                 val = JS_DupValue(ctx, JS_MKPTR(JS_TAG_OBJECT, p));
         }
     } else {
         val = JS_DupValue(ctx, JS_GetPrototypePrimitive(ctx, obj));
     }
     return val;
 }
JS_GetOwnPropertyNames()
int JS_GetOwnPropertyNames (JSContext * ctx, JSPropertyEnum ** ptab, uint32_t * plen, JSValueConst obj, int flags)
Definition at line 7617 of file quickjs.c.
References JS_GetOwnPropertyNamesInternal(), JS_TAG_OBJECT, and JS_ThrowTypeErrorNotAnObject().
Referenced by build_envp().
 {
     if (JS_VALUE_GET_TAG(obj) != JS_TAG_OBJECT) {
         JS_ThrowTypeErrorNotAnObject(ctx);
         return -1;
     }
     return JS_GetOwnPropertyNamesInternal(ctx, ptab, plen,
                                           JS_VALUE_GET_OBJ(obj), flags);
 }
JS_GetOwnProperty()
int JS_GetOwnProperty (JSContext * ctx, JSPropertyDescriptor * desc, JSValueConst obj, JSAtom prop)
Definition at line 7709 of file quickjs.c.
References JS_GetOwnPropertyInternal(), JS_TAG_OBJECT, and JS_ThrowTypeErrorNotAnObject().
Referenced by js_function_bind().
 {
     if (JS_VALUE_GET_TAG(obj) != JS_TAG_OBJECT) {
         JS_ThrowTypeErrorNotAnObject(ctx);
         return -1;
     }
     return JS_GetOwnPropertyInternal(ctx, desc, JS_VALUE_GET_OBJ(obj), prop);
 }
JS_Call()
JSValue JS_Call (JSContext * ctx, JSValueConst func_obj, JSValueConst this_obj, int argc, JSValueConst * argv)
Definition at line 18618 of file quickjs.c.
References JS_CallInternal().
Referenced by call_handler(), handle_posted_message(), internalize_json_property(), js_array_every(), js_array_find(), js_array_from(), js_array_reduce(), js_async_from_sync_iterator_next(), js_async_function_resume(), js_async_generator_next(), js_async_generator_resolve_or_reject(), js_call_bound_function(), JS_CallInternal(), js_dynamic_import_job(), JS_FlattenIntoArray(), js_function_apply(), js_function_call(), JS_GetIterator2(), JS_IteratorNext2(), js_json_check(), js_link_module(), js_map_constructor(), js_promise_all(), js_promise_all_resolve_element(), js_promise_constructor(), js_promise_race(), js_promise_resolve(), js_promise_resolve_thenable_job(), js_promise_then_finally_func(), js_proxy_call(), js_proxy_call_constructor(), js_string_replace(), js_typed_array_find(), js_typed_array_from(), promise_reaction_job(), and qjs::js_traits< std::function< R(Args...)> >::unwrap().
 {
     return JS_CallInternal(ctx, func_obj, this_obj, JS_UNDEFINED,
                            argc, (JSValue *)argv, JS_CALL_FLAG_COPY_ARGV);
 }
JS_Invoke()
JSValue JS_Invoke (JSContext * ctx, JSValueConst this_val, JSAtom atom, int argc, JSValueConst * argv)
Definition at line 18775 of file quickjs.c.
References JS_CallFree(), JS_GetProperty(), and JS_IsException().
Referenced by js_array_every(), JS_InvokeFree(), js_object_toLocaleString(), js_promise_catch(), and js_promise_finally().
 {
     JSValue func_obj;
     func_obj = JS_GetProperty(ctx, this_val, atom);
     if (JS_IsException(func_obj))
         return func_obj;
     return JS_CallFree(ctx, func_obj, this_val, argc, argv);
 }
JS_CallConstructor()
JSValue JS_CallConstructor (JSContext * ctx, JSValueConst func_obj, int argc, JSValueConst * argv)
Definition at line 18767 of file quickjs.c.
References JS_CallConstructorInternal().
Referenced by js_array_buffer_slice(), js_array_from(), js_array_of(), JS_ArraySpeciesCreate(), js_new_promise_capability(), js_regexp_Symbol_matchAll(), js_regexp_Symbol_split(), js_string_match(), and js_typed_array_create().
 {
     return JS_CallConstructorInternal(ctx, func_obj, func_obj,
                                       argc, (JSValue *)argv,
                                       JS_CALL_FLAG_COPY_ARGV);
 }
JS_CallConstructor2()
JSValue JS_CallConstructor2 (JSContext * ctx, JSValueConst func_obj, JSValueConst new_target, int argc, JSValueConst * argv)
Definition at line 18758 of file quickjs.c.
References JS_CallConstructorInternal().
Referenced by js_call_bound_function(), js_function_apply(), js_proxy_call_constructor(), and js_reflect_construct().
 {
     return JS_CallConstructorInternal(ctx, func_obj, new_target,
                                       argc, (JSValue *)argv,
                                       JS_CALL_FLAG_COPY_ARGV);
 }
JS_DetectModule()
JS_BOOL JS_DetectModule (const char * input, size_t input_len)
Definition at line 21398 of file quickjs.c.
References FALSE, simple_next_token(), TOK_EXPORT, TOK_IMPORT, and TRUE.
 {
     const uint8_t *p = (const uint8_t *)input;
     int tok;
     switch(simple_next_token(&p, FALSE)) {
     case TOK_IMPORT:
         tok = simple_next_token(&p, FALSE);
         return (tok != '.' && tok != '(');
     case TOK_EXPORT:
         return TRUE;
     default:
         return FALSE;
     }
 }
JS_Eval()
JSValue JS_Eval (JSContext * ctx, const char * input, size_t input_len, const char * filename, int eval_flags)
Definition at line 33635 of file quickjs.c.
References JSContext::global_obj, and JS_EvalThis().
Referenced by qjs::Context::eval(), js_evalScript(), js_loadScript(), and js_module_loader().
 {
     return JS_EvalThis(ctx, ctx->global_obj, input, input_len, filename,
                        eval_flags);
 }
JS_EvalThis()
JSValue JS_EvalThis (JSContext * ctx, JSValueConst this_obj, const char * input, size_t input_len, const char * filename, int eval_flags)
Definition at line 33621 of file quickjs.c.
References JS_EvalInternal().
Referenced by JS_Eval().
 {
     int eval_type = eval_flags & JS_EVAL_TYPE_MASK;
     JSValue ret;
     assert(eval_type == JS_EVAL_TYPE_GLOBAL ||
            eval_type == JS_EVAL_TYPE_MODULE);
     ret = JS_EvalInternal(ctx, this_obj, input, input_len, filename,
                           eval_flags, -1);
     return ret;
 }
JS_GetGlobalObject()
JSValue JS_GetGlobalObject (JSContext * ctx)
Definition at line 6298 of file quickjs.c.
References JSContext::global_obj, and JS_DupValue().
Referenced by qjs::Context::global(), and js_std_add_helpers().
 {
     return JS_DupValue(ctx, ctx->global_obj);
 }
JS_IsInstanceOf()
int JS_IsInstanceOf (JSContext * ctx, JSValueConst val, JSValueConst obj)
Definition at line 6995 of file quickjs.c.
References JS_CallFree(), JS_GetProperty(), JS_IsException(), JS_IsFunction(), JS_IsNull(), JS_IsObject(), JS_IsUndefined(), JS_OrdinaryIsInstanceOf(), and JS_ToBoolFree().
Referenced by js_operator_instanceof(), and JS_OrdinaryIsInstanceOf().
 {
     JSValue method;
     if (!JS_IsObject(obj))
         goto fail;
     method = JS_GetProperty(ctx, obj, JS_ATOM_Symbol_hasInstance);
     if (JS_IsException(method))
         return -1;
     if (!JS_IsNull(method) && !JS_IsUndefined(method)) {
         JSValue ret;
         ret = JS_CallFree(ctx, method, obj, 1, &val);
         return JS_ToBoolFree(ctx, ret);
     }
     /* legacy case */
     if (!JS_IsFunction(ctx, obj)) {
     fail:
         JS_ThrowTypeError(ctx, "invalid 'instanceof' right operand");
         return -1;
     }
     return JS_OrdinaryIsInstanceOf(ctx, val, obj);
 }
JS_DefineProperty()
int JS_DefineProperty (JSContext * ctx, JSValueConst this_obj, JSAtom prop, JSValueConst val, JSValueConst getter, JSValueConst setter, int flags)
Definition at line 8973 of file quickjs.c.
References __attribute__(), __JS_AtomIsTaggedInt(), __JS_AtomToUInt32(), check_define_prop_flags(), convert_fast_array_to_array(), FALSE, find_own_property(), JSShapeProperty::flags, free_var_ref(), get_prop_flags(), get_shape_prop(), JS_AtomIsNumericIndex1(), JS_AutoInitProperty(), JS_CLASS_ARRAY, JS_CLASS_FLOAT64_ARRAY, JS_CLASS_MODULE_NS, JS_CLASS_UINT8C_ARRAY, JS_CreateProperty(), JS_DupValue(), JS_FreeValue(), JS_IsException(), JS_IsFunction(), JS_IsUndefined(), JS_NewInt32(), JS_NewUint32(), JS_NumberIsInteger(), JS_NumberIsNegativeOrMinusZero(), js_same_value(), JS_SetPropertyValue(), js_shape_prepare_update(), JS_TAG_OBJECT, JS_ThrowTypeErrorNotAnObject(), JS_ToArrayLengthFree(), js_update_property_flags(), JSVarRef::pvalue, JSContext::rt, set_array_length(), set_value(), JSObject::shape, TRUE, and typed_array_get_length().
Referenced by JS_AddIntrinsicBaseObjects(), js_arguments_define_own_property(), js_build_arguments(), JS_CallInternal(), JS_DefineGlobalFunction(), JS_DefinePropertyDesc(), JS_DefinePropertyGetSet(), JS_DefinePropertyValue(), js_object___defineGetter__(), js_object_seal(), js_proxy_define_own_property(), JS_SetPropertyGeneric(), JS_SetPropertyInternal(), and js_string_define_own_property().
 {
     JSObject *p;
     JSShapeProperty *prs;
     JSProperty *pr;
     int mask, res;
     if (JS_VALUE_GET_TAG(this_obj) != JS_TAG_OBJECT) {
         JS_ThrowTypeErrorNotAnObject(ctx);
         return -1;
     }
     p = JS_VALUE_GET_OBJ(this_obj);
  redo_prop_update:
     prs = find_own_property(&pr, p, prop);
     if (prs) {
         /* the range of the Array length property is always tested before */
         if ((prs->flags & JS_PROP_LENGTH) && (flags & JS_PROP_HAS_VALUE)) {
             uint32_t array_length;
             if (JS_ToArrayLengthFree(ctx, &array_length,
                                      JS_DupValue(ctx, val), FALSE)) {
                 return -1;
             }
             /* this code relies on the fact that Uint32 are never allocated */
             val = (JSValueConst)JS_NewUint32(ctx, array_length);
             /* prs may have been modified */
             prs = find_own_property(&pr, p, prop);
             assert(prs != NULL);
         }
         /* property already exists */
         if (!check_define_prop_flags(prs->flags, flags)) {
         not_configurable:
             return JS_ThrowTypeErrorOrFalse(ctx, flags, "property is not configurable");
         }
         if ((prs->flags & JS_PROP_TMASK) == JS_PROP_AUTOINIT) {
             /* Instantiate property and retry */
             if (JS_AutoInitProperty(ctx, p, prop, pr, prs))
                 return -1;
             goto redo_prop_update;
         }
         if (flags & (JS_PROP_HAS_VALUE | JS_PROP_HAS_WRITABLE |
                      JS_PROP_HAS_GET | JS_PROP_HAS_SET)) {
             if (flags & (JS_PROP_HAS_GET | JS_PROP_HAS_SET)) {
                 JSObject *new_getter, *new_setter;
                 if (JS_IsFunction(ctx, getter)) {
                     new_getter = JS_VALUE_GET_OBJ(getter);
                 } else {
                     new_getter = NULL;
                 }
                 if (JS_IsFunction(ctx, setter)) {
                     new_setter = JS_VALUE_GET_OBJ(setter);
                 } else {
                     new_setter = NULL;
                 }
                 if ((prs->flags & JS_PROP_TMASK) != JS_PROP_GETSET) {
                     if (js_shape_prepare_update(ctx, p, &prs))
                         return -1;
                     /* convert to getset */
                     if ((prs->flags & JS_PROP_TMASK) == JS_PROP_VARREF) {
                         free_var_ref(ctx->rt, pr->u.var_ref);
                     } else {
                         JS_FreeValue(ctx, pr->u.value);
                     }
                     prs->flags = (prs->flags &
                                   (JS_PROP_CONFIGURABLE | JS_PROP_ENUMERABLE)) |
                         JS_PROP_GETSET;
                     pr->u.getset.getter = NULL;
                     pr->u.getset.setter = NULL;
                 } else {
                     if (!(prs->flags & JS_PROP_CONFIGURABLE)) {
                         if ((flags & JS_PROP_HAS_GET) &&
                             new_getter != pr->u.getset.getter) {
                             goto not_configurable;
                         }
                         if ((flags & JS_PROP_HAS_SET) &&
                             new_setter != pr->u.getset.setter) {
                             goto not_configurable;
                         }
                     }
                 }
                 if (flags & JS_PROP_HAS_GET) {
                     if (pr->u.getset.getter)
                         JS_FreeValue(ctx, JS_MKPTR(JS_TAG_OBJECT, pr->u.getset.getter));
                     if (new_getter)
                         JS_DupValue(ctx, getter);
                     pr->u.getset.getter = new_getter;
                 }
                 if (flags & JS_PROP_HAS_SET) {
                     if (pr->u.getset.setter)
                         JS_FreeValue(ctx, JS_MKPTR(JS_TAG_OBJECT, pr->u.getset.setter));
                     if (new_setter)
                         JS_DupValue(ctx, setter);
                     pr->u.getset.setter = new_setter;
                 }
             } else {
                 if ((prs->flags & JS_PROP_TMASK) == JS_PROP_GETSET) {
                     /* convert to data descriptor */
                     if (js_shape_prepare_update(ctx, p, &prs))
                         return -1;
                     if (pr->u.getset.getter)
                         JS_FreeValue(ctx, JS_MKPTR(JS_TAG_OBJECT, pr->u.getset.getter));
                     if (pr->u.getset.setter)
                         JS_FreeValue(ctx, JS_MKPTR(JS_TAG_OBJECT, pr->u.getset.setter));
                     prs->flags &= ~(JS_PROP_TMASK | JS_PROP_WRITABLE);
                     pr->u.value = JS_UNDEFINED;
                 } else if ((prs->flags & JS_PROP_TMASK) == JS_PROP_VARREF) {
                     /* Note: JS_PROP_VARREF is always writable */
                 } else {
                     if ((prs->flags & (JS_PROP_CONFIGURABLE | JS_PROP_WRITABLE)) == 0 &&
                         (flags & JS_PROP_HAS_VALUE)) {
                         if (!js_same_value(ctx, val, pr->u.value)) {
                             goto not_configurable;
                         } else {
                             return TRUE;
                         }
                     }
                 }
                 if ((prs->flags & JS_PROP_TMASK) == JS_PROP_VARREF) {
                     if (flags & JS_PROP_HAS_VALUE) {
                         if (p->class_id == JS_CLASS_MODULE_NS) {
                             /* JS_PROP_WRITABLE is always true for variable
                                references, but they are write protected in module name
                                spaces. */
                             if (!js_same_value(ctx, val, *pr->u.var_ref->pvalue))
                                 goto not_configurable;
                         }
                         /* update the reference */
                         set_value(ctx, pr->u.var_ref->pvalue,
                                   JS_DupValue(ctx, val));
                     }
                     /* if writable is set to false, no longer a
                        reference (for mapped arguments) */
                     if ((flags & (JS_PROP_HAS_WRITABLE | JS_PROP_WRITABLE)) == JS_PROP_HAS_WRITABLE) {
                         JSValue val1;
                         if (js_shape_prepare_update(ctx, p, &prs))
                             return -1;
                         val1 = JS_DupValue(ctx, *pr->u.var_ref->pvalue);
                         free_var_ref(ctx->rt, pr->u.var_ref);
                         pr->u.value = val1;
                         prs->flags &= ~(JS_PROP_TMASK | JS_PROP_WRITABLE);
                     }
                 } else if (prs->flags & JS_PROP_LENGTH) {
                     if (flags & JS_PROP_HAS_VALUE) {
                         /* Note: no JS code is executable because
                            'val' is guaranted to be a Uint32 */
                         res = set_array_length(ctx, p, JS_DupValue(ctx, val),
                                                flags);
                     } else {
                         res = TRUE;
                     }
                     /* still need to reset the writable flag if
                        needed.  The JS_PROP_LENGTH is kept because the
                        Uint32 test is still done if the length
                        property is read-only. */
                     if ((flags & (JS_PROP_HAS_WRITABLE | JS_PROP_WRITABLE)) ==
                         JS_PROP_HAS_WRITABLE) {
                         prs = get_shape_prop(p->shape);
                         if (js_update_property_flags(ctx, p, &prs,
                                                      prs->flags & ~JS_PROP_WRITABLE))
                             return -1;
                     }
                     return res;
                 } else {
                     if (flags & JS_PROP_HAS_VALUE) {
                         JS_FreeValue(ctx, pr->u.value);
                         pr->u.value = JS_DupValue(ctx, val);
                     }
                     if (flags & JS_PROP_HAS_WRITABLE) {
                         if (js_update_property_flags(ctx, p, &prs,
                                                      (prs->flags & ~JS_PROP_WRITABLE) |
                                                      (flags & JS_PROP_WRITABLE)))
                             return -1;
                     }
                 }
             }
         }
         mask = 0;
         if (flags & JS_PROP_HAS_CONFIGURABLE)
             mask |= JS_PROP_CONFIGURABLE;
         if (flags & JS_PROP_HAS_ENUMERABLE)
             mask |= JS_PROP_ENUMERABLE;
         if (js_update_property_flags(ctx, p, &prs,
                                      (prs->flags & ~mask) | (flags & mask)))
             return -1;
         return TRUE;
     }
     /* handle modification of fast array elements */
     if (p->fast_array) {
         uint32_t idx;
         uint32_t prop_flags;
         if (p->class_id == JS_CLASS_ARRAY) {
             if (__JS_AtomIsTaggedInt(prop)) {
                 idx = __JS_AtomToUInt32(prop);
                 if (idx < p->u.array.count) {
                     prop_flags = get_prop_flags(flags, JS_PROP_C_W_E);
                     if (prop_flags != JS_PROP_C_W_E)
                         goto convert_to_slow_array;
                     if (flags & (JS_PROP_HAS_GET | JS_PROP_HAS_SET)) {
                     convert_to_slow_array:
                         if (convert_fast_array_to_array(ctx, p))
                             return -1;
                         else
                             goto redo_prop_update;
                     }
                     if (flags & JS_PROP_HAS_VALUE) {
                         set_value(ctx, &p->u.array.u.values[idx], JS_DupValue(ctx, val));
                     }
                     return TRUE;
                 }
             }
         } else if (p->class_id >= JS_CLASS_UINT8C_ARRAY &&
                    p->class_id <= JS_CLASS_FLOAT64_ARRAY) {
             JSValue num;
             int ret;
             if (!__JS_AtomIsTaggedInt(prop)) {
                 /* slow path with to handle all numeric indexes */
                 num = JS_AtomIsNumericIndex1(ctx, prop);
                 if (JS_IsUndefined(num))
                     goto typed_array_done;
                 if (JS_IsException(num))
                     return -1;
                 ret = JS_NumberIsInteger(ctx, num);
                 if (ret < 0) {
                     JS_FreeValue(ctx, num);
                     return -1;
                 }
                 if (!ret) {
                     JS_FreeValue(ctx, num);
                     return JS_ThrowTypeErrorOrFalse(ctx, flags, "non integer index in typed array");
                 }
                 ret = JS_NumberIsNegativeOrMinusZero(ctx, num);
                 JS_FreeValue(ctx, num);
                 if (ret) {
                     return JS_ThrowTypeErrorOrFalse(ctx, flags, "negative index in typed array");
                 }
                 if (!__JS_AtomIsTaggedInt(prop))
                     goto typed_array_oob;
             }
             idx = __JS_AtomToUInt32(prop);
             /* if the typed array is detached, p->u.array.count = 0 */
             if (idx >= typed_array_get_length(ctx, p)) {
             typed_array_oob:
                 return JS_ThrowTypeErrorOrFalse(ctx, flags, "out-of-bound index in typed array");
             }
             prop_flags = get_prop_flags(flags, JS_PROP_ENUMERABLE | JS_PROP_WRITABLE | JS_PROP_CONFIGURABLE);
             if (flags & (JS_PROP_HAS_GET | JS_PROP_HAS_SET) ||
                 prop_flags != (JS_PROP_ENUMERABLE | JS_PROP_WRITABLE | JS_PROP_CONFIGURABLE)) {
                 return JS_ThrowTypeErrorOrFalse(ctx, flags, "invalid descriptor flags");
             }
             if (flags & JS_PROP_HAS_VALUE) {
                 return JS_SetPropertyValue(ctx, this_obj, JS_NewInt32(ctx, idx), JS_DupValue(ctx, val), flags);
             }
             return TRUE;
         typed_array_done: ;
         }
     }
     return JS_CreateProperty(ctx, p, prop, val, getter, setter, flags);
 }
JS_DefinePropertyValue()
int JS_DefinePropertyValue (JSContext * ctx, JSValueConst this_obj, JSAtom prop, JSValue val, int flags)
Definition at line 9272 of file quickjs.c.
References JS_DefineProperty(), and JS_FreeValue().
Referenced by build_backtrace(), build_for_in_iterator(), internalize_json_property(), JS_AddIntrinsicBaseObjects(), JS_AddIntrinsicBasicObjects(), JS_AddIntrinsicTypedArrays(), js_aggregate_error_constructor(), js_build_arguments(), js_build_mapped_arguments(), js_build_module_ns(), JS_CallInternal(), js_closure(), JS_CopyDataProperties(), js_create_desc(), js_create_iterator_result(), JS_DefineObjectName(), JS_DefineObjectNameComputed(), JS_DefinePropertyValueStr(), JS_DefinePropertyValueValue(), js_error_constructor(), js_function_bind(), js_function_set_properties(), js_instantiate_prototype(), JS_InstantiateFunctionListItem(), js_json_parse(), JS_JSONStringify(), js_method_set_properties(), js_object_getOwnPropertyDescriptor(), js_object_getOwnPropertyDescriptors(), js_op_define_class(), js_parse_template(), js_promise_all_resolve_element(), js_proxy_revocable(), JS_ReadArray(), JS_ReadObjectTag(), js_regexp_constructor_internal(), js_regexp_exec(), JS_SetConstructor2(), js_std_getenviron(), js_string_constructor(), JS_ThrowError2(), JS_ToObject(), and json_parse_value().
 {
     int ret;
     ret = JS_DefineProperty(ctx, this_obj, prop, val, JS_UNDEFINED, JS_UNDEFINED,
                             flags | JS_PROP_HAS_VALUE | JS_PROP_HAS_CONFIGURABLE | JS_PROP_HAS_WRITABLE | JS_PROP_HAS_ENUMERABLE);
     JS_FreeValue(ctx, val);
     return ret;
 }
JS_DefinePropertyValueUint32()
int JS_DefinePropertyValueUint32 (JSContext * ctx, JSValueConst this_obj, uint32_t idx, JSValue val, int flags)
Definition at line 9298 of file quickjs.c.
References JS_DefinePropertyValueValue(), and JS_NewUint32().
Referenced by js_append_enumerate(), js_build_mapped_arguments(), js_build_rest(), js_os_pipe(), js_os_readdir(), js_os_ttyGetWinSize(), js_os_waitpid(), js_parse_template(), js_promise_all(), js_promise_all_resolve_element(), JS_ReadArray(), js_regexp_exec(), json_parse_value(), and make_obj_error().
 {
     return JS_DefinePropertyValueValue(ctx, this_obj, JS_NewUint32(ctx, idx),
                                        val, flags);
 }
JS_DefinePropertyValueStr()
int JS_DefinePropertyValueStr (JSContext * ctx, JSValueConst this_obj, const char * prop, JSValue val, int flags)
Definition at line 9312 of file quickjs.c.
References JS_DefinePropertyValue(), JS_FreeAtom(), and JS_NewAtom().
Referenced by handle_posted_message(), JS_AddIntrinsicBaseObjects(), JS_AddIntrinsicProxy(), js_module_set_import_meta(), JS_NewGlobalCConstructor2(), js_os_stat(), js_regexp_exec(), and js_std_urlGet().
 {
     JSAtom atom;
     int ret;
     atom = JS_NewAtom(ctx, prop);
     ret = JS_DefinePropertyValue(ctx, this_obj, atom, val, flags);
     JS_FreeAtom(ctx, atom);
     return ret;
 }
JS_DefinePropertyGetSet()
int JS_DefinePropertyGetSet (JSContext * ctx, JSValueConst this_obj, JSAtom prop, JSValue getter, JSValue setter, int flags)
Definition at line 9324 of file quickjs.c.
References JS_DefineProperty(), and JS_FreeValue().
Referenced by JS_InstantiateFunctionListItem().
 {
     int ret;
     ret = JS_DefineProperty(ctx, this_obj, prop, JS_UNDEFINED, getter, setter,
                             flags | JS_PROP_HAS_GET | JS_PROP_HAS_SET |
                             JS_PROP_HAS_CONFIGURABLE | JS_PROP_HAS_ENUMERABLE);
     JS_FreeValue(ctx, getter);
     JS_FreeValue(ctx, setter);
     return ret;
 }
JS_SetOpaque()
void JS_SetOpaque (JSValue obj, void * opaque)
Definition at line 9741 of file quickjs.c.
References JS_TAG_OBJECT.
Referenced by js_array_buffer_constructor3(), js_async_generator_function_call(), js_create_array_iterator(), js_create_map_iterator(), js_create_resolving_functions(), JS_CreateAsyncFromSyncIterator(), js_generator_function_call(), js_map_constructor(), js_new_std_file(), JS_NewCFunctionData(), js_os_setTimeout(), js_promise_constructor(), js_proxy_constructor(), js_regexp_Symbol_matchAll(), and js_worker_ctor_internal().
 {
    JSObject *p;
     if (JS_VALUE_GET_TAG(obj) == JS_TAG_OBJECT) {
         p = JS_VALUE_GET_OBJ(obj);
         p->u.opaque = opaque;
     }
 }
JS_GetOpaque()
void* JS_GetOpaque (JSValueConst obj, JSClassID class_id)
Definition at line 9751 of file quickjs.c.
References JS_TAG_OBJECT.
Referenced by JS_GetOpaque2(), js_promise_resolve(), qjs::js_traits< std::shared_ptr< T > >::register_class(), and qjs::js_traits< detail::function >::register_class().
 {
     JSObject *p;
     if (JS_VALUE_GET_TAG(obj) != JS_TAG_OBJECT)
         return NULL;
     p = JS_VALUE_GET_OBJ(obj);
     if (p->class_id != class_id)
         return NULL;
     return p->u.opaque;
 }
JS_GetOpaque2()
void* JS_GetOpaque2 (JSContext * ctx, JSValueConst obj, JSClassID class_id)
Definition at line 9762 of file quickjs.c.
References JS_GetOpaque(), and JS_ThrowTypeErrorInvalidClass().
Referenced by qjs::js_traits< detail::function >::register_class(), and qjs::js_traits< std::shared_ptr< T > >::unwrap().
 {
     void *p = JS_GetOpaque(obj, class_id);
     if (unlikely(!p)) {
         JS_ThrowTypeErrorInvalidClass(ctx, class_id);
     }
     return p;
 }
JS_ParseJSON()
JSValue JS_ParseJSON (JSContext * ctx, const char * buf, size_t buf_len, const char * filename)
Definition at line 43512 of file quickjs.c.
References JS_ParseJSON2().
Referenced by qjs::Context::fromJSON(), and js_json_parse().
 {
     return JS_ParseJSON2(ctx, buf, buf_len, filename, 0);
 }
JS_ParseJSON2()
JSValue JS_ParseJSON2 (JSContext * ctx, const char * buf, size_t buf_len, const char * filename, int flags)
Definition at line 43488 of file quickjs.c.
References JSParseState::ext_json, free_token(), JS_FreeValue(), JS_IsException(), js_parse_init(), json_next_token(), json_parse_value(), TOK_EOF, JSParseState::token, and JSToken::val.
Referenced by JS_ParseJSON(), and js_std_parseExtJSON().
 {
     JSParseState s1, *s = &s1;
     JSValue val = JS_UNDEFINED;
     js_parse_init(ctx, s, buf, buf_len, filename);
     s->ext_json = ((flags & JS_PARSE_JSON_EXT) != 0);
     if (json_next_token(s))
         goto fail;
     val = json_parse_value(s);
     if (JS_IsException(val))
         goto fail;
     if (s->token.val != TOK_EOF) {
         if (js_parse_error(s, "unexpected data at the end"))
             goto fail;
     }
     return val;
  fail:
     JS_FreeValue(ctx, val);
     free_token(s, &s->token);
     return JS_EXCEPTION;
 }
JS_JSONStringify()
JSValue JS_JSONStringify (JSContext * ctx, JSValueConst obj, JSValueConst replacer, JSValueConst space0)
Definition at line 43894 of file quickjs.c.
References JSONStringifyContext::b, JSONStringifyContext::empty, JSONStringifyContext::gap, js_array_includes(), JS_AtomToString(), JS_CLASS_NUMBER, JS_CLASS_STRING, JS_DefinePropertyValue(), JS_DupValue(), JS_FreeValue(), js_get_length64(), JS_GetPropertyInt64(), JS_IsArray(), JS_IsException(), JS_IsFunction(), JS_IsNumber(), JS_IsObject(), JS_IsString(), JS_IsUndefined(), js_json_check(), js_json_to_str(), JS_NewArray(), JS_NewObject(), JS_NewStringLen(), JS_SetPropertyInt64(), js_sub_string(), JS_ToBoolFree(), JS_ToInt32Clamp(), JS_ToNumberFree(), JS_ToStringFree(), JSString::len, min_int(), JSONStringifyContext::property_list, JSONStringifyContext::replacer_func, JSONStringifyContext::stack, string_buffer_end(), string_buffer_free(), and string_buffer_init().
Referenced by js_json_stringify().
 {
     StringBuffer b_s;
     JSONStringifyContext jsc_s, *jsc = &jsc_s;
     JSValue val, v, space, ret, wrapper;
     int res;
     int64_t i, j, n;
     jsc->replacer_func = JS_UNDEFINED;
     jsc->stack = JS_UNDEFINED;
     jsc->property_list = JS_UNDEFINED;
     jsc->gap = JS_UNDEFINED;
     jsc->b = &b_s;
     jsc->empty = JS_AtomToString(ctx, JS_ATOM_empty_string);
     ret = JS_UNDEFINED;
     wrapper = JS_UNDEFINED;
     string_buffer_init(ctx, jsc->b, 0);
     jsc->stack = JS_NewArray(ctx);
     if (JS_IsException(jsc->stack))
         goto exception;
     if (JS_IsFunction(ctx, replacer)) {
         jsc->replacer_func = replacer;
     } else {
         res = JS_IsArray(ctx, replacer);
         if (res < 0)
             goto exception;
         if (res) {
             /* XXX: enumeration is not fully correct */
             jsc->property_list = JS_NewArray(ctx);
             if (JS_IsException(jsc->property_list))
                 goto exception;
             if (js_get_length64(ctx, &n, replacer))
                 goto exception;
             for (i = j = 0; i < n; i++) {
                 JSValue present;
                 v = JS_GetPropertyInt64(ctx, replacer, i);
                 if (JS_IsException(v))
                     goto exception;
                 if (JS_IsObject(v)) {
                     JSObject *p = JS_VALUE_GET_OBJ(v);
                     if (p->class_id == JS_CLASS_STRING ||
                         p->class_id == JS_CLASS_NUMBER) {
                         v = JS_ToStringFree(ctx, v);
                         if (JS_IsException(v))
                             goto exception;
                     } else {
                         JS_FreeValue(ctx, v);
                         continue;
                     }
                 } else if (JS_IsNumber(v)) {
                     v = JS_ToStringFree(ctx, v);
                     if (JS_IsException(v))
                         goto exception;
                 } else if (!JS_IsString(v)) {
                     JS_FreeValue(ctx, v);
                     continue;
                 }
                 present = js_array_includes(ctx, jsc->property_list,
                                             1, (JSValueConst *)&v);
                 if (JS_IsException(present)) {
                     JS_FreeValue(ctx, v);
                     goto exception;
                 }
                 if (!JS_ToBoolFree(ctx, present)) {
                     JS_SetPropertyInt64(ctx, jsc->property_list, j++, v);
                 } else {
                     JS_FreeValue(ctx, v);
                 }
             }
         }
     }
     space = JS_DupValue(ctx, space0);
     if (JS_IsObject(space)) {
         JSObject *p = JS_VALUE_GET_OBJ(space);
         if (p->class_id == JS_CLASS_NUMBER) {
             space = JS_ToNumberFree(ctx, space);
         } else if (p->class_id == JS_CLASS_STRING) {
             space = JS_ToStringFree(ctx, space);
         }
         if (JS_IsException(space)) {
             JS_FreeValue(ctx, space);
             goto exception;
         }
     }
     if (JS_IsNumber(space)) {
         int n;
         if (JS_ToInt32Clamp(ctx, &n, space, 0, 10, 0))
             goto exception;
         jsc->gap = JS_NewStringLen(ctx, "          ", n);
     } else if (JS_IsString(space)) {
         JSString *p = JS_VALUE_GET_STRING(space);
         jsc->gap = js_sub_string(ctx, p, 0, min_int(p->len, 10));
     } else {
         jsc->gap = JS_DupValue(ctx, jsc->empty);
     }
     JS_FreeValue(ctx, space);
     if (JS_IsException(jsc->gap))
         goto exception;
     wrapper = JS_NewObject(ctx);
     if (JS_IsException(wrapper))
         goto exception;
     if (JS_DefinePropertyValue(ctx, wrapper, JS_ATOM_empty_string,
                                JS_DupValue(ctx, obj), JS_PROP_C_W_E) < 0)
         goto exception;
     val = JS_DupValue(ctx, obj);
     val = js_json_check(ctx, jsc, wrapper, val, jsc->empty);
     if (JS_IsException(val))
         goto exception;
     if (JS_IsUndefined(val)) {
         ret = JS_UNDEFINED;
         goto done1;
     }
     if (js_json_to_str(ctx, jsc, wrapper, val, jsc->empty))
         goto exception;
     ret = string_buffer_end(jsc->b);
     goto done;
 exception:
     ret = JS_EXCEPTION;
 done1:
     string_buffer_free(jsc->b);
 done:
     JS_FreeValue(ctx, wrapper);
     JS_FreeValue(ctx, jsc->empty);
     JS_FreeValue(ctx, jsc->gap);
     JS_FreeValue(ctx, jsc->property_list);
     JS_FreeValue(ctx, jsc->stack);
     return ret;
 }
JS_NewArrayBuffer()
JSValue JS_NewArrayBuffer (JSContext * ctx, uint8_t * buf, size_t len, JSFreeArrayBufferDataFunc * free_func, void * opaque, JS_BOOL is_shared)
JS_NewArrayBufferCopy()
JSValue JS_NewArrayBufferCopy (JSContext * ctx, const uint8_t * buf, size_t len)
Definition at line 50963 of file quickjs.c.
References js_array_buffer_constructor3(), js_array_buffer_free(), JS_CLASS_ARRAY_BUFFER, and TRUE.
Referenced by JS_ReadArrayBuffer(), and js_std_urlGet().
 {
     return js_array_buffer_constructor3(ctx, JS_UNDEFINED, len,
                                         JS_CLASS_ARRAY_BUFFER,
                                         (uint8_t *)buf,
                                         js_array_buffer_free, NULL,
                                         TRUE);
 }
JS_DetachArrayBuffer()
void JS_DetachArrayBuffer (JSContext * ctx, JSValueConst obj)
Definition at line 51051 of file quickjs.c.
 {
     JSArrayBuffer *abuf = JS_GetOpaque(obj, JS_CLASS_ARRAY_BUFFER);
     struct list_head *el;
     if (!abuf || abuf->detached)
         return;
     if (abuf->free_func)
         abuf->free_func(ctx->rt, abuf->opaque, abuf->data);
     abuf->data = NULL;
     abuf->byte_length = 0;
     abuf->detached = TRUE;
     list_for_each(el, &abuf->array_list) {
         JSTypedArray *ta;
         JSObject *p;
         ta = list_entry(el, JSTypedArray, link);
         p = ta->obj;
         /* Note: the typed array length and offset fields are not modified */
         if (p->class_id != JS_CLASS_DATAVIEW) {
             p->u.array.count = 0;
             p->u.array.u.ptr = NULL;
         }
     }
 }
JS_GetArrayBuffer()
uint8_t* JS_GetArrayBuffer (JSContext * ctx, size_t * psize, JSValueConst obj)
Definition at line 51096 of file quickjs.c.
References JSArrayBuffer::byte_length, JSArrayBuffer::data, JSArrayBuffer::detached, js_get_array_buffer(), and JS_ThrowTypeErrorDetachedArrayBuffer().
Referenced by js_os_read_write(), and js_std_file_read_write().
 {
     JSArrayBuffer *abuf = js_get_array_buffer(ctx, obj);
     if (!abuf)
         goto fail;
     if (abuf->detached) {
         JS_ThrowTypeErrorDetachedArrayBuffer(ctx);
         goto fail;
     }
     *psize = abuf->byte_length;
     return abuf->data;
  fail:
     *psize = 0;
     return NULL;
 }
JS_GetTypedArrayBuffer()
JSValue JS_GetTypedArrayBuffer (JSContext * ctx, JSValueConst obj, size_t * pbyte_offset, size_t * pbyte_length, size_t * pbytes_per_element)
Definition at line 51315 of file quickjs.c.
References JSTypedArray::buffer, FALSE, get_typed_array(), JS_DupValue(), JS_TAG_OBJECT, JS_ThrowTypeErrorDetachedArrayBuffer(), JSTypedArray::length, JSTypedArray::offset, and typed_array_is_detached().
 {
     JSObject *p;
     JSTypedArray *ta;
     p = get_typed_array(ctx, obj, FALSE);
     if (!p)
         return JS_EXCEPTION;
     if (typed_array_is_detached(ctx, p))
         return JS_ThrowTypeErrorDetachedArrayBuffer(ctx);
     ta = p->u.typed_array;
     if (pbyte_offset)
         *pbyte_offset = ta->offset;
     if (pbyte_length)
         *pbyte_length = ta->length;
     if (pbytes_per_element) {
         *pbytes_per_element = 1 << typed_array_size_log2(p->class_id);
     }
     return JS_DupValue(ctx, JS_MKPTR(JS_TAG_OBJECT, ta->buffer));
 }
JS_SetSharedArrayBufferFunctions()
void JS_SetSharedArrayBufferFunctions (JSRuntime * rt, const JSSharedArrayBufferFunctions * sf)
Definition at line 1794 of file quickjs.c.
References JSRuntime::sab_funcs.
Referenced by js_std_init_handlers().
 {
     rt->sab_funcs = *sf;
 }
JS_NewPromiseCapability()
JSValue JS_NewPromiseCapability (JSContext * ctx, JSValue * resolving_funcs)
Definition at line 46513 of file quickjs.c.
References js_new_promise_capability().
Referenced by js_async_from_sync_iterator_next(), js_async_function_call(), js_async_generator_next(), and js_dynamic_import().
 {
     return js_new_promise_capability(ctx, resolving_funcs, JS_UNDEFINED);
 }
JS_SetHostPromiseRejectionTracker()
void JS_SetHostPromiseRejectionTracker (JSRuntime * rt, JSHostPromiseRejectionTracker * cb, void * opaque)
Definition at line 46160 of file quickjs.c.
References JSRuntime::host_promise_rejection_tracker, and JSRuntime::host_promise_rejection_tracker_opaque.
 {
     rt->host_promise_rejection_tracker = cb;
     rt->host_promise_rejection_tracker_opaque = opaque;
 }
JS_SetInterruptHandler()
void JS_SetInterruptHandler (JSRuntime * rt, JSInterruptHandler * cb, void * opaque)
Definition at line 1783 of file quickjs.c.
References JSRuntime::interrupt_handler, and JSRuntime::interrupt_opaque.
Referenced by js_evalScript().
 {
     rt->interrupt_handler = cb;
     rt->interrupt_opaque = opaque;
 }
JS_SetCanBlock()
void JS_SetCanBlock (JSRuntime * rt, JS_BOOL can_block)
JS_SetIsHTMLDDA()
void JS_SetIsHTMLDDA (JSContext * ctx, JSValueConst obj)
Definition at line 9856 of file quickjs.c.
References JS_TAG_OBJECT, and TRUE.
 {
     JSObject *p;
     if (JS_VALUE_GET_TAG(obj) != JS_TAG_OBJECT)
         return;
     p = JS_VALUE_GET_OBJ(obj);
     p->is_HTMLDDA = TRUE;
 }
JS_SetModuleLoaderFunc()
void JS_SetModuleLoaderFunc (JSRuntime * rt, JSModuleNormalizeFunc * module_normalize, JSModuleLoaderFunc * module_loader, void * opaque)
Definition at line 27149 of file quickjs.c.
References JSRuntime::module_loader_func, JSRuntime::module_loader_opaque, and JSRuntime::module_normalize_func.
Referenced by main(), and worker_func().
 {
     rt->module_normalize_func = module_normalize;
     rt->module_loader_func = module_loader;
     rt->module_loader_opaque = opaque;
 }
JS_GetImportMeta()
JSValue JS_GetImportMeta (JSContext * ctx, JSModuleDef * m)
Definition at line 28052 of file quickjs.c.
References JS_DupValue(), JS_IsException(), JS_IsUndefined(), JS_NewObjectProto(), and JSModuleDef::meta_obj.
Referenced by js_import_meta(), and js_module_set_import_meta().
 {
     JSValue obj;
     /* allocate meta_obj only if requested to save memory */
     obj = m->meta_obj;
     if (JS_IsUndefined(obj)) {
         obj = JS_NewObjectProto(ctx, JS_NULL);
         if (JS_IsException(obj))
             return JS_EXCEPTION;
         m->meta_obj = obj;
     }
     return JS_DupValue(ctx, obj);
 }
JS_GetModuleName()
JSAtom JS_GetModuleName (JSContext * ctx, JSModuleDef * m)
Definition at line 28047 of file quickjs.c.
References JS_DupAtom(), and JSModuleDef::module_name.
Referenced by js_module_set_import_meta().
 {
     return JS_DupAtom(ctx, m->module_name);
 }
JS_EnqueueJob()
int JS_EnqueueJob (JSContext * ctx, JSJobFunc * job_func, int argc, JSValueConst * argv)
Definition at line 1801 of file quickjs.c.
References JSJobEntry::argc, JSJobEntry::argv, JSJobEntry::ctx, JSJobEntry::job_func, JSRuntime::job_list, JS_DupValue(), JSJobEntry::link, list_add_tail(), and JSContext::rt.
Referenced by js_dynamic_import(), js_promise_resolve_function_call(), and perform_promise_then().
 {
     JSRuntime *rt = ctx->rt;
     JSJobEntry *e;
     int i;
     e = js_malloc(ctx, sizeof(*e) + argc * sizeof(JSValue));
     if (!e)
         return -1;
     e->ctx = ctx;
     e->job_func = job_func;
     e->argc = argc;
     for(i = 0; i < argc; i++) {
         e->argv[i] = JS_DupValue(ctx, argv[i]);
     }
     list_add_tail(&e->link, &rt->job_list);
     return 0;
 }
JS_IsJobPending()
JS_BOOL JS_IsJobPending (JSRuntime * rt)
Definition at line 1821 of file quickjs.c.
References JSRuntime::job_list, and list_empty().
 {
     return !list_empty(&rt->job_list);
 }
JS_ExecutePendingJob()
int JS_ExecutePendingJob (JSRuntime * rt, JSContext ** pctx)
Definition at line 1828 of file quickjs.c.
References JSJobEntry::argc, JSJobEntry::argv, JSJobEntry::ctx, JSJobEntry::job_func, JSRuntime::job_list, js_free(), JS_FreeValue(), JS_IsException(), JSJobEntry::link, list_del(), list_empty(), and list_head::next.
Referenced by js_std_loop().
 {
     JSContext *ctx;
     JSJobEntry *e;
     JSValue res;
     int i, ret;
     if (list_empty(&rt->job_list)) {
         *pctx = NULL;
         return 0;
     }
     /* get the first pending job and execute it */
     e = list_entry(rt->job_list.next, JSJobEntry, link);
     list_del(&e->link);
     ctx = e->ctx;
     res = e->job_func(e->ctx, e->argc, (JSValueConst *)e->argv);
     for(i = 0; i < e->argc; i++)
         JS_FreeValue(ctx, e->argv[i]);
     if (JS_IsException(res))
         ret = -1;
     else
         ret = 1;
     JS_FreeValue(ctx, res);
     js_free(ctx, e);
     *pctx = ctx;
     return ret;
 }
JS_WriteObject()
uint8_t* JS_WriteObject (JSContext * ctx, size_t * psize, JSValueConst obj, int flags)
Definition at line 34678 of file quickjs.c.
References JS_WriteObject2().
 {
     return JS_WriteObject2(ctx, psize, obj, flags, NULL, NULL);
 }
JS_WriteObject2()
uint8_t* JS_WriteObject2 (JSContext * ctx, size_t * psize, JSValueConst obj, int flags, uint8_t *** psab_tab, size_t * psab_tab_len)
Definition at line 34632 of file quickjs.c.
References BCWriterState::allow_bytecode, BCWriterState::allow_reference, BCWriterState::allow_sab, BCWriterState::atom_to_idx, DynBuf::buf, BCWriterState::byte_swap, BCWriterState::ctx, BCWriterState::dbuf, dbuf_free(), BCWriterState::first_atom, BCWriterState::idx_to_atom, js_dbuf_init(), js_free(), js_object_list_end(), js_object_list_init(), JS_WriteObjectAtoms(), JS_WriteObjectRec(), BCWriterState::object_list, BCWriterState::sab_tab, BCWriterState::sab_tab_len, and DynBuf::size.
Referenced by js_worker_postMessage(), and JS_WriteObject().
 {
     BCWriterState ss, *s = &ss;
     memset(s, 0, sizeof(*s));
     s->ctx = ctx;
     /* XXX: byte swapped output is untested */
     s->byte_swap = ((flags & JS_WRITE_OBJ_BSWAP) != 0);
     s->allow_bytecode = ((flags & JS_WRITE_OBJ_BYTECODE) != 0);
     s->allow_sab = ((flags & JS_WRITE_OBJ_SAB) != 0);
     s->allow_reference = ((flags & JS_WRITE_OBJ_REFERENCE) != 0);
     /* XXX: could use a different version when bytecode is included */
     if (s->allow_bytecode)
         s->first_atom = JS_ATOM_END;
     else
         s->first_atom = 1;
     js_dbuf_init(ctx, &s->dbuf);
     js_object_list_init(&s->object_list);
     if (JS_WriteObjectRec(s, obj))
         goto fail;
     if (JS_WriteObjectAtoms(s))
         goto fail;
     js_object_list_end(ctx, &s->object_list);
     js_free(ctx, s->atom_to_idx);
     js_free(ctx, s->idx_to_atom);
     *psize = s->dbuf.size;
     if (psab_tab)
         *psab_tab = s->sab_tab;
     if (psab_tab_len)
         *psab_tab_len = s->sab_tab_len;
     return s->dbuf.buf;
  fail:
     js_object_list_end(ctx, &s->object_list);
     js_free(ctx, s->atom_to_idx);
     js_free(ctx, s->idx_to_atom);
     dbuf_free(&s->dbuf);
     *psize = 0;
     if (psab_tab)
         *psab_tab = NULL;
     if (psab_tab_len)
         *psab_tab_len = 0;
     return NULL;
 }
JS_ReadObject()
JSValue JS_ReadObject (JSContext * ctx, const uint8_t * buf, size_t buf_len, int flags)
Definition at line 35806 of file quickjs.c.
References BCReaderState::allow_bytecode, BCReaderState::allow_reference, BCReaderState::allow_sab, bc_reader_free(), JSContext::binary_object_count, JSContext::binary_object_size, BCReaderState::buf_end, BCReaderState::buf_start, BCReaderState::ctx, BCReaderState::first_atom, BCReaderState::is_rom_data, JS_ReadObjectAtoms(), JS_ReadObjectRec(), and BCReaderState::ptr.
Referenced by handle_posted_message(), and js_std_eval_binary().
 {
     BCReaderState ss, *s = &ss;
     JSValue obj;
     ctx->binary_object_count += 1;
     ctx->binary_object_size += buf_len;
     memset(s, 0, sizeof(*s));
     s->ctx = ctx;
     s->buf_start = buf;
     s->buf_end = buf + buf_len;
     s->ptr = buf;
     s->allow_bytecode = ((flags & JS_READ_OBJ_BYTECODE) != 0);
     s->is_rom_data = ((flags & JS_READ_OBJ_ROM_DATA) != 0);
     s->allow_sab = ((flags & JS_READ_OBJ_SAB) != 0);
     s->allow_reference = ((flags & JS_READ_OBJ_REFERENCE) != 0);
     if (s->allow_bytecode)
         s->first_atom = JS_ATOM_END;
     else
         s->first_atom = 1;
     if (JS_ReadObjectAtoms(s)) {
         obj = JS_EXCEPTION;
     } else {
         obj = JS_ReadObjectRec(s);
     }
     bc_reader_free(s);
     return obj;
 }
JS_EvalFunction()
JSValue JS_EvalFunction (JSContext * ctx, JSValue fun_obj)
Definition at line 33450 of file quickjs.c.
References JSContext::global_obj, and JS_EvalFunctionInternal().
Referenced by JS_RunModule(), and js_std_eval_binary().
 {
     return JS_EvalFunctionInternal(ctx, fun_obj, ctx->global_obj, NULL, NULL);
 }
JS_ResolveModule()
int JS_ResolveModule (JSContext * ctx, JSValueConst obj)
Definition at line 33642 of file quickjs.c.
References JS_FREE_MODULE_NOT_RESOLVED, js_free_modules(), and JS_TAG_MODULE.
Referenced by js_std_eval_binary().
 {
     if (JS_VALUE_GET_TAG(obj) == JS_TAG_MODULE) {
         JSModuleDef *m = JS_VALUE_GET_PTR(obj);
         if (js_resolve_module(ctx, m) < 0) {
             js_free_modules(ctx, JS_FREE_MODULE_NOT_RESOLVED);
             return -1;
         }
     }
     return 0;
 }
JS_GetScriptOrModuleName()
JSAtom JS_GetScriptOrModuleName (JSContext * ctx, int n_stack_levels)
Definition at line 28020 of file quickjs.c.
References JSStackFrame::cur_func, JSRuntime::current_stack_frame, JSFunctionBytecode::has_debug, js_class_has_bytecode(), JS_DupAtom(), JS_TAG_OBJECT, JSStackFrame::prev_frame, and JSContext::rt.
Referenced by js_dynamic_import(), js_import_meta(), and js_worker_ctor().
 {
     JSStackFrame *sf;
     JSFunctionBytecode *b;
     JSObject *p;
     /* XXX: currently we just use the filename of the englobing
        function. It does not work for eval(). Need to add a
        ScriptOrModule info in JSFunctionBytecode */
     sf = ctx->rt->current_stack_frame;
     if (!sf)
         return JS_ATOM_NULL;
     while (n_stack_levels-- > 0) {
         sf = sf->prev_frame;
         if (!sf)
             return JS_ATOM_NULL;
     }
     if (JS_VALUE_GET_TAG(sf->cur_func) != JS_TAG_OBJECT)
         return JS_ATOM_NULL;
     p = JS_VALUE_GET_OBJ(sf->cur_func);
     if (!js_class_has_bytecode(p->class_id))
         return JS_ATOM_NULL;
     b = p->u.func.function_bytecode;
     if (!b->has_debug)
         return JS_ATOM_NULL;
     return JS_DupAtom(ctx, b->debug.filename);
 }
JS_RunModule()
JSModuleDef* JS_RunModule (JSContext * ctx, const char * basename, const char * filename)
Definition at line 28088 of file quickjs.c.
References JS_DupValue(), JS_EvalFunction(), JS_FREE_MODULE_NOT_RESOLVED, js_free_modules(), JS_FreeValue(), js_host_resolve_imported_module(), JS_IsException(), js_resolve_module(), and JS_TAG_MODULE.
Referenced by js_dynamic_import_job().
 {
     JSModuleDef *m;
     JSValue ret, func_obj;
     m = js_host_resolve_imported_module(ctx, basename, filename);
     if (!m)
         return NULL;
     if (js_resolve_module(ctx, m) < 0) {
         js_free_modules(ctx, JS_FREE_MODULE_NOT_RESOLVED);
         return NULL;
     }
     /* Evaluate the module code */
     func_obj = JS_DupValue(ctx, JS_MKPTR(JS_TAG_MODULE, m));
     ret = JS_EvalFunction(ctx, func_obj);
     if (JS_IsException(ret))
         return NULL;
     JS_FreeValue(ctx, ret);
     return m;
 }
JS_NewCFunction2()
JSValue JS_NewCFunction2 (JSContext * ctx, JSCFunction * func, const char * name, int length, JSCFunctionEnum cproto, int magic)
Definition at line 5030 of file quickjs.c.
References JSContext::function_proto, and JS_NewCFunction3().
Referenced by JS_AddIntrinsicPromise(), JS_AddIntrinsicProxy(), JS_InstantiateFunctionListItem(), JS_NewCFunction(), JS_NewCFunctionMagic(), JS_NewGlobalCConstructor(), JS_NewGlobalCConstructorOnly(), and js_os_init().
 {
     return JS_NewCFunction3(ctx, func, name, length, cproto, magic,
                             ctx->function_proto);
 }
JS_NewCFunctionData()
JSValue JS_NewCFunctionData (JSContext * ctx, JSCFunctionData * func, int length, int magic, int data_len, JSValueConst * data)
Definition at line 5094 of file quickjs.c.
References JSCFunctionDataRecord::data, JSCFunctionDataRecord::data_len, JSCFunctionDataRecord::func, JSContext::function_proto, JS_CLASS_C_FUNCTION_DATA, JS_DupValue(), JS_FreeValue(), js_function_set_properties(), JS_IsException(), JS_NewObjectProtoClass(), JS_SetOpaque(), JSCFunctionDataRecord::length, and JSCFunctionDataRecord::magic.
Referenced by js_async_from_sync_iterator_unwrap_func_create(), js_async_generator_resolve_function_create(), js_promise_all(), js_promise_executor_new(), js_promise_finally(), js_promise_then_finally_func(), and js_proxy_revoke_constructor().
 {
     JSCFunctionDataRecord *s;
     JSValue func_obj;
     int i;
     func_obj = JS_NewObjectProtoClass(ctx, ctx->function_proto,
                                       JS_CLASS_C_FUNCTION_DATA);
     if (JS_IsException(func_obj))
         return func_obj;
     s = js_malloc(ctx, sizeof(*s) + data_len * sizeof(JSValue));
     if (!s) {
         JS_FreeValue(ctx, func_obj);
         return JS_EXCEPTION;
     }
     s->func = func;
     s->length = length;
     s->data_len = data_len;
     s->magic = magic;
     for(i = 0; i < data_len; i++)
         s->data[i] = JS_DupValue(ctx, data[i]);
     JS_SetOpaque(func_obj, s);
     js_function_set_properties(ctx, func_obj,
                                JS_ATOM_empty_string, length);
     return func_obj;
 }
JS_NewCFunction()
static JSValue JS_NewCFunction (JSContext * ctx, JSCFunction * func, const char * name, int length) inline static
Definition at line 945 of file quickjs.h.
References JS_CFUNC_generic, and JS_NewCFunction2().
Referenced by JS_AddIntrinsicBaseObjects(), JS_AddIntrinsicTypedArrays(), and js_std_add_helpers().
 {
     return JS_NewCFunction2(ctx, func, name, length, JS_CFUNC_generic, 0);
 }
JS_NewCFunctionMagic()
static JSValue JS_NewCFunctionMagic (JSContext * ctx, JSCFunctionMagic * func, const char * name, int length, JSCFunctionEnum cproto, int magic) inline static
Definition at line 951 of file quickjs.h.
References JS_NewCFunction2().
Referenced by JS_AddIntrinsicBaseObjects(), and JS_AddIntrinsicMapSet().
 {
     return JS_NewCFunction2(ctx, (JSCFunction *)func, name, length, cproto, magic);
 }
JS_SetConstructor()
void JS_SetConstructor (JSContext * ctx, JSValueConst func_obj, JSValueConst proto)
Definition at line 36078 of file quickjs.c.
References JS_SetConstructor2().
Referenced by JS_AddIntrinsicTypedArrays(), JS_NewGlobalCConstructor2(), and js_os_init().
 {
     JS_SetConstructor2(ctx, func_obj, proto,
                        0, JS_PROP_WRITABLE | JS_PROP_CONFIGURABLE);
 }
JS_SetPropertyFunctionList()
void JS_SetPropertyFunctionList (JSContext * ctx, JSValueConst obj, const JSCFunctionListEntry * tab, int len)
Definition at line 36001 of file quickjs.c.
References find_atom(), JS_FreeAtom(), JS_InstantiateFunctionListItem(), and JSCFunctionListEntry::name.
Referenced by JS_AddIntrinsicAtomics(), JS_AddIntrinsicBaseObjects(), JS_AddIntrinsicBasicObjects(), JS_AddIntrinsicDate(), JS_AddIntrinsicJSON(), JS_AddIntrinsicMapSet(), JS_AddIntrinsicPromise(), JS_AddIntrinsicProxy(), JS_AddIntrinsicRegExp(), JS_AddIntrinsicStringNormalize(), JS_AddIntrinsicTypedArrays(), js_os_init(), JS_SetModuleExportList(), and js_std_init().
 {
     int i;
     for (i = 0; i < len; i++) {
         const JSCFunctionListEntry *e = &tab[i];
         JSAtom atom = find_atom(ctx, e->name);
         JS_InstantiateFunctionListItem(ctx, obj, atom, e);
         JS_FreeAtom(ctx, atom);
     }
 }
JS_NewCModule()
JSModuleDef* JS_NewCModule (JSContext * ctx, const char * name_str, JSModuleInitFunc * func)
Definition at line 27101 of file quickjs.c.
References JSModuleDef::init_func, js_new_module_def(), and JS_NewAtom().
Referenced by js_init_module_os(), js_init_module_std(), and qjs::Context::Module::Module().
 {
     JSModuleDef *m;
     JSAtom name;
     name = JS_NewAtom(ctx, name_str);
     if (name == JS_ATOM_NULL)
         return NULL;
     m = js_new_module_def(ctx, name);
     m->init_func = func;
     return m;
 }
JS_AddModuleExport()
int JS_AddModuleExport (JSContext * ctx, JSModuleDef * m, const char * name_str)
Definition at line 27114 of file quickjs.c.
References add_export_entry2(), JS_EXPORT_TYPE_LOCAL, JS_FreeAtom(), and JS_NewAtom().
Referenced by qjs::Context::Module::add(), JS_AddModuleExportList(), js_init_module_os(), and js_init_module_std().
 {
     JSExportEntry *me;
     JSAtom name;
     name = JS_NewAtom(ctx, export_name);
     if (name == JS_ATOM_NULL)
         return -1;
     me = add_export_entry2(ctx, NULL, m, JS_ATOM_NULL, name,
                            JS_EXPORT_TYPE_LOCAL);
     JS_FreeAtom(ctx, name);
     if (!me)
         return -1;
     else
         return 0;
 }
JS_AddModuleExportList()
int JS_AddModuleExportList (JSContext * ctx, JSModuleDef * m, const JSCFunctionListEntry * tab, int len)
Definition at line 36014 of file quickjs.c.
References JS_AddModuleExport(), and JSCFunctionListEntry::name.
Referenced by js_init_module_os(), and js_init_module_std().
 {
     int i;
     for(i = 0; i < len; i++) {
         if (JS_AddModuleExport(ctx, m, tab[i].name))
             return -1;
     }
     return 0;
 }
JS_SetModuleExport()
int JS_SetModuleExport (JSContext * ctx, JSModuleDef * m, const char * export_name, JSValue val)
Definition at line 27130 of file quickjs.c.
References find_export_entry(), JS_FreeAtom(), JS_FreeValue(), JS_NewAtom(), JSVarRef::pvalue, and set_value().
Referenced by js_os_init(), JS_SetModuleExportList(), js_std_init(), and qjs::Context::Module::Module().
 {
     JSExportEntry *me;
     JSAtom name;
     name = JS_NewAtom(ctx, export_name);
     if (name == JS_ATOM_NULL)
         goto fail;
     me = find_export_entry(ctx, m, name);
     JS_FreeAtom(ctx, name);
     if (!me)
         goto fail;
     set_value(ctx, me->u.local.var_ref->pvalue, val);
     return 0;
  fail:
     JS_FreeValue(ctx, val);
     return -1;
 }
JS_SetModuleExportList()
int JS_SetModuleExportList (JSContext * ctx, JSModuleDef * m, const JSCFunctionListEntry * tab, int len)
Definition at line 36025 of file quickjs.c.
References __JS_NewFloat64(), JSCFunctionListEntry::def_type, JS_NewInt32(), JS_NewInt64(), JS_NewObject(), JS_NewString(), JS_SetModuleExport(), JS_SetPropertyFunctionList(), and JSCFunctionListEntry::name.
Referenced by js_os_init(), and js_std_init().
 {
     int i;
     JSValue val;
     for(i = 0; i < len; i++) {
         const JSCFunctionListEntry *e = &tab[i];
         switch(e->def_type) {
         case JS_DEF_CFUNC:
             val = JS_NewCFunction2(ctx, e->u.func.cfunc.generic,
                                    e->name, e->u.func.length, e->u.func.cproto, e->magic);
             break;
         case JS_DEF_PROP_STRING:
             val = JS_NewString(ctx, e->u.str);
             break;
         case JS_DEF_PROP_INT32:
             val = JS_NewInt32(ctx, e->u.i32);
             break;
         case JS_DEF_PROP_INT64:
             val = JS_NewInt64(ctx, e->u.i64);
             break;
         case JS_DEF_PROP_DOUBLE:
             val = __JS_NewFloat64(ctx, e->u.f64);
             break;
         case JS_DEF_OBJECT:
             val = JS_NewObject(ctx);
             JS_SetPropertyFunctionList(ctx, val, e->u.prop_list.tab, e->u.prop_list.len);
             break;
         default:
             abort();
         }
         if (JS_SetModuleExport(ctx, m, e->name, val))
             return -1;
     }
     return 0;
 }
Variable Documentation
fmt
JSValue const char JSValue const char JSValue const char JSValue const char JSValue const char * fmt
Definition at line 632 of file quickjs.h.