QuickJSPP: qjs::js_traits< std::string_view > Struct Template Reference
qjs::js_traits< std::string_view > Struct Template Reference
Conversion traits from std::string_view and to detail::js_string.
#include "quickjspp.hpp"
Static Public Member Functions
static detail::js_string unwrap (JSContext *ctx, JSValueConst v)
static JSValue wrap (JSContext *ctx, std::string_view str) noexcept
Detailed Description
template<>
struct qjs::js_traits< std::string_view >
Conversion traits from std::string_view and to detail::js_string.
Definition at line 189 of file quickjspp.hpp.
Member Function Documentation
unwrap()
static detail::js_string qjs::js_traits< std::string_view >::unwrap (JSContext * ctx, JSValueConst v) inline static
Definition at line 191 of file quickjspp.hpp.
References qjs::detail::js_string::js_string(), and JS_ToCStringLen().
Referenced by qjs::js_traits< std::string >::unwrap(), and qjs::js_traits< const char * >::unwrap().
     {
         size_t plen;
         const char * ptr = JS_ToCStringLen(ctx, &plen, v);
         if(!ptr)
             throw exception{};
         return detail::js_string{ctx, ptr, plen};
     }
wrap()
static JSValue qjs::js_traits< std::string_view >::wrap (JSContext * ctx, std::string_view str) inline static noexcept
Definition at line 200 of file quickjspp.hpp.
References JS_NewStringLen().
     {
         return JS_NewStringLen(ctx, str.data(), str.size());
     }
The documentation for this struct was generated from the following file:
quickjspp.hpp