QuickJSPP: qjs::js_traits< std::pair< U, V > > Struct Template Reference
qjs::js_traits< std::pair< U, V > > Struct Template Reference
#include "quickjspp.hpp"
Static Public Member Functions
static JSValue wrap (JSContext *ctx, std::pair< U, V > obj) noexcept
static std::pair< U, V > unwrap (JSContext *ctx, JSValueConst jsarr)
Detailed Description
template<typename U, typename V>
struct qjs::js_traits< std::pair< U, V > >
Definition at line 1604 of file quickjspp.hpp.
Member Function Documentation
wrap()
template<typename U , typename V > static JSValue qjs::js_traits< std::pair< U, V > >::wrap (JSContext * ctx, std::pair< U, V > obj) inline static noexcept
Definition at line 1606 of file quickjspp.hpp.
References JS_NewArray(), qjs::Value::operator[](), qjs::Value::release(), and qjs::Value::Value().
     {
         try
         {
             auto jsarray = Value{ctx, JS_NewArray(ctx)};
             jsarray[uint32_t(0)] = std::move(obj.first);
             jsarray[uint32_t(1)] = std::move(obj.second);
             return jsarray.release();
         }
         catch(exception)
         {
             return JS_EXCEPTION;
         }
     }
unwrap()
template<typename U , typename V > static std::pair<U, V> qjs::js_traits< std::pair< U, V > >::unwrap (JSContext * ctx, JSValueConst jsarr) inline static
Definition at line 1621 of file quickjspp.hpp.
References JS_DupValue(), JS_IsArray(), qjs::Value::operator[](), and qjs::Value::Value().
     {
         int e = JS_IsArray(ctx, jsarr);
         if(e == 0)
             JS_ThrowTypeError(ctx, "js_traits<%s>::unwrap expects array", QJSPP_TYPENAME(std::pair<U, V>));
         if(e <= 0)
             throw exception{};
         Value jsarray{ctx, JS_DupValue(ctx, jsarr)};
         const auto len = static_cast<uint32_t>(jsarray["length"]);
         if(len != 2)
         {
             JS_ThrowTypeError(ctx, "js_traits<%s>::unwrap expected array of length 2, got length %d",
                               QJSPP_TYPENAME(std::pair<U, V>), len);
             throw exception{};
         }
         return std::pair<U, V>{
                 static_cast<U>(jsarray[uint32_t(0)]),
                 static_cast<V>(jsarray[uint32_t(1)])
         };
     }
The documentation for this struct was generated from the following file:
quickjspp.hpp