QuickJSPP: qjs::js_traits< detail::function > Struct Template Reference
qjs::js_traits< detail::function > Struct Template Reference
#include "quickjspp.hpp"
Static Public Member Functions
static void register_class (JSContext *ctx, const char *name)
Static Public Attributes
static JSClassID QJSClassId = 0
Detailed Description
template<>
struct qjs::js_traits< detail::function >
Definition at line 849 of file quickjspp.hpp.
Member Function Documentation
register_class()
static void qjs::js_traits< detail::function >::register_class (JSContext * ctx, const char * name) inline static
Definition at line 854 of file quickjspp.hpp.
References qjs::detail::function::destroyer, js_free_rt(), JS_GetOpaque(), JS_GetOpaque2(), JS_GetRuntime(), JS_IsRegisteredClass(), JS_NewClass(), JS_NewClassID(), and QJSClassId.
Referenced by qjs::Context::init().
     {
         if(QJSClassId == 0)
         {
             JS_NewClassID(&QJSClassId);
         }
         auto rt = JS_GetRuntime(ctx);
         if(JS_IsRegisteredClass(rt, QJSClassId))
             return;
         JSClassDef def{
                 name,
                 // destructor
                 [](JSRuntime * rt, JSValue obj) noexcept {
                     auto fptr = reinterpret_cast<detail::function *>(JS_GetOpaque(obj, QJSClassId));
                     assert(fptr);
                     if(fptr->destroyer)
                         fptr->destroyer(fptr);
                     js_free_rt(rt, fptr);
                 },
                 nullptr, // mark
                 // call
                 [](JSContext * ctx, JSValueConst func_obj, JSValueConst this_val, int argc,
                    JSValueConst * argv, int flags) -> JSValue {
                     auto ptr = reinterpret_cast<detail::function *>(JS_GetOpaque2(ctx, func_obj, QJSClassId));
                     if(!ptr)
                         return JS_EXCEPTION;
                     return ptr->invoker(ptr, ctx, this_val, argc, argv);
                 }
         };
         int e = JS_NewClass(rt, QJSClassId, &def);
         if(e < 0)
             throw std::runtime_error{"Cannot register C++ function class"};
     }
Member Data Documentation
QJSClassId
JSClassID qjs::js_traits< detail::function >::QJSClassId = 0 inline static
Definition at line 851 of file quickjspp.hpp.
Referenced by register_class(), and qjs::js_traits< std::function< R(Args...)> >::wrap().
The documentation for this struct was generated from the following file:
quickjspp.hpp