QuickJSPP: qjs::detail::function Struct Reference
qjs::detail::function Struct Reference
A faster std::function-like object with type erasure.
#include "quickjspp.hpp"
Static Public Member Functions
template<typename Functor >
static function * create (JSRuntime *rt, Functor &&f)
Public Attributes
JSValue(* invoker)(function *self, JSContext *ctx, JSValueConst this_value, int argc, JSValueConst *argv) = nullptr
void(* destroyer)(function *self) = nullptr
char functor []
Detailed Description
A faster std::function-like object with type erasure.
Used to convert any callable objects (including lambdas) to JSValue.
Definition at line 815 of file quickjspp.hpp.
Member Function Documentation
create()
template<typename Functor > static function* qjs::detail::function::create (JSRuntime * rt, Functor && f) inline static
Definition at line 825 of file quickjspp.hpp.
References destroyer, functor, and js_malloc_rt().
     {
         auto fptr = reinterpret_cast<function *>(js_malloc_rt(rt, sizeof(function) + sizeof(Functor)));
         if(!fptr)
             throw std::bad_alloc{};
         new(fptr) function;
         auto functorptr = reinterpret_cast<Functor *>(fptr->functor);
         new(functorptr) Functor(std::forward<Functor>(f));
         fptr->destroyer = nullptr;
         if constexpr(!std::is_trivially_destructible_v<Functor>)
         {
             fptr->destroyer = [](function * fptr) {
                 auto functorptr = reinterpret_cast<Functor *>(fptr->functor);
                 functorptr->~Functor();
             };
         }
         return fptr;
     }
Member Data Documentation
invoker
JSValue(* qjs::detail::function::invoker) (function *self, JSContext *ctx, JSValueConst this_value, int argc, JSValueConst *argv) = nullptr
Definition at line 818 of file quickjspp.hpp.
destroyer
void(* qjs::detail::function::destroyer) (function *self) = nullptr
Definition at line 820 of file quickjspp.hpp.
Referenced by create(), and qjs::js_traits< detail::function >::register_class().
functor
char qjs::detail::function::functor[]
Definition at line 822 of file quickjspp.hpp.
Referenced by create(), and qjs::js_traits< std::function< R(Args...)> >::wrap().
The documentation for this struct was generated from the following file:
quickjspp.hpp