QuickJSPP: qjs::js_traits< std::function< R(Args...)> > Struct Template Reference
qjs::js_traits< std::function< R(Args...)> > Struct Template Reference
Convert to/from std::function.
#include "quickjspp.hpp"
Static Public Member Functions
static auto unwrap (JSContext *ctx, JSValueConst fun_obj)
template<typename Functor >
static JSValue wrap (JSContext *ctx, Functor &&functor)
Convert from function object functor to JSValue.
Detailed Description
template<typename R, typename... Args>
struct qjs::js_traits< std::function< R(Args...)> >
Convert to/from std::function.
Actually accepts/returns callable object that is compatible with function<R (Args...)>.
Template Parameters
R return type
Args argument types
Definition at line 1508 of file quickjspp.hpp.
Member Function Documentation
unwrap()
template<typename R , typename... Args> static auto qjs::js_traits< std::function< R(Args...)> >::unwrap (JSContext * ctx, JSValueConst fun_obj) inline static
Definition at line 1510 of file quickjspp.hpp.
References qjs::Value::ctx, JS_Call(), JS_FreeValue(), JS_IsException(), and qjs::Value::v.
     {
         const int argc = sizeof...(Args);
         if constexpr(argc == 0)
         {
             return [jsfun_obj = Value{ctx, JS_DupValue(ctx, fun_obj)}]() -> R {
                 JSValue result = JS_Call(jsfun_obj.ctx, jsfun_obj.v, JS_UNDEFINED, 0, nullptr);
                 if(JS_IsException(result))
                 {
                     JS_FreeValue(jsfun_obj.ctx, result);
                     throw exception{};
                 }
                 return detail::unwrap_free<R>(jsfun_obj.ctx, result);
             };
         }
         else
         {
             return [jsfun_obj = Value{ctx, JS_DupValue(ctx, fun_obj)}](Args&& ... args) -> R {
                 const int argc = sizeof...(Args);
                 JSValue argv[argc];
                 detail::wrap_args(jsfun_obj.ctx, argv, std::forward<Args>(args)...);
                 JSValue result = JS_Call(jsfun_obj.ctx, jsfun_obj.v, JS_UNDEFINED, argc,
                                          const_cast<JSValueConst *>(argv));
                 for(int i = 0; i < argc; i++) JS_FreeValue(jsfun_obj.ctx, argv[i]);
                 if(JS_IsException(result))
                 {
                     JS_FreeValue(jsfun_obj.ctx, result);
                     throw exception{};
                 }
                 return detail::unwrap_free<R>(jsfun_obj.ctx, result);
             };
         }
     }
wrap()
template<typename R , typename... Args> template<typename Functor > static JSValue qjs::js_traits< std::function< R(Args...)> >::wrap (JSContext * ctx, Functor && functor) inline static
Convert from function object functor to JSValue.
Uses detail::function for type-erasure.
Definition at line 1548 of file quickjspp.hpp.
References qjs::detail::function::functor, JS_GetRuntime(), JS_IsException(), JS_NewObjectClass(), and qjs::js_traits< detail::function >::QJSClassId.
     {
         using detail::function;
         assert(js_traits<function>::QJSClassId);
         auto obj = JS_NewObjectClass(ctx, js_traits<function>::QJSClassId);
         if(JS_IsException(obj))
             return JS_EXCEPTION;
         auto fptr = function::create(JS_GetRuntime(ctx), std::forward<Functor>(functor));
         fptr->invoker = [](function * self, JSContext * ctx, JSValueConst this_value, int argc, JSValueConst * argv) {
             assert(self);
             auto f = reinterpret_cast<Functor *>(&self->functor);
             return detail::wrap_call<R, Args...>(ctx, *f, argv);
         };
         JS_SetOpaque(obj, fptr);
         return obj;
     }
The documentation for this struct was generated from the following file:
quickjspp.hpp