QuickJSPP: JSClassExoticMethods Struct Reference
JSClassExoticMethods Struct Reference
#include "quickjs.h"
Public Attributes
int(* get_own_property)(JSContext *ctx, JSPropertyDescriptor *desc, JSValueConst obj, JSAtom prop)
int(* get_own_property_names)(JSContext *ctx, JSPropertyEnum **ptab, uint32_t *plen, JSValueConst obj)
int(* delete_property)(JSContext *ctx, JSValueConst obj, JSAtom prop)
int(* define_own_property)(JSContext *ctx, JSValueConst this_obj, JSAtom prop, JSValueConst val, JSValueConst getter, JSValueConst setter, int flags)
int(* has_property)(JSContext *ctx, JSValueConst obj, JSAtom atom)
JSValue(* get_property)(JSContext *ctx, JSValueConst obj, JSAtom atom, JSValueConst receiver)
int(* set_property)(JSContext *ctx, JSValueConst obj, JSAtom atom, JSValueConst value, JSValueConst receiver, int flags)
Detailed Description
Definition at line 442 of file quickjs.h.
Member Data Documentation
get_own_property
int(* JSClassExoticMethods::get_own_property) (JSContext *ctx, JSPropertyDescriptor *desc, JSValueConst obj, JSAtom prop)
Definition at line 446 of file quickjs.h.
Referenced by JS_GetOwnPropertyInternal(), JS_GetPropertyInternal(), and JS_SetPropertyInternal().
get_own_property_names
int(* JSClassExoticMethods::get_own_property_names) (JSContext *ctx, JSPropertyEnum **ptab, uint32_t *plen, JSValueConst obj)
Definition at line 451 of file quickjs.h.
Referenced by JS_GetOwnPropertyNamesInternal().
delete_property
int(* JSClassExoticMethods::delete_property) (JSContext *ctx, JSValueConst obj, JSAtom prop)
Definition at line 455 of file quickjs.h.
Referenced by delete_property().
define_own_property
int(* JSClassExoticMethods::define_own_property) (JSContext *ctx, JSValueConst this_obj, JSAtom prop, JSValueConst val, JSValueConst getter, JSValueConst setter, int flags)
Definition at line 457 of file quickjs.h.
Referenced by JS_CreateProperty().
has_property
int(* JSClassExoticMethods::has_property) (JSContext *ctx, JSValueConst obj, JSAtom atom)
Definition at line 464 of file quickjs.h.
Referenced by JS_HasProperty().
get_property
JSValue(* JSClassExoticMethods::get_property) (JSContext *ctx, JSValueConst obj, JSAtom atom, JSValueConst receiver)
Definition at line 465 of file quickjs.h.
set_property
int(* JSClassExoticMethods::set_property) (JSContext *ctx, JSValueConst obj, JSAtom atom, JSValueConst value, JSValueConst receiver, int flags)
Definition at line 468 of file quickjs.h.
Referenced by JS_SetPropertyGeneric(), and JS_SetPropertyInternal().
The documentation for this struct was generated from the following file:
quickjs/quickjs.h