QuickJSPP: qjs::js_traits< std::optional< T > > Struct Template Reference
qjs::js_traits< std::optional< T > > Struct Template Reference
Conversions for std::optional.
#include "quickjspp.hpp"
Static Public Member Functions
static JSValue wrap (JSContext *ctx, std::optional< T > obj) noexcept
Wraps T or null.
static auto unwrap (JSContext *ctx, JSValueConst v) noexcept -> std::optional< decltype(js_traits< std::decay_t< T >>::unwrap(ctx, v))>
If conversion to T fails returns std::nullopt.
Detailed Description
template<typename T>
struct qjs::js_traits< std::optional< T > >
Conversions for std::optional.
Unlike other types does not throw on unwrap but returns nullopt. Converts std::nullopt to null.
Definition at line 1648 of file quickjspp.hpp.
Member Function Documentation
wrap()
template<typename T > static JSValue qjs::js_traits< std::optional< T > >::wrap (JSContext * ctx, std::optional< T > obj) inline static noexcept
Wraps T or null.
Definition at line 1651 of file quickjspp.hpp.
     {
         if(obj)
             return js_traits<std::decay_t<T>>::wrap(ctx, *obj);
         return JS_NULL;
     }
unwrap()
template<typename T > static auto qjs::js_traits< std::optional< T > >::unwrap (JSContext * ctx, JSValueConst v) -> std::optional<decltype(js_traits<std::decay_t<T>>::unwrap(ctx, v))> inline static noexcept
If conversion to T fails returns std::nullopt.
Definition at line 1659 of file quickjspp.hpp.
References JS_FreeValue(), JS_GetException(), and JS_IsNull().
     {
         try
         {
             if(JS_IsNull(v))
                 return std::nullopt;
             return js_traits<std::decay_t<T>>::unwrap(ctx, v);
         }
         catch(exception)
         {
             // ignore and clear exception
             JS_FreeValue(ctx, JS_GetException(ctx));
         }
         return std::nullopt;
     }
The documentation for this struct was generated from the following file:
quickjspp.hpp