QuickJSPP: qjs::js_traits< Value > Struct Template Reference
qjs::js_traits< Value > Struct Template Reference
Conversion traits for Value.
#include "quickjspp.hpp"
Static Public Member Functions
static Value unwrap (JSContext *ctx, JSValueConst v)
static JSValue wrap (JSContext *ctx, Value v) noexcept
Detailed Description
template<>
struct qjs::js_traits< Value >
Conversion traits for Value.
Definition at line 1489 of file quickjspp.hpp.
Member Function Documentation
unwrap()
static Value qjs::js_traits< Value >::unwrap (JSContext * ctx, JSValueConst v) inline static
Definition at line 1491 of file quickjspp.hpp.
References JS_DupValue(), and qjs::Value::Value().
     {
         return Value{ctx, JS_DupValue(ctx, v)};
     }
wrap()
static JSValue qjs::js_traits< Value >::wrap (JSContext * ctx, Value v) inline static noexcept
Definition at line 1496 of file quickjspp.hpp.
References qjs::Value::ctx, and qjs::Value::release().
     {
         assert(ctx == v.ctx);
         return v.release();
     }
The documentation for this struct was generated from the following file:
quickjspp.hpp