QuickJSPP: qjs::js_traits< std::variant< Ts... > > Struct Template Reference
qjs::js_traits< std::variant< Ts... > > Struct Template Reference
Conversion from const std::variant.
#include "quickjspp.hpp"
Classes
struct is_boolean
struct is_double
struct is_pair
struct is_pair< std::pair< U, V > >
struct is_shared_ptr
struct is_shared_ptr< std::shared_ptr< T > >
struct is_string
struct is_variant
struct is_variant< std::variant< Us... > >
struct is_vector
struct is_vector< std::vector< T > >
Static Public Member Functions
static JSValue wrap (JSContext *ctx, std::variant< Ts... > value) noexcept
template<template< typename R > typename Trait, typename U , typename ... Us>
static std::optional< std::variant< Ts... > > unwrapImpl (JSContext *ctx, JSValueConst v)
Attempt to match common types (integral, floating-point, string, etc.)
template<typename U , typename ... Us>
static std::optional< std::variant< Ts... > > unwrapObj (JSContext *ctx, JSValueConst v, JSClassID class_id)
Attempt to match class ID with type.
template<template< typename T > typename Trait, template< typename T > typename ... Traits>
static std::variant< Ts... > unwrapPriority (JSContext *ctx, JSValueConst v)
Attempt to cast to types satisfying traits, ordered in terms of priority.
template<typename T >
static bool isCompatible (JSContext *ctx, JSValueConst v) noexcept
static std::variant< Ts... > unwrap (JSContext *ctx, JSValueConst v)
Detailed Description
template<typename ... Ts>
struct qjs::js_traits< std::variant< Ts... > >
Conversion from const std::variant.
Definition at line 240 of file quickjspp.hpp.
Member Function Documentation
wrap()
template<typename ... Ts> static JSValue qjs::js_traits< std::variant< Ts... > >::wrap (JSContext * ctx, std::variant< Ts... > value) inline static noexcept
Definition at line 242 of file quickjspp.hpp.
     {
         return std::visit([ctx](auto&& value) {
             using T = std::decay_t<decltype(value)>;
             return js_traits<T>::wrap(ctx, value);
         }, std::move(value));
     }
unwrapImpl()
template<typename ... Ts> template<template< typename R > typename Trait, typename U , typename ... Us> static std::optional<std::variant<Ts...> > qjs::js_traits< std::variant< Ts... > >::unwrapImpl (JSContext * ctx, JSValueConst v) inline static
Attempt to match common types (integral, floating-point, string, etc.)
Definition at line 270 of file quickjspp.hpp.
     {
         if constexpr (Trait<U>::value)
         {
             return js_traits<U>::unwrap(ctx, v);
         }
         if constexpr ((sizeof ... (Us)) > 0)
         {
             return unwrapImpl<Trait, Us...>(ctx, v);
         }
         return std::nullopt;
     }
unwrapObj()
template<typename ... Ts> template<typename U , typename ... Us> static std::optional<std::variant<Ts...> > qjs::js_traits< std::variant< Ts... > >::unwrapObj (JSContext * ctx, JSValueConst v, JSClassID class_id) inline static
Attempt to match class ID with type.
Definition at line 285 of file quickjspp.hpp.
References JS_FreeValue(), JS_GetPropertyUint32(), and JS_IsArray().
     {
         if constexpr (is_shared_ptr<U>::value)
         {
             if(class_id == js_traits<U>::QJSClassId)
             {
                 return js_traits<U>::unwrap(ctx, v);
             }
         }
         // try to unwrap embedded variant (variant<variant<...>>), might be slow
         if constexpr (is_variant<U>::value)
         {
             if(auto opt = js_traits<std::optional<U>>::unwrap(ctx, v))
                 return *opt;
         }
         if constexpr (is_vector<U>::value)
         {
             if(JS_IsArray(ctx, v) == 1)
             {
                 auto firstElement = JS_GetPropertyUint32(ctx, v, 0);
                 bool ok = isCompatible<std::decay_t<typename U::value_type>>(ctx, firstElement);
                 JS_FreeValue(ctx, firstElement);
                 if(ok)
                 {
                     return U{js_traits<U>::unwrap(ctx, v)};
                 }
             }
         }
         if constexpr (is_pair<U>::value)
         {
             if(JS_IsArray(ctx, v) == 1)
             {
                 // todo: check length?
                 auto firstElement = JS_GetPropertyUint32(ctx, v, 0);
                 auto secondElement = JS_GetPropertyUint32(ctx, v, 1);
                 bool ok = isCompatible<std::decay_t<typename U::first_type>>(ctx, firstElement)
                           && isCompatible<std::decay_t<typename U::second_type>>(ctx, secondElement);
                 JS_FreeValue(ctx, firstElement);
                 JS_FreeValue(ctx, secondElement);
                 if(ok)
                 {
                     return U{js_traits<U>::unwrap(ctx, v)};
                 }
             }
         }
         if constexpr ((sizeof ... (Us)) > 0)
         {
             return unwrapObj<Us...>(ctx, v, class_id);
         }
         return std::nullopt;
     }
unwrapPriority()
template<typename ... Ts> template<template< typename T > typename Trait, template< typename T > typename ... Traits> static std::variant<Ts...> qjs::js_traits< std::variant< Ts... > >::unwrapPriority (JSContext * ctx, JSValueConst v) inline static
Attempt to cast to types satisfying traits, ordered in terms of priority.
Definition at line 343 of file quickjspp.hpp.
     {
         if(auto result = unwrapImpl<Trait, Ts...>(ctx, v))
         {
             return *result;
         }
         if constexpr ((sizeof ... (Traits)) > 0)
         {
             return unwrapPriority<Traits...>(ctx, v);
         }
         JS_ThrowTypeError(ctx, "Expected type %s", QJSPP_TYPENAME(std::variant<Ts...>));
         throw exception{};
     }
isCompatible()
template<typename ... Ts> template<typename T > static bool qjs::js_traits< std::variant< Ts... > >::isCompatible (JSContext * ctx, JSValueConst v) inline static noexcept
Definition at line 358 of file quickjspp.hpp.
References JS_GetClassID(), JS_IsArray(), JS_TAG_BIG_DECIMAL, JS_TAG_BIG_FLOAT, JS_TAG_BIG_INT, JS_TAG_BOOL, JS_TAG_CATCH_OFFSET, JS_TAG_EXCEPTION, JS_TAG_FLOAT64, JS_TAG_FUNCTION_BYTECODE, JS_TAG_INT, JS_TAG_MODULE, JS_TAG_NULL, JS_TAG_OBJECT, JS_TAG_STRING, JS_TAG_SYMBOL, JS_TAG_UNDEFINED, and JS_TAG_UNINITIALIZED.
     {
         //const char * type_name = typeid(T).name();
         switch(JS_VALUE_GET_TAG(v))
         {
             case JS_TAG_STRING:
                 return is_string<T>::value;
             case JS_TAG_FUNCTION_BYTECODE:
                 return std::is_function<T>::value;
             case JS_TAG_OBJECT:
                 if(JS_IsArray(ctx, v) == 1)
                     return is_vector<T>::value || is_pair<T>::value;
                 if constexpr (is_shared_ptr<T>::value)
                 {
                     if(JS_GetClassID(v) == js_traits<T>::QJSClassId)
                         return true;
                 }
                 return false;
             case JS_TAG_INT:
                 [[fallthrough]];
             case JS_TAG_BIG_INT:
                 return std::is_integral_v<T> || std::is_floating_point_v<T>;
             case JS_TAG_BOOL:
                 return is_boolean<T>::value || std::is_integral_v<T> || std::is_floating_point_v<T>;
             case JS_TAG_BIG_DECIMAL:
                 [[fallthrough]];
             case JS_TAG_BIG_FLOAT:
                 [[fallthrough]];
             case JS_TAG_FLOAT64:
             default: // >JS_TAG_FLOAT64 (JS_NAN_BOXING)
                 return is_double<T>::value || std::is_floating_point_v<T>;
             case JS_TAG_SYMBOL:
                 [[fallthrough]];
             case JS_TAG_MODULE:
                 [[fallthrough]];
             case JS_TAG_NULL:
                 [[fallthrough]];
             case JS_TAG_UNDEFINED:
                 [[fallthrough]];
             case JS_TAG_UNINITIALIZED:
                 [[fallthrough]];
             case JS_TAG_CATCH_OFFSET:
                 [[fallthrough]];
             case JS_TAG_EXCEPTION:
                 break;
         }
         return false;
     }
unwrap()
template<typename ... Ts> static std::variant<Ts...> qjs::js_traits< std::variant< Ts... > >::unwrap (JSContext * ctx, JSValueConst v) inline static
Definition at line 411 of file quickjspp.hpp.
References JS_GetClassID(), JS_TAG_BIG_DECIMAL, JS_TAG_BIG_FLOAT, JS_TAG_BIG_INT, JS_TAG_BOOL, JS_TAG_CATCH_OFFSET, JS_TAG_EXCEPTION, JS_TAG_FLOAT64, JS_TAG_FUNCTION_BYTECODE, JS_TAG_INT, JS_TAG_MODULE, JS_TAG_NULL, JS_TAG_OBJECT, JS_TAG_STRING, JS_TAG_SYMBOL, JS_TAG_UNDEFINED, and JS_TAG_UNINITIALIZED.
     {
         const auto tag = JS_VALUE_GET_TAG(v);
         switch(tag)
         {
             case JS_TAG_STRING:
                 return unwrapPriority<is_string>(ctx, v);
             case JS_TAG_FUNCTION_BYTECODE:
                 return unwrapPriority<std::is_function>(ctx, v);
             case JS_TAG_OBJECT:
                 if(auto result = unwrapObj<Ts...>(ctx, v, JS_GetClassID(v)))
                 {
                     return *result;
                 }
                 JS_ThrowTypeError(ctx, "Expected type %s, got object with classid %d",
                                   QJSPP_TYPENAME(std::variant<Ts...>), JS_GetClassID(v));
                 break;
             case JS_TAG_INT:
                 [[fallthrough]];
             case JS_TAG_BIG_INT:
                 return unwrapPriority<std::is_integral, std::is_floating_point>(ctx, v);
             case JS_TAG_BOOL:
                 return unwrapPriority<is_boolean, std::is_integral, std::is_floating_point>(ctx, v);
             case JS_TAG_SYMBOL:
                 [[fallthrough]];
             case JS_TAG_MODULE:
                 [[fallthrough]];
             case JS_TAG_NULL:
                 [[fallthrough]];
             case JS_TAG_UNDEFINED:
                 [[fallthrough]];
             case JS_TAG_UNINITIALIZED:
                 [[fallthrough]];
             case JS_TAG_CATCH_OFFSET:
                 JS_ThrowTypeError(ctx, "Expected type %s, got tag %d", QJSPP_TYPENAME(std::variant<Ts...>), tag);
                 [[fallthrough]];
             case JS_TAG_EXCEPTION:
                 break;
             case JS_TAG_BIG_DECIMAL:
                 [[fallthrough]];
             case JS_TAG_BIG_FLOAT:
                 [[fallthrough]];
             case JS_TAG_FLOAT64:
                 [[fallthrough]];
             default: // more than JS_TAG_FLOAT64 (nan boxing)
                 return unwrapPriority<is_double, std::is_floating_point>(ctx, v);
         }
         throw exception{};
     }
The documentation for this struct was generated from the following file:
quickjspp.hpp