QuickJSPP: JSSharedArrayBufferFunctions Struct Reference
JSSharedArrayBufferFunctions Struct Reference
#include "quickjs.h"
Public Attributes
void *(* sab_alloc)(void *opaque, size_t size)
void(* sab_free)(void *opaque, void *ptr)
void(* sab_dup)(void *opaque, void *ptr)
void * sab_opaque
Detailed Description
Definition at line 822 of file quickjs.h.
Member Data Documentation
sab_alloc
void*(* JSSharedArrayBufferFunctions::sab_alloc) (void *opaque, size_t size)
Definition at line 823 of file quickjs.h.
Referenced by js_array_buffer_constructor3(), and js_std_init_handlers().
sab_free
void(* JSSharedArrayBufferFunctions::sab_free) (void *opaque, void *ptr)
Definition at line 824 of file quickjs.h.
Referenced by js_array_buffer_finalizer(), and js_std_init_handlers().
sab_dup
void(* JSSharedArrayBufferFunctions::sab_dup) (void *opaque, void *ptr)
Definition at line 825 of file quickjs.h.
Referenced by js_array_buffer_constructor3(), JS_ReadObjectRec(), and js_std_init_handlers().
sab_opaque
void* JSSharedArrayBufferFunctions::sab_opaque
Definition at line 826 of file quickjs.h.
Referenced by js_array_buffer_constructor3(), and js_array_buffer_finalizer().
The documentation for this struct was generated from the following file:
quickjs/quickjs.h