QuickJSPP: JSMallocFunctions Struct Reference
JSMallocFunctions Struct Reference
#include "quickjs.h"
Public Attributes
void *(* js_malloc)(JSMallocState *s, size_t size)
void(* js_free)(JSMallocState *s, void *ptr)
void *(* js_realloc)(JSMallocState *s, void *ptr, size_t size)
size_t(* js_malloc_usable_size)(const void *ptr)
Detailed Description
Definition at line 322 of file quickjs.h.
Member Data Documentation
js_malloc
void*(* JSMallocFunctions::js_malloc) (JSMallocState *s, size_t size)
Definition at line 323 of file quickjs.h.
Referenced by js_malloc_rt().
js_free
void(* JSMallocFunctions::js_free) (JSMallocState *s, void *ptr)
Definition at line 324 of file quickjs.h.
Referenced by js_free_rt(), and JS_FreeRuntime().
js_realloc
void*(* JSMallocFunctions::js_realloc) (JSMallocState *s, void *ptr, size_t size)
Definition at line 325 of file quickjs.h.
Referenced by js_realloc_rt().
js_malloc_usable_size
size_t(* JSMallocFunctions::js_malloc_usable_size) (const void *ptr)
Definition at line 326 of file quickjs.h.
The documentation for this struct was generated from the following file:
quickjs/quickjs.h